### ISSUE TITLE
Credentials not reset between commands

### ISSUE THREAD

**Issue by GrahamFord** [aws/aws-sdk-js-v3#1002]
**Describe the bug**
Send an Iam command with credentials containing a correct key but incorrect secret. An error is thrown as expected.
Subsequently send a command with the correct key and secret. The updated credentials are not recognised as being correct.

**SDK version number**
"@aws-sdk/client-iam": "1.0.0-alpha.17"

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.12.0

**To Reproduce (observed behavior)**
https://repl.it/@GrahamFord/AWS-IAM-demo

Replace the values of the credentials as appropriate for testing.

**Expected behavior**
When passed valid credentials, the users details should be returned

**Additional context**
This issue is also present in the Preview version #943

**Comment by GrahamFord** [comment]
This bug still exists in `1.0.0-beta.5` of `@aws-sdk/client-iam`

**Comment by GrahamFord** [comment]
The bug still exists in `1.0.0-gamma.10` of `@aws-sdk/client-iam`

**Comment by AllanZhengYP** [comment]
Hi @GrahamFord 

Thanks a lot for reporting this issue. This issue is caused by the SigV4 signer trying to cache the hashing results. See here: 
https://github.com/aws/aws-sdk-js-v3/blob/f69ff440a79018ad69fcb26ad46e3db65b23ce71/packages/signature-v4/src/credentialDerivation.ts#L38-L48

Because calculating the signing key needs hashing all the elements one by one, it can affect the performance. So we use a cache here to avoid duplicated computation. However, the credential secrete is not part of the cache key. So the signing key will just return the result from previous invoke. V2 SDK also implement similar feature but doesn't have this problem. Because it uses credential secret as part of the caching key.

**Comment by GrahamFord** [comment]
Thanks for the explanation @AllanZhengYP, that makes perfects sense 👍. I thought that because I called `new IAMClient(config)` each time, the issue was with the Client. I hadn't realised things were being persisted elsewhere.
