### ISSUE TITLE
[Beta] Rekognition and Textract are not working with beta clients

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#1054]
**Describe the bug**
Rekognition and Textract have both stopped working with the beta release. Both the service calls are throwing exception
`{"__type":"InvalidSignatureException","message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}`

**SDK version number**
Beta

**Is the issue in the browser/Node.js?**
Browser

**To Reproduce (observed behavior)**
Call RekognitionService.DetectLabels OR RekognitionService.DetectModerationLabels OR RekognitionService.RecognizeCelebrities OR Textract.AnalyzeDocument and see the error mentioned above

**Comment by AllanFly120** [comment]
Hi @Amplifiyer 
I created a reproduce case for with `Rekognition.recognizeCelebrities()` and cannot see the issue. Here is it: https://github.com/aws-samples/aws-sdk-js-tests/tree/issue-1054 Can you confirm it works for you?

**Comment by AllanFly120** [comment]
Found where the bug is but still locating when the bug was introduced. The issue happens because the image binary should be base64 encoded. This is the correct method: 
https://github.com/aws/aws-sdk-js-v3/blob/0f786a09a11f679b22bd58592658c4417f8c53c8/clients/client-rekognition/protocols/Aws_json1_1.ts#L6940
But now it's changed to utf8 encoding:
https://github.com/aws/aws-sdk-js-v3/blob/2de3b31985868906a2e599dcada61243ca3f0867/clients/client-rekognition/protocols/Aws_json1_1.ts#L7248
