### ISSUE TITLE
Drop Internet Explorer support in v3

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1095]
**Is your feature request related to a problem? Please describe.**
* We target ES5 for ES modules mainly for supporting Internet Explorer.
* It requires us to add some hacks like https://github.com/aws/aws-sdk-js-v3/pull/1027

**Describe the solution you'd like**
* Target ES2015 for browsers, which will drop Internet Explorer support in v3
* Bootstrap, a UI framework used by 20% of internet sites, is dropping IE support in next major version - in late 2020 ([link](https://www.zdnet.com/article/bootstrap-a-ui-framework-used-by-20-of-internet-sites-is-dropping-ie-support/)) 

**Describe alternatives you've considered**
Continue adding hacks to make things work in ES5

**Comment by AllanFly120** [comment]
+1 for dropping IE support if this is the community trend. But #1027 is for hacking around IE, it's a know TS issue which affects all the browsers.

**Comment by trivikr** [comment]
StackOverflow discussion (updated Feb 2019) as per which ES6 support is not expected to land in IE11 https://stackoverflow.com/questions/39902809

**Comment by trivikr** [comment]
If we go ahed with targeting ES2015, this would be our support list in v3:

| Browser           | Version |
| ----------------- | ------- |
| Google Chrome     | 49.0+   |
| Mozilla Firefox   | 45.0+   |
| Apple Safari      | 9.0+    |
| Internet Explorer | N/A     |
| Microsoft Edge    | 12.0+   |
| Opera             | 36.0+   |
| Samsung Internet  | 5.0+    |
| UC Browser        | 12.12+  |
| Android Browser   | 76.0+   |

The [official documented browser support list in v2](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/browsers-supported.html) for comparison:

| Browser           | Version |
| ----------------- | ------- |
| Google Chrome     | 28.0+   |
| Mozilla Firefox   | 26.0+   |
| Apple Safari      | 5+      |
| Internet Explorer | 10+     |
| Microsoft Edge    | 25.10+  |
| Opera             | 17.0+   |
| Android Browser   | 4.3+    |

**Comment by trivikr** [comment]
Popular frameworks using TypeScript target ES6, and instruct their consumers to use Polyfills:
* create-react-app https://create-react-app.dev/docs/supported-browsers-features/
* Vue 3 https://github.com/vuejs/vue-next/blob/master/README.md#L11
* Angular https://angular.io/guide/browser-support#polyfills

**Comment by trivikr** [comment]
Amplify team also builds separate ES6 and ES5 bundles.
Code: https://github.com/aws-amplify/amplify-js/blob/9b05aeed43292ba5b9a7df3f4be79c60b654073c/scripts/build.js#L240-L248

**Comment by simonbuchan** [comment]
You should be able to be far more aggressive, according to [kangax]( http://kangax.github.io/compat-table/es2016plus/) - ES2017 is supported by every tracked, supported browser and node version except IE including including Firefox ESR and nearly completely by the earliest tracked iOS Safari (which is actually far better than iOS Safari's ES6 feature support!)

Pros:
- Smaller, faster code.
- Nicer stack traces due to native async functions (as I mentioned in #1287), which is a bullet point feature of v3
- Doesn't seem to be notably worse runtime support in supported browser versions compared to (full) ES6 support.
- In the worst case, users can still transpile as with targeting ES6/ES2015.

Cons:
- Although runtime support is not likely to be a problem, occasionally tooling can still hit issues, e.g. raw webpack 4 w/o a loader still doesn't like the ES2020 syntax `??` and `?.`. I would assume projects willing to update to AWS SDK v3 are likely happy enough to either update other tooling to a more recent version or transpile.
- As mentioned, it's surprising to be targeting a later version, when most packages on NPM target ES3-ES6.

**Comment by trivikr** [comment]
Announcements by Microsoft:

* Teams will stop supporting IE 11 on November 30, 2020
* 365 apps will stop supporting IE 11 on August 17, 2021

https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

**Comment by trivikr** [comment]
The [AWS SDK for JavaScript v3 is now GA](https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/), and we decided to keep supporting Internet Explorer.

We'll explore dropping support in v4 in future.

**Comment by trivikr** [comment]
The support for Internet Explorer will be dropped on October 1, 2022.

Blog post https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-internet-explorer-11-in-the-aws-sdk-for-javascript-v3/
