### ISSUE TITLE
Wrong header x-amz-content-sha256 in Aws_restJson1_1.ts protocol for postContent (AmazonLex) - impacts Amplify Chatbot UI component voice interaction

### ISSUE THREAD

**Issue by kkrzyzek** [aws/aws-sdk-js-v3#1125]
**Describe the bug**
Getting following 'BadRequestException' error when using Amplify Chatbot UI component with voice interaction turned on.
```
Aws_restJson1_1.ts:834 Uncaught (in promise) **BadRequestException: Invalid Request: The header x-amz-content-sha256 must be set to the literal string** UNSIGNED-PAYLOAD.
    at http://localhost:3000/static/js/1.chunk.js:91237:42
    at step (http://localhost:3000/static/js/1.chunk.js:318206:17)
    at Object.next (http://localhost:3000/static/js/1.chunk.js:318137:14)
    at fulfilled (http://localhost:3000/static/js/1.chunk.js:318092:24)
```
**SDK version number**

**Is the issue in the browser/Node.js?**
both
(issue occuring in react-native mobile app integrated with aws-sdk & amplify. Using Chatbot UI component setup based on following instructions: https://docs.amplify.aws/ui/interactions/chatbot/q/framework/react-native#turning-on-voice-interaction)

**Details of the browser/Node.js version**
node 12.14.1

**To Reproduce (observed behavior)**
Setup react-native project using react-native cli and follow instructions to integrate it with Amplify & Chatbot UI component from https://docs.amplify.aws/ui/interactions/chatbot/q/framework/react-native. Error occurs, when I am trying to interact with chatbot using voice.

Chatbot with enabled voice interaction:
```
<ChatBot
    botName={botName}
    welcomeMessage={welcomeMessage}
    onComplete={this.handleComplete}
    clearOnComplete={false}
    voiceEnabled={true}
    voiceLibs={voiceLibs}
    styles={StyleSheet.create({
        itemMe: {
            color: 'red'
        }
    })}
/>

```
**Expected behavior**
Error does not occur, voice interaction with chatbot is happening, postcontent request to chatbot is being fullfilled

**Screenshots**
-

**Additional context**
I believe this error is related to implementation of [`aws-sdk-js-v3/clients/client-lex-runtime-service/protocols/Aws_restJson1_1.ts`](https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-lex-runtime-service/protocols/Aws_restJson1_1.ts), function `async function serializeAws_restJson1_1PostContentCommand`, which is used by Amplify.
**The header: x-amz-content-sha256 should be set there to "UNSIGNED-PAYLOAD" and it is "UNSIGNED_PAYLOAD".**

**Comment by wlee221** [comment]
I'm encountering the same problem in my sample app. We receive `400 Invalid Request: The header x-amz-content-sha256 must be set to the literal string UNSIGNED-PAYLOAD` when using `postContent`. 

Here is a [repo](https://github.com/wlee221/aws-sdk-js-tests) for reproduction. `postContent` works for aws-sdk-v2 but not v3. 

As @kkrzyzek mentioned, I believe the header `x-amz-content-sha256` needs to be set to `UNSIGNED_PAYLOAD`. I could confirm that the request works by changing the header manually.

Also, `aws-sdk-v3` client now returns the audiostream response as `ReadableStream` instead of `Uint8Array` unlike v2. This is demonstrated in the sample repo above. This is currently breaking the Chatbot UI Component of aws-amplify because the component expects Uint8Array. Is this an intended behavior / breaking change for `aws-sdk-v3`?

**Comment by AllanFly120** [comment]
Hi @kkrzyzek Thank you for reporting the issue and detailed reproduction case. I have confirmed the root cause and working on a fix. 

> Also, aws-sdk-v3 client now returns the audiostream response as ReadableStream instead of Uint8Array unlike v2. This is demonstrated in the sample repo above. This is currently breaking the Chatbot UI Component of aws-amplify because the component expects Uint8Array. Is this an intended behavior / breaking change for aws-sdk-v3?

Yes, this is an intended behavior change. The SDK will prefer using `ReadableStream` for streaming response, if the stream is supported in the runtime. If not, SDK will return the data as `Blob`. Here's the rationales and how to work with cross-platform streaming response: https://github.com/aws/aws-sdk-js-v3/issues/843
