### ISSUE TITLE
AWS Credential provider with profile role credentials is not creating sts client if none is supplied

### ISSUE THREAD

**Issue by adcreare** [aws/aws-sdk-js-v3#1193]
**Describe the bug**
The documentation for the credential-provider-node over at https://github.com/aws/aws-sdk-js-v3/tree/master/packages/credential-provider-node#aws-credential-provider-for-nodejs 
says that 
`roleAssumer - A function that assumes a role and returns a promise fulfilled with credentials for the assumed role. If not specified, the SDK will create an STS client and call its assumeRole method.`

However I've found this not to be the case instead it seems I have to provide a roleAssumer function such as below. When this is supplied it works perfectly. 

Either the SDK seems not to be implementing the assumeRole by default if not supplied as it should OR the documentation is incorrect.  It my eyes it would make sense for the sdk to implement this if it isn't provided and that would also make it work much the same as the old sdk.

```typescript
async function assume(sourceCreds: Credentials, params: AssumeRoleParams)
: Promise<Credentials> {

    const sts = new STS({credentials: sourceCreds});
    const result = await sts.assumeRole(params);
    if(!result.Credentials) {
        throw new Error('unable to assume credentials - empty credential object');
    }
    return {
        accessKeyId: String(result.Credentials.AccessKeyId),
        secretAccessKey: String(result.Credentials.SecretAccessKey),
        sessionToken: result.Credentials.SessionToken
    }
}
```

**SDK version number**
"@aws-sdk/client-s3": "1.0.0-beta.5",

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.16.1

**To Reproduce (observed behavior)**
##### 1.  AWS credential setup
My aws credential setup is as follows: *Note: all keys and IDs have been scrubbed*

1. ~/.aws/credentials file

[masteraccount]
aws_access_key_id = xxxxSNIP
aws_secret_access_key =  xxxxSNIP

2: ~/.aws/config file
[profile testaccount]
role_arn = arn:aws:iam::xxxxxACCOUNTID:role/Master-Account-User-Access-Role
source_profile = masteraccount

3. `aws --profile testaccount s3 ls` works

##### 2. Making the SDK call
Using the old sdk I can list and S3 bucket using `export AWS_REGION=us-east-1 && export AWS_PROFILE=testaccount && export AWS_SDK_LOAD_CONFIG=1 && node s3.js`

Using the new SDK with the example provided below the following error is returned
```
(node:20164) UnhandledPromiseRejectionWarning: Error: Profile platform-test requires a role to be assumed, but no role assumption callback was provided.
    at new ProviderError (/Users/xxx/git/testawssdk/node_modules/@aws-sdk/property-provider/build/ProviderError.js:17:28)
    at /Users/xxx/git/testawssdk/node_modules/@aws-sdk/credential-provider-ini/build/index.js:62:31
    at step (/Users/xxx/git/testawssdk/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/xxx/git/testawssdk/node_modules/tslib/tslib.js:120:57)
    at /Users/xxx/git/testawssdk/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/xxx/git/testawssdk/node_modules/tslib/tslib.js:109:16)
    at resolveProfileData (/Users/xxx/git/testawssdk/node_modules/@aws-sdk/credential-provider-ini/build/index.js:43:20)
    at /Users/xxx/git/testawssdk/node_modules/@aws-sdk/credential-provider-ini/build/index.js:32:20
    at async Promise.all (index 1)
(node:20164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The code used for this is as follows:
```typescript
import {S3} from '@aws-sdk/client-s3';

async function main() {
    const s3 = new S3({});
    const buckets = await s3.listBuckets({});
    buckets.Buckets?.forEach((bucket) => console.log(bucket.Name));
}

main();
```

**Expected behavior**
I would expect the credential provider would actually create a stsClient and call the assumeRole operation with the role that is configured inside the configuration file as per the documentation for the credential provider package.

**Comment by laurisvan** [comment]
I would also like to pinpoint that this is an undocumented change from V2 API, as the assumeRole earlier happened without extra operations being triggered.

In our case, our EC2 machines do not need to do assumeRole whereas in local development this is a must. It would be great if we had at least a documented sample on how to handle this.

**Comment by adcreare** [comment]
@laurisvan I agree - we've had to work around in our usage of V3 and pass in a creds function to handle it - I'm honestly surprised this issue hasn't got more attention. I'd expect this to cause people a lot of confusion and breakages if they leave it like this. Although maybe we're the only ones that use roles or something heh!

**Comment by AllanZhengYP** [comment]
Hi, @adcreare 

Thank you for bringing this up.  The README for `@aws-sdk/credential-provider-node` is not accurate. The `roleAssumer` config is a delegation of [roleAssumer in INI Credential Provider](https://github.com/aws/aws-sdk-js-v3/blob/47770fa493c3405f193069cd18319882529ff484/packages%2Fcredential-provider-ini%2Fsrc%2Findex.ts#L69-L76)(The interface comment is more accurate). It doesn't create STS client on behalf of users. We will adress this in our guidance. 

We don't plan to make the `roleAssumer` creates STS client automatically because it makes the credential provider package depending on the STS service client(usually very big). It will be unfriendly to the bundlers. 

Please let me know if it makes sense.

**Comment by adcreare** [comment]
Hi @AllanZhengYP 
Thanks for the response. I do get not wanting to include the STS client in the provider package and that makes sense. 
Obviously the readme needs to be updated and I would suggest putting in an example of what the roleAssume function should be because i think a lot of people will be a bit confused when they migrate over from the V2 sdk that does it all for you. 
Cheers
David

**Comment by laurisvan** [comment]
Hi @AllanZhengYP & thanks from my behalf, too.

I also like having control on whether I use STS or not. I think announcing this as a breaking change and giving a workaround sounds a solution that is on par or above what is in the old client.

Now that I caught your attention - may I ask if AWS SDK v3 will eventually be shipped as separate modules, or a bundle? While a Webpack compressed app would be smaller with the current solution, the current bundling still creates large Docker images etc. I haven't checked under the hood, but if packaging and relasing as individual node modules were simple, that'd solve the package size problem for us.

In our app we are also seeing problems with TypeScript definitions -  I wonder if the current modularisation attempts help on that one or not. Separate npm modules would solve that issue, too...

**Comment by chalford** [comment]
Not including a function to delegate role assumption to STS seems like an omission, for something that happens by default in the AWS CLI. I too understand not wanting to avoid bundling an STS dependency (but maybe its unavoidable). 

Is there a way that the presence of an STS peer dependency can detected by crendential-provider-ini, and use STS if it is available?

**Comment by AllanZhengYP** [comment]
@chalford 

Thank you for the insight! I will update the README for this one. But we *need* to make the credential provider assume the role automatically. We need to come up design to take the STS dependency, because STS client itself also depends on this package. I will label this as a feature request and keep it in the high priority task queue.

**Comment by adcreare** [comment]
@chalford yeah good point about the CLI.

@AllanZhengYP oh so it is going to assume automatically now? Well im glad to hear the reversal of the decision.. I'd suggest you might want to make that GA blocker as well or its going to be a bigger mess once its been used without it for awhile. 

> Thank you for the insight! I will update the README for this one. But we _need_ to make the credential provider assume the role automatically.

**Comment by AllanZhengYP** [comment]
Hi @adcreare  @chalford 

I picked this work up and realized it is much trickier than I thought. On Node.js(because of CommenJS modules specifically), we inevitably have to introduce cyclic dependencies, thus breaks the require chain. Here is the cycle: 

Any client -> `credential-provider-node` -> `credential-provider-ini` -> `client-sts` -> `credential-provider-node` -> `credential-provider-ini` ->  `client-sts`(Again!)

Inspired by @chalford and Java SDK's solution, we can import the STS client **dynamically** instead of hoisted on the top. This way, the STS client imported asynchrously at runtime. But I need to verify its effect in treeshaking/bundlers.

**Comment by AllanZhengYP** [comment]
So I tried to put up [something like this](https://github.com/AllanZhengYP/aws-sdk-js-v3/blob/091d07b09af9eee2b653c642604095848a35e72b/packages/credential-provider-ini/src/getDefaultAssumer.ts#L26) to load the STS client module asynchrously. It has the drawback that Webpack **cannot** treeshake the STS client at all(See [Webpack team's reply](https://github.com/webpack/webpack.js.org/issues/2684), and [this post](https://medium.com/@christiango/the-unexpected-impact-of-dynamic-imports-on-tree-shaking-ddadeb135dd7)). It's maybe acceptable because browser won't have pulling this dependency at all. 

For Node.js we need more data. I've done a local test(simply S3 list buckets) shows that my solution that pulling in full STS client takes ~186 KB whereas the old solution that importing STS client in customer code takes ~161KB. How much it affects Lambda codestart will need more investigation.

**Comment by AllanZhengYP** [comment]
In fact there's an alternative solution to eliminate the circular dependency. Here's how it works: I can generate an STS client class that doesn’t have dependencies on any credential providers, say `STSClientUnauth.ts` . Then the AWS credential file resolver will only depend on this class. This class only accepts credentials from constructor and cannot resolve credentials from elsewhere(environmental variable, credential files..). It makes sense because the STS client needed in AWS credential file resolver doesn’t need to resolve credentials on its own.

**Comment by adcreare** [comment]
@AllanZhengYP sounds like a good solution, Im honestly surprised something as key as this was left out of the original design.. creds and auth seems like job 0 but here we are.
