### ISSUE TITLE
S3 Client by Default Installing 'Pixl-Xml' Based 1.0.0-alpha.1 Version, Not 'Fast-Xml-Parser' 1.0.0-alpha.11

### ISSUE THREAD

**Issue by waleedshkt** [aws/aws-sdk-js-v3#1300]
Hi there,

So as described in subject above, `npm` is installing issue-prone `pixl-xml` based `@aws-sdk/client-s3` version which when bundling with `webpack` is leading to issue been addressed [here](https://github.com/aws/aws-sdk-js-v3/issues/735#issuecomment-582729307)

**Comment by waleedshkt** [comment]
Better make new `gamma` version as default version for this package

**Comment by AllanFly120** [comment]
Hi @waleedshkt 

As you have found, we have dropped the `pixl-xml` dependency in favor of `fast-xml-parser` in gamma clients. We don't use newer `gamma` version as default because we want to bring enough awareness to the developers that these packages are still in `gamma` stage. So developers need to specify it when installing, like `npm install @aws-sdk/client-s3@gamma`.
