### ISSUE TITLE
v3 API documentation

### ISSUE THREAD

**Issue by jadbox** [aws/aws-sdk-js-v3#1346]
Is there API or usage documentation somewhere yet?

**Comment by trivikr** [comment]
v3 API documentation is not deployed yet.

You can refer:
* Diffs given in workshop code https://github.com/aws-samples/aws-sdk-js-v3-workshop
* Examples given in v2 SDK API reference, but use v3 clients instead https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/

**Comment by trivikr** [comment]
Removing closing-soon, and adding response-requested to give time for response if any.

**Comment by vvo** [comment]
Just a side note, this is the second request for documentation from users in this repo in two days (this one and #1355). This comes from the fact that the main AWS sdk js documentation page says "try the v3":

![image](https://user-images.githubusercontent.com/123822/87643931-c8967680-c74b-11ea-99f9-7e08fd5dfd22.png)

And actually the main link in this section points to a blog post 1.5 years old (which seems "bad", but I understand the challenges it can be to do such an important API client).

Still, unless there's a v3 documentation deployed and easily accessible on the main aws js website, I would not advise people to try it.. Because it's frustrating to be told "try the new shiny thing" and there's no documentation or hard to find documentation.

Good luck still!!

**Comment by brmur** [comment]
You can see examples of how to use the V3 of the AWS JS SDK with many of the AWS Services here https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javascript/example_code_v3/ .

**Comment by AllanZhengYP** [comment]
Hi @jadbox @vvo,

Regarding the API reference, we just published the v3 API reference here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html

We are still working on to polishing it, please feel free to open issues if you have any questions or feedbacks. We will add links from our README and dev guides too.
