### ISSUE TITLE
Lambda InvokeCommand payload with UInt8Array type

### ISSUE THREAD

**Issue by samirda** [aws/aws-sdk-js-v3#1433]
**Describe the bug**
Produces error when calling InvokeCommand with Payload type UInt8Array

**SDK version number**
Gamma 6

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v14.5.0

**To Reproduce (observed behavior)**
```typescript
await lambda.send(new InvokeCommand({
  FunctionName: '<FunctionName>',
  Payload: new TextEncoder().encode('abc') //Uint8Array
}))
```

`(node:54212) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Uint8Array`

```typescript
await lambda.send(new InvokeCommand({
  FunctionName: '<FunctionName>',
  Payload: '"abc"' as any
}))
```

Works as expected

**Expected behavior**
Payload with UInt8Array type to not throw error or change Payload type to `string | Buffer`

**Comment by AllanFly120** [comment]
Hi @samirda This is indeed a bug with our implementation. Because the `ClientRequest.end(chunk)` was typed as `any` in `@types/node` but [in fact only `string|Buffer` is accepted in Node](https://github.com/nodejs/node/blob/f512ce6aa0ce7fdfb560a40cb09abcdbc8de1ad9/lib/_http_outgoing.js#L695-L697). I will put up a fix shortly. 

Actually the easiest way to get around it is using `Buffer` in Node.js, which is the default binary representation in Node.js. Buffer itself implements `Uint8Array` interface. We use `Uint8Array` for binary parameters because its native in any JS runtime.
