### ISSUE TITLE
npm package is published in typescript

### ISSUE THREAD

**Issue by eltonio450** [aws/aws-sdk-js-v3#1436]
**Describe the bug**
npm package is published in typescript (at least s3 client)

**SDK version number**

1.0.0.gamma-5

**Is the issue in the browser/Node.js/ReactNative?**
npm

**Expected behavior**
npm published package should be in javascript + types

**Additional context**
client-S3 imported from node_modules must be transpiled with a loader such as ts-loader. It's ok from es6 to es5, but it's very uncommon from typescript to es5

I don't know if it is a bug or not, but I feel that publishing directly in typescript is not suitable for a lot of people

**Comment by justingrant** [comment]
The entry points for AWS SDK client packages are in each client package's  `./dist` folder, which has no TS code, only JS. For example, here's the entry points from the S3 client package:

https://github.com/aws/aws-sdk-js-v3/blob/0c7f7eee39eef17a5baee3c0db78682a54b1028a/clients/client-s3/package.json#L20-L22

The TS code that you're seeing is the original TS source, which is important for sourcemap-enabled debugging because the sourcemap files point to the original source files so that IDE debuggers (and browser devtools) can allow developers to view, step into, and set breakpoints in the original source. But when you bundle this package into your app, only the JS files will be included.

Yes, this is definitely confusing. IMHO, the AWS SDK should put its source files into a `/src` folder, not in the root folder where they are mixed with config files. But this weirdness shouldn't break your app's compilation.

**Comment by justingrant** [comment]
BTW, you're not the only one confused by this. See #1306. I'd suggest that you close this issue in favor of #1306.

**Comment by eltonio450** [comment]
sure!

thanks for the answer, I missed the dist folder!

for the record, I was confused because after installing the sdk, my es5 check did not pass anymore, and when digging, I fall on the typescript files. I think I won't be the only one to have this problem 🤗

have a good week
