### ISSUE TITLE
v1.0.0-gamma.7 / #1420 causes `Region is missing` errors

### ISSUE THREAD

**Issue by roderik** [aws/aws-sdk-js-v3#1466]
**Describe the bug**

v1.0.0-gamma.7 and presumably https://github.com/aws/aws-sdk-js-v3/pull/1420 broke perfectly working S3 client implementation.

```
  console.error
    Error: Region is missing
        at default (/Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/config-resolver/src/RegionConfig.ts:12:4)
        at /Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/node-config-provider/src/fromStatic.ts:9:59
        at step (/Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:141:27)
        at Object.next (/Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:122:57)
        at /Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:115:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:111:16)
        at /Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/node-config-provider/src/fromStatic.ts:9:56
        at /Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/node-config-provider/node_modules/@aws-sdk/property-provider/src/chain.ts:23:19

      at process.uncaught (../../node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)
      at processEmit [as emit] (../../node_modules/signal-exit/index.js:161:32)
```

Reverting back to gamma.6 makes these errors go away.

The code we use to initialize S3 is

```
export enum EKSRegion {
  EUROPE = 'eu-west-3',
  UNITED_STATES = 'us-east-2',
  INDIA = 'ap-south-1',
  SINGAPORE = 'ap-southeast-1',
}
```

```
    this.s3 = new S3({
      credentials: {
        accessKeyId: config.providers.EKS.accessKeyId,
        secretAccessKey: config.providers.EKS.secretAccessKey,
      },
      region: EKSRegion.EUROPE,
    });
```

**SDK version number**

v1.0.0-gamma.7

**Is the issue in the browser/Node.js/ReactNative?**

Node.js

**Details of the browser/Node.js/ReactNative version**

v14.7.0

**Comment by AllanFly120** [comment]
Hi @roderik,

Can you share a reproduction snippet or repo? I tried the code bellow but don't see the error.

```javascript
const { S3 } = require("@aws-sdk/client-s3");

(async () => {
  const client = new S3({
    region: "us-west-2",
    credentials: {
      accessKeyId: "***",
      secretAccessKey: "***"
    }
  });
  const getObjectResp = await client.getObject({
    Bucket: "bucket",
    Key: "key"
  });
  console.log(getObjectResp.$metadata);
  // consume getObjectResp.Body
})();
```
Output looks like:

```console
{
  httpStatusCode: 200,
  httpHeaders: {
    /*headers*/
  },
  requestId: undefined,
  attempts: 1,
  totalRetryDelay: 0
}
```

```console
yarn list @aws-sdk/client-s3                                                                                                                   
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @aws-sdk/client-s3@1.0.0-gamma.7
✨  Done in 0.86s.
```

**Comment by AllanFly120** [comment]
Hi @roderik 

I can reproduce this issue. The issue is caused by the default region provider of the clients. We will fix this issue shortly, for now you can keep on gamma.6 version. Here's the root cause:

S3 loads the region from local INI files and environment variables by default: 
https://github.com/aws/aws-sdk-js-v3/blob/5478012147b475bdce07a2cbe393a972e502c93f/clients/client-s3/runtimeConfig.ts#L31-L32

If you provide a `region` config, it will overwrite the default region provider above. What happens here is that when the default region provider function is created, it already inspected the local INI files and environment vairiables to load the region and would throw if cannot find the region. If region can be found, it will memoize the value and prevent loading it in every evoke.

https://github.com/aws/aws-sdk-js-v3/blob/47770fa493c3405f193069cd18319882529ff484/packages/property-provider/src/memoize.ts#L41-L50

However, the expected behavior of `memoize()` should be loading the value **after first evoke** instead of immediately.

**Comment by AllanFly120** [comment]
This fix has been merged into master. For now, as a workaround, you can set the region before instantiate the client, like:

```javascript
process.env.AWS_REGION = "us-west-2";
const client = new S3({
  credentials: {
    accessKeyId: "***",
    secretAccessKey: "***"
  }
});
await client.putObject(params);
```
