### ISSUE TITLE
DynamoDB converts Uint16Array to Uint8Array when passed as binary

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1530]
**Describe the bug**
DynamoDB converts Uint16Array to Uint8Array when passed as binary

**SDK version number**
```
"@aws-sdk/client-dynamodb": "1.0.0-gamma.9"
```

**Is the issue in the browser/Node.js/ReactNative?**
All

**Details of the browser/Node.js/ReactNative version**
Not relevant

**To Reproduce (observed behavior)**

<details>
<summary>Code</summary>

```js
const { DynamoDB } = require("@aws-sdk/client-dynamodb");

(async () => {
  const region = "us-west-2";
  // Pre-created test table with:
  // AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }],
  // KeySchema: [{ AttributeName: "id", KeyType: "HASH" }],
  const TableName = "test-table-273396711";

  const client = new DynamoDB({ region });

  const id = { S: "id" };
  const uint16Arr = new Uint16Array([27, 31]);

  await client.putItem({ TableName, Item: { id, test: { B: uint16Arr } } });

  const response = await client.getItem({ TableName, Key: { id } });
  const received = new Uint16Array(response.Item.test.B);
  console.log("sent: " + JSON.stringify(uint16Arr));
  console.log("received: " + JSON.stringify(received));

  await client.deleteItem({ TableName, Key: { id } });
})();

```

</details>

<details>
<summary>Output</summary>

```console
sent: {"0":27,"1":31}
received: {"0":27,"1":0,"2":31,"3":0}
```

</details>

**Expected behavior**
DynamoDB doesn't convert supplied binary to Uint8Array

**Comment by AllanFly120** [comment]
In summary, the binary data sent to server-side is not altered but SDK *converts* the Uint16Array to Uint8Array in the response rather than the request. Let's see what actually happen in the code snippet: 

```javascript
 await client.putItem({ TableName, Item: { id, test: { B: uint16Arr } } });
```
When Uint16Array is sent to the DDB, the SDK send the binary as it is, no mather the bits of the representation(`Uint8Array`, `Uint16Array`, `Float32Array` and [so on](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#TypedArray_objects))).

```javascript
const response = await client.getItem({ TableName, Key: { id } });
```
When the same binary is get from DDB, SDK needs to base64 decode it: https://github.com/aws/aws-sdk-js-v3/blob/17620d60ef422e9089c1b91117076c69fa90ec96/clients/client-dynamodb/protocols/Aws_json1_0.ts#L6101
So the output of decoder is `Uint8Array`. This convert is [universal for all the binary shapes](https://github.com/awslabs/smithy-typescript/blob/3a73fba471f5a77328544b67c4dda46c836c7e3d/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java#L118-L121) throughout the SDK.

To avoid the confusion that the same binary artifact is send to DDB in `Uint16Array`(or [other representations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#TypedArray_objects)) but get from DDB in a different representation(`Uint8Array`), we type the shape in `Uint8Array` always, no matter input or output. This is also a benefit of Smithy contract, you can find more context from the discussion in https://github.com/aws/aws-sdk-js-v3/issues/843

However if users don't care about type consistency of request and response, this feature can be bothering because in fact users can supply whatever binary shapes inluding `Blob`, `File` and `Buffer`, but the Typescript type requries those parameters to be `Uint8Array`
