### ISSUE TITLE
How to convert from STS returned credentials to standard credentials type

### ISSUE THREAD

**Issue by mungojam** [aws/aws-sdk-js-v3#1685]
**Describe the issue with documentation**

I'm using STS to get credentials, but all properties are in PascalCase because they are the Credentials type from the models folder, rather than the one from @aws-sdk/types which uses camelCase.

I feel like I'm missing something obvious about the distinction between model types and the @aws-sdk/types

```javascript
    const response = await stsClient.send(new AssumeRoleWithSAMLCommand(credentialRequest));

    const credentials = response.Credentials; //Not the same type as {Credentials} from '@aws-sdk/types'
```

For now this is what I am having to do, which feels pretty yukky:

```javascript
    if(!credentials || !credentials.AccessKeyId || !credentials.SecretAccessKey) {
        return undefined;
    }

    return {
        accessKeyId: credentials.AccessKeyId,
        secretAccessKey: credentials.SecretAccessKey,
        sessionToken: credentials.SessionToken,
        expiration: credentials.Expiration
    };
```

**Comment by AllanZhengYP** [comment]
Hi @mungojam 

You are doing it the right way for now, but we should provide helper function handles assume role better overall. The upper-cased `AccessKeyId` were defined in the service model, not by the SDK. So we are very limited on what we can do on that side. However, on the client config, we decided to use lower-cased `accessKeyId` to make it compatible with v2 SDK. 

You don't need to assign them so often in v2 SDK because we provide assume role within the credential provider, we need to provide similar capability in v3. I will tag it as feature request so we will revise it later.

**Comment by ataylorme** [comment]
Bumping this so the bot doesn’t close it. Any update on a solution?

**Comment by AllanZhengYP** [comment]
Hi @ataylorme @mungojam 

You can fetch the STS credentials with [`fromTemporaryCredentials()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromtemporarycredentials-2). This provider makes call to STS service automatically. You don't need to worry about assigning the credentials from the STS response.

Please create a new issue if you think the issue reported here persists.

**Comment by mungojam** [comment]
@AllanZhengYP thanks, but that doesn't appear to support AssumeRoleWithSaml which was what I was using in my example. Unless I'm misunderstanding how it is used
