### ISSUE TITLE
S3 doesn't follow 301s from  us-east-1 to eu

### ISSUE THREAD

**Issue by alexforsyth** [aws/aws-sdk-js-v3#1802]
**Describe the bug**

```js
const { S3, waitForBucketExists } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-east-1";
  const client = new S3({ region, logger: console });

  const Bucket = `test-bucket-${Date.now()}`;
  await client.createBucket({
    Bucket,
    CreateBucketConfiguration: {
      LocationConstraint: "EU",
    },
  });

  try {
    await client.headBucket({ Bucket });
  } catch (error) {
    // THROWS 301
    console.log(error);
  }
})();

```
The SDK does not follow 301s 

**SDK version number**

`3.0.0`

**Is the issue in the browser/Node.js/ReactNative?**
Browser/Node.js/ReactNative

**Details of the browser/Node.js/ReactNative version**
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**
The sdk should follow a 301 and get the correct result back

**Screenshots**

**Additional context**

**Comment by AllanZhengYP** [comment]
This is expected. Although S3 buckets are globally unique, you need create bucket in a specific region. By default, a bucket will be created in the region where your S3 client's region is. In the example above, it is `us-east-1`. When a bucket is create with `LocationConstraint` configuration, the bucket is created in the specified region(e.g. `EU` or `eu-west-1`).  Since the newly created bucket locates in `eu-west-1`, you need to head bucket with correct region(`bucket.s3.eu-west-1.amazonaws.com`), otherwise you will get a 301 response.

To make to code above work, you have to head bucket to the correct region:

```typescript
const { S3, waitForBucketExists } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-east-1";
  const targetRegion = "eu-west-1";
  const client = new S3({ region, logger: console });

  const Bucket = `test-bucket-${Date.now()}`;
  await client.createBucket({
    Bucket,
    CreateBucketConfiguration: {
      LocationConstraint: targetRegion,
    },
  });

  const newClient = new S3({region: targetRegion});
  await newClient.headBucket({ Bucket });
})();
```

In v2, we implemented a lot of hacky logic to make the S3 client behaves like a global client, but it may confuse the users, espacially those having knowledge of other AWS tools. So we remove the follow-the-redirect feature in v3. If we see more feature requests, we can provide a higher level library to support global client.
