### ISSUE TITLE
Parsing SESv2 Errors

### ISSUE THREAD

**Issue by isaacl** [aws/aws-sdk-js-v3#1821]
I'm trying to use SESv2 to send messages, and I need to know if I'm throttled.   In V2 the code looks like:

```ts
import type { AWSError } from 'aws-sdk';
...
.promise().catch((e: AWSError) => {
    if (e.code === 'Throttling' && e.message !== 'Maximum sending rate exceeded')
      // do something
```

How do I do this in V3?  Should I still I still use the AWSError type from `aws-sdk`?

**Comment by ajredniwja** [comment]
Hi @isaacl thanks for opening this issue, you can find information on how to catch error [here](https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/clients/client-sesv2/README.md#troubleshooting). 

I believe you wont have to import it. I haven't tried the above example but let us know if you still run into issues, would be happy to help.

**Comment by isaacl** [comment]
I don't see how to do that comparably. Where is the code attribute?

**Comment by RanVaknin** [comment]
Hi @isaacl ,

Sorry for the long wait, we are just combing through our backlog and cleaning things up and I saw this issue.

Please refer to this doc regarding [error handling in v3](https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/). We use the `name` field to check for typed errors.

Since this is a very old issue I feel comfortable closing it, if you're still running into issues let me know please.

Thanks,
Ran~
