### ISSUE TITLE
Adding Location API

### ISSUE THREAD

**Issue by Aljendro** [aws/aws-sdk-js-v3#1922]
**Is your feature request related to a problem? Please describe.**
Currently, the location api is not available in the v3 js sdk

**Describe the solution you'd like**
I would like to have the new Location api exported in the v3 js sdk

**Describe alternatives you've considered**
Bundling the entire latest v2 js sdk into a lambda, which I'm trying to avoid.

**Additional context**
No additional context

**Comment by p0wl** [comment]
Looking for this as well. Also because the current default aws-sdk v2 ([2.804.0](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)) does not include AWS.Location either. So to start using it in Lambda you either have to bring your own aws-sdk-v2 (which is huge) or implement the api call directly...

**Comment by p0wl** [comment]
Any updates on this? lambdas default aws-sdk v2 is still 2.804.0...

**Comment by trivikr** [comment]
This happens as smithy models were last updated on 12/12/2020 in https://github.com/aws/aws-sdk-js-v3/pull/1774.

The updates haven't been regular in the past, as we're internally verifying our setup for models generation. We plan to verify and update regularly in future before switching to daily releases.

The client-location is being added in new model update #2258

**Comment by p0wl** [comment]
Awesome! Do you know by chance if there is a regular cadence when the aws-sdk (v2) that comes with lambda is updated? (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
