### ISSUE TITLE
Policy version document in client-iam/GetPolicyVersion result are html-escaped

### ISSUE THREAD

**Issue by megapctr** [aws/aws-sdk-js-v3#1945]
**Describe the bug**
Policy version document is html-escaped, e.g. `"` characters become `&#34;` in the result from sdk-v3. Could this be related to XML parsing?

**SDK version number**
3.3.0

**Is the issue in the browser/Node.js/ReactNative?**
browser

**Details of the browser/Node.js/ReactNative version**
Chrome: 87.0.4280.88

**To Reproduce (observed behavior)**
Create an IAM policy version with with a JSON object in its `Details`. It will be impossible to use `JSON.parse(result.PolicyVersion.Document)` after fetching the policy version using sdk-v3:
```js
const resp = await awsIam.send(new GetPolicyVersionCommand({
  PolicyArn: policy.arn,
  VersionId: policy.defaultVersionId,
}))
// This will fail even though the document is a valid JSON string
const documentObj = JSON.parse(resp.PolicyVersion.Document)
```

**Expected behavior**
The policy document should be `JSON.parse`able

**Additional context**
It worked fine in sdk-v2

**Comment by ajredniwja** [comment]
Hi @megapctr thanks for opening an issue, reading the documentation found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IAM.html#getPolicyVersion-property), policies returned by this operation are URL-encoded compliant with RFC 3986. Which means you'll have to use a URL decoding method in order to receive the `document`. 

So basically you'd do something like:

```JavaScript
(async ()=> {

    const { IAMClient, GetPolicyVersionCommand } = require("@aws-sdk/client-iam");
    const client = new IAMClient({ region: "us-west-2" });

    var params = {
        PolicyArn: 'arn:aws:iam::, 
        VersionId: 'v1'
    };

    const command = new GetPolicyVersionCommand(params);

    try {
        const data = await client.send(command);
        var resp = data.PolicyVersion.Document;
        var decoded = decodeURIComponent(resp);
        var documentObj = JSON.parse(decoded);

        //console.log(documentObj);

    } catch (error) {
        console.log(error)
    } finally {
        // finally.
    }
}) ();
```

I was able to confirm that the behavior for v2 was similar as well, the v2 also returned encoded document. 

Please reach out if you have any other questions.
