### ISSUE TITLE
ApiGatewayManagementApiClient does not work. (403)

### ISSUE THREAD

**Issue by kidpollo** [aws/aws-sdk-js-v3#2001]
## Describe the bug
I could not make the ApiGatewayManagementApiClient work on V3 sdk with assumeRole credentials.

#### SDK version number
`"@aws-sdk/client-apigatewaymanagementapi": "^3.4.1",`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.14.1

## Steps to reproduce
In cljs (sorry)

``` clojure
;;  config => {:region "us-east-1", :credentials #object[Function], :endpoint "https://XXXX.execute-api.us-east-1.amazonaws.com/dev"}

(go
    (try
      (let [response (<p! (.send client (PostToConnectionCommand.
                                         (clj->js {:ConnectionId "aPt3IdMmoAMCEBw="
                                                   :Data (js/JSON.stringify #js {"bar" "value2" "foo" "test"})}))))]
        (tap> response)
        (js/console.log response))
      (catch
       js/Error err
        (js/console.log err)
        (tap> (ex-cause err)))))

```

#### Observed behavior
Get a forbidden exception
```
cljs$core$ExceptionInfo [Error]: Promise error
    at new cljs$core$ExceptionInfo (/Users/franciscovg/gr/ws-event-bridge/target/cljs-runtime/cljs/core.cljs:11332:1)
    at Function.cljs$core$IFn$_invoke$arity$3 (/Users/franciscovg/gr/ws-event-bridge/target/cljs-runtime/cljs/core.cljs:11361:1)
    at /Users/franciscovg/gr/ws-event-bridge/target/cljs-runtime/cljs/core/async/interop.cljs:24:12
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  message: 'Promise error',
  data: {
    meta: null,
    cnt: 1,
    arr: [ [Object], [Object] ],
    __hash: null,
    'cljs$lang$protocol_mask$partition0$': 16647951,
    'cljs$lang$protocol_mask$partition1$': 139268
  },
  cause: ForbiddenException: ForbiddenException
      at deserializeAws_restJson1PostToConnectionCommandError (/Users/franciscovg/gr/ws-event-bridge/node_modules/@aws-sdk/client-apigatewaymanagementapi/protocols/Aws_restJson1.ts:330:39)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
      at /Users/franciscovg/gr/ws-event-bridge/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18
      at /Users/franciscovg/gr/ws-event-bridge/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
      at StandardRetryStrategy.retry (/Users/franciscovg/gr/ws-event-bridge/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)
      at /Users/franciscovg/gr/ws-event-bridge/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20 {
    name: 'ForbiddenException',
    '$fault': 'client',
    '$metadata': {
      httpStatusCode: 403,
      requestId: 'd95cf8d1-e346-43f7-a8f4-eac0c4970b20',
      extendedRequestId: undefined,
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    }
  },
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: Promise error\n' +
    '    at new cljs$core$ExceptionInfo (/Users/franciscovg/gr/ws-event-bridge/target/cljs-runtime/cljs/core.cljs:11332:1)\n' +
    '    at Function.cljs$core$IFn$_invoke$arity$3 (/Users/franciscovg/gr/ws-event-bridge/target/cljs-runtime/cljs/core.cljs:11361:1)\n' +
    '    at /Users/franciscovg/gr/ws-event-bridge/target/cljs-runtime/cljs/core/async/interop.cljs:24:12\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:94:5)'
}
```

#### Expected behavior
Posting a message to a websocket

## Additional context
FWIW I am able to use the same config and credentials succesfully on DynamoDB commands

**Comment by AllanZhengYP** [comment]
Hi @kidpollo 

Thank you for reaching out to us. Can you confirm the issue still exists in JavaScript code? You can refer to [README](https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-apigatewaymanagementapi/README.md) as example.

**Comment by kidpollo** [comment]
Honestly there is nothing interesting about my clojurescript example.  The  problem comes when using https://github.com/aws/aws-sdk-js-v3/tree/master/packages/credential-provider-ini credentials with a roleAssumer function like
```js
{credentials: fromIni({
        roleAssumer: async (credentials, params) => {
            // no idea why we have to implement this ourselves.
            const sts = new STSClient({credentials});
            const response = await sts.send(new AssumeRoleCommand(params));
            return {
                accessKeyId: response.Credentials.AccessKeyId,
                secretAccessKey: response.Credentials.SecretAccessKey,
                sessionToken: response.Credentials.SessionToken,
                expiration: response.Credentials.Expiration,
            };
        }
    }
```

**Comment by jb4e** [comment]
@AllanZhengYP, I am able to repro this as well, but I think the profile credentials are a red herring. I am not able to get postToConnection to work at all with v3. I get the same 403 response as @kidpollo.

I created 2 node projects with HelloWorld examples of postToconnection. One uses the v2 sdk and one uses v3. The code is identical between the 2 except for the call to .promise() for v2. V2 works fine. V3 always gets a 403. 

Let me know if I can provide any additional info to help.

**Comment by DynamicArray** [comment]
Similar problem here.  Using the API Gateway websocket protocol, code that worked happily on v2  receives 403 response from the APIGateway when ported to v3.5.

v2 code that works:

```
exports.sendMessage = async ({ domainName, stage, connectionID, payload }) => {
	const ws = new apig({
		apiVersion: "2018-11-29",
		endpoint: `${domainName}/${stage}`
	});

	const postParams = {
		Data: JSON.stringify( payload ),
		ConnectionId: connectionID
	};

	return await ws
		.postToConnection( postParams )
		.promise()
		.catch(async err => {
			if (err.statusCode === 410) {
				await dynamo.delete(dynamo.tblConnections, { connectionID }).catch(dbErr => {
					console.error("Error deleting connection ID", dbErr);
				});
			}
		});
};
```

v3 code that gets 403:
```
exports.sendMessage = async ({ domainName, stage, connectionID, payload }) => {
	const api = new ApiGatewayManagementApiClient({
		apiVersion: "2018-11-29",
		endpoint: `https://${domainName}/${stage}`
	});

	const postParams = {
		Data: JSON.stringify(payload),
		ConnectionId: connectionID
	};

	try {
		await api.send( new PostToConnectionCommand( postParams ) );
	} catch( err ) {
		if (err.statusCode === 410) {
			await dynamo
				.delete(Dynamo.tblConnected, { ID: connectionID })
				.catch(dbErr => {
					console.error("Error deleting connection ID", dbErr);
				});
		}
	}
};
```

Happy to provide more if it helps.

**Comment by birtles** [comment]
I believe the problem here is that these commands ignore the path specified on the endpoint.

If one has:

```ts
const apiClient = new ApiGatewayManagementApiClient({
  endpoint: 'https://apiid.execute-api.us-west-2.amazonaws.com/stage'
});
const postCommand = new PostToConnectionCommand({
  ConnectionId: connectionId,
  Data: Buffer.from(JSON.stringify(message)),
});
await apiClient.send(postCommand);
```

Then in [`serializeAws_restJson1PostToConnectionCommand`](https://github.com/aws/aws-sdk-js-v3/blob/c612c75890a9b5005ff68b72bcac91761ce5dc14/clients/client-apigatewaymanagementapi/protocols/Aws_restJson1.ts#L79) for example, we have:

https://github.com/aws/aws-sdk-js-v3/blob/c612c75890a9b5005ff68b72bcac91761ce5dc14/clients/client-apigatewaymanagementapi/protocols/Aws_restJson1.ts#L86

followed by:

https://github.com/aws/aws-sdk-js-v3/blob/c612c75890a9b5005ff68b72bcac91761ce5dc14/clients/client-apigatewaymanagementapi/protocols/Aws_restJson1.ts#L100-L109

Here, `hostname` will be set to `apiid.execute-api.us-west-2.amazonaws.com` and hence the stage name part of the path (`/stage` in this example) will be dropped from the path and we'll attempt to POST to `https://apiid.execute-api.us-west-2.amazonaws.com/@connections/<connectionId>` producing the 403.

If we simply change that last part to:

```ts
  const { hostname, path, protocol = "https", port } = await context.endpoint();
  return new __HttpRequest({
    protocol,
    hostname,
    port,
    method: "POST",
    headers,
    path: path + resolvedPath,
    body,
  });
```

it should work.

**Comment by birtles** [comment]
I tried to make a PR for this but didn't succeed. Basically, I don't know how to get smithy to pull out the path from the endpoint context and make that into a parameter we can substitute into the path.

Getting the development environment working wasn't quite straightforward so I'll leave my experience here and hopefully turn it into a PR for `CONTRIBUTING.md` some day.

Firstly, after forking and cloning the repo, I noticed that the file I want to edit looks like generated code.

The [contributing guide](https://github.com/aws/aws-sdk-js-v3/blob/main/CONTRIBUTING.md) mentions running `yarn update-clients` so that seems like a good place to start.

According to `package.json` it's actually `yarn generate-clients` however.

Unsurprisingly, running that didn't work. (I've been around the block enough times to know these scripts never work first time.) Instead I got the following:

<summary>Log</summary>
<details>

```
$ yarn generate-clients
yarn run v1.22.5
$ node ./scripts/generate-clients
no model supplied, generating all AWS clients
Downloading https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
..........10%..........20%..........30%...........40%..........50%..........60%..........70%...........80%..........90%..........100%

Welcome to Gradle 6.8.3!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :protocol-test-codegen
(scanned and found a Smithy CLI version 1.5.1. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Configure project :sdk-codegen
(scanned and found a Smithy CLI version 1.5.1. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Task :sdk-codegen:clean UP-TO-DATE
> Task :smithy-aws-typescript-codegen:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smithy-aws-typescript-codegen:compileJava'.
> Could not resolve all files for configuration ':smithy-aws-typescript-codegen:compileClasspath'.
   > Could not find software.amazon.smithy:smithy-typescript-codegen:0.3.0.
     Searched in the following locations:
       - file:/home/birtles/.m2/repository/software/amazon/smithy/smithy-typescript-codegen/0.3.0/smithy-typescript-codegen-0.3.0.pom
       - https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-typescript-codegen/0.3.0/smithy-typescript-codegen-0.3.0.pom
     Required by:
         project :smithy-aws-typescript-codegen

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 23s
2 actionable tasks: 1 executed, 1 up-to-date
./gradlew failed with { code: 1, signal: null }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

I see someone else has had the same issue before over in #613. It's been closed by a commit that simply adds documentation saying to run `./gradlew clean publishToMavenLocal`.

I try running `./gradlew clean publishToMavenLocal` but I don't have gradlew apparently.

I've no idea what a .pom file is but a search tells me it's something to do with Maven. I don't know Maven but I try running `maven install software.amazon.smithy:smithy-typescript-codegen:0.3.0` anyway but apparently I don't have Maven either.

I head back to `package.json` hoping I just need to run another yarn command, so I give `yarn build:smithy-client` a whirl. It successfully runs, but `yarn generate-clients` still doesn't.

Per chance I discover a copy of `gradlew` in `codegen` so I try running `./gradlew clean publishToMavenLocal` there but with no luck.

<summary>Log</summary>
<details>

```
$ ./gradlew clean publishToMavenLocal

> Configure project :protocol-test-codegen
(scanned and found a Smithy CLI version 1.5.1. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Configure project :sdk-codegen
(scanned and found a Smithy CLI version 1.5.1. You will need to add an explicit dependency on smithy-model if publishing a JAR)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishToMavenLocal' not found in root project 'codegen'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 795ms
```

</details>

I try a dozen other things that bring no luck.

Somewhere along the way I find myself reading the [README.md](https://github.com/awslabs/smithy-typescript/blob/main/README.md) for `smithy-typescript` which talks about installing smithy to Maven local.

I give that a go but get stuck because my system doesn't have `javadoc` installed. 200+Mb of openjdk later and I have `javadoc`.

Back to `./gradlew publishToMavenLocal` for `smithy` and we're in luck. Next it's `smithy-typescript` which appears to download the world but eventually completes.

Finally, back to `aws-sdk-js-v3` for a `yarn generate-clients` and... no luck.

Curiously, the instructions for [`smithy-typescript`](https://github.com/awslabs/smithy-typescript) don't mention running `./gradlew publishToMavenLocal` for `smithy-typescript` only for `smithy` so I give that a try and we're in luck! `yarn generate-clients` is doing things!

It appears to be reformatting a million odd files, but it's happy doing it I think. Finally, a few minutes later it successfully completes and I can see my trivial change to `apigatewaymanagementapi.2018-11-29.json` has been reflected in `Aws_restJson1.ts`.

Now the real work can begin but, as I mentioned above, I have no idea how to get smithy to take the path from endpoint context and turn it into a parameter we can use in the path, and I've used too much time on this problem for one day.

**Comment by birtles** [comment]
@AllanZhengYP @trivikr I'm happy to work on a PR for this but I could use your advice about what the extension points are here and your preferred solution.

The summary is that ApiGatewayManagementApiClient is not functioning correctly because it drops the path from the provided endpoint and ends up posting to the wrong URL.

Assuming we want to keep the same API as v2—where we set the endpoint in the client and then have the commands pick that up—we need a way to get the path from the endpoint context and use that in the path/uri generated by each of the commands.

Alternatively, it's possible this client is working for literally no-one right now (unless POSTing to @​connections on a custom URL works?). If so, I suppose we could change the API such that the `stage` part of the endpoint is an input parameter to each command. That's less ergonomic but at least it seems straightforward to implement.

**Comment by jeanlescure** [comment]
It seems that this is a duplicate of #1830

**Comment by kidpollo** [comment]
@jeanlescure yup! Closing this one then.
