### ISSUE TITLE
Examples in documentation

### ISSUE THREAD

**Issue by kyeotic** [aws/aws-sdk-js-v3#2023]
## Describe the issue with documentation
A lack of examples makes it nearly impossible to figure out correct usage from the docs site itself. Usually the only way I can work it out is to go into the source code, or open an editor and use intellisense.

This is a general problem with typescript-generated docs. Without examples they are merely pointers to an often deep chain of type names.

## Steps to reproduce
Example: [getItem](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#getitem). I challenge anyone to figure out in _less than 5 clicks_ how to provide valid input to this function.

#### Observed behavior
Figuring out how to use functions from the documentation is incredibly difficult.

#### Expected behavior
It should be easy to understand how to use a function by viewing the documentation for that function.

**Comment by douglasnaphas** [comment]
Yes, please add examples to the API docs!

Every single method needs something I can copy and paste into my code.

I am going to use v2 of the AWS SDK for now because of this.

At least in v2 I have something like the Examples section [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminCreateUser-property).

Here's a screenshot of the example for Cognito's `adminCreateUser`:

<img width="1669" alt="Screen Shot 2021-02-15 at 7 23 10 PM" src="https://user-images.githubusercontent.com/5433410/108014732-62b0ec80-6fc3-11eb-8201-0224db2068c8.png">

So with that I know that I need to provide an object with properties named `UserPoolId` and `Username`.

The equivalent for v3 includes the docs for [AdminCreateUserCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/classes/admincreateusercommand.html), which takes an [AdminCreateUserCommandInput](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/globals.html#admincreateusercommandinput) object. But what properties does an `AdminCreateUserCommandInput` include? The docs for `AdminCreateUserCommandInput` just say the type name and have a link to some other TypeScript construct and a line in the source code.

<img width="975" alt="Screen Shot 2021-02-15 at 7 33 16 PM" src="https://user-images.githubusercontent.com/5433410/108015256-ac4e0700-6fc4-11eb-95e8-7418cfc49f0d.png">

From the above I do not see how I can figure out how to tell v3's `AdminCreateUserCommand` what User Pool I'm creating the user in.

The Cognito methods above are just an example--every single method for every single class in the v3 API needs an example that can be copied and pasted.

**Comment by alexforsyth** [comment]
Taggin @AllanZhengYP @brmur for visibility

**Comment by kogratte** [comment]
Almost perfect. But with a runtime who host the new sdk, it'll be perfect :)

**Comment by RanVaknin** [comment]
Hi @kyeotic @douglasnaphas ,

Sorry for the late response. We are aware of this issue, and are trying to rebuild our v3 docs to be more useful. 
Im going to close this issue in favor of tracking it in the [main one](https://github.com/aws/aws-sdk-js-v3/issues/4318) here. 

If this is still a concern for you, please upvote that issue so we can have more visibility to the community impact.

Thank you very much,
Ran~
