### ISSUE TITLE
Use react-native-url-polyfill instead of deprecated url.parse in url-parser-native

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2138]
### Is your feature request related to a problem? Please describe.
Deprecated [`url.parse()`](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) is used in url-parser-native https://github.com/aws/aws-sdk-js-v3/blob/105c9b7d73deeb7f9843a3add1e95399809a7327/packages/url-parser-native/src/index.ts#L3

### Describe the solution you'd like
Use [`react-native-url-polyfill`](https://www.npmjs.com/package/react-native-url-polyfill) which is recommended in favor of implementation of URL polyfill in react-native https://github.com/facebook/react-native/pull/25719#issuecomment-557955892

### Describe alternatives you've considered
Stick with deprecated `url.parse()` as it's not runtime deprecated yet.

**Comment by G-Rath** [comment]
Could this please done in the same manner as recommended for `react-native-get-random-values` in #2108?

Otherwise npm@7 will pull `react-native` in due to `react-native-url-polyfill` having it as a `peerDependency`, which [is not desirable for devs](https://github.com/aws/aws-sdk-js-v3/issues/1536) that [are not actually using `react-native`](https://github.com/aws/aws-sdk-js-v3/issues/1994), as it's [big](https://github.com/aws/aws-sdk-js-v3/issues/2150) and has [unpatchable vulnerabilities](https://github.com/DEFRA/sroc-charging-module-api/pull/300) :)

(Maybe an `@aws-sdk/utils-react-native-polyfils` package could be a good idea, that has all of these and does the requiring, so you could say to folks "if you're on `react-native`, install and require this extra package).

**Comment by trivikr** [comment]
Created an issue upstream to make react-native peerDependency optional https://github.com/charpeni/react-native-url-polyfill/issues/269
