### ISSUE TITLE
@aws-sdk/types 3.10.0 broke Typescript 3 compatibility

### ISSUE THREAD

**Issue by legraphista** [aws/aws-sdk-js-v3#2217]
## Describe the bug
This line is not backward compatible to Typescript V3
https://github.com/aws/aws-sdk-js-v3/blob/4a33342d11e4d8178a23bf8a23434fa83e4e40da/packages/types/src/util.ts#L109

#### SDK version number
`@aws-sdk/types@3.10.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`node -v`: `v12.22.1`
`tsc -v`: `Version 3.9.9`

## Steps to reproduce
package.json
```json
{
  "dependencies": {
    "@aws-sdk/types": "^3.10.0"
  }
}
```

test.ts
```typescript
import '@aws-sdk/types'
```

terminal
```bash
yarn && tsc --lib test.ts
```

#### Observed behavior
```
node_modules/@aws-sdk/types/dist/types/util.d.ts:92:42 - error TS1005: ',' expected.

92 export declare type UserAgentPair = [name: string, version?: string];
                                            ~

node_modules/@aws-sdk/types/dist/types/util.d.ts:92:60 - error TS1005: ',' expected.

92 export declare type UserAgentPair = [name: string, version?: string];
                                                              ~

```

#### Expected behavior
test.ts should compile with no errors
 
## Additional context
@aws-sdk/types v3.6.1 had no issues compiling in TS3

**Comment by trivikr** [comment]
This issue seems to be happening, as postbuild is run twice on `packages/types`

Verified as follows:
```console
> yarn build
yarn run v1.22.5
$ yarn build:es && yarn build:cjs
$ tsc -p tsconfig.es.json
$ tsc -p tsconfig.cjs.json
$ downlevel-dts dist/types dist/types/ts3.4
Done in 9.06s.

> ls dist/types 
abort.d.ts  client.d.ts  command.d.ts  credentials.d.ts  crypto.d.ts  eventStream.d.ts  http.d.ts  index.d.ts  logger.d.ts  middleware.d.ts  pagination.d.ts  response.d.ts  serde.d.ts  signature.d.ts  transfer.d.ts  ts3.4  util.d.ts

> ls dist/types/ts3.4 
abort.d.ts  client.d.ts  command.d.ts  credentials.d.ts  crypto.d.ts  eventStream.d.ts  http.d.ts  index.d.ts  logger.d.ts  middleware.d.ts  pagination.d.ts  response.d.ts  serde.d.ts  signature.d.ts  transfer.d.ts  util.d.ts

> yarn build
yarn run v1.22.5

> yarn build:es && yarn build:cjs
$ tsc -p tsconfig.es.json
$ tsc -p tsconfig.cjs.json
$ downlevel-dts dist/types dist/types/ts3.4
Done in 4.33s.
dev-dsk-trivikr-2b-b5d0913a: types> ls dist/types/ts3.4
abort.d.ts  client.d.ts  command.d.ts  credentials.d.ts  crypto.d.ts  eventStream.d.ts  http.d.ts  index.d.ts  logger.d.ts  middleware.d.ts  pagination.d.ts  response.d.ts  serde.d.ts  signature.d.ts  transfer.d.ts  ts3.4  util.d.ts
```

This could be happening as `packages/types` is built twice, once as part of crypto-dependencies and second time as part of lerna run build.
https://github.com/aws/aws-sdk-js-v3/blob/4a33342d11e4d8178a23bf8a23434fa83e4e40da/package.json#L18

**Comment by trivikr** [comment]
A probable fix would be to move downlevel-dts from `postbuild` to `prepublishOnly` for the following reasons:
* The CI hasn't failed because of backward incompatible types since https://github.com/aws/aws-sdk-js-v3/pull/1938
* The build takes lot of time since the introduction of downlevel-dts in postbuild, and developers usually don't test with old versions of TypeScript.

A GitHub Action needs to be written to regularly run prepublish to ensure types are backward compatible.

**Comment by trivikr** [comment]
Metrics:

<details>
<summary>build time with downlevel-dts in postbuild</summary>

```console
$ git clean -dfx && yarn

$ time yarn build:all
...
Done in 850.77s.
yarn build:all  12588.02s user 307.90s system 1515% cpu 14:10.90 total
```

</details>

<details>
<summary>build time with downlevel-dts in prepublishOnly</summary>

```console
$ git clean -dfx && yarn

$ time yarn build:all
...
Done in 736.90s.
yarn build:all  10956.08s user 248.51s system 1520% cpu 12:17.03 total
```

</details>


The SDK maintainers can explicitly run `prepublishOnly` if they want to test downlevel-dts
```console
$ ./node_modules/.bin/lerna run prepublishOnly
```
