### ISSUE TITLE
[@aws-sdk/client-lambda] - Payload data in uint8array format - how to resolve data to expected output?

### ISSUE THREAD

**Issue by NickLiffen** [aws/aws-sdk-js-v3#2252]
## Describe the bug

When using the new AWS Client Lambda NPM Module, and when invoking a lambda, data from `Payload` is returned in a `Uint8Array`. I can't find a way to resolve/get the data in the original JSON format that it should be? 

#### SDK version number
"@aws-sdk/client-lambda": "^3.12.0",

#### Is the issue in the browser/Node.js/ReactNative?
NodeJS

#### Details of the browser/Node.js/ReactNative version
Node 14.6.1

## Steps to reproduce

**Lambda A tried to invoke Lambda GITHUB_TOKEN_FUNCTION**

```
const { LambdaClient, InvokeCommand } = require('@aws-sdk/client-lambda');

module.exports = {
  getGitHubToken: async () => {
    const client = new LambdaClient({ region: process.env.REGION });

    const params = {
      FunctionName: process.env.GITHUB_TOKEN_FUNCTION,
      LogType: 'Tail',
      Payload: '',
    };

    const command = new InvokeCommand(params);

    try {
      const { Payload } = await client.send(command);
      console.log(Payload)
      return str;
    } catch (error) {
      console.log(error.message);
      throw error;
    }
  },
};

```

**GITHUB_TOKEN_FUNCTION should return this:**

```
const res = {
      statusCode: 200,
      body: JSON.stringify({
        token,
      }),
```

However, when I `console.log(Payload)` I get this:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/6696451/114701039-3511c680-9d1a-11eb-959e-c1d155acfa8a.png">

In the old module (v2) I never got this, I just got the data back as returned from the `GITHUB_TOKEN_FUNCTION`. Which should be:

```
const res = {
      statusCode: 200,
      body: JSON.stringify({
        token,
      }),
```

I have checked the CloudWatch logs for `GITHUB_TOKEN_FUNCTION` and it is successfully sending that object. Lambda A just receives it in a different format that I can't seem to get into the expected one. 

#### Observed behavior
I get some sort of `Unit8Array` back that I can't find out how to turn into the data I expect.

#### Expected behavior
`Payload` ===

```
const res = {
      statusCode: 200,
      body: JSON.stringify({
        token,
      }),
```

My Question:

How do I resolve data from `Unit8Array` to the data I was expecting from the Lambda response? Which is a JSON Object?

**Comment by NickLiffen** [comment]
Okay, I got it working:

```
const asciiDecoder = new TextDecoder('ascii');
const data = asciiDecoder.decode(Payload);
```

A question, why is this module not doing this 🤔 / why is there not an option to do this? 🤔 The reason we use this module is to not have to interact with the apis and services natively. It would be good if this module handled it.

**Comment by NickLiffen** [comment]
Sorry to keep on moaning here but also it makes testing really hard 🤔 We use Jest and there are a bunch of problems with TextDecode and TextEncode. As found [here](https://stackoverflow.com/questions/55521787/filereader-file-and-textdecoder-in-jest-test-not-defined) and [here](https://github.com/facebook/jest/issues/9983).

**Comment by NickLiffen** [comment]
I have looked at the "style" of this library and I think It isn't intended for the module to "by default" decode for the user. I think when it comes to Lambda Invoke especially; it would be good if you could maybe pass in a boolean or something to:

```
    const params = {
      FunctionName: process.env.GITHUB_TOKEN_FUNCTION,
      LogType: 'Tail',
      Payload: '',
    };
```

called: `decode: true/false`. 

The value of this module is the abstraction and I think this would really help out people using this module 👍 Just a thought.

**Comment by NickLiffen** [comment]
I see there is some sort of [encoder interface](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-lambda/interfaces/encoder.html), is this exposed by any chance to the client so I can run this within my code?

**Comment by plummet555** [comment]
I came across the same issue. It does seem odd that we have to decode and then re-parse the output like this:
        const asciiDecoder = new TextDecoder('ascii');
        const creds = JSON.parse(asciiDecoder.decode(data.Payload));

**Comment by ffxsam** [comment]
Just a slight correction to the above:

```js
const asciiDecoder = new TextDecoder('utf-8');
```

This method works too, and requires a little less code:

```js
const creds = JSON.parse(Buffer.from(data.Payload).toString());
```
```

I agree, I'm not sure why the decision was made to use `Uint8Array`. It's really inconvenient.

**Comment by ajredniwja** [comment]
@NickLiffen thanks for opening this issue, apologies for late reply, I think this is the expected behavior for this SDK as you can see payload is now of type `unit8array` https://github.com/aws/aws-sdk-js-v3/blob/3bd30bb798cee9739b98842cfdca5a6b60dec124/clients/client-lambda/models/models_0.ts#L3490. 

I have verified that the @ffxsam code which seems to work. 

With that being said, I think this behavior can be documented but I believe its not a bug. I will mark it as a documentation issue.

**Comment by dgurns** [comment]
Agreed with the above posters. In a JavaScript/TypeScript environment, being able to access the payload data as JSON, even by passing in a flag, would be a major quality of life improvement.

**Comment by toto922** [comment]
This offical util can be uesd to decode and encode ↓

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_util_utf8_node.html

**Comment by sebastien-abbal** [comment]
For typescript, I don't have errors if I use that kind of payload :

```typescript
    lambda.invoke({
      FunctionName: CONVERTER_FILE_INFOS_LAMBDA_NAME,
      InvocationType: 'RequestResponse',
      Payload: Buffer.from(JSON.stringify({ foo: 'bar' })),
    });
```

Hope it will be usefull :)

**Comment by iRoachie** [comment]
Can anyone shed light on this decision? @ajredniwja  Seems very unorthodox especially coming from v2.

**Comment by juicycool92** [comment]
i still want to hear why they decide to use uint8array instead string. :/
does this changed type cost less or something?

**Comment by l3wy** [comment]
This still isn't documented (or at least well documented).  The migration from v2 to v3 page indicates that it should be mostly a transparent migration, no mention of breaking changes (which this definitely is). 

That said, I don't agree that this is a documentation issue.  Just because someone decided to define the Payload type as uint8array in an output interface doesn't mean that it was an appropriate decision to make.  It should have defaulted to the old Payload format and had an optional encoding param if you desired the output (or wanted to provide the input) in a different way.  

Also worth noting that the input payload can still be provided as a string (which further confuses the issue).

**Comment by Unintendedz** [comment]
For me who is new to cloud development, it is very frustrating to not be able to find the correct example from [SDK Document](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-lambda/interfaces/invokecommandinput.html#payload) and have to go through search engines for `lambda payload Uint8Array` and find the solution from the comments of this issue.

**Comment by kuhe** [comment]
The reason for the response type not being `string` is because Lambda functions are user controlled and may return a response that should not be converted into a string.

Upstream, AWS Lambda's definition for the `InvocationResponse::Payload` field is Blob, and not string. While AWS SDK JS v2 was more convenient for string responses, this did not support other response types. V3 aims to both support other response types and more closely follow the AWS service's definitions for input and output types. 

As to how we could make this more convenient, there was a similar issue with `S3::getObject` https://github.com/aws/aws-sdk-js-v3/issues/1877 returning a stream, with solution described in [README](https://github.com/aws/aws-sdk-js-v3/tree/main#streams) for which the solution was to apply a "mixin" that added helper methods to convert the response to a string. Something similar could be done here.

- [ ] add mixin to help convert Blob responses such as `Lambda::invocationResponse::Payload` to string https://github.com/aws/aws-sdk-js-v3/issues/4265

-----

For now, please use one of the suggestions above (@ffxsam) to convert the value to a string.

Where `data` is the invocation response,

```js
// browser
const asciiDecoder = new TextDecoder('utf-8');
const object = JSON.parse(asciiDecoder.decode(data.Payload));

// Node.js
const object = JSON.parse(Buffer.from(data.Payload).toString());
```

Omit or replace `JSON.parse` if you are not using a JSON serialization.

**Comment by RanVaknin** [comment]
Seems like @kuhe answered the question. I feel like this can be closed. If more questions arise, please feel free to open a new issue.

Thanks,
Ran~

**Comment by kuhe** [comment]
in a recently released version https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.357.0, Lambda::invoke and all other payload blobs are no longer restricted to Uint8Array, and can be sent in as strings, and converted to strings on output too:

```typescript
import { InvokeCommand, LambdaClient } from "@aws-sdk/client-lambda";
import { Uint8ArrayBlobAdapter } from "@aws-sdk/util-stream";

const lambda = new LambdaClient({
  region: "us-east-1",
});

const invoke = lambda.send(
  new InvokeCommand({
    FunctionName: "echo",
    Payload: JSON.stringify({
      hello: "world",
    }),
  })
);

const payload: Uint8ArrayBlobAdapter = (await invoke).Payload!;

console.log(JSON.parse(payload?.transformToString() ?? "{}")); // { "hello": "world" }
```
