### ISSUE TITLE
[S3 Client] Errors if the `Body` of `PutObjectCommand`  is a `Readable` type.

### ISSUE THREAD

**Issue by yaquawa** [aws/aws-sdk-js-v3#2348]
**Describe the bug**

I got this error when I set the `Body` to a `Readable` type.

```
(node:88634) UnhandledPromiseRejectionWarning: NotImplemented: A header you provided implies functionality that is not implemented
```
**SDK version number**
3.13.1

**To Reproduce (observed behavior)**
```ts
import { fromIni } from '@aws-sdk/credential-provider-ini'
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3'
import https from 'https'
import { Readable } from 'stream'
import awsConfig from './aws-exports'

const s3Client = new S3Client({
  credentials: fromIni({ profile: 'default' }),
  region: 'ap-northeast-1',
})

async function getFileFromUrl(url: string): Promise<Readable> {
  return new Promise((resolve) => {
    https.get(url, (response) => {
      resolve(response)
    })
  })
}

async function upload(file: Readable) {
  const uploadCommand = new PutObjectCommand({
    Bucket: awsConfig.aws_user_files_s3_bucket,
    Key: 'test.jpg',
    Body: file,
    ACL: 'public-read',
  })

  await s3Client.send(uploadCommand)
}

async function migrate() {
  const file = await getFileFromUrl(
    'https://example.com/logo.png'
  )
  await upload(file)
  console.log('done')
}

migrate()
```

I could confirm that it's ok if I change the `Body` to a string, so I'm sure I have the right permission to put an object to the bucket.

**Comment by fabis94** [comment]
I'm running into the same issue. In v2 of the SDK you could easily upload streams of unknown length through `s3.upload()`, but doesn't look like this is possible with v3. The error message could be better as well, it could let you know that `Content-Length` is missing, instead of mentioning the `Transfer-Encoding` header which seems completely irrelevant.

Pretty big regression, I would say, just because of this I have to revert back to v2 of the SDK as there is no other way to easily upload streams of unknown length.

**Comment by AllanZhengYP** [comment]
Hi @fabis94 @yaquawa @guanzo, The error is indeed caused by stream length remaining unknown. We need to improve the error message and the documentation. As it's pointed out in the [Upgrading Guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#s3-multipart-upload), the similar functionality as `s3.upload()` in v2 is now moved to [`@aws-sdk/lib-storage`](https://www.npmjs.com/package/@aws-sdk/lib-storage) package.

**Comment by guanzo** [comment]
Aha, so this is intended behavior. I did not check the upgrade guide. Thanks for the update!

**Comment by ffxsam** [comment]
Pardon my ignorant question, but isn't the point of a stream that you don't know the length? How could `putObject` require a `Content-Length` header for a readable stream input?

@AllanZhengYP What's the proper course of action here, then? To use `Upload` in `@aws-sdk/lib-storage` instead?

**Comment by ffxsam** [comment]
Just in case anyone needs a clear answer: `putObject` can't write a stream to S3, you have to use the `Upload` class in `@aws-sdk/lib-storage`.
