### ISSUE TITLE
suggestion: Investigate using TypeScript with babel

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#235]
Currently we use TypeScript directly within the project.
In Aug 2018, TypeScript plugin for babel was released ([link](https://devblogs.microsoft.com/typescript/typescript-and-babel-7/)) and it can be used with lerna ([example](https://github.com/serhii-havrylenko/monorepo-babel-ts-lerna-starter#typescript))

This issue is about investigating whether TypeScript with babel will make SDK v3 simpler.

**Comment by AllanFly120** [comment]
@trivikr This is an interesting idea, but I'm not sure whether it will make V3 simpler or what problem is it going to solve. From my point of view we are still going to write TypeScript with the babal plugin. The selling point for TS babel plugin, I think, is that babel offers better transpiler configuration than TypeScript does. So Typescript will be more appear to projects that currently using babel and feel headache adopting the Typescript. Since V3 doesn't use bebal currently, it seems to me just another level of complexity and transpiling.

 Maybe I have some misunderstanding there, maybe some further direction of the investigation will help.

**Comment by trivikr** [comment]
Closing as we're not using babel right now, and introducing it will complicate things.
The primary reason TypeScript introduced support for babel is for existing projects - which already used babel for transpilation and had their scripts set up - can easily use TypeScript for typings.
