### ISSUE TITLE
Hard dependency on Webpack

### ISSUE THREAD

**Issue by 75lb** [aws/aws-sdk-js-v3#2503]
According to the docs, to use this SDK in the browser I need to install Webpack.. Do I really need to install, learn and use a complex third-party development stack to use this library? I only need to persist one value in DynamoDB - seems massively overkill.

This hard dependency on Webpack just adds friction and makes consuming AWS Web services (with v3) more costly in terms of time.. To consume most other APIs, all you need is one or two keys/tokens and a `fetch` statement.. 

Could you take Webpack out of the equation please? What if they deprecate it?

**Comment by 604587986** [comment]
+1

**Comment by vudh1** [comment]
Hi @75lb , thanks for reaching out. You can use this ([link](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/building-sdk-for-browsers.html) for more details. For v3 SDK, because we try to reduce overhead by using small JavaScript files of SDKs you require, bundlers are required to combine into one file and load it into browser scripts using a <script> tag. In the other hand, you can use any bundlers of your choice (Webpack, EsBuild, Rollup), and in most cases, all the popular front-end frameworks already support bundling code.
