### ISSUE TITLE
@aws-sdk/client-kms is missing support for kms-multi-region-keys

### ISSUE THREAD

**Issue by adcreare** [aws/aws-sdk-js-v3#2511]
## Describe the bug
AWS have released multi-region keys
https://aws.amazon.com/about-aws/whats-new/2021/06/kms-multi-region-keys/ however the latest V3 sdk (3.18.0) doesn't support it but the old V2 does have support added

#### SDK version number
`@aws-sdk/client-kms@3.18.0` (current latest)

#### Is the issue in the browser/Node.js/ReactNative?
Node.js but would be browser and reactnative as well

## Steps to reproduce
Use the 3.18.0 sdk (current latest) and try to setup multi-region kms keys. Typing errors will occur as types don't exist in the V3 sdk for multi-region keys yet. 

#### Observed behavior
I would expect the KMS multi-region support that has been released in the V2 SDK to exist in the V3 sdk at the same time. 
Specifically kms.replicateKey and the MultiRegionConfiguration result from kms.describeKey is missing.

#### Expected behavior
I would expect the V3 SDK which is now being recommended by AWS would have new service operations released at exactly the same time as V2. The V2 sdk version 2.930.0https://github.com/aws/aws-sdk-js/releases/tag/v2.930.0
I don't understand why new features aren't sync'd up with the aws support SDKs. Its almost as bad as getting cloudformation support on new services.. AWS need to go better here or everyone is just going to stick with the old sdk which appears to maintained in a more timely fashion.

**Comment by ajredniwja** [comment]
Hi @adcreare thanks for brining this up, the V3 currently does not do automatic releases like V2 which is because this feature got late on V3 as the last release was just done 5 days ago. With that being said, there should be support for support for kms-multi-region-keys in the latest version of the SDK 3.19. 
Also we are looking forward to automate the process but dont have a real timeline on it. 

I will bring this is up with the team again. 

Closing this issue now, please reach out if you have any other questions.
