### ISSUE TITLE
No way to list all batch jobs in a queue without race condition

### ISSUE THREAD

**Issue by rooby** [aws/aws-sdk-js-v3#2584]
## Describe the bug
The Batch API ListJobsCommand can never be trusted to reliably list all jobs in a queue.

This is because the jobStatus parameter is a string where you can only specify a single status and omitting the param still applies a default status of RUNNING.

This means that to list all jobs you need to do multiple requests to check each status, so there could be a job transitioning through states in a way that is missed by the multiple requests for different statuses.

There is no way to reliably be sure that you have listed all jobs in the queue and not missed any.

#### SDK version number
`@aws-sdk/client-batch@3.21.0`

Really all version of all SDKs are affected. It is not limited to javascript.

#### Is the issue in the browser/Node.js/ReactNative?
Everywhere

#### Details of the browser/Node.js/ReactNative version
Not browser dependent.

## Steps to reproduce
Do any request to list jobs and see that you can only get one status at a time. This means you can never get a reliable, definitive list of all jobs in a queue at a given time.

#### Observed behavior
You can only query a single status at a time.

#### Expected behavior
To able to query multiple statuses in a single request.

**Comment by ajredniwja** [comment]
Hi @rooby thanks for opening this issue, I am not sure if I understand the ask here, https://docs.aws.amazon.com/batch/latest/APIReference/API_ListJobs.html the operation returns a list of jobs in a queue. Can you share the code that you are using?

**Comment by rooby** [comment]
@ajredniwja Here's an example of what you have to do currently:

```
    let existingJob = false;
    const statuses = ['SUBMITTED', 'PENDING', 'RUNNABLE', 'STARTING', 'RUNNING'];
    for (status of statuses) {
        const response = await batch.listJobs({
            jobQueue: MY_JOB_QUEUE,
            jobStatus: status
        }).promise();
        if (response?.jobSummaryList?.length) {
            existingJob = true;
            break;
        }
    }
```

The problem with that code, is that it is possible to get inaccurate results since a job may transition between statuses between individual requests to ListJobs. This is somewhat mitigated by the order that the statuses are queried, but it would still be better to be able to do a single request.

The problem is that [ListJobs](https://docs.aws.amazon.com/batch/latest/APIReference/API_ListJobs.html) only accepts a single status at a time, and it defaults to 'RUNNING'.
It would be preferable if you could specify multiple statuses.

The docs also say that if you add filters, then `jobStatus` is ignored, but that doesn't help either, since you cannot filter by status.

**Comment by rooby** [comment]
Yes this is still an issue. Please don't close it.

**Comment by RanVaknin** [comment]
Hi @rooby ,

Sorry for the long wait.

I see what you are saying, but Im confused by your very last statement.

>The docs also say that if you add filters, then jobStatus is ignored, but that doesn't help either, since you cannot filter by status.

From what you have described you don't want to filter by status, you want to all jobs with all statuses. In that case you can the Filter argument without the `Status` argument.  I'm not sure how this does not solve your problem.

For example `AFTER_CREATED_AT` set to 1/1/2021 will result in all jobs (with any status) that were created after the said date. It seems like a pretty reliable way to count all tasks if you know your start date.

At any rate, the data set returned from the service is not determined by the SDK. Since the SDK is a client, it can only facilitates requests on your behalf and help model your data in a convenient way. 
We don't really have a way to change the data being returned from the service. 

Let me know if there's anything else I can do.

Thanks,
Ran~
