### ISSUE TITLE
suggestion: generate interfaces for services

### ISSUE THREAD

**Issue by Ghostium** [aws/aws-sdk-js-v3#261]
Currently, services are exported as classes. Generating interfaces and exporting them would make it easier to switch out implementations. Then the library consumer could depend on the interface not the implementation.

```ts
class S3 implements IS3 {
```

Examples what someone might want to implement behind an S3 interface:
- In-Memory implementation for **much** faster integration tests
- Local filesystem implementation for sensitive data
- Exposing files from remote websites as virtual read only objects in bucket
- Exposing "computed" objects which are generated on request
- Combining multiple implementations and "routing" based on bucket name

Some of those _could_ be implemented at the HTTP level or via the provided Middleware functionality, but some make only sense implemented directly as an implementation of an TypeScript interface.

**Comment by AllanFly120** [comment]
Hey @Ghostium 

Thanks for the feedback. I think I get your point of having a monolithic `S3` interface. It's helpful when you want to rely on some APIs provided by `S3`. But I recommand to use `S3Client` + `OperationCommand` to call the API, since `S3` is just a wrapper for `S3Client` in order to make it easy to transit from V2 SDK.

The design goal for V3 is to import the commands(like [`GetObjectCommand`](https://github.com/aws/aws-sdk-js-v3/blob/master/packages/client-s3-node/commands/GetObjectCommand.ts)) only. To call an API, you need to import the service client(like [`S3Client`](https://github.com/aws/aws-sdk-js-v3/blob/master/packages/client-s3-node/S3Client.ts)) and supply standalone commands to the client. This design will make full use of the treeshaking, and you only need to import the commands you actually need. Here's an example: 

```typescript
import {GetObjectCommand} from '@aws-sdk/client-s3-node/commands/GetObjectCommand';
import {S3Client} from '@aws-sdk/client-s3-node/S3Client';

export async function handler() {

    const client = new S3Client({
        region: 'us-west-2'
    });

    try {
        const command = new GetObjectCommand({
            Bucket: 'bucket',
            Key: 'key'
        });

        const result = await client.send(command);
    } catch (err) {
        console.error(err);
        throw err;
    }
}
```

This will give a smaller bundle size. So we recommand you make request in this manner. Actually, I'm considering removing the client interface like `S3` at all from the packages. It's intended to mimic a similar interface as V2 SDK but it actually brings more drawbacks: bigger bundle size, lack exported interfaces as you suggested.

As it indicated from this design, implements you suggested make more sense to be made in middleware functions. For other functionalities, you can also build higher level functions/modules that takes in the SDK service clients and do what you want to do, instead of extending from existing client class.

**Comment by Ghostium** [comment]
That brilliant, thank you for clarifying. It seems I've misunderstood how the library should be used, as I only skimmed the readme, and went with the old way which was familiar to me, that was bad on my end, sorry. You are right, in this form, implementing it at the middleware layer makes much more sense. Mimicking the parts of the old v2 API might bring a lot of expectations from users switching from v2.  I agree, it might be the right decision not offering the 'v2 mimic layer'. Maybe some of it can be reused for a *real* v2 compatibility layer for the transition to https://github.com/aws/aws-sdk-js.
