### ISSUE TITLE
SQS - Support for virtual queues?

### ISSUE THREAD

**Issue by tom-sherman** [aws/aws-sdk-js-v3#2748]
I'm not actually sure if this is supported? It's not clear from the documentation

### Is your feature request related to a problem? Please describe.

Implementing a request/response pattern in SQS

### Describe the solution you'd like
Virtual temporary queues as described here: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-temporary-queues.html

### Describe alternatives you've considered
Implementing it ourselves on top of the SQS client

### Additional context
None

**Comment by tom-sherman** [comment]
Relevant: https://github.com/awslabs/amazon-sqs-java-temporary-queues-client/issues/15

**Comment by miekassu** [comment]
+1 for this feature

**Comment by kitsunde** [comment]
This would significantly simplify situations where we need to throughput limit things in an already deployed system that's expecting synchronous execution to happen, without having to move in more complex logic or re-architecture flows.

I hope this can get more attention.

**Comment by aBurmeseDev** [comment]
Hey all - apology for the long silence here. This's something that needs to be implemented on service level by SQS rather than SDK. I'm going to submit an internal request to service team and will post when I hear back. (ref: _V1394603877_)

Can you all please provide the details in your use case and some examples so that service can use it as reference?

**Comment by tom-sherman** [comment]
Why does it require work on the service level when temporary queues are already available to use with the Java SDK?

I have a use case described here: https://tom-sherman.com/blog/serverless-xstate
