### ISSUE TITLE
Place module: expose short version of Region

### ISSUE THREAD

**Issue by jzabinski-dolios** [aws/aws-sdk-js-v3#3012]
### Is your feature request related to a problem? Please describe.
In the `Place` [global](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-location/modules/place.html), `Region` contains the full description of the region. 'Rhode Island', for example. `Label` contains a shorter version: 'RI'. It would be useful to have this shorter version available as a discrete field so that, for example, a condensed address can be shown for mobile devices.

### Describe the solution you'd like
In my opinion, the ideal solution would be to change `Region` to an object, containing `Text` and `Abbrev` properties. The `Text` property would be set to the existing value of `Region`: the abbreviation would be in `Abbrev`. If it needs to be backwards-compatible, a new field could be added.

### Describe alternatives you've considered
Another API could be added to convert `Region`s (and whatever else) to their abbreviated form.

### Additional context
Example of what is available now:
```
Label: "Woodland Rd, Woonsocket, RI, 02895, USA"
Region: "Rhode Island"
```

Example of the request:
```
Label: "Woodland Rd, Woonsocket, RI, 02895, USA"
Region: { Text: "Rhode Island", Abbrev: "RI" }
```
Or:
```
Label: "Woodland Rd, Woonsocket, RI, 02895, USA"
Region: "Rhode Island"
AbbrevRegion: "RI"
```

**Comment by RanVaknin** [comment]
Hi @jzabinski-dolios ,

Thanks for the request! Unfortunately what you are asking for is not something the SDK team can change. The SDK is auto-generated from that Location' Service API, and since its client it doesn't have any modeling capabilities.

You can find a copy of the API model [here](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/location.json#L5850-L5855), this is a json representation of the API model owned by the Location service team. 

Thanks for engaging in the community. 
All the best,
Ran~
