### ISSUE TITLE
Custom endpoint not used when bucketEndpoint is true

### ISSUE THREAD

**Issue by MancunianSam** [aws/aws-sdk-js-v3#3031]
## Describe the bug
We have a cloudfront distribution which authenticates with signed cookies. We use this to upload files to S3 as this allows us to have a custom domain endpoint for the S3 upload. Some of our users are not able to access AWS S3 urls.
When we were using AWS SDK V2, we were able to set `xhrWithCredentials` and then set the `endpoint` to out Cloudfront distribution and `s3BucketEndpoint` to true and the SDK would construct the upload urls in the form https://custom.domain.com/s3KeyName.

I cannot replicate this in V3 of the SDK. The path is different and I can't find how to set the xhrWithCredentials setting. This may not be a bug but I can't find anything in the documentation to help me replicate the original behaviour.

#### SDK version number
@aws-sdk/client-s3 and @aws-sdk/lib-storage 3.41.0

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
Chrome: 95.0.4638.69
## Steps to reproduce
I try to upload a file like this

```js
const config: S3ClientConfig = {
  region: "eu-west-2",
  endpoint: { hostname: example.com, protocol: "https", path: "/" },
  credentials: {
    accessKeyId: "placeholder-id",
    secretAccessKey: "placeholder-secret",
  },
  bucketEndpoint: true,
};
const client = new S3Client(config);
const params = { Key: "key", Bucket: "bucket", Body: file };
const progress = new Upload({ client, params });
```

#### Observed behavior
The SDK will try to upload to https://bucket/key.
If I set `forcePathStyle` to true as well, then it will send to https://example.com/bucket/key 

I did get it to output https://example.com/key by setting forcePathStyle to true and then adding in this middleware.

```js
client.middlewareStack.add(
  (next, context) => async (args: any) => {
    args.request.path = `/${args.request.path.split("/").slice(2).join("/")}`;
    args.request.query = {};
    return await next(args);
  },
  { step: "build", name: "removeBucketName" }
);
```
I don't know if there is a better way to do this.

With the middleware, the path is https://example.com/key but the cookies are not sent. The [migration guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#client-constructors) says xhrWithCredentials needs to be set in the base fetch options but the `FetchHttpHandler` only has one option for request timeout so I'm not sure how to set it.

#### Expected behavior
I would have expected it to send to https://example.com/key from the behaviour of V2 of the SDK but it is ignoring the endpoint override. The forcePathStyle url is better in that it uses the custom endpoint but it still includes the bucket name where it didn't before. 

I would also like the request to send any cookies from the browser but I can't see any way to do this.

**Comment by ajredniwja** [comment]
Hi @MancunianSam thanks for opening this issue, I think this behavior/process should be mentioned in the docs. I will track it as a documentation issue. As for the cookies, is it possible for you to open a separate issue(feature-request) and cc @AllanZhengYP as he'll be able to provide some insight on that. Thanks

**Comment by trivikr** [comment]
Visiting this issue from internal discussion in V477160346

On writing test code, this appears to be a bug in AWS SDK for JavaScript (v3) as it sets hostname as bucket name.

For example, if the bucket name is `test-bucket` the v3 request will fail with:
```console
Error: getaddrinfo ENOTFOUND test-bucket
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'test-bucket',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

Test code:
<details>
<summary>AWS SDK for JavaScript (v2)</summary>

```js
import AWS from "aws-sdk"; // v2.1046.0

const region = "us-west-2";
const endpoint = "https://example.com";
const s3BucketEndpoint = true;
const client = new AWS.S3({ region, endpoint, s3BucketEndpoint });

const Bucket = "test-bucket";
const Key = "test-key";

const req = client.getObject({ Bucket, Key });
req.on("error", () => {
  console.log({
    hostname: req.httpRequest.endpoint.hostname,
    path: req.httpRequest.path,
  });
});
req.send(function () {});
```

```console
{ hostname: 'example.com', path: '/test-key' }
```

</details> 

<details>
<summary>AWS SDK for JavaScript (v3)</summary>

```js
import { S3 } from "@aws-sdk/client-s3"; // v3.44.0

const region = "us-west-2";
const endpoint = "https://example.com";
const bucketEndpoint = true;
const client = new S3({ region, endpoint, bucketEndpoint });

client.middlewareStack.add(
  (next, context) => (args) => {
    console.log({ hostname: args.request.hostname, path: args.request.path });
    return next(args);
  },
  { step: "finalizeRequest" }
);

const Bucket = "test-bucket";
const Key = "test-key";

try {
  await client.getObject({ Bucket, Key });
} catch (error) {}
```

```console
{ hostname: 'test-bucket', path: '/test-key' }
```

</details>

**Comment by trivikr** [comment]
The request.hostname was overriden to bucketName when bucketEndpointMiddleware was originally written in https://github.com/aws/aws-sdk-js-v3/pull/104

This bug seems to be pre-existing as NodeHttpHandler used to make request using request.hostname at that point in history
https://github.com/aws/aws-sdk-js-v3/blob/f0c32224455fd3e3be78bfeeeba6f3520f5ea0e9/packages/node-http-handler/src/node-http-handler.ts#L71-L78

**Comment by MancunianSam** [comment]
Thanks for looking at this. I raised a support ticket for an issue where the s3 upload is being made with a POST request instead of PUT and they have referred me to this issue but I'm not sure how this issue relates to the problem of the upload being made with POST. I've raised a separate issue for this https://github.com/aws/aws-sdk-js-v3/issues/3097 If they're part of the same problem then I can close the newer issue.

**Comment by trivikr** [comment]
Revisiting this ticket again from internal discussion in V477160346.

After detailed discussion, we realized that the existing behavior was added on purpose and is the correct behavior as:
* Providing endpoint during client creation is optional. If the endpoint it provided, all operations on the client use that endpoint.
* Providing bucket while running relevant operations (like GetObject) is required. If the operation is going to ignore Bucket value, pass endpoint instead.
* The documentation for `bucketEndpoint` clearly states `Whether to use the bucket name as the endpoint for this request`.
* We currently use other S3 customizations to pass endpoint information in Bucket name (like Accelerate).

The behavior which AWS SDK for JavaScript (v2) follows is confusing as:
* The Bucket provided while running the operation is ignored, since custom endpoint needs to be used.
* It throws an error if `s3BucketEndpoint` is set, and custom endpoint is not passed.
* The client created by using custom endpoint cannot be used for other operations which does not require the custom endpoint.

We'll be retaining this behavior, and make the following documentation updates in https://github.com/aws/aws-sdk-js-v3/pull/3273
* Specify the difference between `s3BucketEndpoint` in v2, and `bucketEndpoint` in v3 in UPGRADING.md.
* Write detailed documentation for `bucketEndpoint` configuration.
