### ISSUE TITLE
S3 makeUnauthenticatedRequest is not supported

### ISSUE THREAD

**Issue by michaelwittig** [aws/aws-sdk-js-v3#3038]
### Is your feature request related to a problem? Please describe.
In AWS JS SDK v2, the API makeUnauthenticatedRequest is available to call an operation on a service without any authentication data. This method is useful for "public" API operations.
Docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Service.html#makeUnauthenticatedRequest-property

This API is not available in AWS JS SDK v3

### Describe the solution you'd like
The API makeUnauthenticatedRequest or equivalent on all clients in JS SDK v3

### Describe alternatives you've considered
Not update to v3
 
### Additional context
#984 which was closed with the comment "Not a currently desired behavior"
Why is this not desired? It makes it very hard to migrate v2 to v3 code.

**Comment by ryan-williams** [comment]
I'm also confused and surprised by this. I'm trying to make a little `index.html` that lists directories+files in a bucket, like https://s3.amazonaws.com/tripdata/index.html but with some other features:

![image](https://user-images.githubusercontent.com/465045/146627725-e9f77892-0729-44c9-837e-4f4bb8999759.png)

That `index.html` just hits the XML/REST API, so that's easy and unauthenticated. As OP mentions, the JS SDK v2 also makes this easy.

I am wrapping mine up as a React component, and trying to use the v3 JS SDK. Apparently I have to make an unauthenticated identity pool in Cognito, and burn its ID into this file that I'm going to publish on the internet and encourage people to copy and put in their own buckets and stuff? That doesn't seem right… what am I missing?

**Comment by AllanZhengYP** [comment]
Close as duplication to https://github.com/aws/aws-sdk-js-v3/issues/2321, please feel free to comment there if you have more questions.
