### ISSUE TITLE
S3 GetObjectCommand docs don't explain how to read the object body

### ISSUE THREAD

**Issue by igilham** [aws/aws-sdk-js-v3#3064]
## Describe the issue with documentation

The [documentation for The S3 `GetObjectCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/getobjectcommand.html) for SDK v3 does not explain how to read the contents of the object or handle common errors.

The [documentation for the result type|https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/getobjectcommandoutput.html#body] describes the body as follows:

> Object data

The type of the object is described as one of three undocumented types: `Readable | ReadableStream | Blob`. No additional detail is available from the API docs.

#### Observed behavior

The documentation describes how to send the command to AWS but not how to use the result of a successful call or handle common error scenarios.

#### Expected behavior

The documentation should describe in detail the code required to use the result of the command. One example usage on NodeJS (Typescript) is [here](https://github.com/aws/aws-sdk-js-v3/issues/1877#issuecomment-755430937). Browser environments require a different implementation.

It may also be helpful to document typical errors and the types of `Error` objects that might be thrown when the command fails.

## Additional context

The design of the `s3:GetObject` command has changed significantly since AWS SDK v2. There is a history of discussion around issues with the design of this API in #1877. The quality of the documentation and lack of a migration guide have been a major point of contention among users. These issues are preventing some customers from migrating to v3 of the SDK and frustrating many who do chose to migrate.

The root documentation page for the S3 SDK module was updated in #1878 but does not include the necessary changes to make this API easy to understand and use.

**Comment by tomchiverton** [comment]
This massive DX problem still exists. Every time I need to use GetObjectCommand I end up on StackOverflow.

**Comment by aBurmeseDev** [comment]
Hi @igilham - thanks for your feedback on our docs and apologies for the long silence here. I came across this when going through open issues and wanted to address. 

Since this issue was created, there has been updates to the docs specifically in [GetObjectCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/) which now presents types of StreamingBlobPayloadOutput and there's also this [updated page](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#streams) with code example for working with output bodyStream. 

We appreciate feedbacks as we try to improve our docs to be more user-friendly and easy to understand.
Hope it addresses your concerns and let us know if there are any other questions!
