### ISSUE TITLE
S3 Upload using POST for multipart uploads.

### ISSUE THREAD

**Issue by MancunianSam** [aws/aws-sdk-js-v3#3097]
## Describe the bug
This is when using client-s3 and lib-storange to upload files to S3. For files over 5Mb (the default chunk size) the SDK is making POST requests to S3 and S3 then responds with method not allowed.

#### SDK version number
`@aws-sdk/client-s3": "^3.44.0`
`@aws-sdk/lib-storage": "^3.44.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
Browsers:
    Chrome: 95.0.4638.69
    Firefox: 90.0

## Steps to reproduce
There is a [minimal repo here](https://github.com/nationalarchives/aws-upload-minimal-repo/) with instructions in the README on how to recreate the bug.

#### Observed behavior
For uploads over 5Mb, a fetch POST request is made which isn't supported by S3.

#### Expected behavior
The upload request should be PUT which is supported by S3.

## Additional context
I have raised a ticket with support for this and they have pointed me at [this issue](https://github.com/aws/aws-sdk-js-v3/issues/3031) which I raised a few weeks back but I'm not sure how that ticket relates to this issue.

**Comment by AllanZhengYP** [comment]
Hi @MancunianSam 

The `@aws-sdk/lib-storage` is expected to make POST requests because it uses [S3 multipart upload APIs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html) when the body size is bigger than 5MB. It offers advantages over the `s3::PutObject` [api](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) like concurrent uploading, better retrying and resuming the upload.

The `s3::PutObject` [api](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) uses a single PUT request. Customer can use the putObject like

```javascript
const config: S3ClientConfig = {
  region: "eu-west-2",
  logger: console,
};
const client = new S3Client(config);
const params = { Key: "key", Bucket: "bucket ", Body: "abc" };

response = await client.send(new PutObjectCommand(params));
```

If you want to keep using the multipart upload, they can [enable the CORS config in the bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html)
