### ISSUE TITLE
AccessDeniedException: User: xxx is not authorized to perform: states:ListExecutions on resource: yyy because no session policy allows the states:ListExecutions action

### ISSUE THREAD

**Issue by LorhanSohaky** [aws/aws-sdk-js-v3#3262]
## Describe the bug
I trying to list executions, but not work

#### SDK version number
`@aws-sdk/client-sfn@^3.48.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

## Steps to reproduce
```js
import { SFNClient, ListExecutionsCommand, DescribeExecutionCommand, ListStateMachinesCommand } from '@aws-sdk/client-sfn'
import { CognitoIdentityClient } from '@aws-sdk/client-cognito-identity'
import { fromCognitoIdentityPool } from '@aws-sdk/credential-provider-cognito-identity'

import { AWS_REGION, AWS_IDENTITY_POOL } from '../../config/env'

const StepFunctionClient = ({
    region = AWS_REGION,
    identityPoolId = AWS_IDENTITY_POOL,
}) => {
    const client = new SFNClient({
        region: AWS_REGION,
        credentials: fromCognitoIdentityPool({
            client: new CognitoIdentityClient({ region }),
            identityPoolId,
        }),
    })

    const listExecutions = async ({ stateMachineArn, maxResults = 5 }) => {
        const params = { stateMachineArn, maxResults }
        const data = await client.send(new ListExecutionsCommand(params))

        return data.executions
    }

    return { listExecutions, _client: client }
}

const stateMachineArn= 'yyy'
client = StepFunctionClient({})
client.listExecutions({ stateMachineArn }).then(r=> console.log(r)).catch(err=> console.error(err))

```

#### Observed behavior
AccessDeniedException: User: xxx is not authorized to perform: states:ListExecutions on resource: yyy because no session policy allows the states:ListExecutions action

## Additional context
My roles:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ControlDashboardAllowedOperations",
            "Effect": "Allow",
            "Action": [
                "states:ListExecutions",
                "states:DescribeExecution"
            ],
            "Resource": "*"
        }
    ]
}
```

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:Query",
                "dynamodb:Scan"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by RanVaknin** [comment]
Hi @LorhanSohaky ,

I'm missing context as to why you want to use cognito identity pool to execute this command. Are you specifically trying to run your code from the front end? If not you should store your credentials on a config file that lives on the root of your machine. The SDK will automatically authenticate your requests using those credentials.

However, if you are trying to use Cognito please try the following steps:

A couple of things you are missing:
- Use only the `client-cognito-identity` package like so:
` import { CognitoIdentityClient, fromCognitoIdentityPool } from '@aws-sdk/client-cognito-identity'`
- You are missing a [trust policy](https://aws.amazon.com/blogs/security/how-to-use-trust-policies-with-iam-roles/) on your IAM role which will result in an access denied.
- Lastly, if non of these work, the error mentions session policy. I suspect it wants you to use 
`fromTemporaryCredentials` from `@aws-sdk/credential-providers`, instead of `fromCognitoIdentityPool`.

Please let me know if you are sucessful.

**Comment by LorhanSohaky** [comment]
Hello @RanVaknin ,

my use case is: I want to extract some information about the last execution of the state machine from the front end

**Comment by LorhanSohaky** [comment]
It worked, it was a role problem

**Comment by rtksmuhammad** [comment]
Hey @LorhanSohaky, what was specifically wrong with the role?

**Comment by LorhanSohaky** [comment]
> Hey @LorhanSohaky, what was specifically wrong with the role?

I added this
```
"states:ListStateMachines",
                "states:ListActivities",
                "states:DescribeStateMachine",
                "states:DescribeStateMachineForExecution",
                "states:ListExecutions",
                "states:DescribeExecution",
                "states:GetExecutionHistory",
                "states:DescribeActivity"
```
