### ISSUE TITLE
Clients should not be assignable to variable declared as other client types

### ISSUE THREAD

**Issue by dmattia** [aws/aws-sdk-js-v3#3278]
## Describe the bug

This is currently valid typescript that compiles without error:

```typescript
const a: TimestreamWriteClient = new TimestreamQueryClient({});
```

This can cause problems, as although both of these clients use the same duck-typing, the endpoints they talk to are different, which can lead to code that compiles (and even passes tests if `send` is mocked) but fail in production.

#### SDK version number
"@aws-sdk/client-timestream-query": "=3.24.0",
 "@aws-sdk/client-timestream-write": "=3.24.0",

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node 14.17.3

## Steps to reproduce
Use the code in the description above

#### Observed behavior
Typescript allows the code

#### Expected behavior
I would expect there to be some static method or const on each client such that no client could be assigned to a client of another type

**Comment by anotherminh** [comment]
A simple (but maybe hacky) solution is to declare private properties separately for each class. This causes a compile-time error: 

```ts
class TimestreamQueryClientWrapper extends TimestreamQueryClient {
  private readonly _useNominal = true;
}

class TimestreamWriteClientWrapper extends TimestreamWriteClient {
  private readonly _useNominal = true;
}

export const defaultTimestreamWriteClient: TimestreamQueryClientWrapper =
  new TimestreamWriteClientWrapper(awsCredentialProvider);
```

**Comment by kuhe** [comment]
reproducing the issue in TypeScript:

```typescript
class Client<T> {
    // public send(t: T) {} // makes Client1/Client2 exclusive.
    public send<S extends T>(s: S) {} // does not make Client1/Client2 exclusive.
}

type t1 = 1
type t2 = 2

class Client1 extends Client<t1> {}
class Client2 extends Client<t2> {}

const c: Client1 = new Client2();
```

**Comment by aBurmeseDev** [comment]
Hi @dmattia - sorry for the long silence here. I just came across this and brought it up to discuss with the team. Upon further discussion with the team, we found that this isn't a bug with the SDK (maybe a feature), in fact we believe that this was due to assigning one client to another client type. It will work because they're both clients but just not the right client type. Ideally, every client could have a marker to be distinct from other clients but this isn't something we'd consider at this time.

Thank you for opening the issue and please let us know if there're any other questions.
