### ISSUE TITLE
Dynamic Code Evaluation not compatible with Next.js 12.1.0

### ISSUE THREAD

**Issue by revmischa** [aws/aws-sdk-js-v3#3329]
## Describe the bug
I am trying to upgrade from Nextjs 12.0.10 to 12.1.0, getting a new error that is caused by the AWS SDK:

```
../../../node_modules/@aws-sdk/smithy-client/dist-es/lazy-json.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware

Import trace for requested module:
../../../node_modules/@aws-sdk/smithy-client/dist-es/index.js
../../../node_modules/@aws-sdk/client-cloudformation/dist-es/CloudFormationClient.js
../../../node_modules/@aws-sdk/client-cloudformation/dist-es/index.js
../../common/build/config/env.js
```

#### SDK version number
`@aws-sdk/client-cloudformation@3.47.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
```
  Browsers:
    Brave Browser: 98.1.35.101
    Safari: 15.2
```

## Steps to reproduce
* Use NextJs 12.1.0
* Create a _middleware.ts file
* Import `@aws-sdk/client-cloudformation`
* Run next build

## Additional context
Surely `eval` isn't needed to call the CloudFormation API?

**Comment by mglazer-hm** [comment]
Yes we had to revert to 12.0.10 from 12.1.0 since the error occurs for no apparent reason even with the example middlware code from vercel themselves: https://github.com/vercel/examples/blob/main/edge-functions/i18n/pages/_middleware.ts

CODE:

```
import { NextRequest, NextResponse } from 'next/server'

const PUBLIC_FILE = /\.(.*)$/

export function middleware(req: NextRequest) {
  const country = req.geo.country?.toLowerCase() || 'us'
  const locale = req.headers.get('accept-language')?.split(',')?.[0] || 'en-US'

  // Only rewrite files that don't have a file extension
  if (!PUBLIC_FILE.test(req.nextUrl.pathname)) {
    req.nextUrl.pathname = `/${locale}/${country}`
    return NextResponse.rewrite(req.nextUrl)
  }
}
```
ERROR:


```
info  - Creating an optimized production build  
Failed to compile.

./node_modules/@babel/runtime/helpers/construct.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware

Import trace for requested module:
./node_modules/@babel/runtime/helpers/wrapNativeSuper.js
./node_modules/next/dist/shared/lib/utils.js
./node_modules/next/dist/shared/lib/router/utils/route-matcher.js
./node_modules/next/dist/shared/lib/router/utils/index.js
./node_modules/next/dist/server/denormalize-page-path.js
./node_modules/next/dist/shared/lib/i18n/get-locale-metadata.js
./node_modules/next/dist/server/web/next-url.js
./node_modules/next/dist/server/web/spec-extension/request.js
./node_modules/next/dist/server/web/adapter.js

./node_modules/@babel/runtime/helpers/isNativeFunction.js
```

Basically, the middleware does not build since version 12.1.0 and up ...

**Comment by RanVaknin** [comment]
Hi @revmischa ,

Unfortunately I was not able to reproduce your issue. I'm not an expert in Next JS. Trying to piece together your workflow is difficult because the information you provided has a lot of stuff missing.

Based on the basic repro steps you provided, I did the following:
- I've [created a new Next project](https://nextjs.org/learn/basics/create-nextjs-app/setup)
- [Created a middleware](https://nextjs.org/docs/advanced-features/middleware)
- Installed with npm `@aws-sdk/client-cloudformation` ,and `import { CloudFormationClient } from '@aws-sdk/client-cloudformation'` to my index.js file.
- Built with `npx next build`

But no errors.

If you can provide more in depth instructions on how to reproduce, and share some of the code that is breaking and the contents of `_middleware.ts`, `tsconfig.json`, and `index.js`


**Important observation:**
This seems like a NextJS issue, and not an AWS issue.
- [Dynamic Code Evaluation (e. g. ‘eval’, ‘new Function’) not allowed in Middleware...](https://github.com/vercel/next.js/issues/32608)
- [Next JS _middleware does not allow use of dynamic evaluation ](https://stackoverflow.com/questions/71844120/next-js-middleware-does-not-allow-use-of-dynamic-evaluation-new-function)
- [Some problems with nextjs12 middleware and upgrade from nextjs 11 to 12
](https://www.reddit.com/r/nextjs/comments/ql57z3/some_problems_with_nextjs12_middleware_and/)
- [[Solved] Can I run the new Next.js middleware in a self hosted environment?](https://solveforum.com/forums/threads/solved-can-i-run-the-new-next-js-middleware-in-a-self-hosted-environment.281442/#login)

Thanks

**Comment by revmischa** [comment]
> Hi @revmischa ,
> 
> Unfortunately I was not able to reproduce your issue. I'm not an expert in Next JS. Trying to piece together your workflow is difficult because the information you provided has a lot of stuff missing.
> 
> Based on the basic repro steps you provided, I did the following:
> 
> * I've [created a new Next project](https://nextjs.org/learn/basics/create-nextjs-app/setup)
> * [Created a middleware](https://nextjs.org/docs/advanced-features/middleware)
> * Installed with npm `@aws-sdk/client-cloudformation` ,and `import { CloudFormationClient } from '@aws-sdk/client-cloudformation'` to my index.js file.
> * Built with `npx next build`
> 
> But no errors.
> 
> If you can provide more in depth instructions on how to reproduce, and share some of the code that is breaking and the contents of `_middleware.ts`, `tsconfig.json`, and `index.js`
> 
> **Important observation:** This seems like a NextJS issue, and not an AWS issue.
> 
> * [Dynamic Code Evaluation (e. g. ‘eval’, ‘new Function’) not allowed in Middleware...](https://github.com/vercel/next.js/issues/32608)
> * [Next JS _middleware does not allow use of dynamic evaluation ](https://stackoverflow.com/questions/71844120/next-js-middleware-does-not-allow-use-of-dynamic-evaluation-new-function)
> * [Some problems with nextjs12 middleware and upgrade from nextjs 11 to 12
>   ](https://www.reddit.com/r/nextjs/comments/ql57z3/some_problems_with_nextjs12_middleware_and/)
> * [[Solved] Can I run the new Next.js middleware in a self hosted environment?](https://solveforum.com/forums/threads/solved-can-i-run-the-new-next-js-middleware-in-a-self-hosted-environment.281442/#login)
> 
> Thanks

Do you have this repro up somewhere? Can I try it please?

**Comment by RanVaknin** [comment]
Hi @revmischa 

Here is a link to a [bare bones repo](https://github.com/RanVaknin/NextJS_CloudFormationClient_Test). 

Let me know if that helps.
