### ISSUE TITLE
Incorrect region info signing service for IoT Secure Tunneling client.

### ISSUE THREAD

**Issue by zoi-pedro-romano** [aws/aws-sdk-js-v3#3353]
## Describe the bug
Incorrect region info signing service for IoT Secure Tunneling client.

#### SDK version number
`@aws-sdk/client-iotsecuretunneling@3.52.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.19.0

## Steps to reproduce
```
import { IoTSecureTunneling } from '@aws-sdk/client-iotsecuretunneling';

const iotSecureTunneling = new IoTSecureTunneling();
console.log(await iotSecureTunneling.listTunnels({}));
```

#### Observed behavior
Sending a command to the client throws an exception:
```
.../node_modules/@aws-sdk/client-iotsecuretunneling/dist-cjs/protocols/Aws_json1_1.js:254
    return Promise.reject(Object.assign(new Error(message), response));
                                        ^
InvalidSignatureException: Credential should be scoped to correct service: 'IoTSecuredTunneling'.
```

#### Expected behavior
Secure tunnels should be listed.

#### Screenshots
N/A

## Additional context
[Region info `signingService` case is incorrect](https://github.com/aws/aws-sdk-js-v3/blob/1945d47c9612eca3d04c8a346bbc4de35c3d0ef3/clients/client-iotsecuretunneling/src/endpoints.ts#L132). It's `iotsecuredtunneling` when it should be `IoTSecuredTunneling`. Fixing the property value solves the issue.

**Comment by amirbavand** [comment]
@pedro-romano-zoi  Thanks for opening this issue. Faced the same issue.  Did you find any workaround?

**Comment by pedro-romano-zoi** [comment]
@amirbavand, short of forking and patching the problem no. I've had to downgrade to SDK v2 for now. I'm not sure why AWS recommends upgrading to v3 when some of the clients, like secure tunneling, but it's not the only one, are completely non-functional because of this simple configuration issue... :disappointed:

**Comment by amirbavand** [comment]
@pedro-romano-zoi Thanks so much. This seems a great solution.

**Comment by pedro-romano-zoi** [comment]
**Thank for sharing @lukasapp!** I was trying to do something like this a while back but due to time constraints ended up not seeing through. This should enable use to migrate SDK v3 until the bug is fixed upstream.

`@aws-sdk/client-iot-jobs-data-plane` has the exact same problem, but due to inactivity here I couldn't be bothered to open a similar ticket there. I'll use this same workaround there.

**Comment by RanVaknin** [comment]
Hi @pedro-romano-zoi ,
Thank you for reaching out. And @lukasapp thank you for the work around.

I have reproduced the problem and can verify that this is an issue and that the workaround is working.
```
const {IoTSecureTunnelingClient, ListTunnelsCommand } = require("@aws-sdk/client-iotsecuretunneling")
const { Sha256 } = require("@aws-crypto/sha256-js");
const { SignatureV4 } = require('@aws-sdk/signature-v4');
const { defaultProvider } = require("@aws-sdk/credential-provider-node");

const region = 'us-east-1';
const service = 'IoTSecuredTunneling';
const signer = new SignatureV4({
  credentials: defaultProvider(),
  sha256: Sha256,
  region,
  service,
});
// Add middleware to sign request yourself.
const client = new IoTSecureTunnelingClient({ region });

client.middlewareStack.add(
  (next, context) => async args => {
    // Sign request with custom (correct) service scope.
    const signed = await signer.sign(args.request, { signingDate: new Date() });
    args.request.body = signed.body;
    args.request.headers = signed.headers;
    return next(args);
  }, {
    step: "finalizeRequest"
  }
);

async function run(){
    try {
        const response = await client.send(new ListTunnelsCommand({maxResults: 3}));
        console.log(response);
    } catch (error) {
        console.log(error)
    }
}
run();

```

@trivikr notice that the customer raised that the same issue is happening with `@aws-sdk/client-iot-jobs-data-plane`
Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @zoi-pedro-romano, @amirbavand, @lukasapp, I just want to let you people know that this issue has been fixed by the following [commit](https://github.com/aws/aws-sdk-js-v3/commit/246d6534c53dcf9bd2eb6a620cb5b6c04b27451a), so that by updating to the latest version the problem should be gone.

Thanks!

**Comment by zoi-pedro-romano** [comment]
I can confirm this is now fixed for me in recent versions of the v3 SDK. Closing.
