### ISSUE TITLE
Importing anything from the latest SDK breaks Cypress tests

### ISSUE THREAD

**Issue by bingnz** [aws/aws-sdk-js-v3#3354]
## Describe the bug

The following change breaks Cypress tests that use the AWS SDK. This is because "fs" is not available in this environment, and "fs" is stubbed out to be empty using a Webpack alias. Attempting to dereference `promises` from `fs` causes an exception when the file is included.

https://github.com/aws/aws-sdk-js-v3/blob/1945d47c9612eca3d04c8a346bbc4de35c3d0ef3/packages/shared-ini-file-loader/src/slurpFile.ts#L2

#### SDK version number
`@aws-sdk/shared-ini-file-loader@3.52.0`

#### Is the issue in the browser/Node.js/ReactNative?
Cypress (browser)

#### Details of the browser/Node.js/ReactNative version
Cypress 9.5.0

## Steps to reproduce
Include an AWS SDK library within a Cypress project; e.g.,
`import { BatchWriteItemCommand, DynamoDBClient, WriteRequest } from "@aws-sdk/client-dynamodb";`

#### Observed behavior
Cypress crashes with the following error: `Cannot read properties of undefined (reading 'readFile')`

#### Expected behavior
In previous versions, it was possible to use the SDK.

**Comment by RanVaknin** [comment]
Hi @bingnz,

Thanks for reaching out. Can you please include full code example of the file that is crashing and a complete stack trace. More detailed reproduction steps would be very helpful as right now it requires a lot of guess work.

Much appreciated!

**Comment by alfonso-paella** [comment]
I'm getting this error too

`  > Cannot read properties of undefined (reading 'readFile')`

<img width="646" alt="Screen Shot 2022-06-19 at 6 57 14 AM" src="https://user-images.githubusercontent.com/93743232/174477603-cc21656a-8546-4018-bd0c-190053bfdce2.png">

**Comment by RanVaknin** [comment]
@alfonso-paella ,

I will need more detailed reproduction steps in order to triage this issue.
Please include actual code and not screen shots as that makes reproducing much more painful.

if you can fill in the intake form:
- **Describe the bug**
_What is the problem? A clear and concise description of the bug._

- **Expected Behavior**
_What did you expect to happen?_

- **Current Behavior**
_What actually happened?
Please include full errors, uncaught exceptions, stack traces, and relevant logs.
If service responses are relevant, please include wire logs._

- **Reproduction Steps**
_Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
For more complex issues provide a repo with the smallest sample that reproduces the bug._

- **Possible Solution**
_Suggest a fix/reason for the bug_
