### ISSUE TITLE
Unable to use with vite.

### ISSUE THREAD

**Issue by chocoford-zhang** [aws/aws-sdk-js-v3#3373]
## Describe the bug
[ERROR] No matching export in "browser-external:buffer" for import "Buffer"

#### SDK version number
`@aws-sdk/client-s3@3.53.1`

## Steps to reproduce
codes from official website
```
import { S3Client } from '@aws-sdk/client-s3';
const REGION = 'us-east-1'; //e.g. "us-east-1"
const s3Client = new S3Client({ region: REGION });
```

#### Observed behavior
```shell
✘ [ERROR] No matching export in "browser-external:buffer" for import "Buffer"

    node_modules/@aws-sdk/util-buffer-from/dist-es/index.js:2:9:
      2 │ import { Buffer } from "buffer";
        ╵          ~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/@aws-sdk/util-buffer-from/dist-es/index.js:2:9: ERROR: No matching export in "browser-external:buffer" for import "Buffer"
    at failureErrorWithLog (.../node_modules/esbuild/lib/main.js:1602:15)
    at .../node_modules/esbuild/lib/main.js:1248:28
    at runOnEndCallbacks (.../node_modules/esbuild/lib/main.js:1033:63)
    at buildResponseToResult (.../node_modules/esbuild/lib/main.js:1246:7)
    at .../node_modules/esbuild/lib/main.js:1355:14
    at.../node_modules/esbuild/lib/main.js:665:9
    at handleIncomingPacket (.../node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (.../node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by mdpratt** [comment]
Since Vitejs does not shim NodeJS libraries on it's own, core libraries such as buffer, fs, and path are not available for use in the browser. You can find shims (eg. https://github.com/feross/buffer or https://github.com/ionic-team/rollup-plugin-node-polyfills) to help handle these cases.

If you are using Vitejs for testing locally, you can also write your credentials to a local JSON file and pass that into your client, which will help prevent relying on _most_ core libraries, such as crypto.

[Note: I am posting as an individual who's run into this same problem, and not not as a member of the AWS SDK team]

**Comment by chocoford-zhang** [comment]
@mdpratt Thanks. Installing `buffer` solves my problems.
