### ISSUE TITLE
client authentication iam authorization

### ISSUE THREAD

**Issue by zacharykane** [aws/aws-sdk-js-v3#3427]
## Describe the bug
I'm trying to use the Cloudwatch Evidently module in my frontend app. I am following a couple guides on the new SDK. There are multiple ways to establish credentials to my account and neither are working.

## Your environment
linux
create-react-app

#### SDK version number
`@aws-sdk/client-evidently@3.53.0`
`@aws-sdk/client-cognito-identity@3.53.0`
`@aws-sdk/credentials-providers@3.53.0`
`@aws-sdk/credentials-provider-cognito-identity@3.53.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
Firefox 91.6.1

## Steps to reproduce
I have followed along by manually created an Evidently project, establishing a feature and created a **Cognito Identity Pool**. I've allowed Unauthorized access (since i have no real users yet) and created the **Unauthorized Role with a Permissions** of `AmazonCloudwatchEvidentlyFullAccess`.

The Trust relationships which was generated shows this:
```json
"Version": "2012-10-17",
"Statement": [
  {
    "Effect": "Allow",
    "Principal": {
      "Federated": "cognito-identity.amazonaws.com"
    },
    "Action": "sts:AssumeRoleWithWebIdentity",
    "Condition": {
      "StringEquals": {
        "cognito-identity.amazonaws.com:aud": "us-west-2:SAME_AS_IDENTITY_POOL_ID"
      },
      "ForAnyValue:StringLike": {
        "cognito-identity.amazonaws.com:amr": "unathenticated"
      }
    }
  }
]
```

```js
import { fromCognitoIdentityPool } from '@aws-sdk/credential-provider-cognito-identity';
import { EvidentlyClient, BatchEvaluateFeatureCommand } from '@aws-sdk/client-evidently';

const client = new EvidentlyClient({
  region: 'us-west-2',
  credentials: fromCognitoIdentityPool({
    client: new CognitoIdentityClient({ region: 'us-west-2' }),
    identityPoolId: 'us-west-2:XXX',
  }),
});
const response = await client.send(new BatchEvaluateFeatureCommand(...)); // omitted for brevity
```

#### Observed behavior
this results in an AccessDeniedException: User is not authorized to perform BatchEvaluateFeatureCommand because no session policy allows the action.

#### Expected behavior
The response from the Evidently API would return, as described in the Cloudwatch Evidently Console

## Additional context
Another tutorial describes a slightly different authentication procedure:

```js
import { fromCognitoIdentityPool } from '@aws-sdk/credential-providers';
import { EvidentlyClient, BatchEvaluateFeatureCommand } from '@aws-sdk/client-evidently';

const client = new EvidentlyClient({
  region: 'us-west-2',
  credentials: fromCognitoIdentityPool({
    identityPoolId: 'us-west-2:XXX',
  }),
});
const response = await client.send(new BatchEvaluateFeatureCommand(...));
```
However this results in a more cryptic error thrown: Region is missing

**Comment by dev-julian** [comment]
Seems to be similar to #3262 .
I have the same setup with evidently, with `@aws-sdk/client-evidently@3.54.1` and `@aws-sdk/credential-providers@3.54.1`.
When using accessKeyId and secretAccessKey for a user with the proper permission in the EvidentlyClient this works.

**Comment by zacharykane** [comment]
Right! I noticed that issue and that's the error I'm getting. I'm on the front end in an SPA so putting down the access ids/keys isn't really an option. I'm sure we could wrap things up in yet another api call but this was detailed to work?

**Comment by dev-julian** [comment]
I just switched to using the authenticated role in my Identity Pool through Cognito User Pools as Identity Provider. This seems to work.
```javascript
 const client = new EvidentlyClient({
    credentials: fromCognitoIdentityPool({
      identityPoolId: '<identityPoolId>',
      logins: {
      'cognito-idp.<region>.amazonaws.com/<CognitoUserPoolId>': '<jwtToken>'
      }
    }),
    region: '<region>'
  })
```

**Comment by FinestV** [comment]
The Basic Auth flow works but the Enhanced Auth flow does not. 

The Evidently tutorial previously used the Basic Auth flow using both the Cognito and STS clients to call commands, GetId -> GetOpenId -> AssumeRoleWithWebIdentity to fetch the credentials.  

This has since been removed from the tutorial and authorization is now hard coded https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Evidently-sample-application.html

**Comment by RanVaknin** [comment]
Hi @zacharykane,

Thank you for bringing this issue to our attention.
I am still researching the issue, but here are a few things I have found:

 I noticed the policy action you have there is specified as `sts:AssumeRoleWithWebIdentity`. I'm not sure how you are going to allow users to register, but the documentation states that this method should be used in the following case:

> Returns a set of temporary security credentials for users who have been authenticated in a mobile or web application with a web identity provider. Example providers include the OAuth 2.0 providers Login with Amazon and Facebook, or any OpenID Connect-compatible identity provider such as Google or [Amazon Cognito federated identities](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html).

This action is for Open ID auth. Meaning you must have an identity token from a supported identity provider, and use the [`fromWebToken` ](https://www.npmjs.com/package/@aws-sdk/credential-providers#fromwebtoken)method. It is calling the respective AssumeRoleWithWebIdentity STS endpoint "under the hood" to generate the credentials for the request.

Additionally, I was able to successfully make that request using `sts:AssumeRole` with the `fromTemporaryCredentials` method. 
I had to remove the `"cognito-identity.amazonaws.com:amr": "unathenticated"` part from the trust policy for it to work, and while I know this is not a perfect solution because by nature the trust policy should be restrictive, Im still researching this issue.

Please let me know if this helped in any way,
Ran
