### ISSUE TITLE
Empty response in the payload

### ISSUE THREAD

**Issue by pranayrauthu** [aws/aws-sdk-js-v3#3538]
## Describe the bug
I am using the lambda-client package in my tests to invoke the lamda function. I am receiving empty payload in the response but the status code in 200. This issue is already mentioned here https://github.com/aws/aws-sdk-js-v3/issues/3183#issue-1101338859

## Your environment
Node

#### SDK version number
`@aws-sdk/client-lambda`

#### Is the issue in the browser/Node.js/ReactNative
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by RanVaknin** [comment]
Hi @pranayrauthu ,

Thanks for reaching out.
I'll look into the existing issue you referred to. In the meantime please fill in the _**Steps to reproduce**_ portion of the intake form including complete code so I can further assist you:

### Steps to reproduce:
Please share code or minimal repo, and steps to reproduce the behavior.

**Observed behavior**
A clear and concise description of what happens.

**Expected behavior**
A clear and concise description of what you were expecting to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
