### ISSUE TITLE
Missing refresh token

### ISSUE THREAD

**Issue by JonNeat** [aws/aws-sdk-js-v3#3548]
## Describe the bug
When calling refresh token, I get an undefined RefreshToken back.

#### SDK version number
`@aws-sdk/client-cognito-identity-provider@3.72.0`

## Steps to reproduce
Get a refresh token and call initateAuth with Authflow "REFRESH_TOKEN_AUTH". Like this:

    const refreshToken = "REFRESH TOKEN GOES HERE";
    const client = new AWS.CognitoIdentityProvider({ region: "eu-west-1" });

    client.initiateAuth({
      AuthFlow: AuthFlowType.REFRESH_TOKEN_AUTH,
      ClientId: 'XYZ',
      AuthParameters: {
        REFRESH_TOKEN: refreshToken
      }
    }).then(w => {
      console.log(w);
    })

#### Observed behavior
The refresh token in the returned payload is undefined.

`{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '<removed by OP>',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  AuthenticationResult: {
    AccessToken: '<removed by OP>',
    ExpiresIn: 300,
    IdToken: '<removed by OP>',
    NewDeviceMetadata: undefined,
    RefreshToken: undefined,   <!----------? ---------!>
    TokenType: 'Bearer'
  },
  ChallengeName: undefined,
  ChallengeParameters: {},
  Session: undefined
}`

#### Expected behavior
I expected to get back a new refresh token as well as a new access token.

**Comment by RanVaknin** [comment]
Hi @JonNeat ,

Thanks for reaching out.
A couple of things:

The example code you are trying to run looks like the V2 of the of the JS SDK but the package your referring to is V3 so the error might be coming from there.

Secondly, please include the imports at the top, or any other code that would help me reproduce your problem

In addition, can you give me more context on your environment? Node/React/Web? I assume it's a front end application since you are using `initiateAuth` but please include the environment and version (example: 'node v16.8.0' or if youre running react with expo 'expo v5.4.6')


Thank you!
