### ISSUE TITLE
s3-request-presigner / getSignedUrl / expiresIn appears to not have any effect

### ISSUE THREAD

**Issue by rpivovar-godaddy** [aws/aws-sdk-js-v3#3608]
I am using `getSignedUrl` to get a signed url for an image in an S3 bucket like so:

```ts
async function getSignedUrlForImageFile(s3Client: S3Client, timestamp: number, serviceId: string) {
  console.log('Getting signed URL for image file...\n');
  const command = new GetObjectCommand({ Bucket: s3Bucket, Key: `${serviceId}-${timestamp}.png` });
  return await getSignedUrl(s3Client, command, { expiresIn: 432000 /* 5 days */ });
}
```

This code is working, but the `expiresIn` property appears to not have any effect -- the signed url seems to expires after 24 hours.

**Comment by yenfryherrerafeliz** [comment]
Hi @rpivovar-godaddy, thank you for reaching out. In the documentation found in the following [link](https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/), almost at the end of the page,  we can find a possible scenario where the URL may expire earlier, and is due to using temporary credentials. Please let me know if that could be your case?, if not, could you please provide the following:
- JS SDK version
- The response from the server when the URL actually expires, along with the date-time when the URL was generated. In the response we can see at what time in specific the URL expired.

Note: please redact any sensitive information!

Thanks!

**Comment by rpivovar-godaddy** [comment]
Hi @yenfryherrerafeliz -- thanks for the link. I also found [this page](https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/) which seems to go over the same issue.

I am getting this presigned url from inside a lambda. This lambda is using a custom execution role. Do roles only provide temporary credentials? I see the role has a "maximum session duration" of 1 hour.

To get this to work for 7 days, would I have to use a signature v4 module to generate a presigned url? Is this the correct module? https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-signer/index.html Do you know of any examples available for doing this?

Thanks for the help!

**Comment by yenfryherrerafeliz** [comment]
Hi @rpivovar-godaddy 

> I am getting this presigned url from inside a lambda. This lambda is using a custom execution role. Do roles only provide temporary credentials? I see the role has a "maximum session duration" of 1 hour.

Yes, roles just provide temporary credentials and they will be valid just for a short period of time.

> To get this to work for 7 days, would I have to use a signature v4 module to generate a presigned url? Is this the correct module? https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-signer/index.html Do you know of any examples available for doing this?

To get this to work up to 7 days you would need to use IAM user credentials, and the s3-request-presigner uses already v4 signature, so that not extra work needs to be done. In the following [link](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) you can find documentation about how to generate credentials or access keys for IAM user, and the following [link](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html) contains information about how to configure them in your environment, you also have the option to pass them manually when generating the presigned url but this is not recommended.

Please see an example below, passing the credentials manually:
```js
async function getSignedUrlForImageFile() {
    const bucket = 'YOUR-BUCKET';
    const key = 'YOUR-KEY';
    const region = 'YOUR-REGION';
    const secretAccessKey = 'YOUR-SECRET-ACCESS-KEY';
    const accessKeyId = 'YOUR-ACCESS-KEY-ID';
    
    const s3Client = new S3Client({
        region: region,
        credentials: Promise.resolve({
            secretAccessKey: secretAccessKey, 
            accessKeyId: accessKeyId
        })
    });
    const command = new GetObjectCommand({ 
        Bucket: bucket, 
        Key: key
    });
    return await getSignedUrl(s3Client, command, { expiresIn: 30 });
}
```
If you defined your credentials in variables environment or in the AWS credentials profile, then you can omit the parameter credentials from the code above.

Thanks!
