### ISSUE TITLE
vite @aws-sdk/lib-storage fs

### ISSUE THREAD

**Issue by 2992362310** [aws/aws-sdk-js-v3#3707]
### Describe the bug

✘ [ERROR] No matching export in "browser-external:fs" for import "lstatSync"

    node_modules/.pnpm/@aws-sdk+lib-storage@3.112.0_mrwqi6ucu5wnuft32kpd53opqm/node_modules/@aws-sdk/lib-storage/dist-es/runtimeConfig.js:2:9:
      2 │ import { lstatSync } from "fs";

### Expected Behavior

use @aws-sdk/lib-storage in vite

### Current Behavior

npm i @aws-sdk/lib-storage fs

 [ERROR] No matching export in "browser-external:fs" for import "lstatSync"

### Reproduction Steps

use @aws-sdk/lib-storage

### Possible Solution

method 1
npm install fs 
but fs is not node fs

method 2
npm install --save-dev rollup-plugin-node-polyfills

// vite.config.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import nodePolyfills from 'rollup-plugin-node-polyfills';

export default defineConfig({
  plugins: [vue(),nodePolyfills()]
})

this way not work

### SDK version used

latest

### Environment details (OS name and version, etc.)

vite latest

**Comment by ajredniwja** [comment]
Hi @2992362310, thanks for opening this issue, this is a known issue with Vite. Which is caused due to a few different reasons one of it is it cant differentiate between node and browser models and another one with webpack. Webpack v < 5 included pollyfills for node modules by default. 
I see an open issue here: https://github.com/vitejs/vite/issues/3715 which may solve this issue.

**Comment by 2992362310** [comment]
thank you

**Comment by 2992362310** [comment]
aboute fs
in vite.config.js,add optimizeDeps
export default defineConfig({
  plugins: [vue()],
  optimizeDeps: {exclude: [ 'fs']}, 
})

about stream
npm i stream
