### ISSUE TITLE
ValidationException when referencing EventBridge EventBuses from partner integration 

### ISSUE THREAD

**Issue by ezmiller** [aws/aws-sdk-js-v3#3714]
### Describe the bug

I am trying to send an event to an event bus created through a partner integration with Shopify. I receive an error:

>  ValidationException: 1 validation error detected: Value 'arn:aws:events:us-east-1:****:event-bus/aws.partner/shopify.com/***/shopify-events-dev' at 'entries.1.member.eventBusName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[\.\-_A-Za-z0-9]+

(note some parts of ARN removed and replaced with `*`s above for privacy)

### Expected Behavior

The ARN is valid so I would expect not to have the Validation error. 

### Current Behavior

The current regex, I think, does not allow for `/`s after the first capturing group, and so the valid ARN is treated as invalid.

### Reproduction Steps

N/A can't provide example since it requires a deployed partner integration event bus resource to reproduce.

### Possible Solution

Adjust regex used for validation.

### SDK version used

^3.112.0

### Environment details (OS name and version, etc.)

mac os, 10.15.4

**Comment by ajredniwja** [comment]
@ezmiller thanks for opening this issue, to help you better can you please share more information about your code. What API you are using? How you are consuming the SDK?

**Comment by ezmiller** [comment]
@ajredniwja sure. Here is a function that makes a call using the v3 `@aws-sdk/client-eventbridge` and the `PutEvents` command:

```
const viaEventBridge = async (
  busName: string,
  source: string,
  detailType: string,
  detail: unknown
) => {
  const eventBridge = new EventBridgeClient({ region: process.env.AWS_REGION })

  const input = {
    Entries: [
      {
        Source: source,
        DetailType: detailType,
        Detail: JSON.stringify(detail),
        EventBusName: busName
      }
    ]
  }

  await eventBridge.send(new PutEventsCommand(input))
}
```

I asksed a [question](https://stackoverflow.com/questions/72670292/is-it-possible-to-put-events-onto-an-eventbridge-event-bus-from-a-partner-integr) about this on stack overflow and someone there pointed out that there's a special command for partner integrations [`PutPartnerEvents`](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutPartnerEvents.html).

So perhaps this behavior is intentional?

**Comment by ezmiller** [comment]
@ajredniwja was that additional context helpful?

**Comment by ezmiller** [comment]
@ajredniwja for additional context, the reason I want to be able to put events on the partner integration event bus is that I want to be able to write e2e tests that start with submitting an event to the event bus. Without the ability to put an event on the bus, I think my hands are tied.

**Comment by ezmiller** [comment]
@ajredniwja any chance you have an answer here?

**Comment by rbuck-som** [comment]
I have the same problem. Only when importing a resource it fails with the same error.

**Comment by RanVaknin** [comment]
Hi @ezmiller ,

I apologize for the long wait.
The problem is that ARN you provided is the ARN is used by SaaS partners to call _**your**_ event bus, not vice versa.
Like you mentioned, this ARN shape corresponds to the one expected in `Source` for
>[PutPartnerEvents](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutPartnerEvents.html)
_This is used by SaaS partners to write events to a customer's partner event bus. AWS customers do not use this operation._
...
...
**Source**
_The event source that is generating the entry._
Type: String
Length Constraints: Minimum length of 1. Maximum length of 256.
**Pattern: aws\.partner(/[\.\-_A-Za-z0-9]+){2,}**

Notice the regex for this arn contains `.partner` like what you have supplied.

The ARN you need to supply should look something like this: `arn:aws:events:us-east-1:123456789012:event-bus/myEventBusName` and should be of an event bus you created.

It sounds like [this article](https://shopify.dev/apps/webhooks/configuration/eventbridge) might help you set up the integration between EB and Shopify.

Let me know if you need anything else,
Ran~
