### ISSUE TITLE
Missing MessagingSessionConfiguration export?

### ISSUE THREAD

**Issue by chris-hinds** [aws/aws-sdk-js-v3#3735]
### Describe the bug

Using V3 of the **client-chime-sdk-messaging** I am not seeing an export for `MessagingSessionConfiguration`

All examples point to using this method after getting the session endpoint but I cannot import this from this SDK? Perhaps I am missing something.

I am currently using the following;

```
import {
  ChimeSDKMessagingClient,
  CreateChannelCommand,
  CreateChannelMembershipCommand,
  ListChannelsCommand,
  GetMessagingSessionEndpointCommand
} from "@aws-sdk/client-chime-sdk-messaging";
```

### Expected Behavior

To be able to import `MessagingSessionConfiguration ` and setup a web socket connection

### Current Behavior

Cannot import `MessagingSessionConfiguration`

### Reproduction Steps

yarn add @aws-sdk/client-chime-sdk-messaging

try and import `MessagingSessionConfiguration `

### SDK version used

V3

### Environment details (OS name and version, etc.)

macOS Monterey

**Comment by RanVaknin** [comment]
Hi @chris-hinds !

Thanks so much for reaching out about this!

The reason you are not seeing an export for `MessagingSessionConfiguration` is because the SDK's client is auto generated from AWS's service's API. From what I can see the [Chime API](https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations.html) does not have that method exposed, however the [Chime SDK](https://aws.github.io/amazon-chime-sdk-js/classes/messagingsessionconfiguration.html) does.

Unfortunately there is nothing I can do to "add" that, however I will reach out to the service team that owns that API and see if I can get some clarifications on why this is not a part of the API and how we can get that propagated to the JS SDK.

Thanks for bringing this to our attention. In the meantime I suggest you leverage the Chime SDK to config messaging sessions programmatically while we work on a solution.
