### ISSUE TITLE
Unterminated template literal

### ISSUE THREAD

**Issue by llh-check** [aws/aws-sdk-js-v3#3754]
### Describe the bug

ERROR in node_modules/@aws-sdk/credential-provider-web-identity/dist-types/ts3.4/fromWebToken.d.ts with version 3.5.3 of Typescript.

### Expected Behavior

Compilation succeeds.

### Current Behavior

ERROR in node_modules/@aws-sdk/credential-provider-web-identity/dist-types/ts3.4/fromWebToken.d.ts:21:19 - error TS1005: ']' expected.

21     [K in keyof T as `${Uncapitalize<string & K>}`]: T[K];
              
node_modules/@aws-sdk/credential-provider-web-identity/dist-types/ts3.4/fromWebToken.d.ts:21:49 - error TS1005: '(' expected.

21     [K in keyof T as `${Uncapitalize<string & K>}`]: T[K];
                                        
node_modules/@aws-sdk/credential-provider-web-identity/dist-types/ts3.4/fromWebToken.d.ts:31:1 - error TS1160: Unterminated template literal.

### Reproduction Steps

more

### SDK version used

@aws-sdk/credential-providers@3.118.1

### Environment details (OS name and version, etc.)

macOS

**Comment by llh-check** [comment]
Same as https://github.com/aws/aws-sdk-js-v3/issues/2474

running typescript < 4.0.0 cannot correctly get types.

**Comment by yenfryherrerafeliz** [comment]
Hi @llh-check, is this still an issue for you?, if so, would it be possible for you to upgrade to a most recent TS version?. Basically this issue happens because the SDK started to use template literal types and mapped types, and the support for this typing mechanism was introduced in TS 4.1.

I look forward to your response.

Thanks!
