### ISSUE TITLE
Bring back SendRawEmailCommand for SESv2

### ISSUE THREAD

**Issue by jaschaio** [aws/aws-sdk-js-v3#3855]
### Describe the feature

It looks like the SESv2Client doesn't support sending raw emails and as far as I know there is no other way to set email headers.

### Use Case

I want to set custom email headers

### Proposed Solution

Make the SendRawEmailCommand available within SESv2

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

osx

**Comment by ajredniwja** [comment]
Hey @jaschaio thanks for opening this feature request, will discuss it with the team but cant promise on priority. Will keep the request open to see if we can get more traction and discussion on it.

**Comment by amitmoondra** [comment]
Any other way to handle to add headers to email using sesv2 sendEmail?

**Comment by RanVaknin** [comment]
Hi there,

I'm not sure why this was marked as "Bring back SendRawEmailCommand". Do you mean this was supported in the SESv2 client in v2? Because both v2 and v3 are generated from the same model file, so this should not be the case.

You can use the `SendRawEmailCommand` that is included in the SESclient (v1):https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/command/SendRawEmailCommand

For this to be added into the SESv2 Client on JS v3 SDK, it needs to have both backend API support, and also it needs to be included in the API model. Since the SDK team cannot add this ourselves, and you can use SESv1 and SESv2 together safely, we are going to close this feature request.

Thanks,
Ran~
