### ISSUE TITLE
Failed requests always return 400 as the response code

### ISSUE THREAD

**Issue by vlovich** [aws/aws-sdk-js-v3#3856]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

CopyObject with a non-existent source bucket is defined as returning a 404 NoSuchBucket. However, the S3 V3 SDK returns 400 NoSuchBucket. I've confirmed that both Boto3 v1.24.44 and AWS JS SDK v2 propagate the status code correctly.

I've tracked it down to this:
```
    if (statusCode < 200 && statusCode >= 300)
        return result;
```
in `@aws-sdk/middleware-sdk-s3/dist-cjs/throw-200-exceptions.js`

I'm guessing it's supposed to be `||`. This impacts more than just CopyObject obviously - all requests that return an error always set the status code erroneously to 400.

### SDK version number

@aws-sdk/client-s3@3.145.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.11.1

### Reproduction Steps

```
      await s3.copyObject({
        Bucket: 'non-existent-bucket',
        Key: 'testObject',
        CopySource: `/mybucket/nonExistentObject`,
      })
```

### Observed Behavior

Returned `httpStatusCode` in the returned `$metadata` is 400.

### Expected Behavior

Returned `httpStatusCode` in the returned `$metadata` should be 400.

### Possible Solution

Fix erroneous conditional. Status code cannot be both < 200 and >= 300, It should be `< 200 || >= 300`. I've confirmed that fixing the conditional fixes the issue & the returned status code is correct.

**Comment by yenfryherrerafeliz** [comment]
Hi @vlovich, thanks for opening this issue. I can confirm this is an issue and also is caused by what you mentioned. The condition [here](https://github.com/aws/aws-sdk-js-v3/blob/3b696a5ee2cc9973d0f3697a6a10566138293195/packages/middleware-sdk-s3/src/throw-200-exceptions.ts#L22) will never be met, since statusCode can't be less than 200 and greater than 299 at the same time, and then [here](https://github.com/aws/aws-sdk-js-v3/blob/3b696a5ee2cc9973d0f3697a6a10566138293195/packages/middleware-sdk-s3/src/throw-200-exceptions.ts#L34) the status code is defaulted to 400 to any response that contains <Error>. 

I will mark this issue to be reviewed so we can further address this.

Thanks @vlovich!

**Comment by yenfryherrerafeliz** [comment]
Code I used for my reproduction:

```js
import {CopyObjectCommand, S3, S3Client} from "@aws-sdk/client-s3";

const s3Client = new S3Client({
    region: 'REGION'
});
const params = {
    Bucket: 'NON-EXISTENT-BUCKET',
    Key: 'KEY',
    CopySource: 'COPY-SOURCE-PATH'
};
const response = await s3Client.send(new CopyObjectCommand(params));

console.log(response);
```
