### ISSUE TITLE
client-s3: add Location to PutObjectCommandOutput

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [aws/aws-sdk-js-v3#3875]
### Describe the feature

In aws-sdk v2, we used to get in the `Location` field in the output which then we could use, now in @aws-sdk/client-s3 we have to construct the same value.

It would be nice if we could have that again in the output:
```js
Location: `https://${putObjectCommand.input.Bucket}.s3.${this.region}.amazonaws.com/${putObjectCommand.input.Key}`
```

### Use Case

To get the URL for the object that I just uploaded in the output without having to construct it myself.

### Proposed Solution

add `Location` to `PutObjectCommandOutput`

### Other Information

I tried to create a PR for this, but I'm facing a few issues with TS, saying `S3Client` does not have a `send` method on `src\S3.ts:7118`

![Screenshot_616](https://user-images.githubusercontent.com/19984935/186048561-331a558a-aae4-4222-aac3-9cc1d38ce272.jpg)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.154.0

### Environment details (OS name and version, etc.)

Windows, Node 16.x

**Comment by yenfryherrerafeliz** [comment]
Hi @AbdelrahmanHafez, thanks for opening this feature request. I was reviewing the JS SDK V2 code and I did not see a Location field for [PutObjectOutput](https://github.com/aws/aws-sdk-js/blob/master/clients/s3.d.ts#L5221) interface, nonetheless I will leave this open as a feature request. I want to mention that we have other items with high priority so that I can not guarantee we will implement this in the near future. 

Regarding this:
>I tried to create a PR for this, but I'm facing a few issues with TS, saying S3Client does not have a send method on src\S3.ts:7118

If we follow the inheritance chain we can see here that S3 extends from S3Client and S3Client extends from the Client class defined in the smithy client package, and this is the class that implements the method send.

Here is the chain:
- S3 extends from S3Client [here](https://github.com/aws/aws-sdk-js-v3/blob/8fe1b54c191dbd0a3915ee64e8f03ed0f2f9ec01/clients/client-s3/src/S3.ts#L438)
- S3Client extends from _Client [here](https://github.com/aws/aws-sdk-js-v3/blob/8fe1b54c191dbd0a3915ee64e8f03ed0f2f9ec01/clients/client-s3/src/S3Client.ts#L714), and _Client is an alias defined [here](https://github.com/aws/aws-sdk-js-v3/blob/8fe1b54c191dbd0a3915ee64e8f03ed0f2f9ec01/clients/client-s3/src/S3Client.ts#L45) when imported
- And [here](https://github.com/aws/aws-sdk-js-v3/blob/8fe1b54c191dbd0a3915ee64e8f03ed0f2f9ec01/packages/smithy-client/src/client.ts#L16) is the implementation for Client, which is the base class that S3Client is extending from.

Thanks!

**Comment by damieng** [comment]
I suspect this was caused by moving from the v2 `s3.upload` function to `s3.putObject` as upload had a Location property.

A better option is to switch from `putObject` to [lib-storage](https://www.npmjs.com/package/@aws-sdk/lib-storage) which has the Upload functionality for v3 including Location and the multi-part handling etc.

**Comment by MJEND7** [comment]
> I suspect this was caused by moving from the v2 `s3.upload` function to v3's `s3.putObject` as upload returned an object with a Location property in v2.
> 
> A better option is to use [lib-storage](https://www.npmjs.com/package/@aws-sdk/lib-storage) which better replicates v2's upload functionality in v3 including Location and the multi-part handling etc.

Is there a major difference to them? I would think the `s3.putObject` would be more performant over the package [lib-storage](https://www.npmjs.com/package/@aws-sdk/lib-storage). I was just thinking that if I wanted the location it would be easier to do 
```js
https://${bucket}.s3${region}.amazonaws.com/${key}
```
strait after I make a put request. I was just wounding the advantage of using  [lib-storage](https://www.npmjs.com/package/@aws-sdk/lib-storage) for this specific issue.

**Comment by damieng** [comment]
lib-storage also allows for multi-part file uploading and can perform those uploads in chunks concurrently so is in fact more performant for larger uploads.

**Comment by MJEND7** [comment]
> lib-storage also allows for multi-part file uploading and can perform those uploads in chunks concurrently so is in fact more performant for larger uploads.

Ah that makes sense, after looking to it more yeah it does provide parallel uploads of files which is great. Thanks for the response 👍

**Comment by AbdelrahmanHafez** [comment]
@yenfryherrerafeliz 
Is this actually complete or just closing because it's stale?
