### ISSUE TITLE
fast-xml-parser and is not es5

### ISSUE THREAD

**Issue by ItamarGronich** [aws/aws-sdk-js-v3#3900]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`fast-xml-parser` library for some reason not being compiled with babel.
Therefore the code contains non es5 output.
And breaks on older browsers.

I've opened a ticket for this: https://github.com/NaturalIntelligence/fast-xml-parser/issues/494

### SDK version number

@aws-sdk/client-s3, and any other package using fast-xml-parser

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

old browsers not supporting > es5

### Reproduction Steps

setup simple webpack project and import client-s3.
Observe the output bundle and see that fast-xml-parser is included with `const` keywords.

### Observed Behavior

App output bundle has `const` keywrods.

### Expected Behavior

no const keywords in bundle.

### Possible Solution

use a different xml parser library.
Get the library author to fix the build and build the library output with babel targeting es5.

**Comment by ajredniwja** [comment]
Thanks for opening this issue, I am not sure if this issue should be fixed here in the SDK.

**Comment by RanVaknin** [comment]
Hi @ItamarGronich ,

Sorry for the long response times. 
Since the SDK version used is not mentioned, and the browser and browser versions are not mentioned its hard for us to determine what is not compatible with what. 

You can refer to the list of supported Browsers and versions that we support with each SDK version [here](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-up.html#browsers-supported)

Since this issue is super old I'm going to close it. 

If this persists, please create a new issue and include all the versions used (browser, SDK)

Thanks,
Ran~
