### ISSUE TITLE
Replacing -> value: string | undefined;  for -> value?: string;

### ISSUE THREAD

**Issue by ChristopherPHolder** [aws/aws-sdk-js-v3#3985]
### Describe the issue

It seems that in the typescript models I keep finding the use of undefined. 

Is there a reason for this?
Or can I contribute by converting them?

From what I understand these to statement bellow mean the same:
```ts
value: string | undefined;
value?: string;
```

### Links

This is from the example above but there really are a lot though out the models

https://github.com/aws/aws-sdk-js-v3/blob/e92370820eedcfbd1516b226034891434666be10/clients/client-ssm/src/models/models_1.ts#L570

**Comment by yenfryherrerafeliz** [comment]
Hi @ChristopherPHolder, thanks for opening this issue. I agree that those two statements mean almost the same, the only difference is that the first one will force the parameter to be given even if is undefined. I do not know the reason why it was implemented in that way, but maybe there are some internal validations for the request which requires those fields to be present even if undefined, however I need to investigate this further to confirm. 

So, in order to investigate this further could you please provide more details about why we should change our current implementation?, and how is the current implementation a blocking for you?

Thanks!
