### ISSUE TITLE
Support AWS SigV2

### ISSUE THREAD

**Issue by Edgar-P-yan** [aws/aws-sdk-js-v3#4032]
### Describe the feature

Hi!
aws-sdk v2 had an option `signatureVersion: 'v2' | 'v4'` which allowed to switch to the old and deprecated AWS SigV2.

### Use Case

While it is recomended to use the newest V4, some third-party S3 storages still require the old version. So supporting it would be really helpful.

### Proposed Solution

The feature can be introduced as a new package `@aws-sdk/signature-v2` (similar to the current `@aws-sdk/signature-v4` package) which will export a `class SignatureV2 implements RequestPresigner, RequestSigner, StringSigner, EventSigner`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

^3.186.0

### Environment details (OS name and version, etc.)

Ubuntu WSL

**Comment by shirady** [comment]
I'm also requesting this feature.

In the AWS SDK V2, [signatureVersion](url) is a property in the [s3-client constructor](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property).
But, unfortunately, it was removed from AWS SDK V3 (copied from the [Upgrading Notes](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md)):

> v2: The signature version to sign requests with (overriding the API configuration).
> v3: Deprecated. Signature V2 supported in v2 SDK has been deprecated by AWS. v3 only supports signature v4.

Since the endpoint can be an s3-storage server that might be using only signature Version v2, please consider this decision again :pray:.

**Comment by aBurmeseDev** [comment]
Hey all - sorry for the long wait. 

We had a team discussion about this today and unfortunately, we won't be implementing this since the ask here to make it work for "some third-party S3 storages still require the old version" and our SDK is only  to be compatible with AWS (services). 
Let us know if you have any other questions.
