### ISSUE TITLE
Duplicate middleware DynamoDB commands

### ISSUE THREAD

**Issue by austinmr** [aws/aws-sdk-js-v3#4181]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When following the pattern established in the Dynamo lib [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_dynamodb.html) for adding middleware with names, the following issues are encountered. 

* With named middleware:  The commands fail with an error about duplicate middleware when the command is run, NOT at add. 
* With un-named middleware: The middleware code is executed twice. 
* When working with the stack, the identify response returns empty array 

### SDK version number

@aws-sdk/lib-dynamodb@3.208

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.16.0

### Reproduction Steps

```js
import { GetCommand } from '@aws-sdk/lib-dynamodb';

const command = new GetCommand({ TableName: 'Foo', Key: { fooId: 'f1' } })
    command.middlewareStack.add(
      (next) => async (args) => {
        console.log('PRE_MARSAHLL MIDDLEWARE');
        return next(args);
      },
      {,
        step: "build",
        priority: "low",
        "name": `PreMarshallValidation:${Math.random()}`,
      }
    )
    const item = await client.sendGet(command);
```

### Observed Behavior

Dynamo client `send` fails with the following error: 

```
  Duplicate middleware name 'PreMarshallValidation:0.4105328852963164'
  at Object.add (node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:130:31)
      at node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:41:21
          at Array.forEach (<anonymous>)
      at Object.cloneTo [as applyToStack] (node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:40:25)
      at Object.use (node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:167:20)
      at Object.concat (node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:193:20)
      at GetItemCommand.resolveMiddleware (node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/GetItemCommand.js:25:35)
      at GetCommand.resolveMiddleware (node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/GetCommand.js:18:44)
      at DynamoDBDocument.send (node_modules/@aws-sdk/smithy-client/dist-cjs/client.js:13:33)
      at DynamoClientLocal.send [as sendGet] (src/aws/Dynamo/clients/DynamoLocal.client.ts:54:30)
      at Object.sendGet (src/test/dynamo/client/DynamoClientL.spec.ts:41:31)
```

When stepping through the code with debugger, there are many more calls to `MiddlewareStack.add` than expected and the `entriesNameSet` is inconsistent, leading me to believe that several distinct middleware stacks are being combined but the manner for combining them is not working. Specifically, I see 3 sequences where the added middleware is being added before it ultimately hits the following code path

```
if (name) {
                if (entriesNameSet.has(name)) {
                    if (!override)
                        throw new Error(`Duplicate middleware name '${name}'`);
```

### Expected Behavior

* Adding middleware should be consistent and not result in duplicate invocations or errors when using names

### Additional Information/Context

More documentation about implementing middleware and plugins would be helpful, as identify seems to be returning a different middleware stack that isn't populated until the command is sent which is not very helpful for properly chaining middleware. 

Additionally, confirmation that the customized command middleware stack is valid approach meaning that we can be confident that middleware functions will be executed once and only once per command invocation with no shared state across other command instances.

**Comment by austinmr** [comment]
One work-around that seems to be working is utilizing context to set a flag that will be included in the second call to `add` or `addRelativeTo` as an alternative to setting override. 

Adding as it may be helpful to debugging if context is shared.

**Comment by yenfryherrerafeliz** [comment]
Hi @austinmr, thanks for opening this issue. After looking into this, I found the problem, and it is basically that [here](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/src/commands/GetCommand.ts#L47) those two variables (this.middlewareStack and this.clientCommand.middlewareStack) become the same object, which means that any value(middleware) added to any of them, but in our case to the middlewareStack of the command will be in both variables of course, but after [here](https://github.com/aws/aws-sdk-js-v3/blob/df1304fadd3bb61dff4a1483af99332630b5c9de/lib/lib-dynamodb/src/commands/GetCommand.ts#L59) is where the duplicity occurs:
- In the following line: 
>const stack = clientStack.concat(this.middlewareStack as typeof clientStack);

we see that the middlewareStack of the client concatenates the middlewareStack provided, which in this case is the middlewareStack of the command, and the concat function basically create a copy of the given middlewareStack, so that the result will be a stack with all the middlewares of the client and the command.
- Then, [here](https://github.com/aws/aws-sdk-js-v3/blob/df1304fadd3bb61dff4a1483af99332630b5c9de/lib/lib-dynamodb/src/commands/GetCommand.ts#L60):
> const handler = this.clientCommand.resolveMiddleware(stack, configuration, options);

the final handler is resolved using "this.clientCommand.resolveMiddleware", which also contains any middleware contained by this.middlewareStack, and basically, resolveMiddleware will also concatenate the middlewares in the stack being resolved with the middlewares of the stack given as parameter, and as we could see in the code before, that stack variable given already contains the middlewares that the stack that is resolving the handler has, and that is how the duplicity occurs.

I will mark this issue to review so we can address this further.

Steps to reproduce:
- Start a new project with npm:
    - ```npm init projectname```
- Install the dependencies lib-dynamodb and dynamodb client
    - ``` npm i @aws-sdk/lib-dynamodb ```
    - ``` npm i @aws-sdk/client-dynamodb ```
- Then, copy paste the following code in a js file, ex: "src/index.js":
    ```js
        import {
            GetCommand,
            DynamoDBDocumentClient
        } from '@aws-sdk/lib-dynamodb';
        import {DynamoDBClient} from "@aws-sdk/client-dynamodb";
    
        const client = new DynamoDBClient({
            region: 'us-east-2'
        });
        const dbdClient = DynamoDBDocumentClient.from(client);
        const command = new GetCommand({ TableName: 'test-table', Key: { id: 'f1' } })
        command.middlewareStack.add( next => args => {
            return next(args);
        }, {
            step: 'build',
            priority: "low",
            name: "PreMarshallValidation: " + Math.random(),
        });
        const item = await dbdClient.send(command);
    
        console.log(item);
    
    ```
- Run the code:
    - ``` node src/index.js ```

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@austinmr as workaround you could also add the middleware to the middlewareStack of the client, instead of the middlewareStack of the command and that will work as well.

Thanks!

**Comment by RanVaknin** [comment]
Another workaround is to use the override:

```js
command.middlewareStack.add( next => args => {
        return next(args);
    }, {
        step: 'build',
        priority: "low",
        name: "PreMarshallValidation: " + Math.random(),
        override: true, 
    });
```

Thanks,
Ran~

**Comment by kuhe** [comment]
Yes, as Ran says above, please use `override: true` and a unique `name` when adding middleware.
