### ISSUE TITLE
`input.regionInfoProvider is not a function` on 3.194.0 when specifying an endpoint

### ISSUE THREAD

**Issue by cnorthwood** [aws/aws-sdk-js-v3#4208]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Upon upgrading to 3.194.0, we are no longer able to configure the CognitoIdentityServiceProvider to talk to cognito-local, which we use for CI end-to-end integration testing

### SDK version number

@aws-sdk/client-cognito-identity-provider@3.194.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.17.1

### Reproduction Steps

```
function buildLocalCognitoClient() {
  return new CognitoIdentityProviderClient({
    region: "local",
    endpoint: "http://localhost:9229",
    credentials: { accessKeyId: "test", secretAccessKey: "test" },
  });
}
```

### Observed Behavior

`TypeError: input.regionInfoProvider is not a function`

### Expected Behavior

For the IdentityProviderClient to be successfully constructed

**Comment by RanVaknin** [comment]
Hi @cnorthwood,

Thanks for opening this issue. 

Recently there have been a lot of rework of how the SDK resolves endpoints so this newer functionality might not play well with that 3rd party tool you are using. As a rule of thumb we do not guarantee support for 3rd party libraries.

**Personal speculation:** I see on the [main page](https://www.npmjs.com/package/cognito-local) of that 3rd party library that many of Cognito's operation are not supported and that the last time it was updated was 4 months ago. Since we release daily I'd assume it's quite out of date.
That being said I've never used that tool and not sure how it works.

If you think this is an unrelated matter and should be supported please let me know and I'll see how I can help.

Thank you!
Ran~

**Comment by cnorthwood** [comment]
I believe that's an unrelated issue, as the error comes when setting the endpoint, and before actually talking to the service. If the process for setting a new endpoint has changed, it doesn't appear to be documented anywhere

**Comment by RanVaknin** [comment]
@cnorthwood can you provide a more in depth code sample and reproduction steps? Are you running into an error when running that function? Because I'm able to construct a client the client without any issues.

Thanks,
Ran

**Comment by cnorthwood** [comment]
I have a sneaking suspicion that this is due to a bug in NPM's dependency resolution as we've had this before, as a result of the aws-sdk's interesting approach to version control. Blowing away node_modules and reinstalling from the same lockfile no longer reproduces it, vs what was happening before after upgrading to the latest point releases.

**Comment by RanVaknin** [comment]
Then I assume this is no longer an issue? If this persists feel free to open another ticket.

Thank you,
Ran~
