### ISSUE TITLE
ruleset file in client-s3 too large (1.4MB)

### ISSUE THREAD

**Issue by dreamorosi** [aws/aws-sdk-js-v3#4296]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The s3 client has a file under called ruleset that accounts for more than half of the size of the whole client, possibly due to excessive use of whitespace and lack of minification

### SDK version number

@aws-sdk/client-s3@latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.12.1

### Reproduction Steps

- `npm i @aws-sdk/client-s3`
- Check size of `node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/ruleset.js`

### Observed Behavior

As it stands, the file appears to be very large (1.4M) and with most of it being whitespace.

### Expected Behavior

Possibly to not have a single file that accounts for 60% of the entire client.

### Possible Solution

Possibly minimize the file to reduce all the whitespace.

I tested manually removing whitespaces and the file size went down to 84K.

**Comment by yenfryherrerafeliz** [comment]
Hi @dreamorosi, thanks for opening this issue. We have opened the [following](https://github.com/aws/aws-sdk-js-v3/issues/4299) feature request in order to take in consideration the improvement of the size for the ruleset file. Please feel free to comment there so it gets more traction from the community.

Thanks!

**Comment by dreamorosi** [comment]
@yenfryherrerafeliz How come this issue was marked as duplicate while it was created days before the one you linked?

I understand you wanted to classify it as a feature request (arguable decision) instead of a bug, however you could have simply either edited this issue or continued the conversation below.

I took the time to open an issue after a lot of customers have been complaining on social media, opening a separate issue voids any kind of attribution and discouraged the community from approaching with your project.

**Comment by yenfryherrerafeliz** [comment]
Hi @dreamorosi, my apologies, my intention was never meant to ignore the effort you put in creating this issue, and we really value the contribution from our community. The reason why I marked it as duplicate was because the linked issue was created by one of our engineers, in order to have it in his backlog, and I though was going to be much better to track the work status of it in that item. 

Again thank you for bringing this issue to us.

Thanks!

**Comment by kuhe** [comment]
In https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.235.0 a compression effect has been applied that brings down the size of the endpoint ruleset.

Comparison available here: https://packagephobia.com/result?p=@aws-sdk/client-s3@3.235.0
