### ISSUE TITLE
util-stream-browser has no dist-cjs

### ISSUE THREAD

**Issue by sonyaos** [aws/aws-sdk-js-v3#4330]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

util-stream-browser has no dist-cjs folder

### SDK version number

@aws-sdk/client-s3@3.245.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.18.0

### Reproduction Steps

npm i @aws-sdk/client-s3

### Observed Behavior

util-stream-browser has no dist-cjs folder

### Expected Behavior

util-stream-browser has dist-cjs folder

**Comment by yenfryherrerafeliz** [comment]
Hi @sonyaos, thanks for opening this issue. The reason why there is not a dist-cjs folder is because, that package is intended to be used just with browser as runtime specifically. We have another package, which you can use when working with node runtime, that is util-stream-node, which you can take a look to [here](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/util-stream-node/src).

Please let me know if you have any questions regarding to this.

Thanks!
