### ISSUE TITLE
An Example of how to use @aws-sdk/client-apigatewayv2

### ISSUE THREAD

**Issue by gxxcastillo** [aws/aws-sdk-js-v3#4354]
### Describe the issue

Hi, for as much as I've looked I have not been able to find an example of how to use @aws-sdk/client-apigatewayv2 to make an api call to my api gateway.  I found [this document](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apigatewayv2/index.html) but I don't see where I would give it the path, how to use a IAM role with it, or how to pass in arguments for the request.  I've spent nearly an hour on the phone with tech support but we weren't able to get to an answer. I've also looked at examples in the examples repo but could not find examples for apigateway.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apigatewayv2/index.html

**Comment by RanVaknin** [comment]
Hi @gxxcastillo 

Thanks for opening this issue.
Admittedly I've spent hours trying to find examples for this and they simply don't exist, so I did my best trying to follow the available tutorials and trying to find the corresponding API operations for each one.

For starters, I'd check if you even need to use `@aws-sdk/client-apigatewayv2` this client is for Apigateway APIs that are of HTTP type or WebSocket type. If you have created an API already and it is of type REST you'll wanna use the `@aws-sdk/client-apigateway` package instead.

Assuming you are using an HTTP API, the example Im going to share loosely follows this [tutorial](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-dynamo-db.html#http-api-dynamo-db-create-api) by trying to mimic the SDK operations needed to achieve the same flow.

> how to pass in arguments for the request

You'll need to create an integration for that, and in it defining the lambda function you are going to use.
After that, you create a route and tie the integration to that route.
In theory each route can have its own lambda but in this example I use the same one across both get calls to /items and /items/{id}.

```js
import { ApiGatewayV2Client, CreateIntegrationCommand, CreateRouteCommand, CreateStageCommand, CreateDeploymentCommand } from "@aws-sdk/client-apigatewayv2";

const client = new ApiGatewayV2Client({region: "us-east-1"})


try {
    // create integration for each type of action: GET POST PUT
    const res = await client.send(new CreateIntegrationCommand({
        ApiId: API_ID,
        IntegrationMethod: "GET",
        IntegrationType: "AWS_PROXY",
        IntegrationUri: "arn:aws:lambda:us-east-1:<your-acount-number>:function:<your-lambda-name>",
        PayloadFormatVersion: "2.0"
    }))

    // if the integration creation is successful, us the integration id to tie it to a route.
    // in this case if GET to host/items or host/items/{id} is called the lambda function supplied in the previous step would be called.
    if (res.IntegrationId) {
        await client.send(new CreateRouteCommand({
            ApiId: API_ID,
            RouteKey: "GET /items",
            Target: `integrations/${res.IntegrationId}`
        }))
    }

    if (res.IntegrationId) {
        console.log(res.IntegrationId)
        await client.send(new CreateRouteCommand({
            ApiId: API_ID,
            RouteKey: "GET /items/{id}",
            Target: `integrations/${res.IntegrationId}`
        }
        ))
    }

    // Once we set up the desired routes and integration we need to create a stage before we deploy our API. 
    const createStageResult = await client.send(new CreateStageCommand({
        ApiId: API_ID,
        StageName: "stage-one",
    }))

    // if stage creation is successful, deploy that stage / version of the API.
    if (createStageResult.StageName){
        const data = await client.send(new CreateDeploymentCommand({
            ApiId: API_ID,
            StageName: createStageResult.StageName
        }))
        console.log(data)
    }

} catch (error) {
    console.log(error)
}
```

> how to use a IAM role with it

Im not sure what you mean by this. The Lambda has to have a role that allows the APIGateway to call it on your behalf.
If you you mean how to use the SDK with an IAM role instead of credentials you can check out [this doc].(https://docs.aws.amazon.com/sdkref/latest/guide/feature-assume-role-credentials.html)

Again, since there was nothing for me to reference, I hope my little reproduction was somewhat helpful.
Let me know if you have any other questions.

Thank you!
Ran

**Comment by gxxcastillo** [comment]
Thanks @RanVaknin!  In the end, I think I ended up just bypassing the sdk, instead building the request and signing it manually.  

It's good to know that @aws-sdk/client-apigateway and @aws-sdk/client-apigatewayv2 have to completely different use cases though! I couldn't find documentation on the subject so I just assumed that v2 was the newer and therefore the better choice :)
