### ISSUE TITLE
fromInstanceMetadata does not retry on error despite maxRetries set

### ISSUE THREAD

**Issue by jhuckaby** [aws/aws-sdk-js-v3#4407]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using `@aws-sdk/client-s3` with `@aws-sdk/credential-providers` and `fromInstanceMetadata()`, sometimes the metadata service fails for unknown reasons (usually status code 503).  When this happens, **no retries are ever attempted**, despite `maxRetries` being set.  I know this to be the case because:

1. The `$metadata` property in the error object shows: `{ attempts: 1 }`.
2. The total time elapsed on a test script equals the timeout (it should be the timeout multiplied by the retries).

### SDK version number

@aws-sdk/client-s3@3.264.0, @aws-sdk/credential-providers@3.264.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.12.0

### Reproduction Steps

Run this script on a server that **doesn't** have the EC2 metadata service running (so requests to 169.254.169.254 will all fail), such as a local server.

```js
const S3 = require("@aws-sdk/client-s3");
const { fromInstanceMetadata } = require("@aws-sdk/credential-providers");

const s3 = new S3.S3Client({
	region: 'us-west-1',
	maxAttempts: 5,
	credentials: fromInstanceMetadata({
		maxRetries: 5,
		timeout: 5000,
	})
});

let params = {
	Bucket: 'adm-media-ca-ec2-prod-uswest1',
	Key: 'robots.txt'
};

(async function() {
	try {
		let data = await s3.send( new S3.HeadObjectCommand(params) );
		console.log( data );
	}
	catch (err) {
		console.error(err);
	}
})();
```

### Observed Behavior

The output will show:

```
ProviderError: Unable to connect to instance metadata service
    at ClientRequest.<anonymous> (/Users/jhuckaby/temp/awsretry/node_modules/@aws-sdk/credential-provider-imds/dist-cjs/remoteProvider/httpRequest.js:16:34)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  tryNextLink: true,
  errno: -64,
  code: 'EHOSTDOWN',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

Notice that the `$metadata` object shows: `{ attempts: 1 }`.

Also notice that the total elapsed time of the test script is approximately 5 seconds (the same as the timeout).  

### Expected Behavior

The instance metadata request should be retried 5 times, so the `$metadata` property from the error object should show: `{ attempts: 5 }`.

Also, the script should take approximately 25 seconds to fail all attempts, when run on a server without the metadata service running.

### Possible Solution

n/a

### Additional Information/Context

fromInstanceMetadata seems to be ignoring the `maxRetries` property entirely.  Is there a different way I should be specifying this value?  I followed the documentation here:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromcontainermetadata-and-frominstancemetadata

Possibly related issue: https://github.com/aws/aws-sdk-js-v3/issues/4328

**Comment by yenfryherrerafeliz** [comment]
Hi @jhuckaby, thanks for opening this issue. After looking into this I found that even though the retries made are not reported in the metadata field, they are still done, but not sure if in the correct way. Lets analyze the flow based on the repro steps you have provided:
The first http request to be done, when calling the imds credential provider, starts [here](https://github.com/aws/aws-sdk-js-v3/blob/df945f5225c6f7962e2b56d8c899156df427920a/packages/credential-provider-imds/src/fromInstanceMetadata.ts#L65), where it will fail since we are not testing on a ec2 instance, and therefore an exception will be thrown.
Then, in the catch body we have the following:
```js
if (error?.statusCode === 400) {
    throw Object.assign(error, {
        message: "EC2 Metadata token request returned error",
    });
} else if (error.message === "TimeoutError" || [403, 404, 405].includes(error.statusCode)) {
    disableFetchToken = true;
}

return getCredentials(maxRetries, { ...endpoint, timeout });
```
In our case none of the conditions there will be met, so that the next line to be executed will be [this](https://github.com/aws/aws-sdk-js-v3/blob/df945f5225c6f7962e2b56d8c899156df427920a/packages/credential-provider-imds/src/fromInstanceMetadata.ts#L74) one:
```js
return getCredentials(maxRetries, { ...endpoint, timeout });
```
Then, the next execution statements will be the ones that will do the retry, which is when getting the profile [here](https://github.com/aws/aws-sdk-js-v3/blob/df945f5225c6f7962e2b56d8c899156df427920a/packages/credential-provider-imds/src/fromInstanceMetadata.ts#L29):
```js
const profile = (
    await retry<string>(async () => {
        let profile: string;
        try {
            profile = await getProfile(options);
        } catch (err) {
            if (err.statusCode === 401) {
                disableFetchToken = false;
            }
            throw err;
        }
        return profile;
    }, maxRetries)
).trim();
```
As we could see, the logic to fetch the profile is passed as an async function to the retry function, which implementation is [here](https://github.com/aws/aws-sdk-js-v3/blob/df945f5225c6f7962e2b56d8c899156df427920a/packages/credential-provider-imds/src/remoteProvider/retry.ts#L8), where we will iterate n times, where n is the maxRetries value given, and we will schedule a call for the function given "the one to fetch the profile" if the previous promise gets rejected. So, I also confirmed the retries happens there by logging any value from the getting profile function. For example, logging any value before this [line](https://github.com/aws/aws-sdk-js-v3/blob/df945f5225c6f7962e2b56d8c899156df427920a/packages/credential-provider-imds/src/fromInstanceMetadata.ts#L33), and you will see is retried the n times specified in maxRetries.

However, as I said, I observed two things here, the first one is that the retry should be done starting [here](https://github.com/aws/aws-sdk-js-v3/blob/df945f5225c6f7962e2b56d8c899156df427920a/packages/credential-provider-imds/src/fromInstanceMetadata.ts#L65), where the toke is tried to be fetched, etc., and the other thing I found is that there is not delay in between the retries which can be an issue because we are not giving enough time for the problem that causes the request to failed to maybe get fixed. Because, it will not be fixed so quick as the retries happen.

I will leave this issue under investigation until we can confirm the right behavior for the retries.

If you have any thoughts or comments please just let me know.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @WarrenWongCodes, as you can see in my comment [here](https://github.com/aws/aws-sdk-js-v3/issues/4407#issuecomment-1442650377), the retries are actually being done, but not logged in the response. I think the reason for this is because the retries we actually show in this response is the retries done for requests done to the operational services such as S3, etc. 

Please let me know if that helps!

Thanks!
