### ISSUE TITLE
getSignedUrl in v3 is 8-10x slower than v2

### ISSUE THREAD

**Issue by claycoleman** [aws/aws-sdk-js-v3#4421]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We recently upgraded from AWS SDK v2 to v3 and noticed that our code which produced large numbers of signed urls (5k) was running significantly slower.

I wrote a small script using `benchmark` to verify this, and it seems that the new code is around 8x slower than the old code.

```console
creating 100 presigned urls
sdk v2 x 195 ops/sec ±4.30% (87 runs sampled)
sdk v3 x 25.16 ops/sec ±5.40% (65 runs sampled)
Fastest is sdk v2
- sdk v3 is 7.74x slower
```

I ran this multiple times with various amounts of urls and saw similar results

```console
creating 10 presigned urls
sdk v2 x 1,880 ops/sec ±1.81% (84 runs sampled)
sdk v3 x 207 ops/sec ±3.65% (84 runs sampled)
Fastest is sdk v2
- sdk v3 is 9.07x slower

creating 1000 presigned urls
sdk v2 x 20.17 ops/sec ±3.76% (53 runs sampled)
sdk v3 x 2.52 ops/sec ±5.39% (17 runs sampled)
Fastest is sdk v2
- sdk v3 is 8.00x slower
- 
creating 5000 presigned urls
sdk v2 x 4.16 ops/sec ±3.03% (25 runs sampled)
sdk v3 x 0.48 ops/sec ±5.37% (7 runs sampled)
Fastest is sdk v2
- sdk v3 is 8.59x slower
```

Also, why did the function signature between v2 and v3 change from sync to async? my understanding was that signing urls did not involve IO in any way.

### SDK version number

@aws-sdk/client-s3@3.259.0 vs aws-sdk@2.1097.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.14.0

### Reproduction Steps

```js
const NUM_ITERATIONS = 100;

const options: Benchmark.Options = {
  onStart() {
    console.log(this.name ?? 'Running benchmark');
  },
  onError(event: any) {
    console.log(event.target.error);
  },
  onCycle(event: any) {
    console.log(String(event.target));
  },
  onComplete() {
    const fastestResult: {
      name: string;
      hz: number;
    } =
      // @ts-expect-error
      this.filter('fastest')[0];

    console.log(`Fastest is ${fastestResult.name}`);
    // calculate how much faster the fastest is than each other run
    // @ts-expect-error
    this.forEach((result: { name: string; hz: number }) => {
      if (result.name !== fastestResult.name) {
        const multipleSlower = (fastestResult.hz / result.hz).toFixed(2);

        console.log(`- ${result.name} is ${multipleSlower}x slower`);
      }
    });
  },
};

new Benchmark.Suite(`creating ${NUM_ITERATIONS} presigned urls`, options)
  .add(`sdk v2`, {
    defer: true,
    async fn(deferred: { resolve: () => void }) {
      const s3 = new AWS.S3();

      for (let i = 0; i < NUM_ITERATIONS; i++) {
        s3.getSignedUrl('getObject', {
          Bucket: bucket,
          Key: key,
        });
      }

      deferred.resolve();
    },
  })
  .add(`sdk v3`, {
    defer: true,
    async fn(deferred: { resolve: () => void }) {
      const s3 = new S3({});

      const promises = [];
      for (let i = 0; i < NUM_ITERATIONS; i++) {
        promises.push(
          getSignedUrl(
            s3,
            new GetObjectCommand({
              Bucket: bucket,
              Key: key,
            }),
          ),
        );
      }

      await Promise.all(promises);

      deferred.resolve();
    },
  })
  .run({ async: true });
```

### Observed Behavior

I wrote a small script using `benchmark` to verify this, and it seems that the new code is around 8x slower than the old code.

```console
creating 100 presigned urls
sdk v2 x 195 ops/sec ±4.30% (87 runs sampled)
sdk v3 x 25.16 ops/sec ±5.40% (65 runs sampled)
Fastest is sdk v2
- sdk v3 is 7.74x slower
```

I ran this multiple times with various amounts of urls and saw similar results

```console
creating 10 presigned urls
sdk v2 x 1,880 ops/sec ±1.81% (84 runs sampled)
sdk v3 x 207 ops/sec ±3.65% (84 runs sampled)
Fastest is sdk v2
- sdk v3 is 9.07x slower

creating 1000 presigned urls
sdk v2 x 20.17 ops/sec ±3.76% (53 runs sampled)
sdk v3 x 2.52 ops/sec ±5.39% (17 runs sampled)
Fastest is sdk v2
- sdk v3 is 8.00x slower
- 
creating 5000 presigned urls
sdk v2 x 4.16 ops/sec ±3.03% (25 runs sampled)
sdk v3 x 0.48 ops/sec ±5.37% (7 runs sampled)
Fastest is sdk v2
- sdk v3 is 8.59x slower
```

### Expected Behavior

For there to be less of a performance gap?

Also for there to be an API to get a signed url in a synchronous way (some packages we use don't support async functions and v3 prevents us from using them :/)

**Comment by claycoleman** [comment]
I did some further investigation – it also seems that the urls produced by these functions are different:

Url produced by v3: https://BUCKET.s3.REGION.amazonaws.com/KEY?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=CREDENTIAL&X-Amz-Date=DATE&X-Amz-Expires=14400&X-Amz-Signature=SIGNATURE&X-Amz-SignedHeaders=host&x-id=GetObject

Url produced by v2: https://BUCKET.s3.REGION.amazonaws.com/KEY?AWSAccessKeyId=ACCESS_KEY&Expires=1675912189&Signature=SIGNATURE

Is there a way to produce the below type of signed url using the v3 sdk?

**Comment by yenfryherrerafeliz** [comment]
Hi @claycoleman, thanks for opening this issue. I can confirm the reported behavior, so that I will mark this issue to be reviewed so it can be further addressed. 

Steps to reproduce:
- Create an empty node project ``` npm init -y ```
- Install the V3 dependencies:
    - ``` npm i @aws-sdk/client-s3 ```
    - ``` npm i @aws-sdk/s3-request-presigner ```
- Install the V2 dependencies:
    -  ``` npm i aws-sdk ```
- Create a js file, maybe src/index.js, and copy paste the following code:
```js
import {
    GetObjectCommand,
    S3Client
} from "@aws-sdk/client-s3";
import {
    getSignedUrl
} from "@aws-sdk/s3-request-presigner";
import AWS from "aws-sdk";

const v3Client = new S3Client({
    region: process.env.TEST_REGION
})
const v2Client = new AWS.S3({
    region: process.env.TEST_REGION
})

const buildV3Promise = () => {
    return new Promise(async (resolve, reject) => {
        try {
            const signedUrl = await getSignedUrl(v3Client, new GetObjectCommand({
                Bucket: process.env.TEST_BUCKET,
                Key: process.env.TEST_KEY
            }))
            resolve({
                version: 'V3',
                value: signedUrl
            });
        } catch (e) {
            reject(e);
        }
    });
}
const buildV2Promise = () => {
    return new Promise((resolve, reject) => {
        try {
            const signedUrl = v2Client.getSignedUrl('getObject', {
                Bucket: process.env.TEST_BUCKET,
                Key: process.env.TEST_KEY
            })
            resolve({
                version: 'V2',
                value: signedUrl
            });
        } catch (e) {
            reject(e);
        }
    });
};
const itemCount = 10;
for (let i = 0; i < itemCount; i++) {
    const value = await Promise.race([buildV2Promise(), buildV3Promise()]);
    console.log('Version that won the race: ', value.version);
}
```
- Run the file: ``` node src/index.js```
- You will see that V2 always wins the race

Thanks!

**Comment by kuhe** [comment]
@claycoleman what if you initialize the S3 clients outside of the benchmarked function?

**Comment by CM96** [comment]
@claycoleman were you able to get the same output as the v2 one ? I have been getting access denied because the output presigned url is not matching my v2 output url? or I am missing something not mentioned in the doc. I also noticed that my metadata from params weren't getting signed. Even after explicitly adding their headers as part of the signableHeaders. Here is what I tried to do:

```js
    const params = {
        Bucket: s3Bucket,
        Key: key,
        ContentType: 'application/x-www-form-urlencoded; charset=UTF-8',
        Metadata: { userId, sourceSystem }
    };

    try {
        const s3Client = new S3Client({region});
        const command = new PutObjectCommand(params);
        return getSignedUrl(s3Client, command, { expiresIn: 120, signableHeaders: new Set(['x-amz-meta-userid', 'x-amz-meta-sourcesystem'])})
    }
    catch (e) {
        const msg = `Unable to get PUT presignedUrl: ${e.message}`;;
        throw new Error(msg);
    }
```
The output doesn't seem to sign the metadata headers which I am assuming is the reason why the upload fails.

**Comment by claycoleman** [comment]
> what if you initialize the S3 clients outside of the benchmarked function?

@kuhe good call – seems v3 is still slower than v2, but only by 7-8x (instead of 8-10x)

```
creating 100 presigned urls
sdk v2 x 211 ops/sec ±1.96% (85 runs sampled)
sdk v3 x 26.95 ops/sec ±3.80% (68 runs sampled)
Fastest is sdk v2
- sdk v3 is 7.84x slower

creating 10 presigned urls
sdk v2 x 2,009 ops/sec ±3.55% (84 runs sampled)
sdk v3 x 280 ops/sec ±2.56% (83 runs sampled)
Fastest is sdk v2
- sdk v3 is 7.17x slower


creating 1000 presigned urls
sdk v2 x 18.79 ops/sec ±4.80% (56 runs sampled)
sdk v3 x 2.63 ops/sec ±4.72% (18 runs sampled)
Fastest is sdk v2
- sdk v3 is 7.14x slower

creating 5000 presigned urls
sdk v2 x 3.96 ops/sec ±5.82% (25 runs sampled)
sdk v3 x 0.52 ops/sec ±5.78% (7 runs sampled)
Fastest is sdk v2
- sdk v3 is 7.62x slower
```

**Comment by claycoleman** [comment]
> were you able to get the same output as the v2 one ?

@CM96 we haven't, unfortunately. for us, the structure of the url doesn't matter, so we are just interested in speed. the node aws sdk docs for signing urls are rather sparse

**Comment by RanVaknin** [comment]
Hi @claycoleman ,

Regarding the differences between v2 and v3. I believe this is related to what the customer @plumdog describes [here](https://github.com/aws/aws-sdk-js/issues/4369) as "permissive regions". We haven't root caused this yet, but I believe this is an oversight in terms of v2 implementation.

The presigned URL has to have fields like `X-Amz-SignedHeaders` present in the query string.
With presigned URLS you can't have any headers since its represented in a query string, instead headers are hoisted into the url as query params and signed that way. 

The fact that you are getting the redacted version of the signed URL might be a bug in v2. Can you generate a presigned url in one of the following regions and check if the v2 signer "slows down" to the same speed that v3 does? `us-east-2` for example.

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @claycoleman 

Using the sample code in the initial nomment by @claycoleman, I'm able to reach virtually the same execution time. 
Based on @plumdog 's [investigation](https://github.com/aws/aws-sdk-js/issues/4369), the JS SDK v2 uses the SigV2 protocol in some regions, and SigV4 in other regions, we have still not root caused this, but this seems like an oversight. 

For s3, you can tell if a presigned URL is signed with SigV4 if it will have a "AWS4-HMAC-SHA256" in the URL string, while SigV2 should have only "AWS". @CM96 this is the reason for the difference in the signed URL string you are seeing.

After refactoring the initial code snippet by moving the clients instantiation outside of the test suite, and specifying `signatureVersion: "v4"` on the v2 client, the results are pretty similar:

```js
const AWS = require('aws-sdk');
const { S3 } = require('@aws-sdk/client-s3');
const { GetObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');
const Benchmark = require('benchmark');

const NUM_ITERATIONS = 100;

const options = {
  onStart() {
    console.log(this.name ?? 'Running benchmark');
  },
  onError(event) {
    console.log(event.target.error);
  },
  onCycle(event) {
    console.log(String(event.target));
  },
  onComplete() {
    const fastestResult =
      this.filter('fastest')[0];

    console.log(`Fastest is ${fastestResult.name}`);

    this.forEach((result) => {
      if (result.name !== fastestResult.name) {
        const multipleSlower = (fastestResult.hz / result.hz).toFixed(2);

        console.log(`- ${result.name} is ${multipleSlower}x slower`);
      }
    });
  },
};

const s3v2Client = new AWS.S3({
    signatureVersion: "v4"
});
const s3 = new S3({});

new Benchmark.Suite(`creating ${NUM_ITERATIONS} presigned urls`, options)
  .add(`sdk v2`, {
    defer: true,
    async: true,
    fn(deferred) {

      for (let i = 0; i < NUM_ITERATIONS; i++) {
        s3v2Client.getSignedUrl('getObject', {
            Bucket: "testbucket-3650",
          Key: "hey.txt",
        });
      }

      deferred.resolve();
    },
  })
  .add(`sdk v3`, {
    defer: true,
    async: true,
    fn(deferred) {

      const promises = [];
      for (let i = 0; i < NUM_ITERATIONS; i++) {
        promises.push(
          getSignedUrl(
            s3,
            new GetObjectCommand({
              Bucket: "testbucket-3650",
              Key: "hey.txt",
            }),
          ),
        );
      }

      Promise.all(promises).then(() => {
        deferred.resolve();
      });
    },
  })
  .run({ async: true });

```

Output:

```console
creating 100 presigned urls
(node:18177) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
sdk v2 x 186 ops/sec ±0.47% (88 runs sampled)
sdk v3 x 155 ops/sec ±1.17% (89 runs sampled)
Fastest is sdk v2
- sdk v3 is 1.20x slower
```

This is probably due to do Sigv4 having a "heavier" implementation. The security benefits of using SigV4 generally outweigh any potential performance overhead, so our recommendation would be that you use the presigner in V3.

Thanks,
Ran~

**Comment by mattboutet** [comment]
It seems like the performance issues have been tracked down, but it doesn't look like this question was ever addressed:

> Also, why did the function signature between v2 and v3 change from sync to async? my understanding was that signing urls did not involve IO in any way.

I came here looking for the answer to the same question.  I have a lot of code that's generating signed urls in places where async operations aren't supported, so this is going to be a major migration pain point.

**Comment by yenfryherrerafeliz** [comment]
Hi @mattboutet, the reason why getSignedUrl is async is because in order to generate the final signed url we need to resolve some configs, such as region and endpoint, etc, and those config resolver are async.

I will mark this issue as resolved now, but please if you have any issues feel free of opening a new bug report and we will be glad to assist you.

Thanks!
