### ISSUE TITLE
The ChallengeResponses of AdminRespondToAuthChallenge doesn't have options for CUSTOM_CHALLENGE

### ISSUE THREAD

**Issue by jove0610** [aws/aws-sdk-js-v3#4428]
### Describe the issue

When viewing the shape of **ChallengeResponses** in [AdminRespondToAuthChallengeCommandInput](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/interfaces/adminrespondtoauthchallengecommandinput.html), it says that its value depend on the **ChallengeName** and proceeds to list down all the values for each challenge...

However the challenge **CUSTOM_CHALLENGE** isn't written in there. What should be the **ChallengeResponses** for the **CUSTOM_CHALLENGE**?

### Links

- https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/interfaces/adminrespondtoauthchallengecommandinput.html#challengeresponses

**Comment by RanVaknin** [comment]
Hi @jove0610,

Thanks for bringing this to our attention. 

The enum value is indeed missing, the reason it is missing is because the Cognito API itself is missing that enum value. 
Each SDK client is auto-generated from the respective API model of that service it interacts with, [Here is the model](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/cognito-identity-provider.json#L4658-L4722) which is the source of truth for the SDK. As you can see, contrary to their published docs, that enum value is not exported into the API model.

Since in this case the enum values are just predefined strings, and that value _is_ documented in the API docs, I wonder if you can just explicitly specify:

```js
const command = new RespondToAuthChallengeCommand({
    ClientId: myClientID,
    ChallengeName: "CUSTOM_CHALLENGE",
    // other arguments
})
```

If this works, let me know and I can cut a ticket to service team to add this to their model. If it doesn't work I'll need to contact them regarding fixing their documentation. 

Thanks,
Ran~

**Comment by jove0610** [comment]
@RanVaknin here's what I ended up doing
```js
const command = new RespondToAuthChallengeCommand({
    ClientId: myClientID,
    ChallengeName: "CUSTOM_CHALLENGE",
    ChallengeResponses: {
        ANSWER: 'the answer',
        USERNAME: 'the username',
        SECRET_HASH: 'if has secret id'
    }
})
```

thanks anyways...

**Comment by RanVaknin** [comment]
Hi @jove0610 ,
Please disregard what I wrote, I totally misunderstood you.

It seems like you figured it out. I feel comfortable we can close this. Feel free to open a new issue if you have any additional questions.

Thanks,
Ran~
