### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by lucsan** [aws/aws-sdk-js-v3#4452]
### Describe the issue

Elasticsearch Service Client - AWS SDK for JavaScript v3
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elasticsearch-service/index.html

Neither of the below links from the page above, lead to examples of @aws-sdk/client-elasticsearch-service

For sample code that uses the Configuration API, see the [Amazon Elasticsearch Service Developer Guide](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-samples.html). The guide also contains [sample code for sending signed HTTP requests to the Elasticsearch APIs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html).

From: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elasticsearch-service/classes/acceptinboundcrossclustersearchconnectioncommand.html#input

```js
import { ElasticsearchServiceClient, AcceptInboundCrossClusterSearchConnectionCommand } from "@aws-sdk/client-elasticsearch-service"; // ES Modules import
// const { ElasticsearchServiceClient, AcceptInboundCrossClusterSearchConnectionCommand } = require("@aws-sdk/client-elasticsearch-service"); // CommonJS import
const client = new ElasticsearchServiceClient(config);
const command = new AcceptInboundCrossClusterSearchConnectionCommand(input);
const response = await client.send(command);
```
Again, no examples, what is config? what is input? A connection can not be made without detailed examples of these components.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elasticsearch-service/index.html
From: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elasticsearch-service/classes/acceptinboundcrossclustersearchconnectioncommand.html#input

**Comment by RanVaknin** [comment]
Hi @lucsan,

Thanks for opening this issue. We are aware that our docs are hard to navigate through and are actively making attempts to relaunch the v3 docs. 

With regards to what config is. That information would be input regarding the client, like which region to route requests to, or elasticSearch related fine grained control of the client itself. This information **will not** be documented in `AcceptInboundCrossClusterSearchConnectionCommand` doc page since that page would be for the command. To learn what config options you can supply you can go to the [client config doc page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elasticsearch-service/interfaces/elasticsearchserviceclientresolvedconfig.html)

With regards to the command itself, if you click on the input section of that doc it will take you [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elasticsearch-service/interfaces/acceptinboundcrossclustersearchconnectioncommandinput.html#crossclustersearchconnectionid).

I understand the docs are hard to navigate, I highly recommend using an IDE like Visual Studio Code, when constructing commands the Intellisense can suggest the missing values and prompt you if anything is missing like so:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/50976344/220450705-4b205cb8-cfd3-4e6c-9ab3-00504016502f.png">

In this specific case, `AcceptInboundCrossClusterSearchConnectionCommand` only accepts one parameter - `CrossClusterSearchConnectionId`.

If you are not working with the IDE another temporary workaround would be to visit the [v2 docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ES.html). They are clearer but you'll have to make certain changes to conform to the v3 style.

We are currently tracking the documentation changes on this [thread](https://github.com/aws/aws-sdk-js-v3/issues/4318). 

If you need additional help please let me know.
Thanks,
Ran~

**Comment by lucsan** [comment]
@Ran_Vaknin
Thanks, very informative, is exactly what I'm looking for. If this is an
example of what v3 docs will look like, then the forums will go very quiet
indeed.
I do use VScode, I migrated from Atom some time ago as I had very much
liked JSCode (an early ancestor of VSCode)
One thing, what values are accepted by  CrossClusterSearchConnectionId ?
Would a value be for example the http// of the elasticsearch instance?

Thanks

Luke

**Comment by RanVaknin** [comment]
Hi Luke,

Since you have two different issues opened for the same thing, I will close this one.

Thanks,
Ran~
