### ISSUE TITLE
Make Command input object optional -- ELBv2: `Cannot read properties of undefined (read 'LoadBalancerArns')`

### ISSUE THREAD

**Issue by ZachTRice** [aws/aws-sdk-js-v3#4579]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using @aws-sdk/client-elastic-load-balancing-v2 at version 3.299.0, I am receiving the following error:
`TypeError: Cannot read properties of undefined (reading 'LoadBalancerArns')`

### SDK version number

@aws-sdk/client-elastic-load-balancing-v2@v3.299.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.15.0

### Reproduction Steps

```
#!/usr/bin/env node

const { ElasticLoadBalancingV2: ELBv2 } = require('@aws-sdk/client-elastic-load-balancing-v2')

const elbv2 = new ELBv2()

async function main () {
  await findLoadBalancer()
}

async function findLoadBalancer () {
  const results = await elbv2.describeLoadBalancers()
  console.log(results)
}

main().catch((err) => {
  console.error(err.stack)
})
```

### Observed Behavior

```
TypeError: Cannot read properties of undefined (reading 'LoadBalancerArns')
    at serializeAws_queryDescribeLoadBalancersInput (/Users/zrice/projects/project/bin/node_modules/@aws-sdk/client-elastic-load-balancing-v2/dist-cjs/protocols/Aws_query.js:2845:15)
    at serializeAws_queryDescribeLoadBalancersCommand (/Users/zrice/projects/project/bin/node_modules/@aws-sdk/client-elastic-load-balancing-v2/dist-cjs/protocols/Aws_query.js:211:12)
    at serialize (/Users/zrice/projects/project/bin/node_modules/@aws-sdk/client-elastic-load-balancing-v2/dist-cjs/commands/DescribeLoadBalancersCommand.js:39:79)
    at /Users/zrice/projects/project/bin/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:12:27
    at /Users/zrice/projects/project/bin/node_modules/@aws-sdk/client-elastic-load-balancing-v2/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:20:16
    at async /Users/zrice/projects/project/bin/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async findLoadBalancer (/Users/zrice/projects/project/bin/lb-test:14:19)
    at async main (/Users/zrice/projects/project/bin/lb-test:9:14)
```

### Expected Behavior

I expect the following to be returned:
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'abcdefgh-1234-5678-abcd-abcdefgh1234',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  LoadBalancers: [
    {...},
    {...}
  ]
}
```

### Possible Solution

Allow `await elbv2.describeLoadBalancers()` to be used without needing to pass `{}`

In aws-sdk v2 you can do the following without an error.
```
const results = await elbv2.describeLoadBalancers()
console.log(results)
```
I would except the same behavior in aws-sdk v3, but in v3, you have to include a `{}`
```
const results = await elbv2.describeLoadBalancers({})
console.log(results)
```

**Comment by RanVaknin** [comment]
Hi @ZachTRice,

`describeLoadBalancers` takes in an argument of type `describeLoadBalancersInput` which has no required fields.  Imagine calling the same method, but providing one of the optional arguments:

```js
describeLoadBalancers({ Names: ["foo", "bar", "baz"] })
```

That's why when making the request without any arguments, it will look like:
```js
describeLoadBalancers({})
```

Same goes to your client creation:
```js
// wrong
// const elbv2 = new ELBv2()


const elbv2 = new ELBv2({})
// or 
// const elbv2 = new ELBv2({ region:"us-east-1" })
```

Despite not following the same shape as v2, this behavior is [documented](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elastic-load-balancing-v2/classes/describeloadbalancerscommand.html).

Additionally to make the transition between v2 and v3 easier, @trivikr has built [Codemod](https://github.com/awslabs/aws-sdk-js-codemod), a tool that will generate v3 code from v2. 
___
### Conclusion: not a bug.

An argument can be made that for convenience sake, the SDK should check whether an object is provided or not, and if not, it should construct an empty object on behalf of the user. 

I will convert this to a feature request and discuss it with the team since this is not the first time this has come up.

Thanks,
Ran~

**Comment by ZachTRice** [comment]
The above source code from aws-sdk v2 was the following running codemod:
```
#!/usr/bin/env node

const AWS = require('aws-sdk')
const elbv2 = new AWS.ELBv2()

async function main () {
  await findLoadBalancer()
}

async function findLoadBalancer () {
  const results = await elbv2.describeLoadBalancers().promise()
  console.log(results)
}

main().catch((err) => {
  console.error(err.stack)
})
```
