### ISSUE TITLE
Bad link to AccountAlias docs.

### ISSUE THREAD

**Issue by cpyle0819** [aws/aws-sdk-js-v3#4600]
### Describe the issue

https://github.com/aws/aws-sdk-js-v3/blob/a237e363cec4a37dff86cf6ecca0afb3c186adc5/clients/client-iam/src/commands/CreateAccountAliasCommand.ts#L39

The above is a dead link.

### Links

https://github.com/aws/aws-sdk-js-v3/blob/a237e363cec4a37dff86cf6ecca0afb3c186adc5/clients/client-iam/src/commands/CreateAccountAliasCommand.ts#L39

**Comment by RanVaknin** [comment]
Hi @cpyle0819 ,

The doc string attached to the service operations is auto-generated from the API model of IAM. In fact, the entire SDK gets generated from each API model of the various AWS Services, including the doc string. Unfortunately we here at the SDK have no discretion on how the service team annotates their docs. 

You can use the `Feedback` button on the top right corner of [this page](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccountAlias.html) to submit a documentation edit. This would send your edit request directly to the doc writer of the IAM service team. 

Since there is no action item here for the SDK team I feel confident we can close this.

If you have any other question, feel free to open an additional issue.
Thanks,
Ran~
