### ISSUE TITLE
Describe using `toUint8Array` for Lambda Invoke Payload

### ISSUE THREAD

**Issue by onyxraven** [aws/aws-sdk-js-v3#4623]
### Describe the issue

The `InvokeCommandInput` object `Payload` field is of type `Uint8Array`, but the documentation has a basic string input as its example. 

It would be helpful to include a short note on converting the string to the required type (using [util-utf8](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/functions/_aws_sdk_util_utf8.toUint8Array.html)).

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-lambda/classes/invokecommand.html

**Comment by yenfryherrerafeliz** [comment]
Hi @onyxraven, thanks for opening this issue. In the sample code, from the documentation, we are not giving the parameters specifically, instead, with a string text we say what we should provide as parameter. I know this can be confusing and that having a full working example would be more easy to understand. We are currently working on getting our documentation better, however, in the meantime here is an example providing the payload as parameter:

```js
import {InvokeCommand, LambdaClient} from "@aws-sdk/client-lambda";

const client = new LambdaClient({
    region: 'us-east-2'
})
const response = await client.send(new InvokeCommand({
    FunctionName: 'test',
    InvocationType: 'Event',
    LogType: 'Tail',
    ClientContext: 'context',
    Payload: Buffer.from('JSON INPUT', 'utf-8')
}))

console.log(response)
``` 

Please let me know if that helps!

Thanks!

**Comment by cpyle0819** [comment]
The types that are supported for the Payload value depend on the context.

For the browser, the type must match one of the types of [options.body in the Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request);

For Node, the type must match one of the types of [a chunk](https://nodejs.dev/en/api/v18/http/#requestwritechunk-encoding-callback).

Can the type be updated to reflect this?

**Comment by tcyrus** [comment]
Based on what I understand, the typing of `Payload` in `InvocationRequest` is incorrect.

https://github.com/aws/aws-sdk-js-v3/blob/06feb14d9dd4975a9d3e24d8f65a1edfa11277a1/clients/client-lambda/src/models/models_0.ts#L4009-L4014

This is partially because `HttpRequest` takes an `any` type.

https://github.com/aws/aws-sdk-js-v3/blob/06feb14d9dd4975a9d3e24d8f65a1edfa11277a1/clients/client-lambda/src/protocols/Aws_restJson1.ts#L1489-L1502

I can't seem to find the section of the code where `body` is being processed.

Based on what @cpyle0819 said earlier, both the browser behavior and the Node.js behavior takes the `string` type as a valid input.

This means that `Payload?` should be marked as type `Uint8Array | string` to match with the example in the AWS docs.

The proper solution would be to handle typing based on the environment, but I'm not sure how you'd go about that.

**Comment by kuhe** [comment]
`Uint8Array` is no longer strictly required for blob payloads like `Lambda::Invoke::Payload`. This was done in https://github.com/awslabs/smithy-typescript/pull/835.

The type is now described here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-types/TypeAlias/BlobPayloadInputTypes/ and reflected in the API docs for Invoke:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/InvokeCommand/

What this means is that you can submit a JSON string like this:

```js
import { Lambda } from '@aws-sdk/client-lambda';

await new Lambda({}).invoke({
  FunctionName: '...',
  Payload: JSON.stringify(youInputObject)
})
```


--- 
Note: shapes are described with the type `Uint8Array` for all fields that AWS services model as "BLOB". When a field also corresponds to the body of a request/response, it is called a payload blob. Payload blobs can be submitted as strings because the HTTP implementations (fetch for browser, http for Node.js) accept multiple value types for request bodies. 

For blob fields that are not payloads, they must still be converted to Uint8Array.
