### ISSUE TITLE
Offer ETag calculation method

### ISSUE THREAD

**Issue by alshdavid** [aws/aws-sdk-js-v3#4627]
### Describe the feature

I am writing a custom S3 deployment script that aims to determine which items to upload by listing the objects in the bucket and comparing the md5 hash of the local file against the etag of the stored s3 object.

Currently I can use the `paginateListObjectsV2` method to get all the items in a bucket, along with their etags.

My understanding is that the etag is an md5 checksum that is calculated in a special way (I could be wrong about this) so a simple md5 calculation of the local file may result in a different hash than is stored as the etag.

Can you offer a function in the S3 client library to help calculate the etag value locally?

### Use Case

When writing deployment scripts or otherwise determining when a store s3 object needs to be updated with a local file

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.306.0

### Environment details (OS name and version, etc.)

Fedora 37, Node 18, pnpm

**Comment by yenfryherrerafeliz** [comment]
Hi @alshdavid, thanks for opening this feature request. According to the documentation, that can be found [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html), the ETag may or may not be an MD5 checksum. 
Please see below:
>The entity tag is a hash of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:

>    Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.

>    Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-C or SSE-KMS, have ETags that are not an MD5 digest of their object data.

>    If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption. If an object is larger than 16 MB, the AWS Management Console will upload or copy that object as a Multipart Upload, and therefore the ETag will not be an MD5 digest.

I will relay this feature request to the correspondent team, however, I do not guarantee this item will be prioritized in the near future, since there are other items with higher priority. 

I also found the [following](https://stackoverflow.com/questions/12186993/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb) post, from Stack Overflow, which seems to offer a solution. 

Thanks!
