### ISSUE TITLE
CreateUploadCommand should be more clear about usage.

### ISSUE THREAD

**Issue by Vithop** [aws/aws-sdk-js-v3#4671]
### Describe the issue

The `CreateUploadCommand` takes in the filename and various file data only to return a url? To me the name implies that the command would do the work of uploading the file but it doesn't! Although there are multiple ways to upload a file to the url provided the documentation should at least state that it's up to the user to upload the file to the url provided. 

Another related issue in response of the command is the returned URL is optional in the documentation. This makes it a little confusing as to how a user would create an upload if the URL isn't returned? 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/device-farm/command/CreateUploadCommand/
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-device-farm/interfaces/upload-3.html

**Comment by RanVaknin** [comment]
Hi @Vithop ,

Thanks for opening the issue. I understand that documentation and naming conventions can be confusing and frustrating, however the SDK's documentation is auto-generated from the API model of each AWS service - in this case [this page](https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_CreateUpload.html#API_CreateUpload_ResponseSyntax) is the source of truth for the generated docs. The SDK team cannot change the documentation that is associated with the auto-generated clients (in this case device-farm) because it will get overwritten in the next release.
Instead, I encourage you to [submit feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Device%20Farm&topic_url=https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_CreateUpload.html#API_CreateUpload_ResponseSyntax) about documentation using the **Feedback** button at the top right corner of each doc page.


>Another related issue in response of the command is the returned URL is optional in the documentation. This makes it a little confusing as to how a user would create an upload if the URL isn't returned?

This is again due to how the Device Farm service annotated their model, not something the SDK has control over. My assumption is that since the following operations `CreateUpload`, `UpdateUploadResult`, `GetUpload`, `InstallToRemoteAccessSession` all return the `Upload` type, in some some cases a URL is not guaranteed or even needed in the response.

When running a CreateUploadCommand, was the URL field not returned?

Thanks,
Ran~

**Comment by Vithop** [comment]
I see thanks for understanding. 😄 I'll provide my feedback on the `docs.aws` pages. I personally got lost in the docs pages and went to the generated docs for more help but found out that I needed to learn python to understand the example provided. 

I guess I'll close this as I'll provide my feedback in the correct place.
