### ISSUE TITLE
CredentialsProviderError comes intermittently

### ISSUE THREAD

**Issue by sonimadhuri** [aws/aws-sdk-js-v3#4679]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We are intermittently seeing CredentialsProviderError after upgrading production code to v3

```
     at listOnTimeout (node:internal/timers:528:9)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at processTimers (node:internal/timers:502:7)
     at runMicrotasks (<anonymous>)
     at runNextTicks (node:internal/process/task_queues:65:3)
     '$metadata': { attempts: 1, totalRetryDelay: 0 }
      tryNextLink: false,
      CredentialsProviderError: Could not load credentials from any providers
```
I've looked up on github and stack overflow and realised that it could be because we use kube2iam as credential provider for our processes running on k8s.

Here is a sample usage,
`const ddb = new DynamoDB({ region: 'us-east-1' });`

given how AWS SDK v3 resolves credentials, this should work and it does, but sometimes our pods restart throwing this error. 
There are suggestion to use AWS_METADATA_SERVICE_TIMEOUT so that kube2iam can re-attempt generating credentials but I saw in the documentation that the env variable is not supported in v3 version. What is the workaround for this?
Also is there any issue if I am not providing any credentials provider params during instantiating services?
Thanks.  

### SDK version number

@aws-sdk/client-s3@3.279.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.19.1

### Reproduction Steps

Not sure how to include the reproduction steps here, but this is how we are initialising services
`const ddb = new DynamoDB({ region: 'us-east-1' });`

### Observed Behavior

at /var/lib/node/common/node-packages/util/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at /var/lib/node/common/node-packages//node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at async /var/lib/node/common/node-packages/util/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /var/lib/node/common/node-packages/util/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/lib/node/common/node-packages/util/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:16:18
    at async SignatureV4.credentialProvider (/var/lib/node/common/node-packages/util/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)
    at async SignatureV4.signRequest (/var/lib/node/common/node-packages/util/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:87:29)
    at async coalesceProvider (/var/lib/node/common/node-packages/util/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at async wrappedHeaderMw (/var/lib/node/sales-batch/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:57:12)
    at listOnTimeout (node:internal/timers:528:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at processTimers (node:internal/timers:502:7)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:65:3)
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
  tryNextLink: false,
CredentialsProviderError: Could not load credentials from any providers

### Expected Behavior

timeout should be configurable

**Comment by sonimadhuri** [comment]
@yenfryherrerafeliz can you check this?

**Comment by yenfryherrerafeliz** [comment]
Hi @sonimadhuri, I am not very familiar with kube2iam, however, reading the documentation I see that the way it works is by intercepting the calls made to the ec2 metadata service, in this case to the container metadata service, and based on the configuration given to the pod making the request, it will make a call the same metadata service to fetch temporary credentials and return it in the initial request being made. So, if you are getting "Could not load credentials from any providers" error is because either the metadata service was not ready to handle the request being made by kube2iam, or the kube2iam was not running at the time of the request. Basically, since you are not providing any credentials provider to the client, the client will use the default resolution chain to try to resolve the credentials, but if all of them fail you will get the error that you are reporting. Something to take in consideration when running containers on top of EC2 instances is the httpPutResponseHopLimit , which is somehow a channel restriction to put a session token in order to retrieve credentials from the imds service, and by default this limit is 1. This feature was introduced in IMDSv2. You can find more information about it [here](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/), most likely in "What's new in IMDSv2". In short words, if you have the hop limit set to 1, then there will be just one channel to fetch credentials from IMDSv2 and probably is assigned to the ec2 instance, however, what the SDKs do is that, if fails when fetching credentials from  IMDSv2, then we try to do so from IMDSv1, but this adds some latency to the credential resolution process. 

Answering your questions:

> here are suggestion to use AWS_METADATA_SERVICE_TIMEOUT so that kube2iam can re-attempt generating credentials but I saw in the documentation that the env variable is not supported in v3 version. What is the workaround for this?

Can you please provide a link to the documentation you mentioned since I am not sure what AWS_METADATA_SERVICE_TIMEOUT is used for?

> Also is there any issue if I am not providing any credentials provider params during instantiating services?

Not really. The SDK will use the default resolution chain if not credential provider is given. However, something you could try is to specify which credential provider you want to use and see if that helps as well:

```js
import {DynamoDBClient} from "@aws-sdk/client-dynamodb";
import {fromContainerMetadata} from "@aws-sdk/credential-providers";

const client = new DynamoDBClient({
    region: process.env.TEST_REGION,
    credentials: fromContainerMetadata({
        maxRetries: 5, // Preferred max retries
        timeout: 1000 * 5 // Preferred timeout
    })
})
```

Thanks!
