### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by mitz0077** [aws/aws-sdk-js-v3#4723]
### Describe the issue

update to overcome these issues - Error: write EPROTO 882A0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922: with HTTPSAgent

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/ssm/command/GetParametersCommand/

**Comment by RanVaknin** [comment]
Hi @mitz0077,

The error you're encountering is typically associated with SSL/TLS negotiation, which is handled by Node.js and your operating system rather than the SDK itself. As such, it might not be directly related to the SDK and thus not be covered in our documentation.

We'd be happy to help troubleshoot this further, if you kindly share with us the following details: your SDK version, Node.js version, the environment you're running this from (like local Node.js, web, react, lambda, etc.), and most importantly, the actual code that triggers the error. This information will greatly assist us in providing a more accurate solution.

Thanks,
Ran
