### ISSUE TITLE
ERR_INVALID_OBJECT_DEFINE_PROPERTY

### ISSUE THREAD

**Issue by juztinlazaro** [aws/aws-sdk-js-v3#4735]
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

For some reason, I'm receiving this error  after upgrading node18

```
2023-05-19T08:53:44.841Z	a3eee9cb-780d-4fed-908d-324a08efd103	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "'process.env' only accepts a configurable, writable, and enumerable data descriptor",
    "code": "ERR_INVALID_OBJECT_DEFINE_PROPERTY",
    "stack": [
        "TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor",
        "    at InvokeContext._forwardXRay (file:///var/runtime/index.mjs:663:43)",
        "    at InvokeContext.attachEnvironmentData (file:///var/runtime/index.mjs:637:14)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1086:73)"
    ]
}
```

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

serverless framework

### Reproduction Steps

![image](https://github.com/aws/aws-sdk-js-v3/assets/10995629/0199aa94-d824-4d62-912a-b61aaf39fdd2)

in my lambda function, this one is working in node12 but in node18, the issue introduced 

![image](https://github.com/aws/aws-sdk-js-v3/assets/10995629/34d7b115-e01e-41b8-afed-67c0c9a89e1e)

### Observed Behavior

seems like when assigning process.env in lambda function, the ERR_INVALID_OBJECT_DEFINE_PROPERTY happens

![image](https://github.com/aws/aws-sdk-js-v3/assets/10995629/34d7b115-e01e-41b8-afed-67c0c9a89e1e)

![image](https://github.com/aws/aws-sdk-js-v3/assets/10995629/8df89657-9b3e-4519-8711-090195c78044)

**Comment by yenfryherrerafeliz** [comment]
Hi @juztinlazaro, sorry to hear about your issues. I see that you skipped the reproduction steps section, but this is important for us to better  root cause the issue. So, could you please let me know if this issue is happening when using the AWS SDK for JavaScript V3?, if so, could you please provide a sample code that we can use, and I see you specified that your runtime is serverless, could you please provide more details regarding?

Thanks!

**Comment by juztinlazaro** [comment]
Hi @yenfryherrerafeliz updated my details thanks

**Comment by RanVaknin** [comment]
Hi @juztinlazaro,

This does not look an SDK related error, and from reading your code I don't see anything that stands out as a misconfiguration. I assume your .env file is set up correctly, since it seems like your setup has worked before upgrading to Node 18.

 From googling this issue, it seems like it has to do with Node 18 and Windows. Are you using a windows OS?
 You can try following the suggestions on [this thread](https://github.com/felixrieseberg/windows-build-tools/issues/20).
 
Let us know if that works.

Thanks,
Ran~

**Comment by juztinlazaro** [comment]
@RanVaknin Hi i-updated my details seems like there's an issue in node18 when assigning `process.env`

**Comment by juztinlazaro** [comment]
Good day guys? any update? if we have an issue in node18

**Comment by juztinlazaro** [comment]
Hi @yenfryherrerafeliz any thoughts?

**Comment by yenfryherrerafeliz** [comment]
Hi @juztinlazaro, this issue is not related to the SDK, however, did this happen on a lambda function?, if so, it should be fixed since I just did a test on a lambda and I had not issues using process.env.

I look forward to your response.

Thanks!

**Comment by tim1uphealth** [comment]
> Hi @juztinlazaro, this issue is not related to the SDK, however, did this happen on a lambda function?
I'm getting this error on a lambda function with similar circumstances to OP.
