### ISSUE TITLE
AWS SDK DescribeStorageVirtualMachinesCommand problem

### ISSUE THREAD

**Issue by guypar** [aws/aws-sdk-js-v3#4737]
### Describe the bug

members :
StorageVirtualMachine.rootVolumeSecurityStyle,
StorageVirtualMachine.Tags
are not populated.

### Expected Behavior

StorageVirtualMachine.rootVolumeSecurityStyle,
StorageVirtualMachine.Tags
should be not empty and populated with the actual values of the SVM

### Current Behavior

these members are just empty

### Reproduction Steps
```js
const resp = await this.getFsxClient(awsCredsAndRegion).send(new DescribeStorageVirtualMachinesCommand({ StorageVirtualMachineIds: [svmId] }));
 resp.StorageVirtualMachines[0].rootVolumeSecurityStyle
 resp.StorageVirtualMachines[0].Tags
```

### SDK version used

3.112.0

### Environment details (OS name and version, etc.)

mac 13.3.

**Comment by RanVaknin** [comment]
Hi @guypar 

Are you getting a 200 status or an error? Your reproduction steps do not include a `catch` block so we don't know if you are error handling, and if an error is returned resulting in those members being empty. 

A full reproduction setup will be very helpful for us in order to correctly emulate your situation. Preferably information about how you set up your resources and a complete code snippet that can consistently reproduce the issue.

Thanks!
Ran~

**Comment by guypar** [comment]
hi,
i am not getting an error.
how to reproduce:
1. create fsx for netapp
2. an default SVM will be created.
3. go to the default SVM page in aws console and add tags to the SVM
<img width="987" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/61222918/5a673d2b-98b3-43f7-b63e-d0d936bb749b">
![image](https://github.com/aws/aws-sdk-js-v3/assets/61222918/7c838c12-3b61-4240-b28e-ae44bfdf06d4)
![image](https://github.com/aws/aws-sdk-js-v3/assets/61222918/d2e4affe-4037-4905-9fb4-ea37d251fe16)
5. copy the svmId from aws console

execute:
const resp = await this.getFsxClient(awsCredsAndRegion).send(new DescribeStorageVirtualMachinesCommand({ StorageVirtualMachineIds: [<paste here the svm-id>] }));
console.log(resp)

you will see that :
resp.StorageVirtualMachines[0].rootVolumeSecurityStyle
resp.StorageVirtualMachines[0].Tags
are undefined although these values are present in aws console
