### ISSUE TITLE
Updated S3 SDK version to v3.341.0

### ISSUE THREAD

**Issue by edfmarco** [aws/aws-sdk-js-v3#4773]
### Description

Currently have @aws-sdk/client-s3 installed in our project at v3.337.0. Tried updating this package to >= v3.338.0, and it caused failing tests in our code.

### SDK version number

@aws-sdk/client-s3@3.338.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.14.2

### Reproduction Steps

- updated @aws-sdk/client-s3 to v3.341.0 (tried with 3.338.0 and above)
- ran our 'npm test' script which runs our jest unit tests

### Observed Behavior

`expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: "testBucket", "dummyPrefix/file1.txt", {"destroy": [Function destroy]}
    Received
           1
              "testBucket",
              "dummyPrefix/file1.txt",
              {"destroy": [Function destroy]},
           2
              "testBucket",
              "dummyPrefix/file2.txt",
              {"destroy": [Function destroy]},
           3
              "testBucket",
              "dummyPrefix/file3.txt",
              {"destroy": [Function destroy]},

    Number of calls: 3

      243 |         mockSQSParams.message,
      244 |       );
    > 245 |       expect(s3DeleteFile).toHaveBeenCalledWith(
          |                            ^
      246 |         mockDeleteParams.bucketName,
      247 |         mockDeleteParams.objectKey,
      248 |         new S3Client(),`

### Expected Behavior

- passing unit tests with s3 sdk calls functioning as expected

**Comment by RanVaknin** [comment]
Hi @edfmarco ,

From the issue description, it is unclear what the issue with the SDK is.
Could it be that your tests relied on some behavior that may have changed in the newer versions of the SDK (which is expected) and are now failing? 

In order to better assist you we will need more information about the issue at hand (failing tests is not an indication that something is a bug with the SDK), once the problem is described please include a complete and concise code snippet and reproduction steps so that we can reproduce it on our end.

Thanks,
Ran
