### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by Shiva7071007** [aws/aws-sdk-js-v3#4775]
### Describe the issue

wrong command referenced in StartExpenseAnalysisCommand developer preview document.
```
If so, call GetExpenseAnalysis , and pass the job identifier (JobId) that was returned by your call to StartExpenseAnalysis
```
here link to`GetExpenseAnalysis` does not work.
I think this might be a reference to
 https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-textract/Class/GetExpenseAnalysisCommand/

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-textract/Class/StartExpenseAnalysisCommand/

**Comment by MYoung25** [comment]
Hi @Shiva7071007,

Thanks for taking the time to leave us feedback and bringing this to our attention.  I've been investigating the root cause of this, its occurring in _at least_ [3 other clients](https://github.com/aws/aws-sdk-js-v3/issues/4794), and I suspect more.

I don't have more to share right now, but I'm continuing to investigate.

Thank you!

Michael
