### ISSUE TITLE
ResourceNotFoundException: Event source or Event bus not found 

### ISSUE THREAD

**Issue by Omdaprog** [aws/aws-sdk-js-v3#4788]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

im trying to activate a event source by by `ActivateEventSourceCommand` but it returns `ResourceNotFoundException: Event source aws.partner/shopify.com/------/certor-dev or event bus aws.partner/shopify.com/-----/certor-dev does not exist.` though my partner event source connect successfully. 
<img width="1094" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/43305769/4da04b29-ee01-4627-a188-dcc5be8ff7f3">

### SDK version number

"@aws-sdk/client-eventbridge": "^3.337.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node: v16.15.1

### Reproduction Steps

connect partner event source and activate it by AWS SDK `ActivateEventSourceCommand` 

### Observed Behavior

ResourceNotFoundException: Event source aws.partner/shopify.com/------/certor-dev or event bus aws.partner/shopify.com/-------/certor-dev does not exist.

### Expected Behavior

activate event source with success

**Comment by RanVaknin** [comment]
Hi @Omdaprog ,

Are you calling the request from the correct AWS region? Ie, is your event source defined in us-east-1 and you are calling it from us-west-2? 

Thanks,
Ran~

**Comment by Omdaprog** [comment]
Hi @RanVaknin 
Thanks for your response, yes im sure that calling with correct region, Additionally when i fetch all eventSource it return a list  pending eventSources but i'm unable to activate any of them. 
<img width="936" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/43305769/dab5abb0-20ad-4452-94c8-cf33973b2ced">

**Comment by RanVaknin** [comment]
Hi @Omdaprog ,

Thanks for the follow up info. 

I'm not entirely sure why you are running into this problem. I can only speak to SDK's functionality rather than each individual AWS Service and since operation goes through, and gets a response from the service, we can deduct that this is either a service issue, or a misuse of the API. 

I was able to verify that it's not an SDK issue by running the command in the cli:
```console
$ aws events activate-event-source --name aws.partner/shopify.com/*******8961/certor-dev

An error occurred (ResourceNotFoundException) when calling the ActivateEventSource operation: Event source aws.partner/shopify.com/43936808961/certor-dev or event bus aws.partner/shopify.com/*******8961/certor-dev does not exist.
```
(You didnt redact the result from the `Name` field in the response photo you pasted)

So now that we know it's not SDK issue but rather a usage issue or service issue, looking at some of the documentation for Eventbridge I see that:

1. in the Documentation for [ActivateEventSource ](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_ActivateEventSource.html) the doc string reads:
>Activates a partner event source that has been deactivated. Once activated, your matching event bus will start receiving events from the event source.

- Since your event source is `pending` and not `deactivated` I don't know if this is what you need to do. 
Are you following some tutorial or doc that tells you to use this method?
- it says the "your matching event bus will start receiving events from the event source." - Did you have an event bus tied to this event? Please see the next section

2.  In this [doc](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-saas.html#eb-saas-integration):
>Go back to the EventBridge console and choose Partner event sources in the navigation pane.

>Select the button next to the partner event source and then choose Associate with event bus.

>The status of the event source changes from Pending to Active, and the name of the event bus updates to match the partner event source name. You can now start creating rules that match events from the partner event source. For more information, see [Creating a rule that matches SaaS partner events](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-saas.html#eb-create-rule-partner-events).

It sounds like the way to activate an event source, is by associating it with an event bus. `CreateEventBus` takes in an event source as an argument. I would start there.

Unfortunately I cannot setup a whole reproduction on my end since it is an integration with a 3rd party application, but I hope this can help. 

Let me know how it goes.
Thanks,
Ran~
