### ISSUE TITLE
Global search to support multiple terms, including namespace

### ISSUE THREAD

**Issue by Michael-1** [aws/aws-sdk-js-v3#4789]
#### Steps to reproduce
In the global search, enter “getfunction lambda”

#### Expected result
“lambda - GetFunctionCommand” is suggested as result

#### Actual result
No suggestions are shown

### Links

Any

**Comment by MYoung25** [comment]
Hi @Michael-1,

Thanks for taking the time to leave us feedback, I have been working on upgrading search since we got to preview. 
 In order to support a more powerful search, we've needed to rebuild the search experience from the ground up, which was released to the preview this week!

I'm happy to share that it includes a version of namespace search and the ability to search all types across all packages.  I'd love to hear your thoughts on the new and improved search.

Best,

Michael
