### ISSUE TITLE
The example of SendRawEmailCommand does not match the docs so the example fails if you try to replicate

### ISSUE THREAD

**Issue by LucasGarci** [aws/aws-sdk-js-v3#4800]
### Describe the issue

The example shows no base64 encoding 
```js
// The following example sends an email with an attachment:
const input = {
  "Destinations": [],
  "FromArn": "",
  "RawMessage": {
    "Data": "From: sender@example.com\\nTo: recipient@example.com\\nSubject: Test email (contains an attachment)\\nMIME-Version: 1.0\\nContent-type: Multipart/Mixed; boundary=\"NextPart\"\\n\\n--NextPart\\nContent-Type: text/plain\\n\\nThis is the message body.\\n\\n--NextPart\\nContent-Type: text/plain;\\nContent-Disposition: attachment; filename=\"attachment.txt\"\\n\\nThis is the text in the attachment.\\n\\n--NextPart--"
  },
  "ReturnPathArn": "",
  "Source": "",
  "SourceArn": ""
};
const command = new SendRawEmailCommand(input);
const response = await client.send(command);
/* response ==
{
  "MessageId": "EXAMPLEf3f73d99b-c63fb06f-d263-41f8-a0fb-d0dc67d56c07-000000"
}
*\/
// example id: sendrawemail-1469118548649
```

But the docs especifies that it need to be base64 encoded

![image](https://github.com/aws/aws-sdk-js-v3/assets/28561858/b8f9f2c0-d6c2-4661-a773-ad7aebe82efd)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/ses/command/SendRawEmailCommand/

**Comment by kuhe** [comment]
RawMessage.Data is declared as a blob type, and the current JSv3 implementation is to require a Uint8Array for blob type inputs that are not modified (i.e. type-widened) by the streaming trait, which does not apply in this case.

Using the example as-is may cause a type error when a string instead of a Uint8Array is provided. As part of ongoing work to simplify type conversions for Blobs in https://github.com/aws/aws-sdk-js-v3/issues/4265, we will try to cover the case where a Uint8Array blob representation is currently required but the user supplies a string. We will aim to add automatic conversion in these cases.

**Comment by kuhe** [comment]
The docs mention base64 encoding, but this is something that the AWS SDKs do for you, if you provide the expected Uint8Array.
