### ISSUE TITLE
Enhanced Raw Message Support with Stream Input

### ISSUE THREAD

**Issue by isaiah-v** [aws/aws-sdk-js-v3#4808]
### Describe the feature

Enable stream input for raw messages in the SES Client, improving memory efficiency and performance when handling large emails and attachments.

### Use Case

I'm currently working on a lambda project to forward emails received by my domain, but using the SES client requires loading everything, even attachments, into memory, which isn't ideal. It would be great if I could utilize the SES client instead of an SMTP client to simplify the process and avoid the hassle of managing extra credentials.

### Proposed Solution

Enhance the [RawMessage](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/interfaces/rawmessage-1.html) feature by enabling the "Data" parameter to accept a "Readable stream," facilitating direct streaming of the data to the underlying open connection, thereby eliminating the need for intermediate storage.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

client-ses v3.348.0

### Environment details (OS name and version, etc.)

Node 18

**Comment by yenfryherrerafeliz** [comment]
Hi @isaiah-v, thanks for opening this feature request. I understand the value of using readable stream when working with large files. I will mark this feature request as needs-review so we can evaluate this further.

Thanks!

**Comment by RanVaknin** [comment]
Hi @isaiah-v ,

Thanks for reaching out. 

The SDK already supports streaming operations where the request body consists of a single, streamable payload. However, in the case of `SendRawEmailCommand` (I assume this is the operation you are referring to), the request body is not just the `RawMessage` data; it includes multiple fields such as `Source`,`Destinations`, `Tags` and others. 

This is not a limitation of the SDK, but rather how this operation was defined by the service itself.

With other streamable operations like `s3.putObject` for example, the other request parameters are either sent as query parameters or headers and the body only consists the streamable payload. 

Since there is no straight forward way of implementing this feature, we are not inclined to move forward with this. 
I hope this does not discourages you from submitting addition feature requests in the future. We rely on customer engagement to improve the SDK. I want to thank you again for taking the time and raising the request with us. 

All the best,
Ran~
