### ISSUE TITLE
ECS client config is incomplete

### ISSUE THREAD

**Issue by adityasrini** [aws/aws-sdk-js-v3#4834]
### Describe the issue

I am on the documentation page to see how to use the ECS Client. I go to the ECS Client Constructor [page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-ecs/Class/ECSClient/) and after clicking on 

(constructor) | constructor(configuration: ECSClientConfig)
-- | --

specifically, the `ECSClientConfig`, I am redirected to the same [ECSClientConfigType](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-ecs/TypeAlias/ECSClientConfigType/) page in a loop. This is not the case with the [older page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ecs/interfaces/ecsclientconfig.html) that lists out what params are needed or optional to pass in so I can instantiate the `ECSClient()`.

I intend to use this in a nodejs Lambda function to list and destroy ECS clusters and services.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-ecs/TypeAlias/ECSClientConfigType/

**Comment by RanVaknin** [comment]
Hi @adityasrini ,

Thanks for the info. This certainly looks like a bug.

We will try to look into this with priority.

Thanks,
Ran~

**Comment by kuhe** [comment]
Here is the link without the preview part of the path: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-ecs/TypeAlias/ECSClientConfigType/

The types that are merged to form the config type are now linked. Unfortunately, we don't have a single page that lists out all of the config options due to the difficulty of the doc generator understanding the merged TypeScript typings, but each public config component has a link that brings up the fields available for configuration.

**Comment by kuhe** [comment]
created a request to make it easier to find this type https://github.com/aws/aws-sdk-js-v3/issues/5054
