### ISSUE TITLE
Cognito verify the verification code is correct

### ISSUE THREAD

**Issue by joao-moonward** [aws/aws-sdk-js-v3#4853]
### Describe the feature

I'd like to reopen this discussion:
https://github.com/amazon-archives/amazon-cognito-identity-js/issues/466

I have searched if it is possible to check the verification code without either confirming forgot password command or confirming sign-up. I couldn't find it.

### Use Case

> The user requests a reset code via email and then is taken to a view where he needs to enter this code. Then he will be taken to another view to set a new password. So I need to find a way to verify that he entered a valid code before going to the password view.

### Proposed Solution

I think one more command should be enough. We send the username and the code, which returns whether the code is valid. The `attempts` and `totalRetryDelay` should also work if the code is incorrect.

### Other Information

I know the abovementioned issue was a long time ago, but I haven't found any feedback. 
The solution we found here is to change the designs, but it is a problem that makes me rethink and decide not to use Cognito as a solution for the next projects.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.328.0

### Environment details (OS name and version, etc.)

All platforms

**Comment by RanVaknin** [comment]
Hi @joao-moonward,

Thanks for raising this issue. I see how this use case can be useful and the lack of ability to verify the code entered by the customer is frustrating. Unfortunately, there is not much the SDK team can do about how the flow is implemented. 
The SDK is code-generated from Cognito's API model. This means that [`confirmForgotPasswordCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/classes/confirmforgotpasswordcommand.html) is generated from [`confirmForgotPassword`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmForgotPassword.html) which is a doc representation of the API model for cognito.

From an API design standpoint, this flow is unlikely to change, since changing it would be considered a backwards incompatible change that will break existing customers code. Ideally this should be raised as a feature request to the service team itself, in the form of a separate operation.

The SDK is a **client** that abstracts the need to interact with the API server directly, it does not represent the **service** itself so the SDK team cannot change / add to the implementation of that operation because there needs to be a server side support for that.

I'm surprised no one directly acknowledges this fact on the old thread. My guess that back then (2017) there were no internal processes to submit feature requests easily so when the maintainer said:
 >We took this as an internal feature request.
 
I assume what he meant was, they created or intended to create a feature request with the Cognito service team, but there is no way for me to see if that was ever created internally.

While we, on the SDK team are unable to change service-side behavior, we encourage you to pursue this request with the Cognito service team through a Technical Account Manager, or a Solutions Architect assigned to your AWS account (could be done in the "Support" section of the management console).

If you need help with anything else, feel free to open another issue or a discussion.
Thanks,
Ran~

**Comment by joao-moonward** [comment]
Thank you for your feedback
