### ISSUE TITLE
Unable to get values of "Type" and "PrincipalId" from userIdentity Property of DynamoDB stream Record

### ISSUE THREAD

**Issue by eulogio-3t** [aws/aws-sdk-js-v3#4878]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Unable to get values of `"Type"` and `"PrincipalId"` from userIdentity Property of DynamoDB stream Record - Type does not match the stream output.

As per the docs - [Identity docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb-streams/interfaces/identity.html), the userIdentity (type `"Identity"`) props are in upper case:

```js
export interface Identity {
    /**
     * A unique identifier for the entity that made the call. For Time To Live, the principalId is "dynamodb.amazonaws.com".
     */
    PrincipalId?: String;
    /**
     * The type of the identity. For Time To Live, the type is "Service".
     */
    Type?: String;
  }
```

The data returned by the stream, however, has lowercase keys:

```console
    "userIdentity": {
        "principalId": "dynamodb.amazonaws.com",
        "type": "Service"
    },
```

### SDK version number

`@aws-sdk/client-dynamodb@3.358.0`

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.18.1

### Reproduction Steps

1. Create DynamoDB with a stream and a TTL
2. In the DynamoDB stream lambda, attempt to identify if a record is deleted because of the TTL:

```js
export const dynamoDbStreamHandler = async (event: GetRecordsOutput) => {
    event.Records
        .filter(r =>
            r.eventName === 'REMOVE' &&
            r.userIdentity?.Type === 'Service' &&
            r.userIdentity?.PrincipalId === 'dynamodb.amazonaws.com')
        .map(r => console.log(`record deleted by TTL ${JSON.stringify(r)}`));

    return;
};
```

### Observed Behavior

The above sample will fail to identity TTL deleted records, due to `r.userIdentity.Type` and `r.userIdentity.PrincipalId` returning `undefined`

The above code will log nothing in CloudWatch.

### Expected Behavior

The above code should log an entry for each TTL deleted record.

A workaround is to use object bracket notation:

```js
export const dynamoDbStreamHandler = async (event: GetRecordsOutput) => {
    event.Records
        .filter(r =>
            r.eventName === 'REMOVE' &&
            r.userIdentity &&
            r.userIdentity['type']=== 'Service' &&
            r.userIdentity['principalId'] === 'dynamodb.amazonaws.com')
        .map(r => console.log(`record deleted by TTL ${JSON.stringify(r)}`));

    return;
};
```

### Possible Solution

Change Identity type properties `"Type"` and `"PrincipalId"` to lowercase `"type"` and `"principalId"`

### Additional Information/Context

* [useridentity docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb-streams/interfaces/_record.html#useridentity)
* [Identity docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb-streams/interfaces/identity.html)

**Comment by RanVaknin** [comment]
Hi @eulogio-3t ,

Thanks for opening the issue. 

The difference you are describing between the data returned (lower case) and the expected modeled data (upper case) is because of the way the dynamodb service team defined their model (upper case) 

So this is an oversight with how the service team defined their API model (since the SDKs are generated from that API model, the types are inherited as upper case) 

That being said, I'm able to successfully log that remove event to cloudwatch without the bracket notation:

**Lambda code, Node 18 - using the embedded SDK v3:**
```js
const { GetRecordsOutput } = require("@aws-sdk/client-dynamodb-streams");

const dynamoDbStreamHandler = async (event) => {
    event.Records
        .filter(r =>
            r.eventName === 'REMOVE' &&
            r.userIdentity?.type === 'Service' &&
            r.userIdentity?.principalId === 'dynamodb.amazonaws.com')
        .map(r => console.log(`record deleted by TTL ${JSON.stringify(r)}`));

    return;
};

module.exports = { dynamoDbStreamHandler };

```

**Cloudwatch log:**
```console
	INFO	record deleted by TTL 
{
    "eventID": "REDACTED",
    "eventName": "REMOVE",
    "eventVersion": "1.1",
    "eventSource": "aws:dynamodb",
    "awsRegion": "us-east-1",
    "dynamodb": {
        "ApproximateCreationDateTime": 1687898040,
        "Keys": {
            "id": {
                "N": "124"
            }
        },
        "OldImage": {
            "id": {
                "N": "124"
            },
            "ttl": {
                "N": "1687897271"
            }
        },
        "SequenceNumber": "3515300000000010064594797",
        "SizeBytes": 19,
        "StreamViewType": "NEW_AND_OLD_IMAGES"
    },
    "userIdentity": {
        "principalId": "dynamodb.amazonaws.com",
        "type": "Service"
    },
    "eventSourceARN": "arn:aws:dynamodb:us-east-1:REDACTED:table/ttl-table/stream/2023-06-27T20:02:26.986"
}
```

In some cases the SDK would be able to identify discrepancies between modeled and returned data and convert the types to avoid any errors. 

>The above code will log nothing in CloudWatch.

Even if the values are undefined, the event should be logged to your cloudwatch log groups. The only difference is that those values would be undefined. I suggest you give your cloudwatch logs another look.

Thanks,
Ran~

**Comment by eulogio-3t** [comment]
Hi Ran

What I meant with "logs nothing" is that the properties themselves weren't logged. Apologies for not being clear there. 

I'll change the bracket notation to lower case property names and try again. 

Thanks for looking into this

Eulogio

**Comment by RanVaknin** [comment]
Hi @eulogio-3t ,

I agree that this should get fixed, but a change would have to happen with the service team itself, and not the SDK team. 
Unfortunately this can take a long time, especially with core service teams like (Dynamo, S3, EC2) since they are so big, and finding an owner can take a long time.  

Im going to assign low priority for this, if other folks are running into this we can prioritize a fix. 

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi there,

I have raised this with the DDB team internally (ticket `P139325711`). Since this is not actionable by the SDK team directly, Im going to close this. If you have access to AWS support via the developer console, please open a support ticket and refer to the ticket ID I have shared for more updates.

Thanks,
Ran~
