### ISSUE TITLE
Add examples to docs..

### ISSUE THREAD

**Issue by agonzalezo** [aws/aws-sdk-js-v3#4922]
### Add examples to docs..

The new documentation for AWSJavaScriptSDK/v3 looks so bad, this don't have any example of the client commands unlike the legacy documentation...

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/iam/

**Comment by RanVaknin** [comment]
Hi @agonzalezo ,

The examples are now generated on a per operation basis. For example IAM's [AttachRolePolicyCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/iam/command/AttachRolePolicyCommand/) documentation will be in the operation page itself rather than the client page.

Examples are now much more in depth, they include all the input parameters (required and optional). The legacy documentation presented a generic example for each client and operation and did not have specific input parameters listed.

Is this what you were after? It will be helpful if you can better articulate what kind of examples you are after. 

Thanks,
Ran~

**Comment by agonzalezo** [comment]
Hi @RanVaknin  thanks

My bad, that was what I was looking for
