### ISSUE TITLE
TypeError: Cannot read properties of undefined (readding '#text') when putObject agains a mock server

### ISSUE THREAD

**Issue by thynson** [aws/aws-sdk-js-v3#4935]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When testing against a mock server of [s3rver](https://www.npmjs.com/package/s3local) in Github Action CI, the following 
error happened **occasionally**. 

It seems like the mock server return a malformed response occasionally for unknown reason, causing the SDK to throw a TypeError. It might not happens with a production Amazon S3 endpoint, but it could happens with any S3-compatible endpoint.

```
TypeError: Cannot read properties of undefined (reading '#text')
      Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.

      104 |   async beginPartitionedUpload(name: string, info: MultipartFileInfo): Promise<S3MultipartUploadState> {
      105 |     const fileKey = this.#getFileKey(name, info);
    > 106 |     const multipartOutput = await this.#s3Client.createMultipartUpload({
          |                             ^
      107 |       Bucket: this.#s3Bucket,
      108 |       Key: fileKey,
      109 |       ContentType: info.mimeType,

      at ../../node_modules/.pnpm/@aws-sdk+client-s3@3.345.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:96[39](https://github.com/sensejs/sensejs/actions/runs/5474142672/jobs/9968544135#step:6:40):30
      at parseErrorBody (../../node_modules/.pnpm/@aws-sdk+client-s3@3.345.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:9648:19)
      at de_CreateMultipartUploadCommandError (../../node_modules/.pnpm/@aws-sdk+client-s3@3.345.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3208:15)
      at ../../node_modules/.pnpm/@aws-sdk+middleware-serde@3.3[42](https://github.com/sensejs/sensejs/actions/runs/5474142672/jobs/9968544135#step:6:43).0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
      at ../../node_modules/.pnpm/@aws-sdk+middleware-signing@3.342.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
      at ../../node_modules/.pnpm/@aws-sdk+middleware-retry@3.342.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:[46](https://github.com/sensejs/sensejs/actions/runs/5474142672/jobs/9968544135#step:6:47)
      at ../../node_modules/.pnpm/@aws-sdk+middleware-logger@3.342.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
      at S3StorageAdaptor.beginPartitionedUpload (src/index.ts:106:29)
```

### SDK version number

@aws-sdk/client-s3@3.345.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 16.20.1

### Reproduction Steps

Sorry, but I cannot provide some step to reproduced it deterministically. It happens occasionally when using `this.#s3Client.putObject` against a mock server.

### Observed Behavior

`this.#s3Client.putObjec` shall either completed successfully, or failed with an error like `S3ServiceException`

### Expected Behavior

An error of TypeError is thrown instead.

### Possible Solution

Additional checks around https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/protocols/Aws_restXml.ts#L12986 shall be applied.

### Additional Information/Context

CI Log: https://github.com/sensejs/sensejs/actions/runs/5474142672/jobs/9968544135

**Comment by RanVaknin** [comment]
Hi @thynson,

Thanks for opening this issue. The type error you are seeing points to a deserialization issue, which is likely due to the SDK receiving an unexpected response from the s3rver mock server.

While the SDK aims to be compatible with all S3 compatible endpoints, compatibility with specific third party tools such as s3rver can't be guaranteed, especially considering the last update of s3rver was in October 2021. It's possible that changes in the SDK or differences in implementation may have caused intermittent issues like this one.

As a self diagnosis step, you might want to log and inspect the raw HTTP responses from the s3rver when the error occurs. This might give you clues on the nature of the malformed response, which you can then share with the s3rver team.

Although I can't officially endorse or support any of these mock services, I see many developers in the community use services like Minio or Localstack, so you might want to take a look at using those instead as they tend to be updated more frequently. However, just like with s3rver, it's up to these third-party libraries to maintain their compatibility with the SDK.

I understand this might not be the solution you were looking for, but I hope it gives you some direction on where to look next.

Thanks,
Ran~
