### ISSUE TITLE
Amazon Personalize CreateCampaignCommand - Invalid parameters

### ISSUE THREAD

**Issue by crisdmp** [aws/aws-sdk-js-v3#4982]
### Describe the issue

The CreateCampaignCommand  receives the param `solutionVersionArn ` to specify the arn of a particular solution version. However, in the console a particular solution version is not required, it's enough only with the solution arn itself. 
When I try to assign the value of the solution arn ( without specifying any version) an exception of [ResourceNotFoundException](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-personalize/Class/ResourceNotFoundException) is thrown which forces to create a new solution version. 

I'm an Amazon employee, you can contact me: @crisdmp for more information. 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/personalize/command/CreateCampaignCommand/

**Comment by RanVaknin** [comment]
Hi @crisdmp ,

Thanks for reaching out. The SDKs are different from the AWS console as they are a direct extension of the AWS service APIs they interact with. If you didn't know, all the SDKs client are auto-generated from the API model files published by each AWS service. 

The error message you are seeing is coming directly from the service, not the SDK. And since the [Personalize API](https://docs.aws.amazon.com/personalize/latest/dg/API_CreateCampaign.html#API_CreateCampaign_RequestParameters) defines both `SolutionVersionArn` and `Name` as required fields, by not supplying both, the service will return this exception:

![image](https://github.com/aws/aws-sdk-js-v3/assets/50976344/6bc42d50-7067-483b-a36d-cfce4ef1816b)

Since you are an Amazon employee, you can direct this question to the Personalize service team. If you have any other SDK related questions please reach out to us internally as there are different teams supporting external and internal customers. 

Thanks,
Ran~
