### ISSUE TITLE
Error is misleading

### ISSUE THREAD

**Issue by waynet-ihm** [aws/aws-sdk-js-v3#5005]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Misleading error text is returned.

GetParameterCommand: {"middlewareStack":{},"input":{"Name":"xxx/yyy","WithDecryption":true}}

Error: getParameterByName Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_

yeah it needs a forward beginning slash but this error is not helpful

### SDK version number

 "@aws-sdk/client-ssm": "3.363.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.13.0

### Reproduction Steps

get a parameter using the sdk with no leading slash on a name with a path

### Observed Behavior

misleading/unhelpful error is returned

### Expected Behavior

tell us what's wrong, not what ain't

### Possible Solution

you're missing a leading slash

**Comment by RanVaknin** [comment]
Hi @waynet-ihm ,

This error you are seeing is coming from the SSM service itself, not the SDK. 
Because this is service side behavior, this needs to be opened with the service team as a feature request. You can do that by reaching out to internal AWS support person via the AWS console and asking them to raise an internal feature request with your use case and proposed changes.

Since the SDK team cannot do anything about the error returned from the service Im confident we can close this issue.

Thanks again,
Ran~
