### ISSUE TITLE
Shape not found

### ISSUE THREAD

**Issue by SteveEarl-AWS** [aws/aws-sdk-js-v3#5023]
### Describe the issue

```json
{"name":"EvaluationFormItem.QuestionMember","pkg":"@aws-sdk/client-connect","type":"Interface","text":"QuestionMember"}
```

I'm getting a message "Sorry, we couldn't find that shape" when attempting to view the QuestionMember docs.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/connect/command/DescribeEvaluationFormCommand/

**Comment by RanVaknin** [comment]
Hi @SteveEarl-AWS ,

From this bug report it's not clear what the issue is. `QuestionMember` does not exist on the link you provided:
![image](https://github.com/aws/aws-sdk-js-v3/assets/50976344/04d8ccde-085c-4f88-bb76-f676885a6911)


Can you please elaborate on what seems to be the problem? 

Thanks,
Ran~
