### ISSUE TITLE
ListUsersCommand Input - Limit default/maximum?

### ISSUE THREAD

**Issue by markw351** [aws/aws-sdk-js-v3#5026]
### Describe the issue

It would be good to see what the default limit is since it is an optional field, and also advise what the maximum is so we don't need to programmatically determine that.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/command/ListUsersCommand/

**Comment by RanVaknin** [comment]
Hi @markw351 ,

Thanks for your feedback. The docs you are seeing are directly generated from the Service's API documentation, and since the API itself doesn't have information about what the default value is, it will not appear in the docs.

For JS v3 the default value for pagination is always the max. So for `ListUsers` it would be 60.

I can discuss it with the team to see if this is something we can add.

Thanks again for your feedback. 
Cheers,
Ran~

**Comment by RanVaknin** [comment]
Hi @markw351 ,

We have discussed this as a team. And I actually have found that the default value for list operations varies based on each service.  The Service team does not include the default value for `limit` in their API model, so when requests are sent without the `limit` the SDK is "at the mercy" of the service team in terms of how many results are returned. 

Unfortunately this is not something we can implement since we rely on the API model to specify information like this (currently only min and max values are documented)
<img width="634" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/08722cf0-5800-447c-90ae-3b53a6469255">

Instead you can [provide feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Cognito&topic_url=https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html) directly to the service team so they can document the default limit on their doc page. 

Since this is not actionable by the SDK team, I'm inclined to close this. Please don't let this discourage you from opening additional feature requests in the future.


Thanks again,
Ran~
