### ISSUE TITLE
Correct the description of the UpdateUserAttributesCommand

### ISSUE THREAD

**Issue by dev-situaction** [aws/aws-sdk-js-v3#5029]
### Describe the issue

Modify the description of the API:

*** Allows a user to update a specific attribute (one at a time).
->
*** Allows a user to update specific attributes.

The API currently allows to modify multiple attributes at a time, eg: birthdate and address can be modified through the same API call.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/command/UpdateUserAttributesCommand/

**Comment by RanVaknin** [comment]
Hi @dev-situaction ,

Thanks for raising this issue.

The doc string you are seeing is defined in the [API reference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html) for Cognito and is directly generated from there. Since the SDK team cannot change this directly, this Github issue is not actionable by the SDK team.

I suggest you [submit feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Cognito&topic_url=https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html) through AWS docs, as this feedback goes directly to the doc writers on the service team itself which is the "source of truth" for this documentation.

Thanks again!
Ran~
