### ISSUE TITLE
Which Region Is Needed for Listbuckets?

### ISSUE THREAD

**Issue by shirady** [aws/aws-sdk-js-v3#5082]
### Describe the issue

Hello,
According to the documentation and what I saw `Listbuckets` returns all the buckets regardless of where they are located.
And it is aligned with the documentation:

> Returns a list of all buckets owned by the authenticated sender of the request. 

But in order to create the client to use it we need to add the region, but it doesn't accept every region and returns an error.
So I wonder what should b the region in this case?

Thanks!

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/ListBucketsCommand/

**Comment by RanVaknin** [comment]
Hi @shirady 

`listBuckets` will return the entire list of buckets in your account. The SDK client needs a region because it needs to know to which AWS partition it needs to route the request.

> but it doesn't accept every region and returns an error.
So I wonder what should b the region in this case?

For `listBuckets`, you can pass in any region and the results will be the same.

Without seeing your code, or errors, it will be hard to advise you. In the future please fill the intake form in it's entirety so we can better assist you.

Thanks,
Ran
