### ISSUE TITLE
Total Object Count For An S3 Bucket

### ISSUE THREAD

**Issue by joyceben33** [aws/aws-sdk-js-v3#5101]
### Describe the feature

# Add Feature That Lists The Total Number of Objects Contained In An S3 Bucket.
Similar to AWS CLI Command `aws s3 ls s3://$bucketName/ --recursive | wc -l`

### Use Case

**PROBLEM: Lambda timeout when trying to find the total key count in an S3 Bucket**  

I'm currently using the `@aws-sdk/client-s3`package in my Serverless NodeJS Express Lambda function. I'm running into a timeout issue when trying find the total key count in my s3 bucket that contains a huge data set. Below is an example of the only way to find the total count using the sdk.

```typescript
export async function listS3BucketKeyCountTotal(bucketName: string) {
  let totalObjectCount = 0;
  let nextContinuationToken = '';

  const s3Command = new ListObjectsV2Command({
    Bucket: bucketName,
    ...(nextContinuationToken && { nextContinuationToken }),
  });

  do {
    const response = await s3Client.send(s3Command);
    logger.info(`Key Count Per Request: ${response.KeyCount} OR ${response.Contents?.length}`);

    totalObjectCount += response.KeyCount ?? 0;
    logger.info(`Key Count Total: ${totalObjectCount}`);
    nextContinuationToken = response.NextContinuationToken ?? '';
  } while (nextContinuationToken);

  return totalObjectCount;
}
```

### Proposed Solution

Add a new S3 client operation to `@aws-sdk/client-s3` called something like`GetBucketDetails` and this would return an something similar to the JSON below.
```JSON
{
"bucketSize": 545424524 // in bytes,
"objectCount": 10255,
"directoryCount": 5,
...etc.
}
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.391.0

### Environment details (OS name and version, etc.)

NodeJS 18.16.0

**Comment by RanVaknin** [comment]
Hi @joyceben33 ,

The `aws s3 <command>` scheme in the CLI is a convenience client built on top of the regular `aws s3api` client. There is no service side support for providing the number of objects in the bucket so the SDK doesn't generate a method for it.

The CLI calls ListObjectsV2 "under the hood", and you can witness that by running your command with the `--debug` flag and inspecting the output:

```console
$ aws s3 --debug ls s3://mybucket/ --recursive | wc -l 

2023-08-17 09:36:29,751 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListObjectsV2) with params: {'url_path': '?list-type=2', 'query_string': {'prefix': '', 'encoding-type': 'url'}, 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/2.11.18 Python/3.11.3 Darwin/22.5.0 exe/x86_64 prompt/off command/s3.ls'}, 'body': b'', 'auth_path': '/mybucket?list-type=2', 'url': 'https://mybucket.s3.us-east-1.amazonaws.com/?list-type=2&prefix=&encoding-type=url', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x110328c10>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}, 'encoding_type_auto_set': True, 's3_redirect': {'redirected': False, 'bucket': 'mybucket', 'params': {'Bucket': 'mybucket', 'Prefix': '', 'EncodingType': 'url'}}}}
```

>Add a new S3 client operation to @aws-sdk/client-s3 called something likeGetBucketDetails and this would return an something similar to the JSON below.

While I agree with you that this could be beneficial, the SDK cannot add method without anything in the server that sends the correct information back. If you didn't know the SDKs are all auto code-generated from each service's API model, so whatever exists on the API level, also exists on the SDK - nothing more, nothing less.  

The solution here is to increase your Lambda's timeout:

```console
$ aws lambda update-function-configuration --function-name myLambda --timeout 15 // or your desired value
```

Since this is not actionable from the SDK's team perspective, you can create a support ticket from your AWS console and submit a feature request to the S3 team directly.

Thanks again,
Ran~
