### ISSUE TITLE
ACCESS DENIED

### ISSUE THREAD

**Issue by EbotRawley** [aws/aws-sdk-js-v3#5114]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Thanks for solving me previous problem, that worked! It now uploads images as before and updates the database but I get another error access denied, The image cannot be accessed: This is what I get when I open the link I a browser:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3S9K5JT1AP3HMS61</RequestId>
<HostId>RIEIq8t4oPV5JtXE+SLrwB2sRhyRI9IrJ54x13TXACUPVa9HiH88XFd7AwVa3Da2L1Ysj4BK1fg=</HostId>
</Error>
```

Also I think the last thing to do is the delete, you asked me to use upload to handle this issue with the upload, how can I deal with the update and delete as well ???

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

...

### Reproduction Steps

...

### Observed Behavior

This is what the console.log(data) returns :
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'BJT8FE32HCQXEDWT',
    extendedRequestId: 'P6M5HnIa9BAcU9zfz11AxvDJPEx4S7uQyjU/2sOBzKo1rcbA3p9ldS86ZTgtftnvRZgVH9EnoYE=',       
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: '"fbb501258123a9d154f97729558adbc7"',
  ServerSideEncryption: 'AES256',
  Bucket: 'dbchat-profile-images-v1',
  Key: '64db491004ce74d30306a344-profile-image.jpg',
  Location: 'https://dbchat-profile-images-v1.s3.eu-north-1.amazonaws.com/64db491004ce74d30306a344-profile-image.jpg'
}
```

### Expected Behavior

I'm expecting to see the image uploaded.

**Comment by RanVaknin** [comment]
Hi @EbotRawley ,

I assume you are trying to open this link from S3 and seeing this access denied from your browser?
This is because your bucket is not open to the public and the request is not signed with valid credentials.
You can retrieve objects hosted on s3 either by running a [`GetObjectCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/) on the object, or generating a [presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) (short lived). 

You can consult[ this doc](https://docs.aws.amazon.com/AmazonS3/latest/userguide/troubleshoot-403-errors.html) about common issues

Other than that, its not very clear to me what you are trying to do. 
If you need to delete an object you can use the [`DeleteObjectCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/DeleteObjectCommand/).

If you need further help, it would be helpful if you can articulate better what you are trying to achieve.

Thanks,
Ran~

**Comment by EbotRawley** [comment]
Yeah but yesterday I opend an issue becuase i used the normal putObjectCommand since it doesn't support location property. I wanted to upload the image to the bucket and return the images' url so it can be updated in the database but didn't work so the issue i opened was resolved using the upload from the aws-sdk-js-v3/lib-storage, but now I succeded to upload the image and get the url but recieve the ACCESS DENIED 
I set the bucket and objects to not public but created 3 policies, getObject, PutObeject and DeleteObject but I don't know what's wrong

**Comment by RanVaknin** [comment]
Hi @EbotRawley,

I think the confusion comes from the fact that you are expecting that the location URL you get back from upload, will be accessible from the browser.

If your bucket is not public (it should be private as a best practice), you will not be able access the image directly through your browser because your browser does not have authenticated access to your S3 bucket.
If you want to access your image via the browser, you will need to create a presigned URL for it from your application. 

A presigned URL is you telling the S3 service - "Im going to make this GetObject request, but instead of returning the object to my computer, give me a URL so I can access that object from anywhere"

A presigned URL is short lived through. Once it expires you will not able to access it, and you might want to generate a new presigned URL every time you want to access the image.
If your application is meant to host static assets that are open to the public you might want want to make your bucket public. You just need to understand that everything else in the bucket will be accessible via the internet, so you will need to make your own security consideration (for example, don't host sensitive data on that bucket)

Thanks,
Ran~

**Comment by EbotRawley** [comment]
Ok I got it, the bucket I created was just for user profile images, I think it can be public, I might create another bucket in future to handle user images, audio, docs and videos sent in chat rooms as media. I think that will need to be private. So how can I create this presigned URL ? And when using it, if i set my current bucket to public, can I still use the normal commands the put, get and delete ? And will i still need to use the presigned url if i need to return the uploaded image url when its uploaded ?

**Comment by RanVaknin** [comment]
>So how can I create this presigned URL ?

The link I previously provided has code examples. 

>And when using it, if i set my current bucket to public, can I still use the normal commands the put, get and delete ?

Nothing is preventing you from setting your bucket to public AND generating a presigned URL, but the solution I provided was to either make the bucket public OR generate a presigned URL. The commands will work regardless of whether the bucket is public or private.

>And will i still need to use the presigned url if i need to return the uploaded image url when its uploaded ?

If the bucket is public you can provide the URL you get from `location` directly. If the bucket is private you'll need to generate a presigned URL.

Thanks,
Ran~

**Comment by EbotRawley** [comment]
Okay thanks I've succeded to do most of the work. Now I'm using the presigned URL to update and display the images in my app but when it expires i get the access denied message again. How can i make it not to expire or maybe keep regenerating a new resigned url everytime it expires automatically. I don't even know how to regenerate one

**Comment by RanVaknin** [comment]
Hi @EbotRawley ,

A presigned URL is by design a short lived asset. If you want to keep accessing it, you will have to generate a presigned URL every time you are trying to access it. 

> I don't even know how to regenerate one
Regenerating a presigned URL is just creating a new one.

I can't give you advice on how to design your product, but from the sound of it you are trying to make your objects accessible all the time. For that you'd want to make your objects public. 

Thanks,
Ran~
