### ISSUE TITLE
fart

### ISSUE THREAD

**Issue by codyfrisch** [aws/aws-sdk-js-v3#5147]
fart

**Comment by RanVaknin** [comment]
Hi @codyfrisch ,

Thanks for the feature request. This feature sounds very specific and serves to be an abstraction on top of the already provided base client. We prioritize feature requests based on customer engagement and since we do not see a use case that can benefit most of our customers, this remains a low priority. 

If anything changes we will reprioritize. 

Thank you again,
Ran~

**Comment by kellertk** [comment]
Why?

Anyway, if you want this to be reviewed again, please open a new issue. Otherwise this issue will get lost like a toot in the wind.
