### ISSUE TITLE
OpenSearch:updateDomainConfig call from CloudFormation using AwsCustomResource fails

### ISSUE THREAD

**Issue by cristidiaconu** [aws/aws-sdk-js-v3#5151]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

AwsCustomResource in CloudFormation fails to call OpenSearch updateDomainConfig with MaintenanceSchedules.

### SDK version number

@aws/aws-sdk-js-v3

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18.x

### Reproduction Steps

I have an AwsCustomResource defined in CDK that looks something like this:

```js
// some fields were removed for simplicity
new AwsCustomResource(this, "AutoTuneConfiguration", {
    onCreate: {
        service: "OpenSearch",
        action: "updateDomainConfig",
        parameters: {
            "AutoTuneOptions": {
                "MaintenanceSchedules": [{
                    "StartAt": new Date().getTime()
                }]
            }
        }
    }
})
```

### Observed Behavior

The custom resource fails with the following error:

```console
2023-08-29T08:12:08.111Z	8cc9c6f2-bdd3-4cd8-9c9b-cde502721e2f	INFO	TypeError: _.getTime is not a function
    at StartAt (/tmp/node_modules/@aws-sdk/client-opensearch/dist-cjs/protocols/Aws_restJson1.js:3821:38)
    at applyInstruction (/tmp/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:73:33)
    at take (/tmp/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:44:9)
    at se_AutoTuneMaintenanceSchedule (/tmp/node_modules/@aws-sdk/client-opensearch/dist-cjs/protocols/Aws_restJson1.js:3818:37)
    at /tmp/node_modules/@aws-sdk/client-opensearch/dist-cjs/protocols/Aws_restJson1.js:3828:16
    at Array.map (<anonymous>)
    at se_AutoTuneMaintenanceScheduleList (/tmp/node_modules/@aws-sdk/client-opensearch/dist-cjs/protocols/Aws_restJson1.js:3827:10)
    at MaintenanceSchedules (/tmp/node_modules/@aws-sdk/client-opensearch/dist-cjs/protocols/Aws_restJson1.js:3834:38)
    at applyInstruction (/tmp/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:73:33)
    at take (/tmp/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:44:9)
```

### Expected Behavior

The same custom resource was working fine a few months ago. Not sure what changed - could be that the AwsCustomResource Lambda switched from Node.js 16.x to 18.x. Because based on the code I see in that Lambda, it seems to now choose the aws-sdk-v3-handler. Sample code from the (auto-generated) Lambda function:

```js
runtime = env && env >= "AWS_Lambda_nodejs18.x" ? require("./aws-sdk-v3-handler") : require("./aws-sdk-v2-handler");
```

I assume before it was working with the v2 handler.

### Possible Solution

Seems to me that this is related to this recent change: https://github.com/aws/aws-sdk-js-v3/pull/4625. Specifically this line: https://github.com/aws/aws-sdk-js-v3/blame/main/clients/client-opensearch/src/protocols/Aws_restJson1.ts#L5331. This code assumes that the StartAt value is a Date and has a `getTime` method. I don't know if there are any data parsing/transformation happening on the way, but the original JSON includes a Number, not a Date (of course).

**Comment by ajredniwja** [comment]
Hi there, thanks for opening this issue, with node 18 lambda ships the V3 of the SDK https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/opensearch/command/UpdateDomainConfigCommand/. The issue here seems to be `StartAt` expecting a Date object as you can see [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/opensearch/command/UpdateDomainConfigCommand/) where as V2 would accept a number.

**Comment by cristidiaconu** [comment]
Hey. I understand that. But I'm not calling the AWS JS SDK directly. Instead, I define a custom resource in CloudFormation (or CDK), which takes the `StartAt` as parameter (please see my example in the original post). In JSON, the only types are number or string. 

That custom resource, when deployed via CloudFormation, executes a Lambda that takes the `StartAt` parameter and invokes AWS JS SDK with it. But that Lambda (which is generated by CDK, is not my code), doesn't know that it needs to parse the `StartAt` parameter as `Date`. It just reads it and sends it further!

So I believe that the AWS JS SDK should accept `StartAt` as string and parse it internally, just like it happened in V2.

Alternatively, this could be solved by AWS CDK. If the Lambda running custom resources, would parse the JSON and convert the `StartAt` parameter to a `Date`, it would work... But currently it doesn't (and with SDK v2 it didn't need to do it!).

**Comment by RanVaknin** [comment]
Hi there,

This is quite an old issue, but I think I know why this is happening.

`startAt` is modeled as a `timestamp` that must conform to RFC3339. When you are invoking this operation with a timestamp in the wrong format the SDK will throw a serialization error which is what you are seeing.

Specifically: `new Date().getTime()` will return timestamp in epoch format: `1723071209726` which does not conform to RFC3339.
Instead, you might be able to use `new Date().toISOString()` which returns `2024-08-07T22:53:29.726Z` and is closer to RFC3339. Please note that you might need to manually cleanup the milliseconds from that timestamp: `2024-08-07T22:53:29Z`.

The Opensearch service is the entity that defines in which format it requires the data to be provided in, not the SDK. The SDK only strictly adheres to the input type defined by that service.

Since this is not something we can change on the SDK side, Im going to close this.

Thanks,
Ran~
