### ISSUE TITLE
docs are seemingly wrong / incomplete

### ISSUE THREAD

**Issue by joshribakoff-sm** [aws/aws-sdk-js-v3#5168]
### Describe the issue

Trying to follow https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html
- you reference thing you don't import
- you don't specify the versions of things you reference, and there were breaking changes to `proxy-agent`.

Eventually, I found https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/global-config-object.html
- also missing imports

Then, I found https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/installing-jssdk.html
- command(s) provided installs v2 when I'm using v3

It feels like AWS consistently has a terrible developer experience. How am I supposed to use the global config w/ v3? Or was it presumably removed? So how do I use a proxy then? Do I have to downgrade to v2? Or do I have to read the source code myself in lieu of correct/complete docs?

Here's a crazy idea, don't ship incomplete APIs that require installing 3rd party packages to use? Actually verify the code examples compile before publishing your docs (they don't). If telling people to install things, reference the version(s). Don't reference newer versions of your code on one page and then older versions on the other page? Provide *complete* examples instead of fragmenting the docs?

### Links

see above

**Comment by joshribakoff-sm** [comment]
Finally found https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-proxies.html corresponding to v3. My point still stands your docs are horribly fragmented / wrong. For example, the v2 docs still reference ambiguous versions of packages where there were broken changes, fail to show where they import from, etc.

**Comment by joshribakoff-sm** [comment]
![Screenshot 2023-09-01 at 2 31 59 PM](https://github.com/aws/aws-sdk-js-v3/assets/97546767/89a14a4a-c074-4f7b-83fc-9f5a96df11b1)

Still not working.

**Comment by joshribakoff-sm** [comment]
Ok, switched to `hpagent`, still not working, same error. Current issue you show how to configure the proxy for dynamo client but apparently not all clients provided in this SDK actually confirm to the same API (or the docs are just out of date, again)? Using AWS makes me want to rage quit, every time.

**Comment by joshribakoff-sm** [comment]
I finally found https://stackoverflow.com/questions/66969381/how-to-configure-nodejs-aws-sdk-using-s3-client-library-with-proxy (pretty bad when docs are so bad you resort to stack overflow instead)

```
import { HttpsProxyAgent } from "hpagent";
import { NodeHttpHandler } from "@aws-sdk/node-http-handler";

const agent = new HttpsProxyAgent(process.env["HTTPS_PROXY"]);

  const sts = new STSClient({
    region,
    requestHandler: new NodeHttpHandler({
      httpsAgent: agent,
      httpAgent: agent,
    }),
  });
```

Still not working:

```
INFO index.ts Terminating, reason: TypeError: Cannot read properties of undefined (reading 'hostname')
    at HttpsProxyAgent.createConnection (node_modules/hpagent/index.js:78:24)
```

Yes, I'm passing the proxy URL not undefined. I'm using the library your docs suggest to use, in the manner shown in your docs.

**Comment by joshribakoff-sm** [comment]
Finally got it working:

```
import { HttpsProxyAgent } from "hpagent";
import { NodeHttpHandler } from "@aws-sdk/node-http-handler";

const region = "us-east-2";
const agent = new HttpsProxyAgent({ proxy: process.env["HTTPS_PROXY"] ?? "" });
const sts = new STSClient({
  region,
  requestHandler: new NodeHttpHandler({
    httpsAgent: agent,
    httpAgent: agent,
  }),
});
```

The last issue from my previous post was another example of your docs having more issues. In this case, referencing an older version of `hpagent` package, apparently, without telling us which version you are using.

**Comment by RanVaknin** [comment]
Hi @joshribakoff-sm ,

Thanks for your feedback.

The JS SDK versions v2 and v3 are two separate major version and have different API, a complete re-write if you will. Since the two version have different syntax, the documentation between the two is not necessarily interchangeable. 

In your initial issue report, you linked v2 documentation, which will not apply to v3. For guidance on v3 related subjects you should consult the v3 docs.

I'm a bit confused because this [last comment](https://github.com/aws/aws-sdk-js-v3/issues/5168#issuecomment-1703349922) where you mentioned that this is working for you, is exactly what our docs specify(which you have linked in your [second comment](https://github.com/aws/aws-sdk-js-v3/issues/5168#issuecomment-1703337795)) so Im not sure where the discrepancy lies?

Regarding versions listed. If a version is not specified(which it almost never is) you can infer that we are suggesting you use the latest version of the package. This is a common documentation paradigm and is not unique to AWS. 

If you have further actionable feedback, please let us know so we can make our docs better. 
Thanks again,
Ran~

**Comment by joshribakoff-sm** [comment]
> you can infer that we are suggesting you use the latest version of the package.

Maybe the "latest" versions worked when you published these docs, but currently the latest versions do not work, I had to seek out the older version(s) (that you fail to specify) to get it working. Not sure what is so hard to understand about this.

**Comment by kuhe** [comment]
Here is the code sample from the linked doc page:
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-proxies.html

Converting it from DynamoDB to STS (our clients have the same config API for requestHandler):
```js
import { STSClient } from '@aws-sdk/client-sts'; // 3.421.0 (latest)
import { NodeHttpHandler } from "@smithy/node-http-handler"; // 2.1.6 (latest)
import { HttpsProxyAgent } from "hpagent"; // 1.2.0 (latest)
const agent = new HttpsProxyAgent({ proxy: "http://internal.proxy.com" });
const stsClient = new STSClient({
    requestHandler: new NodeHttpHandler({
        httpAgent: agent,
        httpsAgent: agent
    }),
});
```

Here is the code you said was working:
```js
import { STSClient } from "@aws-sdk/client-sts"; # 3.360.0
import { HttpsProxyAgent } from "hpagent";  # ^1.2.0
import { NodeHttpHandler } from "@aws-sdk/node-http-handler"; # ^3.374.0

const region = "us-east-2";
const agent = new HttpsProxyAgent({ proxy: process.env["HTTPS_PROXY"] ?? "" });
const sts = new STSClient({
  region,
  requestHandler: new NodeHttpHandler({
    httpsAgent: agent,
    httpAgent: agent,
  }),
});
```

We don't consider these to differ meaningfully, but to address the visible diffs:
- `@aws-sdk/node-http-handler` has moved to `@smithy/node-http-handler`. This is why our docs use the latter. It has its own version numbers but has a backwards compatible API. Announcement: https://github.com/aws/aws-sdk-js-v3/issues/5102 You can temporarily continue to use `@aws-sdk/node-http-handler` because it is compatible, but you should update to the renamed package following the docs in the future.

- The example does not provide the region parameter. We do not include credentials or region in the examples because they can be supplied from environment variables or profile settings. They are documented here: 
  - https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html
  - https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html

From the example, using the latest versions of all shown packages does work.
