### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by TWDBrob** [aws/aws-sdk-js-v3#5182]
### Describe the issue

Page should call out that you use the "replace" op to create a new record (why there's no add command or it's not called addOrReplace is another issue, but probably not a docs issue).  

Currently, the page mentions only that the two possible op values are remove and replace.  Additionally, it's unclear that remove merely deletes the record value, but doesn't delete the entire record (again, why it behaves that way is weird, too).

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-sync/command/UpdateRecordsCommand/

**Comment by RanVaknin** [comment]
Hi @TWDBrob ,

If you didn't know,  all the AWS SDKs are code generated from the API models of each service team (including documentation)

Since all the service client-specific information you see is code generated, a request to change the docs should be made upstream to that service.

You can find the original documentation from which the SDK docs are generated [here](https://docs.aws.amazon.com/cognitosync/latest/APIReference/API_UpdateRecords.html)

In the future, if you have more suggestions you can directly submit them using the `Feedback` button at the top right corner of each doc page.

<img width="1418" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/d2a5e7b3-50f2-4c6c-aa36-f760faf311ec">


Thanks,
Ran ~
