### ISSUE TITLE
Error in sample code for client-cloudformation ListStacksCommand

### ISSUE THREAD

**Issue by box-turtle** [aws/aws-sdk-js-v3#5183]
### Describe the issue

Code sample has wrong construction of StackStatusFilter

existing code sample:

```js
const input = { // ListStacksInput
  NextToken: "STRING_VALUE",
  StackStatusFilter: [ // StackStatusFilter
    "CREATE_IN_PROGRESS" || "CREATE_FAILED" || "CREATE_COMPLETE" || "ROLLBACK_IN_PROGRESS" || "ROLLBACK_FAILED" || "ROLLBACK_COMPLETE" || "DELETE_IN_PROGRESS" || "DELETE_FAILED" || "DELETE_COMPLETE" || "UPDATE_IN_PROGRESS" || "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS" || "UPDATE_COMPLETE" || "UPDATE_FAILED" || "UPDATE_ROLLBACK_IN_PROGRESS" || "UPDATE_ROLLBACK_FAILED" || "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS" || "UPDATE_ROLLBACK_COMPLETE" || "REVIEW_IN_PROGRESS" || "IMPORT_IN_PROGRESS" || "IMPORT_COMPLETE" || "IMPORT_ROLLBACK_IN_PROGRESS" || "IMPORT_ROLLBACK_FAILED" || "IMPORT_ROLLBACK_COMPLETE",
  ],
};
```

The StackStatusFilter should not be a series of OR expressions, but a comma-separated list of statuses to include, like this:

```console
  StackStatusFilter: ['CREATE_COMPLETE', 'UPDATE_COMPLETE', 'IMPORT_COMPLETE'],
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudformation/command/ListStacksCommand/

**Comment by kuhe** [comment]
In each operation there is a generated syntax example and 0 or more hand-written examples.

In this case there is only the generated syntax example code, and it is meant to be copy-pastable as a starting point for writing an operation request. To help with that, it uses syntactically valid JavaScript so as not to raise any errors, including possible TypeScript errors, in the initial copy-paste. 

For structural syntax examples of enums, the `||` operator is used to enumerate values.
```js
{
 MyEnum: "A" || "B" || "C"
}
```

For structural syntax examples of lists, a JS array is used to contain a single example of the list member type. 

```js
{
  MyStringList: [ "STRING_VALUE" ]
}
```

Because our lists are homogeneous, and to save space, syntax examples for lists only contain one member. As you can now conclude, a list of enums is going to look like the example you found.

```js
{
  MyEnumList: [ "A" || "B" || "C" ]
}
```

For consistency, we are not planning to change this pattern.
