### ISSUE TITLE
Regression to number types with respect to SDKv2

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js-v3#5198]
### Describe the feature

This issue is very similar to #5181.

Apparently, the same problem applies to `number` types. In SDKv2, `number` types that are accidentally passed as `strings`, the SDK converts them to the right type silently. 

SDKv3 will not do the conversion, allowing the server call to fail because of mismatched types.

Example:

## SDKv2

```ts
  const codedeploy = new AWS.CodeDeploy({ region: 'eu-west-1' });

  const input: AWS.CodeDeploy.CreateDeploymentConfigInput = {
    deploymentConfigName: 'testtest',
    computePlatform: 'Lambda',
    trafficRoutingConfig: {
      type: "TimeBasedLinear",
      timeBasedLinear: {
        linearInterval: "1" as any, // The type says 'number' but I'm forcing strings here
        linearPercentage:"5" as any,
      },
    }
  };


  // Following call happily succeeds
  console.log(await codedeploy.createDeploymentConfig(input).promise());
```

## SDKv3

```ts
  const codedeploy = new CodeDeploy();

  const input: CreateDeploymentConfigCommandInput = {
    deploymentConfigName: 'testtest',
    computePlatform: 'Lambda',
    trafficRoutingConfig: {
      type: "TimeBasedLinear",
      timeBasedLinear: {
        linearInterval: "1" as any, // The type says 'number' but I'm forcing strings here
        linearPercentage:"5" as any,
      },
    }
  };

  await codedeploy.createDeploymentConfig(input);
```

The call fails with:

```
SerializationException: STRING_VALUE can not be converted to an Integer
```

### Use Case

Why does this matter to us? 

Same reason as in #5181, we allow users to drive SDK calls using arbitrary, user-controlled parameters that cannot be type checked. We are transparently migrating all SDKv2 calls to SDKv3 calls, and calls that used to work no longer work after the upgrade.

### Proposed Solution

Accept the same argument types as in SDKv2

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.409.0

### Environment details (OS name and version, etc.)

-

**Comment by kuhe** [comment]
we're not likely to implement this, because SDKs have a directive against doing most client side validation and type coercions. 

please convert the value at the SDK operation call site to its intended type.

**Comment by RanVaknin** [comment]
Hi @rix0rrr 
Just to add on top of what @kuhe said:

In the past versions of the AWS SDKs there were many customizations that were introduced over the years. The SDK organization as a whole has moved away from implementing customizations as they are not maintainable and instead, the newer SDKs are code generated directly from the API models of each AWS service and rely on the model to dictate the desired behavior.

Since CodeDeploy specifies `linearInterval` as an Integer, the SDK will be generated with that type:

>linearInterval
The number of minutes between each incremental traffic shift of a TimeBasedLinear deployment.
>
>Type: Integer

Unfortunately there is no plan to introduce similar behavior of this sort.

Thanks,
Ran
