### ISSUE TITLE
`PartNumberMarker` is string (not number) in `ListParts`

### ISSUE THREAD

**Issue by shirady** [aws/aws-sdk-js-v3#5199]
### Describe the issue

Hello,
I found a difference between `PartNumberMarker` in the 2 versions:
In AWS SDK V2 `PartNumberMarker` is integer
In AWS SDK V3 `PartNumberMarker` is string
When using an integer instead of a string results in an error:
> SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method

In my opinion, it is a confusing change - I would expect a variable named `PartNumberMarker` to be an integer.
I found [this issue](https://github.com/aws/aws-sdk-net/issues/447) (not in AWS SDK V3 of javascript) and this change might be a decision.

I'll share a code snippet:
```javascript
            res = await this.s3_sdkv3.listParts({
                Bucket: this.bucket,
                Key: params.key,
                UploadId: params.obj_id,
                MaxParts: params.max,
                PartNumberMarker: params.num_marker, // need to change to params.num_marker.toString() to align variable type
            });
```

Thanks,
Shira

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/ListPartsCommand/
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listParts-property

**Comment by RanVaknin** [comment]
Hi @shirady,

The v3 SDK is directly generated from the API model of each AWS service.

The S3 model [specifies](https://github.com/aws/aws-sdk-js-v3/blob/91e51ab99e58091068d1f4173ecf9f457db92df8/codegen/sdk-codegen/aws-models/s3.json#L26421)  `PartNumberMarker` as a string so the SDK is generated with that parameter as a string.

Since the type is correctly documented in our docs, and a change would be considered backwards incompatible, there is no plan to change it.

Sorry for the inconvenience.
Thanks,
Ran

**Comment by RanVaknin** [comment]
Hi @shirady ,

As far as I can tell this was not changed, as a change like this from an API standpoint would be backwards incompatible. 
The API requires that `PartNumberMarker` will be sent as a query parameter. Here is an example raw request from the S3 docs:

```ruby
GET /Key+?max-parts=MaxParts&part-number-marker=PartNumberMarker&uploadId=UploadId HTTP/1.1
Host: Bucket.s3.amazonaws.com
x-amz-request-payer: RequestPayer
x-amz-expected-bucket-owner: ExpectedBucketOwner
x-amz-server-side-encryption-customer-algorithm: SSECustomerAlgorithm
x-amz-server-side-encryption-customer-key: SSECustomerKey
x-amz-server-side-encryption-customer-key-MD5: SSECustomerKeyMD5
```

Since the field is sent via query parameter, it has to be a string type. Perhaps in v2 SDK the supplied integer was converted into a string silently. As I mentioned before the newer SDKs have moved away from customizations and are closely following the API model published by the service team. 

Thanks,
Ran~
