### ISSUE TITLE
Cannot Reach $response of Successful PutObject

### ISSUE THREAD

**Issue by shirady** [aws/aws-sdk-js-v3#5218]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello,
In AWS SDK v2 we could get the headers of a successful response, but I don't have this ability using AWS SDK V3.
For example, we could get the date header after `PutObject` by using `res.$response?.httpResponse.headers.date`, but in the response in AWS SDK v3 we don't have the `$response`.

Notes:
1) I saw in another SDK that it was already raised ([here](https://github.com/aws/aws-sdk-cpp/issues/1466)), but closed because the issue was idle.
2) I know from your API reference that we have headers, and specifically the Date header ([here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html)).

Thank you,
Shira

### SDK version number

@aws-sdk/client-s3@3.400.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v18.14.2

### Reproduction Steps

1) Create s3 client (S3).
2) Run PutObject.
3) Try to reach the date header and print it.

### Observed Behavior

In AWS SDK V3 we cannot reach `$response`

### Expected Behavior

Using `res.$response?.httpResponse.headers.date` we can reach the header date

### Possible Solution

Use the same solution you had in AWS SDK v2.

**Comment by RanVaknin** [comment]
HI @shirady ,

The S3 model [does not specify](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_ResponseElements) that the `Date` header should be in the response. If this existed in v2, again this is a customization we are not going to support in v3.
```console
{
  '$metadata': { <- protocol level headers
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: '"REDACTED"', <- modeled header
  ServerSideEncryption: 'AES256', <- modeled header
  VersionId: 'REDACTED' <- modeled header
}
```
You can gain access to the Date field via middleware:

```js
const client = new S3Client({})

client.middlewareStack.add(next => async(args) => {
    const response = await next(args);
    console.log(response.response.headers.date)
    return response
}, {step: 'build'})
```

Thanks,
Ran~

**Comment by shirady** [comment]
Hi @RanVaknin,
1) In the s3 model the APi of `putObject` there is an example and I can see the `Date` header (it's not related to the SDK version) under the title 'Sample Response: Versioning suspended':

> HTTP/1.1 100 Continue
> 
> HTTP/1.1 200 OK
> x-amz-id-2: LriYPLdmOdAiIfgSm/F1YsViT1LW94/xUQxMsF7xiEb1a0wiIOIxl+zbwZ163pt7
> x-amz-request-id: 0A49CE4060975EAC
> Date: Wed, 12 Oct 2009 17:50:00 GMT
> ETag: "1b2cf535f27731c974343645a3985328"
> Content-Length: 0
> Connection: close
> Server: AmazonS3

2) Thank you for the middleware code snippet, but it does not give me the same result as `res.$response?.httpResponse.headers.date`. Let's say that instead of logging the date header I would like to save it:
```javascript
let my_date;
const client = new S3Client({})

client.middlewareStack.add(next => async(args) => {
    const response = await next(args);
    my_date = response.response.headers.date
    return response
}, {step: 'build'})
```
But on every call to it will be written, and I don't know which response had this header, unlike the way it was in AWS SDK V2 when I knew exactly the response that I had and then reached the `Date` header:

```javascript
const res = await s3_sdkv2.putObject(params).promise();
const my_date = res.$response?.httpResponse.headers.date;
```
By the way, I'm aware that we can add middleware on specific commands, and I still have the same problem.

Thanks,
Shira

**Comment by RanVaknin** [comment]
Hi @shirady ,

>In the s3 model the APi of putObject there is an example and I can see the Date header (it's not related to the SDK version) under the title 'Sample Response: Versioning suspended':
HTTP/1.1 100 Continue

That is the _raw HTTP response_ you can expect when interacting with the API, not the SDK. Just like the response does not contain `Content-length` and `connection` it will not include the `Date` header because the _model_ doesn't specify it.  
Essentially, since the S3 service did not model those fields, they would not get deserialized by the SDK.
There is nothing stopping the service from returning arbitrary data that is not modeled. The model in this case is a contract saying "I'm guaranteed to get this data so I'm going to generate types and deserializers for it".

I'm not entirely sure about the use case here of relying on the server's processing time, I'm not sure why a client application would even need to know that - maybe that's why the S3 service did not model this field in the first place(?) 
If your use case is just to have an uploaded time stamp, can you not use a client side timestamp? 

```js
const res = await s3client.putObject(params);
const my_date = new Date(); 
```

Alternatively you can use something like axios to make an authenticated call to the S3 service and capture the raw response:

```js
import { SignatureV4 } from '@aws-sdk/signature-v4';
import axios from 'axios';
import { defaultProvider as defaultCredentialProvider } from "@aws-sdk/credential-provider-node";
import { Sha256 } from "@aws-crypto/sha256-js";

const signer = new SignatureV4({
  service: "s3",
  credentials: defaultCredentialProvider(),
  sha256: Sha256,
  region: "us-east-1"
});

async function putObjectViaHttp() {
  const payload = "hello-world";
  const host = "yourBucketName.s3.amazonaws.com";
  const objectKey = "keyName";
  const url = `https://${host}/${objectKey}`;

  const apiUrl = new URL(url);
  const request = {
    hostname: apiUrl.hostname,
    protocol: apiUrl.protocol,
    path: apiUrl.pathname,
    method: "PUT",
    headers: {
      "Content-Type": "text/plain",
      "host": apiUrl.hostname,
    },
    body: payload
  };

  const signedRequest = await signer.sign(request);

  try {
    const response = await axios({
      method: signedRequest.method,
      url: url,
      headers: signedRequest.headers,
      data: payload
    });
    console.log(response.headers.date);
  } catch (error) {
    console.log('Error uploading to S3:', error);
  }
}

putObjectViaHttp();
```

**Comment by shirady** [comment]
Hi @RanVaknin,
Thank you for the detailed answer.
I was wondering - if `$meta` is the protocol level header and `Date` is a header from the raw HTTP response, you could support it by adding it as a property in the `$meta`? (It is not changing the s3 model as I understand it).

**Comment by RanVaknin** [comment]
Hi @shirady ,

$meta is a mix of metadata provided by the SDK (attempts: 1) and the protocol level information (http status and request Id) which are guaranteed for every request. Since `Date` is not defined by the REST XML protocol we cannot assume it will exist on every AWS service that uses this protocol. 

I know this must be frustrating, but aside from those two workarounds I suggested, your only recourse is using your AWS console to open a support ticket with the S3 service team and ask them to include `Date` in their API model, and in the spirit of transparency I'd say this is unlikely to go through. 

If you need additional guidance on the two other workarounds I posted, feel free to open a discussion on our discussions page and tag me.  Since we are not planning on adding this customization in v3, Ill close this.

Thanks again,
Ran~
