### ISSUE TITLE
Firehose PutRecordCommand Sends Wrong Value (AWS SDK v3)

### ISSUE THREAD

**Issue by samuel-knutson** [aws/aws-sdk-js-v3#5235]
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am using the AWS SDK for JS to send data to Kinesis Data Firehose. When I use AWS SDK v2, it works fine: the `Data` value is Base64-encoded in the HTTP traffic. However, when I use AWS SDK v3 to send the same payload, the `Data` value is wrong in the HTTP traffic.

NOTE: I originally posted a question to [StackOverflow](https://stackoverflow.com/questions/77138035/how-to-send-data-to-kinesis-data-firehose-using-the-aws-javascript-sdk-v3) and [repost.aws](https://repost.aws/questions/QUfcKLCzLGRpa_nCQoeCJKGg/how-to-send-data-to-kinesis-data-firehose-using-the-aws-javascript-sdk-v3). However, after further research, I am starting to think it may be a bug.

### SDK version number

@aws-sdk/client-firehose@3.414.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome: 116.0.5845.188

### Reproduction Steps

Prerequisite: set up a Delivery Stream in Amazon Kinesis Data Firehose. My Delivery Stream points to an S3 bucket, but I don't think that is important.

AWS SDK v2 (I see expected `Data` value in the HTTP traffic):

```js
const AWS = require('aws-sdk');

// Full config not shown.
AWS.config.update({
  region: 'us-east-1'
});

const Firehose = new AWS.Firehose();
const params = {
  DeliveryStreamName: 'MY-STREAM-NAME',
  Record: {
    Data: JSON.stringify({
      key: "test",
      value: "hello world"
    }),
  },
};
    
Firehose.putRecord(params, () => {});
```

AWS SDK v3 (`Data` value is wrong in the HTTP traffic):

```js
import { FirehoseClient, PutRecordCommand } from "@aws-sdk/client-firehose";

// Full config not shown.
const config = {
  region: "us-east-1"
};

const client = new FirehoseClient(config);
const input = {
  DeliveryStreamName: "MY-STREAM-NAME",
  Record: {
    Data: JSON.stringify({
      key: "test",
      value: "hello world"
    })
  },
};

const command = new PutRecordCommand(input);
const response = await client.send(command);
console.log(response);
```

### Observed Behavior

Observed payload in the HTTP traffic for AWS SDK v3 is this:

```json
{
  "DeliveryStreamName": "MY-STREAM-NAME",
  "Record": {
    "Data": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  }
}
```

### Expected Behavior

This is what I see in the HTTP traffic for AWS SDK v2; I expected to see it for AWS SDK v3 as well:

```json
{
  "DeliveryStreamName": "MY-STREAM-NAME",
  "Record": {
    "Data": "eyJrZXkiOiJ0ZXN0IiwidmFsdWUiOiJoZWxsbyB3b3JsZCJ9"
  }
}
```

Where `eyJrZXkiOiJ0ZXN0IiwidmFsdWUiOiJoZWxsbyB3b3JsZCJ9` is the Base64-encoded, stringified version of my JSON payload.

**Comment by samuel-knutson** [comment]
Someone posted this solution on [my StackOverflow question](https://stackoverflow.com/questions/77138035/how-to-send-data-to-kinesis-data-firehose-using-the-aws-javascript-sdk-v3) that seems to work:

```js
Data: new TextEncoder().encode(JSON.stringify({key: "test", value: "hello world" }))
```

So it looks like the expected format of the `Data` value changed from v2 to v3. Is that intentional? This was not clear to me based on the documentation and examples I read, so I suggest you update those.

**Comment by RanVaknin** [comment]
Hi @samuel-knutson ,

The reason you are seeing a change in behavior between v2 and v3, is that v3 closely aligns with the service's API model that specifies that Data is a Blob. In v3, we generate this type as a Uint8Array. In v2 there are a lot of custom transformations and handwritten customizations, one of which is to encode that data field implicitly. 

In newer SDK major versions we have decided as an organization to avoid customizations as much as possible in order to avoid future feature-parity gaps (just like this), resulting in customers having to encode that payload themselves.

Textencoder is only used in browsers right now, for Node.js environments you can wrap your json string in a buffer and specify the encoding method:
```js
const buffer = Buffer.from(JSON.stringify({
    key: "test",
    value: "hello world"
  }), "base64")

const client = new FirehoseClient(config);
const input = {
  DeliveryStreamName: "MY-STREAM-NAME",
  Record: {
    Data: buffer
  },
};
```

I can see how this is confusing given that our v3 docs only specify "BLOB_VALUE" for data. I have created a [documentation issue](https://github.com/aws/aws-sdk-js-v3/issues/5240) trying to address this. 

Since it seems like you have been unblocked I feel like we can close this issue.

Thanks again,
Ran~
