### ISSUE TITLE
Allow DynamoDB key updates if key doesn't exist

### ISSUE THREAD

**Issue by cjoecker** [aws/aws-sdk-js-v3#5239]
### Describe the feature

If I have the fllowing object in dynamoDB:

```JSON
{
 "prop":{
  "a":1,
  "b":2
 },
}
```

and want to update `prop.a` using `UpdateItemCommand` with `SET prop.a = :propA`, there is no problem. 
But if `prop` does not exist in the JSON document, I get the error `An error occurred (ValidationException) when calling the UpdateItem operation: The document path provided in the update expression is invalid for update`.

I want to be able to upsert `prop.a` without getting an error.

The issue is described [here](https://stackoverflow.com/q/66776239/4934446)

### Use Case

I want to be able to update a nested key from a dynamo DB object without modifying the existing ones.

### Proposed Solution

The `sdk` should create the nested property on `SET` if it doesn't exist yet.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

3.417.0

### Environment details (OS name and version, etc.)

Node 18

**Comment by RanVaknin** [comment]
Hi @cjoecker ,

Thanks for raising the feature request. I can see how this feature can be useful, but unfortunately we cannot implement it.

The SDK cannot cover all bases of "if this error, then preform that action". As a matter of fact, the SDK tries to be non-deterministic when receiving errors.

This feature request should really be to the Dynamo service team, as they need to add service side support for it, and adopt model changes that would support this functionality. 

What you can do is open a support ticket through you AWS console and ask for it to be routed to the DynamoDB team. 
Since this feature request is not actionable by the SDK team, I'm inclined to close this. 

Thanks again,
Ran~

**Comment by cjoecker** [comment]
@RanVaknin thanks for your answer. Is there a way to submit the feature request to the DynamoDB team without having an AWS support plan? I don't want to subscribe to a support plan just for submitting the request.
