### ISSUE TITLE
Can't find documentation for migrating tests

### ISSUE THREAD

**Issue by klimkina** [aws/aws-sdk-js-v3#5339]
### Describe the issue

We migrated to node18 and v3 but can't find documentation on how to migrate existing tests for lambda code update.

### Links

REDACTED

**Comment by RanVaknin** [comment]
Hi @klimkina,

The package you were using ( https://github.com/dwyl/aws-sdk-mock), is not owned by our team, or even by AWS. We do not provide an SDK mocking library. You create any class that follows the same I/O of each client you are trying to mock and as long as the interface matches, you can successfully mock tests.
The SDK team does not provide documentation for general mocking techniques. 

Since you are an AWS employee, if you need additional assistance, you can reach out to the team internally.
Thanks,
Ran~
