### ISSUE TITLE
Update link to code example repo in Getting Started page

### ISSUE THREAD

**Issue by ypliu-AWS** [aws/aws-sdk-js-v3#5348]
### Describe the issue

In the [Getting Started page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/), the link to AWS Code Example Repository is pointing to the JS SDK v2 version of the example repo, but it should point to the JS SDK v3 example repo: https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/

**Comment by RanVaknin** [comment]
Hi @ypliu-AWS ,

Good catch, thank you! Adding to our backlog. 

All the best,
Ran~

**Comment by aBurmeseDev** [comment]
Hello, the link to Code Example Repository in [Getting Started page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/) has been updated to navigate to [Javascript SDK v3 code example repo](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code) instead of the previous link that pointed to the v2 repository. Closing this now.
