### ISSUE TITLE
client/rds DownloadDBLogFilePortion not returning Unicode

### ISSUE THREAD

**Issue by horrendo** [aws/aws-sdk-js-v3#5378]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This could very well be something I'm doing wrong but I have a csv logfile that contains unicode strings with accented characters. If I download the logfile from the AWS web portal, it shows the data correctly:

```
... ""title"": ""Vice-Président"", ""last_name"": ""L''Écuyer"", ...
```

If I retrieve the logfile using DownloadDBLogFilePortion, the unicode data gets garbled:

```
... ""title"": ""Vice-Pr�sident"", ""last_name"": ""L''�cuyer"", ...
```

### SDK version number

@aws-sdk/client-rds@3.429.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.1

### Reproduction Steps

```typescript
    const rdsClient = new RDSClient({});
    :
        const downloadLogInput: DownloadDBLogFilePortionCommandInput = {
            DBInstanceIdentifier: rdsInstance,
            LogFileName: 'error/postgresql.log.2023-10-17-17.csv',
            Marker: '0',
            NumberOfLines: 5000
        };
        let more = true;
        while (more) {
            const downloadLogOutput = await rdsClient.send(new DownloadDBLogFilePortionCommand(downloadLogInput));
            more = downloadLogOutput.AdditionalDataPending ?? false;
            downloadLogInput.Marker = downloadLogOutput.Marker;
            if (downloadLogOutput.LogFileData !== undefined) {
                const chunk = downloadLogOutput.LogFileData;
                if (chunk.includes('2023-10-17 17:01:05.770 UTC')) {
                    const lines = chunk.split(`\n`);
                    for (const line of lines) {
                        if (line.includes('2023-10-17 17:01:05.770 UTC')) {
                            console.log(line);
                        }
                    }
                    return;
                }
            }
        }
```

### Observed Behavior

Refer to "Describe the bug", above.

### Expected Behavior

Refer to "Describe the bug", above.

**Comment by aBurmeseDev** [comment]
Hi @horrendo - thanks for reaching out and sorry to hear you're running into an issue.

I attempted to reproduce this on my end but unfortunately, I'm not seeing this behavior. I have a few questions to narrow down the root cause:
- What are the size of the log files and do you happen to be running any VPN or firewall which could break the network connection during the data transmission? 
- Does it happen intermittently?  
- Can you run AWS CLI [command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/download-db-log-file-portion.html) and see if it returns as expected?
```
aws rds download-db-log-file-portion --db-instance-identifier my-db-instance --log-file-name my-log-file
```
Looking forward to hear back!
John

**Comment by horrendo** [comment]
Thanks for your response John.

Unfortunately I ran into a show stopping error using this API, so the unicode mangling was the least of my worries. The error was [a very old one](https://github.com/aws/aws-sdk/issues/20). When I opened an AWS support case the engineer claimed that the issue was being worked on, but as it was originally raised 6+ years ago, I very much doubt it. Anyway, I switched to use the [REST API](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/DownloadCompleteDBLogFile.html) and it's working fine and is way faster than fetching the log files in chunks.

So, I've kind of lost interest in seeing this issue solved, but I appreciate your response. If you work for AWS and have access to all RDS log files in us-east-1, I can point you at one of our instances that should help you reproduce the issue.

Cheers,

Steve

**Comment by aBurmeseDev** [comment]
Thank you for getting back, Steve! @horrendo 

Upon reviewing the issue you linked, I understand that this behavior is more of service-related issue rather than SDK and we don't have much control over service team decisions, unfortunately. However, I can dig around to see if there's any more to it and I'm happy to hear that switching to use REST API has been working out for you. 

If there's any SDK related issue going forward, please don't hesitate to reach out as we'd be more than happy to help.
Thanks,
John
