### ISSUE TITLE
Inconsistent documentation for 'TIMEOUT' on Pinpoint DeliveryStatus Enum

### ISSUE THREAD

**Issue by Velitheda** [aws/aws-sdk-js-v3#5385]
### Describe the issue

The `TIMEOUT` DeliveryStatus for Pinpoint is not present in the implementation itself for the enum, but it is still present in the documentation on the `MessageResult` page.

Can the documentation be updated to remove the `TIMEOUT` status on the `MessageResult` page?

### Links

The `DeliveryStatus` documentation page where the `TIMEOUT` status is not listed: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-pinpoint/Variable/DeliveryStatus/

The `MessageResult` documentation page where the `TIMEOUT` status for `DeliveryStatus` _is_ listed: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-pinpoint/Interface/MessageResult/

The implementation for the `DeliveryStatus` enum, where `TIMEOUT` is not listed: https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-pinpoint/src/models/models_0.ts#L7267-L7275

**Comment by RanVaknin** [comment]
Hi @Velitheda ,

Thanks for opening this documentation issue. 
Both the API model from which the SDK types and doc strings are directly owned by each AWS Service team. 
You can see the source documentation here 
In this case the Pinpoint service team probably removed/ changed the TIMEOUT value without removing the related documentation. 

Unfortunately as I mentioned the SDK is directly code-generated from that model and the SDK team cannot directly change the documentation. I have created a documentation request with the Pinpoint service team to update their docs.

Since this is not actionable by the SDK team, I'll go ahead and close this issue. 

Thanks again for letting us know!
All the best,
Ran~

`P103236994`
