### ISSUE TITLE
Special characters in S3 object name not handled in CopyObjectCommand

### ISSUE THREAD

**Issue by QAnders** [aws/aws-sdk-js-v3#5475]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When uploading a file to S3 containing a "special" character, for example a Swedish "Ö", you can read the file using `GetObjectCommand` without any issues, also `PutObjectCommand` works with Swedish "å", "ä" or "ö".

When using the `CopyObjectCommand` however we get an error thrown as:
```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at throwDefaultError (/home/anders/qip-lambda-invoice-routing/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /home/anders/qip-lambda-invoice-routing/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_CopyObjectCommandError (/home/anders/qip-lambda-invoice-routing/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3143:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/anders/qip-lambda-invoice-routing/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/anders/qip-lambda-invoice-routing/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /home/anders/qip-lambda-invoice-routing/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /home/anders/qip-lambda-invoice-routing/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

Doing a `encodeURIComponent()` on the `SourceKey` solves the error and the object is copied.

`CopyObjectCommand` should handle it the same way as `GetObjectCommand` and not requre an encoding.

### SDK version number

"@aws-sdk/client-s3": "^3.410.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.14.2

### Reproduction Steps

Store an object in an S3 Bucket with the filename `contains_å_ä_and_ö.xml`

Performa a `CopyObjectCommand`, copying the object to another file (or Bucket)

### Observed Behavior

Throws error `SignatureDoesNotMatch`

### Expected Behavior

For the object to be copied

**Comment by aBurmeseDev** [comment]
Hi @QAnders - thanks for reaching out and reporting this. 

I was able to reproduce and confirm that:
- this only occurs with `CopyObjectCommand` where `GetObjectCommand` and `PutObjectCommand` works as expected with the filename that contains characters such as "å", "ä" or "ö".
- workaround available by URL-endcoding `CopySource` with `encodeURIComponent()`
```ts
const input = {
    Bucket: "destinationBucket",
    CopySource: encodeURIComponent("/copyingBucket/contains_å_ä_and_ö.xml"),
    Key: "xmlcopy",
}
```

The reason this only being reproducible with `CopyObject` is because S3 requires `CopySource` to be URL encoded, where `GetObject` and `PutObject` doesn't use `CopySource` parameter. It's mentioned in the [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestParameters) as well: 
>[x-amz-copy-source](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestSyntax)
For objects not accessed through an access point, specify the name of the source bucket and the key of the source object, separated by a slash (/). For example, to copy the object reports/january.pdf from the bucket awsexamplebucket, use awsexamplebucket/reports/january.pdf. The value must be URL-encoded.

Hope that helps!
John
