### ISSUE TITLE
Add `ListManagementOptions` to the `SendBulkEmailCommand`

### ISSUE THREAD

**Issue by jeremybarbet** [aws/aws-sdk-js-v3#5495]
### Describe the feature

I was trying to use `ListManagementOptions` on the `SendBulkEmailCommand` command. Here is the documentation for the [option](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-sesv2/Interface/ListManagementOptions).

However, it's only supported by the `SendEmailCommand` command.

I then found about an old issue [here](https://github.com/aws/aws-sdk-net/issues/1795) that has been closed.

Any reconsideration on supporting `ListManagementOptions` for the bulk command?

### Use Case

Would be nice to have the same options than the `SendEmailCommand` command

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.451.0

### Environment details (OS name and version, etc.)

macOS 13.6.1 (22G313)

**Comment by RanVaknin** [comment]
Hi @jeremybarbet,

Thanks for opening the issue.  The SDK team cannot add this option because the SDK mirrors the API provided by the service team itself. If the service team doesn't add support for it service-side there will be no client side option to add it.

As the older issue you pointed out mentions, this was upstreamed to the SES service team before but they decided to not implement this.  I can see two separate issue for this: `P58495551` `P49903965` both were closed with this explanation: `"SES currently has no immediate plans to expand ListManagementOptions to SendBulkEmail. In the mean time, please use the SendEmail API."`

Since this is not actionable by the SDK team, my best suggestion to you would be to create a support ticket via the AWS console and ask to be routed to the SES team itself. Please mention those two internal ticket IDs so they can see there is lots of traction for this feature. You can also mention my internal alias `rvaknin` if they need a poc from the SDK Team.

Thanks again for taking the time to submit the request. 

Good luck,
Ran~

**Comment by jeremybarbet** [comment]
Sure thing, will do, thanks!
