### ISSUE TITLE
When using lib-dynamodb to retrieve Items, list attributes are shown as `{}` and are not completely listed

### ISSUE THREAD

**Issue by sohmc** [aws/aws-sdk-js-v3#5546]
### Describe the bug

I'm using the latest versions of lib-dynamodb and client-dynamodb for Javascript.  I have a DynamoDB table that has an Item that is as follows:

```json
{
    "Item": {
        "myPrimaryKey": {
            "S": "config"
        },
        "mySecondaryKey": {
            "S": "sports"
        },
        "configValues": {
            "SS": [
                "baseball",
                "basketball",
                "football"
            ]
        }
    }
}
```

I am running the following code, based on the documentation presented in the [npm repository](https://www.npmjs.com/package/@aws-sdk/lib-dynamodb):

```javascript
const { DynamoDB } = require('@aws-sdk/client-dynamodb');
const client = new DynamoDB({ region: 'us-east-1' });

const { DynamoDBDocument, GetCommand } = require('@aws-sdk/lib-dynamodb');
const ddbDocClient = DynamoDBDocument.from(client);

const params = {
  'TableName': 'mySportBookTable',
  'Key': {
    'myPrimaryKey': 'config',
    'mySecondaryKey': 'sports',
  },
};

const data = await ddbDocClient.send(new GetCommand(params));
console.log('sendDocClientCommand -- Received data: ', JSON.stringify(data));
```

When inspecting `data`, the nested attribute `configValues` is represented as `{}` and is empty.  However, when I run the equivalent CLI command, the data is properly shown.

```
$ aws dynamodb get-item \
    --table-name "mySportBookTable" \
    --key '{"myPrimaryKey":{"S":"config"},"mySecondaryKey":{"S":"sports"}}'
{
    "Item": {
        "myPrimaryKey": {
            "S": "config"
        },
        "mySecondaryKey": {
            "S": "sports"
        },
        "configValues": {
            "SS": [
                "baseball",
                "basketball",
                "football"
            ]
        }
    }
}
```

This could be a simple configuration option but I can't seem to find any documentation that expands nested lists.  In fact, all documentation I've come across states that unless `ProjectionAttributes` is provided, all values are returned.

### Expected Behavior

I expect the DynamoDB client to return an JSON object of the DynamoDB Item associated with the provided key and sort key with all attributes and their values, including lists unmarshalled into an array.

### Current Behavior

```
sendDocClientCommand -- Received data:  
{
    "$metadata": {
        "httpStatusCode": 200,
        "requestId": "--removed--",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "Item": {
        "myPrimaryKey": "config",
        "configValues": {},
        "mySecondaryKey": "sports"
    }
}
```

### Reproduction Steps

```javascript
const { DynamoDB } = require('@aws-sdk/client-dynamodb');
const client = new DynamoDB({ region: 'us-east-1' });

const { DynamoDBDocument, GetCommand } = require('@aws-sdk/lib-dynamodb');
const ddbDocClient = DynamoDBDocument.from(client);

const params = {
  'TableName': 'mySportBookTable',
  'Key': {
    'myPrimaryKey': 'config',
    'mySecondaryKey': 'sports',
  },
};

const data = await ddbDocClient.send(new GetCommand(params));
console.log('sendDocClientCommand -- Received data: ', JSON.stringify(data));
```

### Additional Information/Context

Please note that this is example data.

### SDK version used

3.454.0

### Environment details (OS name and version, etc.)

nodejs 18.x

**Comment by aBurmeseDev** [comment]
Hi @sohmc - thanks for reaching out and apologies for not responding it sooner. 

If I understand this correctly from your initial report, you were using `GetCommand` from `lib-dynamodb`, JSON.stringify() the output data but getting empty `configValues` whereas when you ran AWS CLI `get-item` command, you get the expected output. 

A few things to address from your initial report and the following comment:
- `get-item` CLI command uses [DynamoDB API ](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html) which translates to `GetItemCommand` from JavaScript SDK `client-dynamodb` and I noticed that you get the expected output by `GetItemCommand` in your following comment. 
- Using `lib-dynamodb` is just to simplify working with items in DynamoDB by abstracting away the notion of attribute values. This abstraction annotates native JavaScript types supplied as input parameters, as well as converts annotated response data to native JavaScript types.
- The Set output data you see returns in unmarshalled into plain JavaScript objects which cannot be expressed via JSON.stringify, as you also figured that out. This is actually mentioned in our [documentation](https://github.com/aws/aws-sdk-js-v3/tree/main/lib/lib-dynamodb#marshalling-input-and-unmarshalling-response-data) as follows:
<h2 tabindex="-1" dir="auto" data-react-autofocus="true" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--borderColor-muted, var(--color-border-muted)); color: rgb(240, 243, 246); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(10, 12, 16); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Marshalling Input and Unmarshalling Response Data</h2><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(240, 243, 246); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(10, 12, 16); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The document client affords developers the use of native JavaScript types instead of<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">AttributeValue</code>s to simplify the JavaScript development experience with Amazon DynamoDB. JavaScript objects passed in as parameters are marshalled into<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">AttributeValue</code><span> </span>shapes required by Amazon DynamoDB. Responses from DynamoDB are unmarshalled into plain JavaScript objects by the<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">DocumentClient</code>. The<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">DocumentClient</code><span> </span>does not accept<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">AttributeValue</code>s in favor of native JavaScript types.</p>

To recap, this's expected behavior for `GetCommand` with `lib-dynamodb` to return Set because responses from DynamoDB are unmarshalled into plain JavaScript objects by the DocumentClient (lib-dynamodb), mentioned above. Since there's no Array on DynamoDB AttributeValue, and there's only `SS` of which the corresponding native JS type would be `Set<String>`.  Refer to the table below.


|          JavaScript Type           | DynamoDB AttributeValue |
| :--------------------------------: | ----------------------- |
|               String               | S                       |
|   Number / BigInt / NumberValue    | N                       |
|              Boolean               | BOOL                    |
|                null                | NULL                    |
|               Array                | L                       |
|               Object               | M                       |
|    Set\<Uint8Array, Blob, ...\>    | BS                      |
| Set\<Number, BigInt, NumberValue\> | NS                      |
|           Set\<String\>            | SS                      |
| Uint8Array, Buffer, File, Blob...  | B                       |

I hope that all makes sense. If you have any other questions, please do not hesitate to reach out. 
Best,
John

**Comment by sohmc** [comment]
Thanks for the update!  It makes sense now, but didn't about two weeks ago.  I'll go ahead and close the issue.
