### ISSUE TITLE
@aws-sdk/client-s3 region redirect throws exception in random cases.

### ISSUE THREAD

**Issue by ryan65** [aws/aws-sdk-js-v3#5554]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

we had an exception in one of our CI tests and reason is a call using a client that was initialized with followRegionRedirects:true.
seems like the returned error did not contain $metadata and in SDK middleware-sdk-s3 source code -region_redirect-middleware.js this is not checked.
line 13
below is the problematic code. 
```js
catch (err) {
            if (clientConfig.followRegionRedirects &&
                **err.$metadata.httpStatusCode** === 301) {
                try {
```

Note this is not reproducible and I cant say why there was no $metadata this time but seems that it can happen occasionally 
**Below are the logs from our CI** 
```
{
14:31:42 common-library_1  |   clientName: 'S3Client',
14:31:42 common-library_1  |   commandName: 'ListObjectsV2Command',
14:31:42 common-library_1  |   input: { Bucket: **removed bucket name for security reasons**, Prefix: 'test-s3-upload' },
14:31:42 common-library_1  |   error: TypeError: Cannot read properties of undefined (reading 'httpStatusCode')
14:31:42 common-library_1  |       at /opt/common.library/s3/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:13:31
14:31:42 common-library_1  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
14:31:42 common-library_1  |       at async /opt/common.library/s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
14:31:42 common-library_1  |   metadata: undefined
```
### SDK version number

@aws-sdk/client-s3":"3.465.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NA

### Reproduction Steps

cant reproduce. happened once.

### Observed Behavior

exception due to missiing $metadata

### Expected Behavior

code should handle such a case or make sure there is always metadata.

### Possible Solution

Code must handle cases with missing metadata.

### Additional Information/Context

None.

**Comment by RanVaknin** [comment]
Hi @ryan65 ,

Thanks for opening the issue and letting us know. This is an interesting issue you are seeing. By default, every response should have a `httpStatusCode`. 

We will have someone look into it. 
Thanks,
Ran~

**Comment by ryan65** [comment]
> Hi @ryan65 ,
> 
> Thanks for opening the issue and letting us know. This is an interesting issue you are seeing. By default, every response should have a `httpStatusCode`.
> 
> We will have someone look into it. Thanks, Ran~

Great thanks. 
Indeed I noticed that the feature support followRegionRedirects , is a little half baked itself. 
there is another issue related to the logs , 
this line in region-redirect-middleware. always logs a debug message and if logger does not have debug it crashes , unlike ec2 client or ecs client which checks first to see if debug dexists on logger.
Below is the line: 
(_a = context.logger) === null || _a === void 0 ? void 0 : _a.debug(`Redirecting from ${await clientConfig.region()} to ${actualRegion}`);

**Comment by ryan65** [comment]
Hi Again . 
I did some debugging , added a middleware to catch error before it returned to the region-redirect.
The error is thrown from 
@smithy/config-resolver/dist-cjs/regionConfig/config.js:10:15)
and since its a normal error , the it wont have $metadata or anything therefore the crash.
Not sure why it happens only in certain environments probably related to some env  name expected , but still is not documented and not quite consistent. redirect should work regardless IMHO.

Thanks.
Seem below the logged error from my middleware. 
Hope this will help . 

 Error, {"stack":"Error: Region is missing\n    at default (/opt/common.library/s3/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10:15)\n    at /opt/common.library/s3/node_modules/@smithy/node-config-provider/dist-cjs/fromStatic.js:6:83\n    at /opt/common.library/s3/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async coalesceProvider (/opt/common.library/s3/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)\n    at async /opt/common.library/s3/node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28\n    at async region (/opt/common.library/s3/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:17:36)\n    at async /opt/common.library/s3/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:6:32\n    at async /opt/common.library/s3/lib/s3-svc-v3.js:77:35\n    at async /opt/common.library/s3/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20\n    at async /opt/common.library/s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26\n    at async S3._sendCommandAsync (/opt/common.library/s3/lib/s3-svc-v3.js:147:14)\n    at async S3.listObjects (/opt/common.library/s3/lib/s3-svc-v3.js:492:26)","message":"Region is missing"}

**Comment by ryan65** [comment]
BTW , I must say that I dont understand why the logic in the first place is to catch an exception and then change the region according to the response data. if a client is not configured with a region , it should just resolve the region in advance and then call the request. the logic of extracting data from the failed request is strange I think,

**Comment by RanVaknin** [comment]
Hi @ryan65 

>BTW , I must say that I dont understand why the logic in the first place is to catch an exception and then change the context region and according to the headers returned in the error and then perform the call again. if a client is not configured with a region , it should just resolve the region in advance and then call the request. the logic of extracting data from the failed request is strange I think , without causing any failure in advance.

The SDK clients are designed to "not know" which region is needed. Just like when using the API directly, a user would need to know the region in which their bucket is in prior to making a request to that bucket. When you are making a request to a bucket in the wrong region, S3 should return a 301 with the correct region and when `followRegionRedirects` is enabled, the SDK should make a subsequent request to that region specified in the initial failed response. This functionality of making an additional request is [documented](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-middleware-sdk-s3/Interface/S3InputConfig/).

What you are suggesting of knowing the region in advance is not possible since the SDK clients are clients, and do not have any upstream knowledge of where buckets live. The SDK builds the request URL based on the user input, the host in the URL contains the user provided region.

This new feature that you have found some sharp edges with is a very recent implementation that mirrors a functionality that existed in v2 and we introduced again in v3 after many customer requests. 

I have assigned @siddsriv and we have determined that fixing this feature is standard priority, which means that there is no ETA on a fix, but unless there are any higher priority issues this should be getting looked at right after. The workaround here is to keep using the SDK the way its intended, where you specify the correct region ahead of time.

Thanks,
Ran~

**Comment by RanVaknin** [comment]
HI @ryan65 ,

By looking at the error stack trace I can see that your CI environment that is failing is throwing a very clear error:
>","message":"Region is missing"}

This means to me that the environment in which you are running this SDK code is not getting configured with an environment properly. Probably something you migrated from v2, but didn't make the necessary changes in by explicitly setting a region. 

This is a client side validation error, and that explains why the service doesnt come back with the expected 301 error with the redirection instructions. 

The changes we are about to make will just throw a sensible error, but it would not follow any redirect if you didnt provide a region to get past this validation error. 

Thanks,
Ran~

**Comment by ryan65** [comment]
> HI @ryan65 ,
> 
> By looking at the error stack trace I can see that your CI environment that is failing is throwing a very clear error:
> 
> > ","message":"Region is missing"}
> 
> This means to me that the environment in which you are running this SDK code is not getting configured with an region properly. Probably something you migrated from v2, but didn't make the necessary changes in by explicitly setting a region.
> 
> This is a client side validation error, and that explains why the service doesnt come back with the expected 301 error with the redirection instructions.
> 
> The changes we are about to make will just throw a sensible error, but it would not follow any redirect if you didnt provide a region to get past this validation error.
> 
> Thanks, Ran~

@RanVaknin 
but this client side validation did not exist in V2. Its is exactly the same environment we had with V2 and V2 worked. so this is definitely a break from V2.
What exactly is missing in the environment and V3 expects and V2 didnt and why is this relevant only to redirect. I mean s3 works well with region on this environment so what is so special with the redirect that it throws an Error ?
Thanks.

**Comment by RanVaknin** [comment]
Hi @ryan65 ,

I understand that this is frustrating, however changes between major versions are inherently breaking.

A region is required for almost all AWS services in order to 1. direct the request to the correct AWS partition and 2. to sign the request correctly so it will get validated with the service itself.

S3's legacy implementation supported the global endpoint - ie not having to provide a region at all. This is still supported but modern bucket creation is usually done in a regional manner. Because of this, the SDK requires a region for every service client, not just S3. 

>What exactly is missing in the environment ? is it the AWS_REGION and if so what does it expect it to be. I mean I cant set it to a specific region , since I want it to work with different buckets on different regions.

I think there might be a misunderstanding here. If your buckets are regional, meaning you have bucket A in us-east-2 and bucket B in us-west-1, and you didn't specify a region, the v2 SDK will use whichever region you have provided. 
It will be provided in your `AWS_REGION` env variable, or your config file, or if it's lambda it will be tied to a role, or it will use the default region which is us-east-1.  A region will have to come from _somewhere_. 

The v2 SDK implicitly redirected the failed requests "under the hood" for you making it seem like you didnt specify a region and the SDK just "figured it out". This comes at a cost, because requests are retried you are making 2 requests instead of 1. This is a behavior that should not be transparent as there are real monetary implications associated with it especially with large scale applications. JS v3 has that same functionality but it requires you to explicitly turn on the `followRegionRedirects` so that added cost is intentional.

If your architecture relies on a redirects to happen (like it did implicitly in v2) you can specify **any region**, this is covered in our [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html). This will cause the SDK to make a request, if the region is wrong it will fail and then redirect to the correct endpoint provided in the response from S3 just like it did in v2. 

Thanks,
Ran

**Comment by ryan65** [comment]
> Hi @ryan65 ,
> 
> I understand that this is frustrating, however changes between major versions are inherently breaking.
> 
> A region is required for almost all AWS services in order to 1. direct the request to the correct AWS partition and 2. to sign the request correctly so it will get validated with the service itself.
> 
> S3's legacy implementation supported the global endpoint - ie not having to provide a region at all. This is still supported but modern bucket creation is usually done in a regional manner. Because of this, the SDK requires a region for every service client, not just S3.
> 
> > What exactly is missing in the environment ? is it the AWS_REGION and if so what does it expect it to be. I mean I cant set it to a specific region , since I want it to work with different buckets on different regions.
> 
> I think there might be a misunderstanding here. If your buckets are regional, meaning you have bucket A in us-east-2 and bucket B in us-west-1, and you didn't specify a region, the v2 SDK will use whichever region you have provided. It will be provided in your `AWS_REGION` env variable, or your config file, or if it's lambda it will be tied to a role, or it will use the default region which is us-east-1. A region will have to come from _somewhere_.
> 
> The v2 SDK implicitly redirected the failed requests "under the hood" for you making it seem like you didnt specify a region and the SDK just "figured it out". This comes at a cost, because requests are retried you are making 2 requests instead of 1. This is a behavior that should not be transparent as there are real monetary implications associated with it especially with large scale applications. JS v3 has that same functionality but it requires you to explicitly turn on the `followRegionRedirects` so that added cost is intentional.
> 
> If your architecture relies on a redirects to happen (like it did implicitly in v2) you can specify **any region**, this is covered in our [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html). This will cause the SDK to make a request, if the region is wrong it will fail and then redirect to the correct endpoint provided in the response from S3 just like it did in v2.
> 
> Thanks, Ran

Hi Ran
Thanks a lot for the clarification. 
No , our code does not rely on redirection and in most cases we have the region in advance, this is just extra protection in the rare cases where we don't , and where latency is less critical.
That said , its clearer now and I see that all I have to do is provide any region as default in the client initialization,  and that is no problem. 
I see that now after adding a default region (different from the actual bucket)  the tests work , so I know that the functionality will work and all is good.

Thanks alot for your help.

**Comment by RanVaknin** [comment]
Anytime 👍  Thanks for reaching out.
