### ISSUE TITLE
OutputKey parameter in StartMedicalScribeJob.

### ISSUE THREAD

**Issue by sudoadarsh** [aws/aws-sdk-js-v3#5560]
### Describe the feature

**OutputKey** parameter in **StartMedicalScribeJob** API to specify the output folder path for the medical transcription.

### Use Case

To implement proper structure for the medical transcriptions in the S3 bucket.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3.x

### Environment details (OS name and version, etc.)

N/A, Node 20+

**Comment by RanVaknin** [comment]
Hi @sudoadarsh ,

Thanks for reaching out.
What you are asking for is a feature request for the Transcribe service itself. The SDK team cannot add server side functionality that allows for this parameter. 

I have created a feature request with the AWS Transcribe Service team on your behalf (ticket ID `V1156019221`), but since this feature on github is not actionable by the SDK team Im going to close it.

Thanks again,
Ran~
