### ISSUE TITLE
Search for package name instead of package commands

### ISSUE THREAD

**Issue by dil-jofla** [aws/aws-sdk-js-v3#5581]
### Describe the issue

If I search for CodePipeline  in the search bar I would like to go to the package view instead of get a paginated list of every command. I have never been able to use your search bar functionality as you intended and I'm sure I must not be the only one

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/codepipeline/

**Comment by aBurmeseDev** [comment]
Hi @dil-jofla - thanks for reaching out and sharing feedback as we're always looking to improve our docs.

Our current search works in a way where if you search for a client package CodePipeline (for example), it outputs a list of every client method/operation of that client because sometimes users might be searching for specific command of a client instead of client itself.

For scenario like this where you just want to bring up client package view quickly, I would suggest using left navigation of Services list or `cmd/ctrl + F` the client name on the home page. 

Again we do appreciate your feedback and will take it into consideration in our future documentation improvements.
Best,
John
