### ISSUE TITLE
Update valid values for BackupType parameter in ListBackupsCommand - Dynamo client

### ISSUE THREAD

**Issue by diavrank** [aws/aws-sdk-js-v3#5601]
### Describe the issue

Currently it says:
BackupType: "USER" || "SYSTEM" || "AWS_BACKUP" || "ALL",

It should be:
BackupType: "USER" || "SYSTEM" || "ALL",

As it says in the documentation:

The backups from the table specified by BackupType are listed.

Where BackupType can be:

USER - On-demand backup created by you. (The default setting if no other backup types are specified.)
SYSTEM - On-demand backup automatically created by DynamoDB.
ALL - All types of on-demand backups (USER and SYSTEM).

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/dynamodb/command/ListBackupsCommand/

**Comment by kuhe** [comment]
It says `AWS_BACKUP` in the [docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ListBackups.html).

At any rate, we can't update this because it comes from an API model managed by the service teams, and removing an enum value may be breaking for other SDK languages.

**Comment by aBurmeseDev** [comment]
Hi @diavrank - thanks for reaching out. 

As mentioned above, our SDK docs are generated upstream by service API models as you can find the same list of `BackupType` in the service [docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ListBackups.html) as well as in the AWS CLI [docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dynamodb/list-backups.html). Any changes to those docs will have to be made by service team and changes to SDK will have to be considered cross-SDK since we like to keep consistent across different SDKs. 

Additionally, I think `AWS_BACKUP` is a valid "possible values" simply because it's one of the backup options you could use for DynamoDB, ref [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/backuprestore_HowItWorksAWS.html).

Hope that makes sense and if you're running into any issue, please feel free to reach out again!
Best,
John

**Comment by diavrank** [comment]
@aBurmeseDev thanks for the clarification, I got confused because when I wanted to filter by `AWS_BACKUP` and use the `ListBackupsCommand`, it didn't get the backups of the dynamodb table. Some minutes after I realized that I had to use the `ListBackupJobsCommand` instead. For me it was a little confusing because in the code example shows this:

![image](https://github.com/aws/aws-sdk-js-v3/assets/39581375/94f3f205-ea07-4984-8fa0-716f5a7310c6)

And in the parameters section, the `AWS_BACKUP` type doesn't appear:

![image](https://github.com/aws/aws-sdk-js-v3/assets/39581375/caf9e951-0f02-4f9e-886b-3ba33879e1cf)

**Comment by diavrank** [comment]
I will close this issue since it seems that this is managed by the service teams but feel free to reopen if you consider that it needs to be fixed.
