### ISSUE TITLE
ThrottlingException for Transcribe

### ISSUE THREAD

**Issue by ftr-lwilson** [aws/aws-sdk-js-v3#5610]
### Describe the feature

I've managed to get the Transcribe to throw ThrottlingException a few times now, but it doesn't seem like there is an easy way to check for this exception. I notice a few of the other AWS clients export this particular exception so I was wondering if Transcribe could do the same thing.

### Use Case

I want to be able to catch the exception, identify it and handle it appropriately by backing off and retrying. E.g.
```TypeScript
try {
  await someTranscribeRequest()
} catch (error) {
  if (error instanceof ThrottlingException) {
    backOffAndRetry()
  } else {
    throw error
  }
}  
```

### Proposed Solution

Implement and export `ThrottlingException` for the Transcribe client.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.459.0

### Environment details (OS name and version, etc.)

Mac Sonoma, Node 18

**Comment by RanVaknin** [comment]
Hi @ftr-lwilson ,

`ThrottlingException` is a base level exception that most services can respond with.  This is modeled in Smithy:

```js
import { ThrottlingException } from '@smithy/service-error-classification';
```

Thanks,
Ran~

**Comment by ftr-lwilson** [comment]
> Hi @ftr-lwilson ,
> 
> `ThrottlingException` is a base level exception that most services can respond with. This is modeled in Smithy:
> 
> ```js
> import { ThrottlingException } from '@smithy/service-error-classification';
> ```
> 
> Thanks, Ran~


Thanks @RanVaknin for your speedy response! I've just tried this, but it seems that package doesn't export the exception either. I get the following error:

```
TS2305: Module "@smithy/service-error-classification" has no exported member ThrottlingException
````

**Comment by RanVaknin** [comment]
Hi @ftr-lwilson ,

Thanks for the follow up. I just ran this myself and see you are right. 

>I notice a few of the other AWS clients export this particular exception so I was wondering if Transcribe could do the same thing.

This is correct and should be the best case scenario. The SDK is code generated directly from the API model of each service. In this case transcribe does not define `ThrottlingException` so the SDK doesn't generate a type for this client.

Unfortunately this would have to be solved upstream with the trasncribe service itself.

As a workaround, you should be able to use error.name === "ThrottlingException" safely. We are considering removing the `instanceof` recommendation of error handling since a lot of the services do not define many of the base exceptions and this is a common issue we are seeing. 

Thanks,
Ran~

**Comment by ftr-lwilson** [comment]
Okay I see. I will use your suggested workaround, thank you!

I do notice that `@smithy/service-error-classification` exports a function called `isThrottlingError`, which appears to check for 429 codes. Would this work for my usecase?
