### ISSUE TITLE
`@aws-sdk/types` stuck at version `3.468.0`

### ISSUE THREAD

**Issue by garysassano** [aws/aws-sdk-js-v3#5631]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Not sure if it's normal that it's not aligned with current SDK version (`3.484.0`).

### SDK version number

@aws-sdk/types@3.468.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.16.0

### Reproduction Steps

see above

### Observed Behavior

see above

### Expected Behavior

see above

**Comment by RanVaknin** [comment]
Hi @garysassano,

I'm not sure what you mean by "stuck"? The packages are updated individually, so not all them would have the same version. Additionally, we recently moved a lot of the core packages to `@smithy` namespace. So there might have been updates added to [`@smithy/types` ](https://github.com/smithy-lang/smithy-typescript/tree/main/packages/types).

Are you running into a specific issue with the version?

Thanks,
Ran~

**Comment by garysassano** [comment]
I've always assumed that the SDK modules would be updated in bulk, and that this was an [use case for syncpack](https://jamiemason.github.io/syncpack/examples/fix-aws-sdk-version-mismatch/).

**Comment by RanVaknin** [comment]
Hi @garysassano ,

>I've always assumed that the SDK modules would be updated in bulk,

This is not the case. The gaps in minor version tags is because our central release system only updates modules that have changes in them, and assigns the current "workspace" (currently set to 3.484.0) version to them. So there would be an incremental bump, instead whenever a module changes, it will get the current workspace version.

As far as Syncpack goes,  I have never used it firsthand, but based on the docs it seems like it helps align minor version of _the same module_ across multiple `package.json` files. So if your project has multiple copies of lets say `@aws-sdk/client-s3` it would help make sure all of your package.json files have the same pinned minor version of this. 

Their explanation here, is incorrect:
>1. Add a pinned version group
Match all dependencies whose name starts with @aws-sdk/.
Mark the version as being pinned to 3.272.0 in this case.

My suggestion would be to use `@aws-sdk/pacakge-name@latest` and let npm/yarn resolve the dependency tree on its own. 

Thanks,
Ran~

**Comment by garysassano** [comment]
>As far as Syncpack goes, I have never used it firsthand, but based on the docs it seems like it helps align minor version of the same module across multiple package.json files.

What Syncpack actually does in this case is pinning all deps that match a specified pattern to the same version. This obviously assumes that the same version exists for all matched deps. However, as I've just learned, this assumption of universal version doesn't always hold true.

**Comment by RanVaknin** [comment]
Hi @garysassano ,

Thanks for the clarification. If anything else comes up feel free to open a new issue.

All the best,
Ran~
