### ISSUE TITLE
Publish an additional single "monolith" package with all SDK v3 clients

### ISSUE THREAD

**Issue by cogwirrel** [aws/aws-sdk-js-v3#5646]
### Describe the feature

It would be great to have the option for the entire SDK to be installed as a single dependency (similarly to the v2 SDK), eg:

```json
"dependencies": {
  "@aws-sdk/all": "^3.0.0"
}
```

There are many pros/cons of a monolith vs modular packages, with compelling arguments on both sides, however it would be great if consumers of the SDK could make that choice based on their specific use case (even if the default recommended approach remains the modular one).

### Use Case

Some developers may wish to optimise for developer experience over performance/bundle-size, and a monolith provides a few developer experience improvements over modular packages:

* No need to add new dependencies when using a new service - the SDK client is already there so you can start writing the code immediately without installing another package
* It's easier to upgrade the SDK as there's only one version to bump
* No issues to debug when versions of SDK packages are incompatible with one another which appears to be a gotcha in the community, for example:
  *  #5252 
  *  #5080
  *  #5030

### Other Information

The [CDK monolithic packaging RFC](https://github.com/aws/aws-cdk-rfcs/blob/main/text/0006-monolothic-packaging.md) is an interesting read for what motivated CDK to move to a single package. While a lot of it doesn't apply to the SDK it's interesting to read the pros/cons they considered.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3

### Environment details (OS name and version, etc.)

OSX

**Comment by RanVaknin** [comment]
Hi @cogwirrel,

At this moment the SDK team does not have a plan to publish a monolith. The idea behind launching v3 is to move away from the monolith architecture as modularization is a more modern approach for JS, it allows for tree-shaking and works better with bundlers.

I will raise this with the rest of the team to see if there is something else we can do to address the pain points you have raised.
One workaround I can think of is for you to do the following:
1. create a node project
2. Write a script to clone the aws/aws-sdk-js-v3 repository, parse through the clients' directories, and extract the names and versions of all the SDK clients.
3. Your script then should update the `package.json` of your project so that all the dependencies are up to date. 

Once your `package.json` is updated with all the required SDK client packages, running `npm install` in your project will install all these dependencies in one go.

Thanks,
Ran~

**Comment by cogwirrel** [comment]
Thanks! Would certainly be open to other ways to provide a similar developer experience to a monolith if your team would rather avoid publishing one alongside the individual modules! 😄

The script idea sounds interesting - a bit of overhead to maintain vs importing a single dependency but could make life a bit easier, eg re-running the script to update the sdk in a single action :)

**Comment by RanVaknin** [comment]
Hi @cogwirrel ,

After reviewing this from the team I can confirm that we don't have plans to introduce a monolith. We explored other solutions of putting all clients and types in the same namespace but there would be collisions. 
Im going to close this for now, if this comes up again in the future we can re-assess. 

Thanks again for taking the time to submit a feature request.
All the best,
Ran~
