### ISSUE TITLE
Property 'ReadableStream' doesn't exist (Production environment ONLY)

### ISSUE THREAD

**Issue by Joshandrews43** [aws/aws-sdk-js-v3#5649]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The following code works on a react native simulator, as well as with my `expo-dev-client`, but once I upload a build to testflight or the google play store for a production beta, I get the following error when trying to upload any asset: 

`Property 'ReadableStream' doesn't exist` from the `isStreamingPayload ` (found in sentry, don't have much more info than that).

I've tried polyfilling `ReadableStream` with `import 'web-streams-polyfill/ponyfill';` at the entry point of my app, but no luck. I have also tried changing it to a buffer, but that did not work either as people upload 1+minute long videos for my app and it crashed it. 

```
 const awsUpload = async (uri: string, path: string) => {
    return fetch(uri)
      .then((data) => data.blob())
      .then(async (blob) => {
        const command = new PutObjectCommand({
          Bucket: 'images',
          Key: path,
          Body: blob,
        });

        const { url } = await s3Client.send(command);
        return url;
      });
  };
```

### SDK version number

"@aws-sdk/client-s3": "^3.485.0"

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

v16.13.1 locally, 18.18.0 on physical device

### Reproduction Steps

```
 const awsUpload = async (uri: string, path: string) => {
    return fetch(uri)
      .then((data) => data.blob())
      .then(async (blob) => {
        const command = new PutObjectCommand({
          Bucket: 'images',
          Key: path,
          Body: blob,
        });

        const { url } = await s3Client.send(command);
        return url;
      });
  };
```

### Observed Behavior

Error thrown  only in production

### Expected Behavior

The image should go through correctly

### Possible Solution

Looking at other docs, I am going to downgrade to the old `aws-sdk` package and see if that works.

**Comment by aBurmeseDev** [comment]
Hi @Joshandrews43 - thanks for reaching out. 

I haven't had a lot of experiences around React Native with JS SDK but upon doing quick research, there seems to be some issues around react native dependencies related to the error you're getting. I'm curious to which react dependencies you've installed or imported. Since you mentioned [web-streams-polyfill](https://www.npmjs.com/package/web-streams-polyfill), I would assume that you've also installed `npm i react-native-url-polyfill react-native-get-random-values` and imported them?

```
import "react-native-get-random-values";
import "react-native-url-polyfill/auto";
```

I'm trying to narrow down root causes before trying to reproduce. I would really appreciate if you could share your react component as well.

One last thing, can you confirm that you're able to successfully upload s3 files from your local and this error only occurs when you upload a build to testflight or the google play store for a production beta?

Best,
John
