### ISSUE TITLE
Indicate wrong input type instead of unhelpful generic error

### ISSUE THREAD

**Issue by bernardodesousa** [aws/aws-sdk-js-v3#5661]
### Describe the feature

It would be nice to have a "wrong input type" error, instead of the current "TypeError: Cannot read property 'byteLength' of undefined" when providing a string instead of a Uint8Array as the Passphrase parameter to the ACMClient.ExportCertificateCommand.

### Use Case

A helpful error message would have saved me some time trying to figure out what I was doing wrong. In fact, the example in the documentation is misleadingly a string. Sure, it says "BLOB_VALUE", but it's a string, nevertheless. I feel dumb for having spend time looking for a solution while the documentation clearly states the type as Uint8Array, but helpful error messages go a long way helping dummies like me.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.485.0

### Environment details (OS name and version, etc.)

Windows 10, WSL Ubuntu 22.04, Node 20.10.0

**Comment by RanVaknin** [comment]
Hi @bernardodesousa,

Thanks for reaching out and raising a feature request. 
The error you are seeing `TypeError: Cannot read property 'byteLength' of undefined` is a JavaScript runtime error, which surfaces when there's a mismatch between the expected and provided input types. In this case, the SDK expects a Uint8Array but receives a different type.

The SDK's type system is directly code generated from the API model of the various AWS service (ACM in this case), and it typically relies on the JavaScript runtime for type handling and error reporting. The error you're seeing is a result of this design choice, where the SDK doesn't extensively validate input types but rather depends on the JavaScript environment to handle such errors.

> I feel dumb for having spend time looking for a solution while the documentation clearly states the type as Uint8Array, but helpful error messages go a long way helping dummies like me.

Don't feel dumb! I think our docs could be better, but I find the SDK much easier to use when using an IDE like VScode, the intellisense tooltip brings up the types and makes it easy to see which fields expects which types:

<img width="549" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/0c1db895-fecd-4e26-a659-fbb1f2f87871">

 Additionally using Typescript could have surfaced a much more useful error ahead of running the code:
 
<img width="944" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/964602de-5b55-4c04-b257-bf43d623d063">

Since the SDK only validates on missing fields or certain string Regex that are all defined in the API model itself, and we rely on the runtime for type safety, there are no plans to implement this feature. 

I do appreciate you taking the time and pointing out pain points when using the SDK, and I hope this does not discourage you from interacting with us in the future.

If you have any other questions, please let me know.
All the best,
Ran~
