### ISSUE TITLE
Lambda Invoke hides the error instead of rejecting the promise

### ISSUE THREAD

**Issue by itai-spiritt** [aws/aws-sdk-js-v3#5689]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When executing the `InvokeFunction` fn and an error occurs in my lambda, I'm receiving a resolved promise with an error as a JSON,
I know that the Lambda return a special header that indicates that there's an application error, so why doesn't the SDK reject the promise?
It doesn't make sense to parse the payload and look for the "ErrorMessage" entry.

### SDK version number

"@aws-sdk/client-lambda": "^3.490.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.0

### Reproduction Steps

Just `InvokeCommand` some lambda that throws an exception

### Observed Behavior

```{"errorMessage":"No :in or :where clause specified","errorType":"datomic.ion.lambda.handler.exceptions.Incorrect","stackTrace":["datomic.ion.lambda.handler$throw_anomaly.invokeStatic(handler.clj:25)","datomic.ion.lambda.handler$throw_anomaly.invoke(handler.clj:21)","datomic.ion.lambda.handler.Handler.on_anomaly(handler.clj:175)","datomic.ion.lambda.handler.Handler.handle_request(handler.clj:205)","datomic.ion.lambda.handler$fn__3856$G__3781__3861.invoke(handler.clj:68)","datomic.ion.lambda.handler$fn__3856$G__3780__3867.invoke(handler.clj:68)","clojure.lang.Var.invoke(Var.java:399)","datomic.ion.lambda.handler.Thunk.handleRequest(Thunk.java:35)"]}```

Returned as a successful promise (resolved).

### Expected Behavior

Reject the promise

### Possible Solution

Look for the `X-Amz-Function-Error` and reject the promise with the provided JSON error

**Comment by RanVaknin** [comment]
Hi @itai-spiritt.

The error you shared seems like a Lambda runtime error, and not an operation error. In the context of `invokeFunction` the Lambda API might return a 200, meaning "the lambda was invoked successfully", but the actual Lambda runtime failed to execute the function.

It's important to make this distinction between the Lambda API that the SDK interacts with which constitutes a control plane API (creating, updating, deleting and invoking functions) and your actual Lambda code that can return errors to whoever invokes the endpoint your lambda exposes (either directly or via APIGateWay). 

Since I dont see your actual code, this is a speculation. But a way we can investigate this further is by you adding to your LambdaClient a simple middleware hook that will log the response like so:

```
client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```

This middleware will log the raw response prior to deserialization and promise resolution. 
If the response contains a metadata httpStatusCode of 200, you know that this the Lambda API responding with a 200 to invocation of the function rather than the function returning a runtime / compile error.

Thanks,
Ran~

**Comment by itai-spiritt** [comment]
Hey @RanVaknin  thank you for your response.
You are correct in that the error is a lambda runtime error.
My question is why the SDK does resolve the promise?
Why did you make the decision of ignoring lambda runtime errors?
I understand that if I would have executed a HTTP request that return a 200 (which is your design decision) I had to check the response body (or header in this case) and decide whether the request succeeded or not.
But since I'm using a wrapper to the HTTP request (this sSDK) I expect it to reject (or at least let the user configure it) upon runtime errors.

I'm trying to understand 2 things:
1. Why did you decide to implement the SDK this way?
2. How do I check for errors? Should I read the Payload and look for an `errorMessage`? Because I don't have access to the header anymore (`X-Amz-Function-Error`)

**Comment by RanVaknin** [comment]
Hi @itai-spiritt ,

> My question is why the SDK does resolve the promise?

Because the response for invoke was a 200, which means "I have invoked the lambda successfully" 
The `@aws-sdk/client-lambda` is a control plane client as I have explained in my previous comment. 

>Why did you decide to implement the SDK this way?

The AWS SDKs are code-generated from each AWS service's model. Whether it resolves or throws an error is based on the network response returned by the _lambda server_ itself. Lambda does not have a data plane API, its up to you to implement the logic on how to handle responses from your own API. The SDK merely acts as a control plane interface for invoking, creating and updating your lambda definition. 

The difference is that your lambda's response are sent as a whole http response represented as a payload string, when in fact the entire server response wraps whatever your lambda sends back with the actual control plane headers like the network protocol's http status which in this case is 200. 

Here is a visual example (this is not a real response):

```
HTTP/1.1 200 OK
Content-Type: application/json
X-Amz-Function-Error: Handled

{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST",
    "FunctionError": "Unhandled",
    "Payload": "{\"errorMessage\":\"Error message detailing what went wrong\",\"errorType\":\"ErrorType\",\"stackTrace\":[\"Stack trace details\"]}"
}


```

You can observe that in this response the actual http status is 200, therefore the Lambda service treats this invocation as "successful", and therefore the SDK will resolve this promise and not reject it. 

As opposed to a control plane related error, for example if you try to invoke a non existent lambda function, the server will respond with something like this:

```
HTTP/1.1 404 Not Found
Content-Type: application/json
X-Amz-Error-Type: ResourceNotFoundException

{
    "Type": "User",
    "Message": "Function not found: arn:aws:lambda:us-east-1:123456789012:function:FakeLambdaFunctionName",
    "Code": "ResourceNotFoundException"
}
```

If the http status code returned from the server is anything other than a 2xx status, the SDK will treat it as an error and will reject the promise. 

>How do I check for errors? Should I read the Payload and look for an errorMessage? Because I don't have access to the header anymore (X-Amz-Function-Error)

I'm not familiar with the syntax you shared so I'm not able to provide a solution in that programming language, but using JS, you will need to read the response body, and parse it to determine whether the payload contained an error or not. Something roughly like this:

```js
async function invokeLambda(functionName, payload) {
    const command = new InvokeCommand({
        FunctionName: functionName,
        Payload: Buffer.from(JSON.stringify(payload))
    });

    try {
        const { Payload } = await client.send(command);
        const response = JSON.parse(new TextDecoder().decode(Payload));
        
        // parse the response and determine whether something is a data plane error
        // throw new Error("this is a runtime error")
        
      } catch (error) {
        console.error('Control Plane Error! Failed to invoke Lambda function:', error);
    }
}
```

Thanks,
Ran~
