### ISSUE TITLE
It will be helpful to mention transformToString

### ISSUE THREAD

**Issue by hqblock** [aws/aws-sdk-js-v3#5696]
### Describe the issue

Just add that in case the Body is text, then use await transformToString()

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/

**Comment by RanVaknin** [comment]
Hi @hqblock ,

Thanks for reaching out.

The documentation in the link you included is directly provided by the S3 documentation model itself. Our docs generate types and examples based on pre-defined mapping between API model types and SDK types. Since TransformToString() is a customization we cannot add it to this page. However, this is documented in multiple places:
- [v3 migration guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#lambda)
- [Developer Guide](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#streams)
- [Code Examples](https://docs.aws.amazon.com/code-library/latest/ug/javascript_3_s3_code_examples.html#actions)

Since the examples in the docs you linked are generic and written by the S3 service team itself, this is not actionable by the SDK team. 

Given this is documented multiple times in other places I'm inclined to close this request. 
Thanks again for taking the time and submitting the issue. 

Ran~
