### ISSUE TITLE
Add Range for 'MaxRecords' parameter

### ISSUE THREAD

**Issue by chrisnellis** [aws/aws-sdk-js-v3#5727]
### Describe the issue

When running with a MaxRecords parameter set to '1', I got an error message that says "Invalid value for max records. Must be between 20 and 100".

Please add this range to the docs here for better visibility.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/elasticache/command/DescribeServerlessCachesCommand/

**Comment by RanVaknin** [comment]
Hi @chrisnellis ,

Thanks for reaching out. The JS SDK docs are code-generated directly from every AWS service's API docs. In this case Elastic Cache's doc:
https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeServerlessCaches.html

Since our docs are code generated from the service's docs, we cannot make changes to them on the SDK level, and changes need to be made upstream on the service level.

You can use the [Feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?feedback_destination_id=68666466-6b49-4b2d-b91e-3ebc83e32250&topic_url=https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeServerlessCaches.html) button a the top right corner of the page, and your bug report will be submitted directly to the service's doc writers. 

Since this is not actionable by the SDK team, I will close this.

Thanks again for taking the time and submit the issue.
All the best,
Ran~
