### ISSUE TITLE
cloudfront-signer is always a couple of versions behind

### ISSUE THREAD

**Issue by hfhchan-plb** [aws/aws-sdk-js-v3#5737]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

For some reason, on NPM, cloudfront-signer is always a couple of versions behind the rest of the packages.

e.g. client-s3, client-lambda are now on 3.501.0, but cloudfront-signer is still on 3.496.0.

### SDK version number

@aws-sdk/cloudfront-signer@3.496.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

`yarn add @aws-sdk/client-s3 @aws-sdk/client-lambda @aws-sdk/cloudfront-signer`

### Observed Behavior

It added 3.501.0 for `@aws-sdk/client-s3` `@aws-sdk/client-lambda` but 3.496.0 for `@aws-sdk/cloudfront-signer`.

### Expected Behavior

It adds 3.501.0 for `@aws-sdk/client-s3`, `@aws-sdk/client-lambda` and `@aws-sdk/cloudfront-signer`.

**Comment by RanVaknin** [comment]
Hi @hfhchan-plb,

`@aws-sdk/cloudfront-signer` is a handwritten utility, and is not related to changes that the rest of the code generated clients (`@aws-sdk/client-*`) would pick up (mostly related to codegen changes impacting all clients). It is independent and should be safe to use.

Are you running into a specific issue with this package? Or are you just concerned about the version?

Thanks,
Ran~

**Comment by hfhchan-plb** [comment]
> It is independent and should be safe to use.

I see.

I _think_ I've seen at times where some aws-sdk were pulling in different versions of the same deps, but I'm not seeing them in the latest release.

Edit: actually it looks like "@aws-sdk/client-api-gateway@^3.490.0", "@aws-sdk/client-cloudformation@^3.410.0", "@aws-sdk/client-dynamodb@^3.494.0" etc are pulling "@smithy/url-parser" "^2.0.16", but "@smithy/credential-provider-imds@^2.2.0" itself is pulling "@smithy/url-parser" "^2.1.0", so what I saw is not related to the aws-sdk version not syncing but rather the aws-sdk libraries not referencing the newest smithy packages.

**Comment by RanVaknin** [comment]
Hi @hfhchan-plb,

> the aws-sdk libraries not referencing the newest smithy packages. 🤷 

This is because your dependencies are all using different versions instead of `@latest`. 

>but "@smithy/credential-provider-imds@^2.2.0" itself is pulling "@smithy/url-parser" "^2.1.0"

When smithy uses its own packages as dependencies it uses the [workspace version](https://github.com/smithy-lang/smithy-typescript/blob/3769699491dcc1bd5ace2973f2efdf6d85b37cf4/packages/credential-provider-imds/package.json#L32) itself.

If we inspect the latest versions of each of these clients, we can see that they all use the latest, and correct version:
- [client-api-gateway](https://github.com/aws/aws-sdk-js-v3/blob/d27301d48f3e75fdaccabf58f779f0b33a70664e/clients/client-api-gateway/package.json#L51)
- [client-cloudformation](https://github.com/aws/aws-sdk-js-v3/blob/d27301d48f3e75fdaccabf58f779f0b33a70664e/clients/client-cloudformation/package.json#L51)
- [client-dynamodb](https://github.com/aws/aws-sdk-js-v3/blob/d27301d48f3e75fdaccabf58f779f0b33a70664e/clients/client-dynamodb/package.json#L51)


In order to avoid an issue where you have multiple copies of the same dependency at different versions, you need to make sure all of your clients are using the latest version.

You can either do that manually, or just let yarn resolve the dependency tree for you by:
- deleting `node_modules`
- delete your lock file
- running `yarn install`

Let me know how it goes.
Thanks,
Ran~
