### ISSUE TITLE
Is this documentation designed for.... a none engineer?

### ISSUE THREAD

**Issue by tankcdr** [aws/aws-sdk-js-v3#5754]
### Describe the issue

The documentation is pretty. But really kind of useless. Use the AWS CDK documentation as a point of reference for useful information.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/dax/

**Comment by RanVaknin** [comment]
Hi @tankcdr ,

We had a big refactor to our docs in the last year and I agree that its still somewhat confusing. 
Since you are not calling out specific issues you are having with our docs, its hard to understand what you are struggling with.

Unless you have a question or concern about specific aspects of our documentation, this issue is not actionable. 

Thanks,
Ran~
