### ISSUE TITLE
support paginator for DescribeDocumentPermissionCommand in @aws-sdk/client-ssm

### ISSUE THREAD

**Issue by nagmesh** [aws/aws-sdk-js-v3#5757]
### Describe the feature

Currently, there is no option to use a paginator for DescribeDocumentPermissionCommand. 

### Use Case

Currently we do this,
```typescript
const documentPermission: string[] = [];
let nextToken: string | undefined = undefined;
  // there is no paginator for DescribeDocumentPermissionCommand, so we need to loop through all pages.
  do {
    const page = await throttlingBackOff(() =>
      ssmClient.send(new DescribeDocumentPermissionCommand({ Name: name, PermissionType: 'Share' })),
    );

    for (const accountId of page.AccountIds ?? []) {
      documentPermission.push(accountId);
    }
    nextToken = page.NextToken;
  } while (nextToken);
```

### Proposed Solution

Use paginator like paginateDescribeDocumentPermission to run the code below

```typescript
const documentPermission: string[] = [];
for await (const page of paginateDescribeDocumentPermission({ client }, {})) {
    // page contains a single paginated output.
    documentPermission.push(...page.AccountIds ?? []);
}
```

### Other Information

https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.410.0

### Environment details (OS name and version, etc.)

macOS 14.3 (23D56)

**Comment by RanVaknin** [comment]
Hi @nagmesh ,

Thanks for reaching out. The reason some paginators are missing from the SDK is that the SDK is code-generated directly for the API models of all the services. In this specific case, SSM does not model `DescribeDocumentPermission` as a paginatable operation, therefore the SDK does not "know" the I/O needed to generate this paginator.

I have created an internal feature request with the SSM team to add this paginator definition (`P116899486`)

Since this is not actionable by the SDK team, I will close the ticket. 

Thanks again,
Ran~

**Comment by RanVaknin** [comment]
Hi @nagmesh ,

We heard back from the SSM service team. This is not possible to add to the model, because pagination for DescribeDocumentPermission is not supported in certain regions yet, therefore cannot be described accurately in the API model as conditional modeling is not supported since this can subsequently lead to an unexpected behavior in the SDK.

Thanks,
Ran~
