### ISSUE TITLE
Error initiating s3Client

### ISSUE THREAD

**Issue by RijanFedo** [aws/aws-sdk-js-v3#5777]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When i try to connect to s3Client using the accesskey and secretkey from react native app and call the putobject command. It is throwing me Cannot read property 'apply' of undefined.

### SDK version number

@aws-sdk/package-name@version, 3.509.0

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.72.4

### Reproduction Steps

Connect to the client and pass the putobject command

### Observed Behavior

Throwing typeerror Cannot read property 'apply' of undefined

### Expected Behavior

Able to initiate the client and upload file to s3

**Comment by dpyeates** [comment]
I am seeing this as well. Using in React Native.

```
const S3 = new S3Client({
  region: 'WEUR',
  endpoint: 'https://[endpoint].r2.cloudflarestorage.com',
  credentials: {
    accessKeyId: CFR2ACCESSKEY,
    secretAccessKey: CFR2SECRETKEY
  }
});

console.log('***',
        await S3.send(
          new ListObjectsV2Command({ Bucket: 'a-bucket-name' })
        )
      );
```

generates a Error [TypeError: Cannot read property 'apply' of undefined]

**Comment by kuhe** [comment]
If you add this line to your application before SDK operations, that should get you past this error.

Add this:
```js
import "@aws-sdk/util-endpoints"; // ESM
// or 
require("@aws-sdk/util-endpoints"); // CJS
```

----

#### Notes

I believe this is due to the metro bundler stripping out a static import.

In our client code we have the following statement:
```ts
import "@aws-sdk/util-endpoints";
```

This means to load the module, but we are not doing anything with its exports. This code is needed to register AWS endpoint functions in another library, but metro appears to remove this because it thinks that this statement is an unused import. The package.json metadata does not say `sideEffects: true` or anything that should indicate it can be removed.

This may be due to a combination of esbuild and metro bundlers.

`esbuild` assigns a variable name to all imports in cjs (why? I don't know):

Source:
```ts
import "@aws-sdk/util-endpoints";
```
dist-cjs:
```js
var import_util_endpoints = require("@aws-sdk/util-endpoints");
```

Because this assigned variable is unused, metro may assume that it is tree-shakeable. Attempting to tree-shake CJS code is very risky ☹️ . We can try to add some dummy code or other transform to make `metro` not ignore the import.

**Comment by RijanFedo** [comment]
Got it. But this was working previously. why is this throwing an error now ?. The import statement works. But need to know why it was working previously and not now

> If you add this line to your application before SDK operations, that should get you past this error.
> 
> Add this:
> 
> ```js
> import "@aws-sdk/util-endpoints"; // ESM
> // or 
> require("@aws-sdk/util-endpoints"); // CJS
> ```
> 
> #### Notes
> I believe this is due to the metro bundler stripping out a static import.
> 
> In our client code we have the following statement:
> 
> ```ts
> import "@aws-sdk/util-endpoints";
> ```
> 
> This means to load the module, but we are not doing anything with its exports. This code is needed to register AWS endpoint functions in another library, but metro appears to remove this because it thinks that this statement is an unused import. The package.json metadata does not say `sideEffects: true` or anything that should indicate it can be removed.
> 
> This may be due to a combination of esbuild and metro bundlers.
> 
> `esbuild` assigns a variable name to all imports in cjs (why? I don't know):
> 
> Source:
> 
> ```ts
> import "@aws-sdk/util-endpoints";
> ```
> 
> dist-cjs:
> 
> ```js
> var import_util_endpoints = require("@aws-sdk/util-endpoints");
> ```
> 
> Because this assigned variable is unused, metro may assume that it is tree-shakeable. Attempting to tree-shake CJS code is very risky ☹️ . We can try to add some dummy code or other transform to make `metro` not ignore the import.

Got it. But this was working previously. why is this throwing an error now ?. The import statement works. But need to know why it was working previously and not now

**Comment by OpenSpacesAndPlaces** [comment]
Also seeing this when pulling in:
import { CloudWatchClient, GetMetricDataCommand } from "@aws-sdk/client-cloudwatch";

The "import "@aws-sdk/util-endpoints"; hack suggested seems to solve for now.

Error we had was:
TypeError: Cannot read properties of undefined (reading 'partition')

**Comment by kuhe** [comment]
This issue should be fixed in the latest version of the SDK without needing to explicitly import util-endpoints.

The change we made was to make the registration of the additional util-endpoints functions explicit instead of a module level initialization, so that bundlers would not mistakenly omit it.

**Comment by kuhe** [comment]
The versions containing this fix are v3.540.0 and higher.

**Comment by OpenSpacesAndPlaces** [comment]
At least for:
"@aws-sdk/client-cloudwatch": "^3.596.0",
    
  We were seeing the above:
  TypeError: Cannot read properties of undefined (reading 'partition')

**Comment by kuhe** [comment]
please create a separate issue including reproduction step. Including your package-lock.json and build configuration would be helpful, since the problem can be quite specific to a certain build and package arrangement.
