### ISSUE TITLE
@aws-sdk/client-healthlake FHIR REST API operations

### ISSUE THREAD

**Issue by ArtashMardoyanS** [aws/aws-sdk-js-v3#5779]
### Describe the feature

In the @aws-sdk/client-healthlake package, we couldn't find CRUD methods like createPatient, for instance. The PutResourceCommand could be used to create a patient in the data store.

### Use Case

![Screenshot 2024-02-09 at 17 01 18](https://github.com/aws/aws-sdk-js-v3/assets/132377773/9c9e8d85-7bfc-42bc-be22-e6ed9fc51ab3)
We would like to utilize this endpoint in the @aws-sdk/client-healthlake. Could you assist us with this?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.509.0

### Environment details (OS name and version, etc.)

macos

**Comment by RanVaknin** [comment]
Hi @ArtashMardoyanS ,

The AWS SDKs are all mirroring and are code-generated from the various API Models of each service. 

This means that the list of available API operations available in the model, will be the same list of operations available in the SDK.

Since we on the SDK team do not have visibility as to why / why not certain services include operations in their model I can't say why these were not added. I have created a feature request to the service team on your behalf to add these to the model. 

Instead, I have usptreamed your feature request to the HealthLake Service team directly (`P117612826`). 
Because this github issue is not actionable by the SDK team, Im going to close it.

If I hear back internally I will update this thread.

Thanks again,
Ran~

**Comment by ArtashMardoyanS** [comment]
Hi @RanVaknin,

Thank you for your prompt response. This topic is crucial for our development. 
If you come across any solutions, please do not hesitate to assist us. 
Alternatively, could you provide access to communicate with the "@aws-sdk/client-healthlake" developers?

Best regards,
@ArtashMardoyanS

**Comment by RanVaknin** [comment]
Hi @ArtashMardoyanS ,

Like I mentioned, the SDK clients are all code-generated from the API models of each service. The feature request you had was really meant for the service team itself, and not `@aws-sdk/client-healthlake` (this is code generated).  I have already created an internal ticket with the HealthLake service team on your behalf. 

You can try to open a support ticket via the AWS console and ask to be routed to the HealthLake service team. You should also mentioned the existing ticket I have opened with them (ticket `P117612826`).

The SDK team cannot add or change operations to `@aws-sdk/client-healthlake` since those are generated from the API model itself, and without appropriate modeling the SDK cannot build the requests accordingly.

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Downstreaming the response from the service team:

>AWS service SDKs are used to manage the HealthLake service functions. That is different from the FHIR REST APIs that HealthLake as a service provides to the customers.  
>
>FHIR REST APIs by service design are not included in the AWS SDK. 
>
>While not recommended - if the customer wants to acccess HealthLake REST APIs through SDK - they can use API Gateway to generate an SDK for the FHIR REST endpoints. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/generate-javascript-sdk-of-an-api.html
