### ISSUE TITLE
Unable to init in an expo api route

### ISSUE THREAD

**Issue by assertnotnull** [aws/aws-sdk-js-v3#5815]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In an expo project initializing the dynamodb client gives an error

### SDK version number

@aws-sdk/client-dynamodb@3.515.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 20, expo v50, react-native 0.73.2

### Reproduction Steps

write an api route and call it from.

/app/api/messages+api.ts
```js
import { DynamoDBClient, ListTablesCommand } from "@aws-sdk/client-dynamodb";
import { ExpoRequest, ExpoResponse } from "expo-router/server";

const client = new DynamoDBClient({
  apiVersion: "2012-08-10",
  region: "us-east-1",
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
  },
});

export async function GET(request: ExpoRequest) {
  console.log("GET /api/messages");
  console.log(client);
}
```

### Observed Behavior

Running the project through `expo start` the client initialization gives an error:
```console
TypeError: (0 , import_slurpFile.slurpFile) is not a function
    at /code/project/node_modules/@smithy/shared-ini-file-loader/dist-cjs/index.js:134:35
```

### Expected Behavior

No error

**Comment by RanVaknin** [comment]
Hi @assertnotnull ,

Can you please update a small github repository with all the files needed to reproduce this behavior?

Thanks,
Ran~

**Comment by assertnotnull** [comment]
Ok yeah I will do a small repo

**Comment by assertnotnull** [comment]
Repo is here https://github.com/assertnotnull/expo-aws-sdk-bug

**Comment by jawndiego** [comment]
did you ever sort this out?

**Comment by kuhe** [comment]
In our CJS distribution for `@aws-sdk/client-dynamodb`, which is what we expect react-native to use for reasons originating in the metro bundler, we have the following platform specific files

```
/dist-cjs/runtimeConfig.js
/dist-cjs/runtimeConfig.native.js
```

When operating in react-native, the SDK relies on the behavior described here https://reactnative.dev/docs/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web that automatically loads the `.native.js` file instead of the regular file.

In the code sample, expo has not loaded the right file, and therefore the SDK is calling Node.js filesystem module APIs like `readFile`. 

I don't know how to configure this on the expo/metro side, but the solution will involve loading the `.native.js` file. 

----

One workaround I can think of is to create a react-native bundle containing the AWS SDK using only the metro bundler, and then loading that in the expo application instead of using expo itself to bundle.

**Comment by AntoineAtMistral** [comment]
Hitting the exact same issue using `@aws-sdk/client-s3` in Expo API route, did you ever figure it out?
