### ISSUE TITLE
GCMMessage is missing keys for collapsible messages in browser/apple

### ISSUE THREAD

**Issue by bergmorten** [aws/aws-sdk-js-v3#5862]
### Describe the feature

Pinpoint `GCMMessage` supports `CollapseKey' to collapse messages with same key, however this only works on Android. For browser targets you should use Topic and Apple apps use apns-collapse-id. See Google Firebase Documentation on these keys [FCM message format](https://firebase.google.com/docs/cloud-messaging/concept-options#which_should_i_use)

### Use Case

I want the message to be collapse on all platform, not only Android,

### Proposed Solution

Either include `Topic` and `apns-collapse-id` in GCMMessage , or translate `CollapseKey`  to this variables.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.525.0

### Environment details (OS name and version, etc.)

AWS Lambda

**Comment by RanVaknin** [comment]
Hi @bergmorten ,

Thanks for reaching out.  This feature request is geared towards the SNS service team and not the SDK team. If you didn't know, all of the AWS SDKs are code generated from each service's API model. For those fields to exist on the SDK, there needs to be both backend support for sending those, and appropriate modeling. 
Because of this, this is not actionable by the SDK team. 


After combing our internal ticketing system I do see requests to add support for `apns-collapse-id`. I'll add your requests to those so they might get prioritized. However, I did find that you can achieve the same functionality via a message attribute`AWS.SNS.MOBILE.APNS.COLLAPSE_ID` : https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html#sns-attrib-mobile-reserved

Since this is not actionable by the SDK team, I'll go ahead and close this.
Thanks again,
Ran~
