### ISSUE TITLE
MIGRATION ISSUE: Chime - CreateMeetingDialOutCommand not present in dedicated namespace, and will not work using ChimeClient

### ISSUE THREAD

**Issue by rd37011** [aws/aws-sdk-js-v3#5886]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [ ] Yes, my application is running on AWS Lambda.
- [X] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

We are running into an issue migrating our Chime code to AWS SDK v3. The new implementation (or at least, the only implementation I can find for this particular command - `CreateMeetingDialOutCommand`) is not present in a new dedicated namespace, and the client (`ChimeClient` from `@aws-sdk/client-chime`) is also deprecated. I can't find any other information regarding this command within the migration docs - has support for this command simply dropped? 

The command fails when called, with a 404 status code. It is critical to some of our business functions. Does anyone know what's happening here?  

### Code Comparison

V2 Code Snippet:
```
  
    this.chime = new AwsInstance.Chime({ region: config.get('CHIME_SDK_REGION') }) 
    this.chime.endpoint = new AWS.Endpoint(
      'https://service.chime.aws.amazon.com/console'
    )
  }
  
  ......
  
   await this.chime.createMeetingDialOut({
      JoinToken,
      FromPhoneNumber: `+11232345678`,
      ToPhoneNumber: `+1${ToPhoneNumber.trim()}`,
      MeetingId,
    })
    .promise()
    
```
V3 Code Snippet:
    
```
   import { ChimeClient, CreateMeetingDialOutCommand } from '@aws-sdk/client-chime'
    
    ......
    
   const command = new CreateMeetingDialOutCommand({
      JoinToken,
      FromPhoneNumber: `+11232345678`,
      ToPhoneNumber: `+1${ToPhoneNumber.trim()}`,
      MeetingId,
    })
    await this.chimeClient.send(command)
    
```

### Observed Differences/Errors

Error: 

`Unexpected token < in JSON at position 0\n Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
`

Upon inspection of the {error}.$response field, the only relevant information is a `404` status code with message `Not Found`.

**Comment by RanVaknin** [comment]
Hi @rd37011 ,

Thanks for reaching out. The Chime API team has deprecated the `@aws-sdk/client-chime` in favor of releasing their own [separate SDK](https://github.com/aws/amazon-chime-sdk-js).
This is documented here https://docs.aws.amazon.com/zh_cn/chime/latest/APIReference/API_CreateMeetingDialOut.html

Reading notes from the [namespace migration](https://docs.aws.amazon.com/chime-sdk/latest/dg/migrate-from-chm-namespace.html), it looks like this API operation have been deprecated altogether (might still be supported, but not updated / maintained).

It's important to note that the AWS SDKs are all code generated from the various AWS services' API models. Because of this, we on the SDK team cannot add / remove / deprecate / un-deprecate certain clients or operations. 

Thanks,
Ran~

**Comment by rd37011** [comment]
Thanks for the info, @RanVaknin. I suppose we'll need to look into alternatives.
