### ISSUE TITLE
@aws-sdk/client-pinpoint-email v3 client not found

### ISSUE THREAD

**Issue by avb-skye** [aws/aws-sdk-js-v3#5888]
### Describe the issue

I don't see examples using [v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-pinpoint-email/Class/PinpointEmail/) which the developer guide still links to [v2](https://docs.aws.amazon.com/pinpoint/latest/apireference/operations.html).

I am trying to setup v3 since it uses bcc addresses, but it keeps saying the client is not found when it takes the same region config as v2. The template name and arn is provided using the `SendEmail` command for v3, but the API reference guide uses v2 for `SendMessages`.

v2 also allows substitution in a hash map, while v3 is unclear where substitutions happen for the email. I assume its in the email blob but v3 client is still not found

Error: `NotFoundException`
Request ID: `7ea57b6b-ac26-428d-9fce-d9c8f6d9ee61` 

### Links

v3: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-pinpoint-email/Class/PinpointEmail
v2: https://docs.aws.amazon.com/pinpoint/latest/apireference/operations.html

**Comment by RanVaknin** [comment]
Hi @avb-skye ,

Thanks for reaching out. The code examples are found in the individual commands page. So for example [`SendEmailCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/pinpoint-email/command/SendEmailCommand/).

Since your report did not contain any code snippet of your setup now, or the actual error returned it's quite difficult to point you to the solution. 

Please make sure you give our [Readme](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#aws-sdk-for-javascript-v3) a read as it contains general code examples and syntax style for v3. We also have a [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html) that talks more about the changes and migration.
If you're also interested in seeing more specific changes you can look at our [upgrading notes](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).

Let me know if you have any other question,
Ran~
