### ISSUE TITLE
InvokeModelCommand missing used tokens

### ISSUE THREAD

**Issue by boyandimitrov** [aws/aws-sdk-js-v3#5917]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

InvokeModelCommand does not contain information for used tokens.

### SDK version number

3.437.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

17.1.0/Edge

### Reproduction Steps

    const command = new InvokeModelCommand(input);
    let response;
    try {
        response = await client.send(command);
        console.log("RESPONSE", response)
    }
    

### Observed Behavior

Response log:
INFO	RESPONSE => {
  '$metadata': {
    httpStatusCode: 200,
    requestId: '7fd1ed37-1f08-439a-9bd9-041aa1a93330',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  contentType: 'application/json',
  body: Uint8ArrayBlobAdapter(488) [Uint8Array] [
    123,  34,  99, 111, 109, 112, 108, 101, 116, 105, 111, 110,
     34,  58,  34,  32,  60, 106, 115, 111, 110,  62, 123,  92,
     34, 116, 105, 116, 108, 101,  92,  34,  58,  92,  34,  65,
     99, 109, 101,  32,  67, 111, 114, 112, 111, 114,  97, 116,
    105, 111, 110,  32,  65,  99, 113, 117, 105, 115, 105, 116,
    105, 111, 110,  92,  34,  44,  92,  34, 115, 110, 105, 112,
    112, 101, 116,  92,  34,  58,  92,  34,  65, 110, 103, 101,
    108, 105, 110,  97,  32,  66, 101, 110, 104,  97, 109,  32,
     97, 110, 100,  32,
    ... 388 more items
  ]
}

### Expected Behavior

Similar log from python boto3

 {'ResponseMetadata': {'RequestId': '07f4143f-8814-4669-84a1-60958ee59094', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Mon, 18 Mar 2024 14:07:44 GMT', 'content-type': 'application/json', 'content-length': '344', 'connection': 'keep-alive', 'x-amzn-requestid': '07f4143f-8814-4669-84a1-60958ee59094', 'x-amzn-bedrock-invocation-latency': '7213', 'x-amzn-bedrock-output-token-count': '64', 'x-amzn-bedrock-input-token-count': '714'}, 'RetryAttempts': 0}, 'contentType': 'application/json', 'body': <botocore.response.StreamingBody object at 0x7f1deb9fc310>}

**Comment by RanVaknin** [comment]
Hi @boyandimitrov ,

I'm not sure what code did you use in the boto3 SDK to see this response, but its possible that what you are seeing is the raw data sent back from the Bedrock-Runtime service, and not the deserialized data. 

The service can send any arbitrary data it wants to, but if that data is not modeled in the API, the SDK would not "know" which response elements it needs to deserialize and how. 

If you inspect the doc page for [InvokeModel](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html), you can see that there is no mention to `x-amzn-bedrock-input-token-count`, `x-amzn-bedrock-output-token-count` or `x-amzn-bedrock-invocation-latency`. 

You can inspect the raw response sent back by the service using this middleware:

```js
client.middlewareStack.add(next => async (args) => {
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```

My guess is that you will see the missing information there, but it will not be available to use programmatically because of the reasons I mentioned above.

Let us know what you find.
Thanks,
Ran~

**Comment by boyandimitrov** [comment]
Hi, your assumptions is right. The raw response contains the headers and I could not propagate them to InvokeModelCommand. 

What i did is a global hash

    client.middlewareStack.add(next => async (args) => {
    const response = await next(args);

    // Extract token counts from the headers
    const requestId = response.response.headers['x-amzn-requestid'];
    const inputTokenCount = response.response.headers['x-amzn-bedrock-input-token-count'];
    const outputTokenCount = response.response.headers['x-amzn-bedrock-output-token-count'];

    if (requestId) {
        tokenCountsByRequestId[requestId] = {
            inputTokenCount: inputTokenCount ? parseInt(inputTokenCount, 10) : null,
            outputTokenCount: outputTokenCount ? parseInt(outputTokenCount, 10) : null,
        };
    }

    return response;
}, {step: 'finalizeRequest'})

than after InvokeModelCommand i retrieve the values 

    const command = new InvokeModelCommand(input);
    console.log('bedrock start')
    let response;
    try {
        response = await client.send(command);
        const requestId = response?.$metadata?.requestId;
        console.log('requestId', requestId)

        // Retrieve and then remove the token counts from the global hash
        const tokenCounts = tokenCountsByRequestId[requestId];
        if (tokenCounts) {
            console.log(`Input Token Count: ${tokenCounts.inputTokenCount}`);
            console.log(`Output Token Count: ${tokenCounts.outputTokenCount}`);
       }
    }


Python code that does the same:

  def extract_token_counts_from_response(response):
    if 'ResponseMetadata' in response and 'HTTPHeaders' in response['ResponseMetadata']:
        http_headers = response['ResponseMetadata']['HTTPHeaders']

        # Extracting input and output token counts
        input_token_count = http_headers.get('x-amzn-bedrock-input-token-count')
        output_token_count = http_headers.get('x-amzn-bedrock-output-token-count')

        # Converting token counts to int if they are not None
        input_token_count = int(input_token_count) if input_token_count is not None else None
        output_token_count = int(output_token_count) if output_token_count is not None else None

        return input_token_count, output_token_count
    else:
        # Returning None for both counts if the expected structure is not found
        return None, None


    response = bedrock.invoke_model(body=body, modelId=modelId, accept=accept, contentType=contentType)
    input_tokens, output_tokens = extract_token_counts_from_response(response)

**Comment by RanVaknin** [comment]
Hi @boyandimitrov,

I reached out to the Bedrock team internally, and it appears they have released those fields privately, so while they are available as metadata right now, the reason they are not publicly modeled is because the data might change in the future (header name might change, or removed altogether,  or data might be returned in the body of the response rather than the header)

My suggestion to you is to have a mitigation strategy going forward and not to rely on these fields existing in the future. 

Since this is not further actionable by the SDK team, I'm going to close this.
Thanks,
Ran~
