### ISSUE TITLE
signature v4 support in cloudfront edge lambdas

### ISSUE THREAD

**Issue by dza89** [aws/aws-sdk-js-v3#5919]
### Describe the issue

@aws-sdk/signature-v4 has been moved to @smithy/signature-v4.
Cloudfront edge lambdas have native support for @aws-sdk but not for @smithy.
I am confused about what i should use, or if I should include it myself. 

Will edge lambdas support smithy in the future?

### Links

https://www.npmjs.com/package/@aws-sdk/signature-v4

**Comment by RanVaknin** [comment]
Hi @dza89 ,

Thanks for reaching out. I think your question is totally valid, but we have no visibility to how Lambda provides and packages their runtime to customers.

My advice to you (which is [the recommended solution from lambda](https://docs.aws.amazon.com/lambda/latest/operatorguide/sdks-functions.html)) is to always provide your own application dependencies either by bundling and uploading them to lambda, or providing them as a Lambda layer, and not to rely on the dependencies provided by the lambda runtime itself.

>The bundled SDK is provided as a convenience for developers building simpler functions or using the Lambda console for development. 

Providing your own dependencies will not only help you with [optimizing your lambda](https://aws.amazon.com/blogs/developer/reduce-lambda-cold-start-times-migrate-to-aws-sdk-for-javascript-v3/) for better cold start times, it will also allow you to control which SDK version you want to use (lambda updates their provided SDK version only a couple of times a year) so you can take advantage of newer features that otherwise might not make it to Lambda for a while.

Let me know if you have any questions.
Thanks,
Ran~
