### ISSUE TITLE
Use `httpsAgent` instead of `httpAgent`

### ISSUE THREAD

**Issue by perpil** [aws/aws-sdk-js-v3#5921]
### Describe the issue

In the example for how to turn off keep-alive on this [page](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-reusing-connections.html) you use `httpAgent`.  For DynamoDB and any AWS Service I can think of it should be `httpsAgent`.  See `httpOptions` on [this page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/) for details.

### Links

https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-reusing-connections.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/

**Comment by perpil** [comment]
I should also mention, this requires importing `Agent` from `https` so the full snippet likely should be:

```
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { NodeHttpHandler } from "@smithy/node-http-handler";
import { Agent } from "https";
const dynamodbClient = new DynamoDBClient({
    requestHandler: new NodeHttpHandler({
        httpsAgent: new Agent({ keepAlive: false })
    })
});
```

**Comment by RanVaknin** [comment]
Hi @perpil,

Thanks again. Adding this to our backlog. 

Ran~

**Comment by aBurmeseDev** [comment]
@perpil thanks again for this feedback. 

We've updated our documentation with a code example demonstrating how to use `httpsAgent` instead of `httpAgent`. You can find the updated information in our developer guide at [our developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-reusing-connections.html).
```js
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { NodeHttpHandler } from "@smithy/node-http-handler";
import { Agent } from "https";

const dynamodbClient = new DynamoDBClient({
    requestHandler: new NodeHttpHandler({
        httpsAgent: new Agent({ keepAlive: false })
    })
});
```

We appreciate your feedback and suggestions, as they help us improve our documentation and provide clear and accurate guidance to our users. Closing the issue.
Best,
John
