### ISSUE TITLE
Input props are not documented for v3, Lambda->InvokeCommand

### ISSUE THREAD

**Issue by JoeMuff999** [aws/aws-sdk-js-v3#5937]
### Describe the issue

How do I find what parameters to use? I see the props are documented in the [v2 docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/InvokeCommand/

**Comment by JoeMuff999** [comment]
I see that the props are documented in InvocationRequest. Could this be made more visible?

**Comment by RanVaknin** [comment]
Hi @JoeMuff999 

in the first link you sent the input structure is shown in the code example:

<img width="606" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/db6f0249-4459-40c6-b18c-f3a99a83c05b">


Since our documentation engine generates every class in a new page its not possible to consolidate them in one doc page. 

Thanks,
Ran~

**Comment by JoeMuff999** [comment]
Thanks Ran. Would it be possible to add the link so others could find the details for each parameter? Would be happy to submit a small PR for it (I'm assuming its the comment header for [InvokeCommand.ts](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-lambda/src/commands/InvokeCommand.ts))

**Comment by RanVaknin** [comment]
Hi @JoeMuff999 ,

It's not clear which link you are trying to add and where?

Thanks,
Ran~
