### ISSUE TITLE
Extend Step Function API Support to Express Type Step Functions

### ISSUE THREAD

**Issue by austin-merkle** [aws/aws-sdk-js-v3#5945]
### Describe the feature

I realize this is would require an API change before the SDK could support it, but wasn't sure where else to request this. We've been able to List and Describe Express Step Function Executions in the AWS Console since 10/2022: https://aws.amazon.com/about-aws/whats-new/2022/10/aws-step-functions-adds-new-execution-observability-features-express-workflows/

Would be awesome if we could extend some of that functionality to the API and SDK. At least being able to List and Describe Executions via the SDK would be super helpful.

### Use Case

It's frustrating to manually comb through hundreds of executions when certain edge cases arise. Being able to List and Describe them via the SDK would let my team build some internal tools to make debugging easier.

### Proposed Solution

Ask the Step Functions team to expose these APIs so the SDKs can incorporate them. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.535.0

### Environment details (OS name and version, etc.)

MacOS Sonoma (14.0)

**Comment by RanVaknin** [comment]
Hi @austin-merkle ,

Thanks for reaching out. Like you correctly pointed out, the Step functions API team has not exposed these APIs in their model therefore the SDK will not have any of the express operations.

I have created an internal ticket with the SFN team (`P124957058`) for them to expose those APIs. If you have access to AWS support through the console, you can provide this ticket ID to your dedicated support person and theyll be able to give you continuous updates regarding the status of the ticket.

Since this is not actionable by the SDK team, I will close this issue but will update it when I hear back.

Thanks again,
Ran~
