### ISSUE TITLE
PublishVersionCommand creating new version each time regardless of any delta

### ISSUE THREAD

**Issue by asimboruwa-pivotree** [aws/aws-sdk-js-v3#5946]
### Describe the issue

Calling **PublishVersionCommand()** creates a new version regardless of any code change or not. The documentation is very misleading - especially the part where it says "**_Lambda doesn't publish a version if the function's configuration and code haven't changed since the last version. Use UpdateFunctionCode or UpdateFunctionConfiguration to update the function before publishing a version._**"

The only way to publish a new version based upon code changes is by calling **UpdateFunctionCodeCommand()** and setting **Publish:true**. However, by using this method you do not get the ability to set a "**Description**" against the new published version. I am trying to set the commit message/id against each new published version. Currently, I do not see any way to set a description against a version that is uniquely created for the code change.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/PublishVersionCommand/

**Comment by RanVaknin** [comment]
Hi @asimboruwa-pivotree ,

Thanks for reaching out.

The SDK's docs are generated from the [main API docs](https://docs.aws.amazon.com/lambda/latest/api/API_PublishVersion.html) for each operation which is owned by the service itself, and not the SDK team. 

Please submit a documentation [feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Lambda&topic_url=https://docs.aws.amazon.com/lambda/latest/api/API_PublishVersion.html) at the top right side of the documentation page and it will go directly to the doc writers of that service. 

Since this is not actionable by the SDK team I'm going to go ahead and close this.

Thanks again,
Ran~
