### ISSUE TITLE
Class Input Documentation doesnt match example code

### ISSUE THREAD

**Issue by bodagg** [aws/aws-sdk-js-v3#5960]
### Describe the issue

Your example code for RegisterUserCommand for the input parameter IdentityType you have 3 options listed including "IAM_IDENTITY_CENTER" which doesnt appear in the documentation for the input class

const input = { // RegisterUserRequest
  IdentityType: "IAM" || "QUICKSIGHT" || "IAM_IDENTITY_CENTER", // required

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/quicksight/command/RegisterUserCommand/

**Comment by RanVaknin** [comment]
Hi @bodagg ,

Thanks for reaching out. The SDK docs are code generated from the API docs of each AWS Service. In this case the source of truth is here https://docs.aws.amazon.com/quicksight/latest/APIReference/API_RegisterUser.html

Since the SDK docs are generated from a different "Source of truth", I have created a request with the service team to update the documentation (`P125062289`).

You can also submit feedback to them directly by clicking on the `Feedback` button on the top right corner of that link I sent.

Since this is not actionable by the SDK team, I'm going to go ahead and close this.

Thanks again for reaching out,
Ran~
