### ISSUE TITLE
util-arn-parser: Add logic for extracting resource name from various ARN formats

### ISSUE THREAD

**Issue by AlJohri** [aws/aws-sdk-js-v3#5966]
### Describe the feature

This ticket is to bump https://github.com/aws/aws-sdk-js-v3/issues/4243 again as I have run into the exact same use case.

### Use Case

I am parsing ECS Service ARNs like `arn:aws:ecs:us-east-1:890277807768:service/ecs-all-greek-to-me-beta-us-east-1/DataNode-default-63-idx-1-us-east-1-beta-20240404-163815-770Z`.

I want to get the service name and I expected running the following code to work:

```
import { parse } from '@aws-sdk/util-arn-parser';
parse(arn).resource
```

However, it only gives me:

```
service/ecs-all-greek-to-me-beta-us-east-1/DataNode-default-63-idx-1-us-east-1-beta-20240404-163815-770Z
```

Where as I expected it to give me:

```
DataNode-default-63-idx-1-us-east-1-beta-20240404-163815-770Z
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.420.0

### Environment details (OS name and version, etc.)

AL2

**Comment by RanVaknin** [comment]
Hi @AlJohri ,

Thanks for reaching out. I have raised this with the team once again and we have decided not the extend the functionality of the arn parser. 

Right now the arn parser extracts the resource group so for example
`arn:partition:service:region:account-id:resource-type/resource-id` will result in `resource-type/resource-id`, which serves its purpose for internal use.

You will be better equipped extracting the part you need from the arn string yourself because you know your specific use case yourself better.

Thanks,
Ran~
