### ISSUE TITLE
GetCredentialsForIdentityCommand response case problem

### ISSUE THREAD

**Issue by gemmerton** [aws/aws-sdk-js-v3#5997]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using `GetCredentialsForIdentityCommand` the response returns `AccessKeyId`, `SecretKey` and `SessionToken`.  However, other AWS services to which these credentials need to be passed are expecting the format `accessKeyId`, `secretAccessKey` and `sessionToken`.

So the response from the Cognito call needs to have the case changed in order to be useful for calls to other AWS services.

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome vers 123.0.6312.106

### Reproduction Steps

Standard response from a `GetCredentialsForIdentityCommand`

### Observed Behavior

As per description, response is incorrect case/format for use with other AWS services

### Expected Behavior

response should contain `accessKeyId`, `secretAccessKey` and `sessionToken`

**Comment by RanVaknin** [comment]
Hi @gemmerton ,

If you didn't know, all of the AWS SDKs are code generated from the API models of the various AWS services. The types the SDK generates are matching whatever the AWS service specifies in their API model (PascalCase AccessKeyId). The service team cannot change the casing of the response they return since it would be considered a breaking change.

The solution here is to reconstruct the credential object yourself. something like this:
 ```js
const credentials = {
        accessKeyId: cognitoResponse.Credentials.AccessKeyId,
        secretAccessKey: cognitoResponse.Credentials.SecretAccessKey,
        sessionToken: cognitoResponse.Credentials.SessionToken
 }
```

Thanks,
Ran~
