### ISSUE TITLE
Provide utility to programatically create deep links to Cloudwatch Insights queries.

### ISSUE THREAD

**Issue by cdearden** [aws/aws-sdk-js-v3#6016]
**Is your feature request related to a problem? Please describe.**
We have metrics which will alarm when there is more than x number of errors being thrown in our application in a 5 minute period. When the alarm goes of it will cut a ticket to our team which includes the link to the metric dashboard but we'd like to also include the link to a Cloudwatch Insights query for errors in our application so that it's faster/easier to debug the metric alarm.

**Describe the solution you'd like**
We would like a utility that will take in a query string, a start time, an end time, the time zone, the region, and the time type ("ABSOLUTE" or "RELATIVE") and return a deeplink to the Cloudwatch Insights page.
  
```
  const logGroup = "ourLogGroup.log";

  const queryString = `fields @timestamp, @message
    | sort @timestamp desc
    | filter namespace like /Application/
    | filter logLevel like /ERROR/
    | display @timestamp, message`;

  const startTime = -3600
  const endTime = 0
  const timeType = "ABSOLUTE",
  const timeZone = "UTC"
  const region = "us-west-2"
 
  const deepLink = getCloudwatchInsightsDeepLink(region, logGroup, queryString, startTime, endTime, timeType, TimeZone)
```

**Describe alternatives you've considered**
Creating our own implementation. This has been a bit challenging as we've had to figure out how Cloudwatch encodes the query parameters for the url. It looks like it's a combination of calling "encodeURIComponent" a few times as well as manually encoding certain characters like ~, (, ),  and ' as well as replacing "%" with "$" and some other characters with "*".

**Comment by RanVaknin** [comment]
Hi there,

Thanks for your patience. We have discussed this as a team and this is unlikely that we will be adding this customizations. We strive to add customizations only as cross-SDK efforts in order to eliminate feature parity gaps both between different SDK languages but also between major versions of that same SDK. 

While this seems like a nice-to-have, it is unlikely that we will prioritize this anytime soon, and for the sake of transparency I'm going to go ahead and close this instead of letting it languish in our queue.

Thanks again for taking the time and writing the FR, I hope this doesnt discourage you from writing to us in the future.
All the best,
Ran~
