### ISSUE TITLE
credentials property of SSM constructor is not documented

### ISSUE THREAD

**Issue by chrisjameslennon** [aws/aws-sdk-js-v3#6029]
### Describe the issue

An SSM client (and many other objects) can be created by passing in an `AwsCredentialIdentityProvider` in the `credentials` property of the config that is passed in the constructor. I know this because I do it and it works. However I cannot find this anywhere in the documentation.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/

**Comment by aBurmeseDev** [comment]
Hi @chrisjameslennon - thanks for reaching out. 

This page [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/) is what you're looking for, that shows all the credential providers with code examples. I understand that it might be helpful to have it in client pages but it may also cause some confusion which is why we keep everything credential related in one spot. 

I appreciate your feedback!
