### ISSUE TITLE
StartDirectoryListingCommand is missing from @aws-sdk/client-transfer

### ISSUE THREAD

**Issue by alexander-medvedev** [aws/aws-sdk-js-v3#6085]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

StartDirectoryListingCommand does not exist in AWS Transfer SDK

The next code fails with "StartDirectoryListingCommand is not a constructor;" error

import pkg from '@aws-sdk/client-transfer';
const { TransferClient, StartDirectoryListingCommand } = pkg;
const command = new StartDirectoryListingCommand(input);

after printing out pkg I found that the getter is missing:
...
  SendWorkflowStepStateCommand: [Getter],
  ServiceUnavailableException: [Getter],
  SetStatOption: [Getter],
  SftpAuthenticationMethods: [Getter],
  SigningAlg: [Getter],
  // StartDirectoryListingCommand should be here
  StartFileTransferCommand: [Getter],
  StartServerCommand: [Getter],
  State: [Getter],
  StopServerCommand: [Getter],
...

### SDK version number

@aws-sdk/client-transfer

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20.x (running on AWS Lambda)

### Reproduction Steps

import pkg from '@aws-sdk/client-transfer';
const { TransferClient, StartDirectoryListingCommand } = pkg;
const command = new StartDirectoryListingCommand(input);

### Observed Behavior

StartDirectoryListingCommand is not a constructor

### Expected Behavior

command is created

### Additional Information/Context

executed on AWS Lambda (nodejs20.x)

**Comment by RanVaknin** [comment]
Hi @alexander-medvedev ,

I can see that [`StartDirectoryListingCommand`](https://github.com/aws/aws-sdk-js-v3/blob/e7a50809bc15fbdc0a6185f8ec4ea167621fa3f1/clients/client-transfer/src/commands/StartDirectoryListingCommand.ts) was added 3 weeks ago. Since you mentioned you are running this from Lambda, my guess is that you are using the SDK provided through Lambda itself. The [Lambda provided SDK](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html) only gets updated a handful of times per year, the last time being a few months ago.

In order to access the most up to date SDK version with the changes you are after you need to [provide your own SDK](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html). 

Thanks,
Ran~
