### ISSUE TITLE
`ValidationError` should report the error fields starting from upper case that matches the command's input type

### ISSUE THREAD

**Issue by riywo** [aws/aws-sdk-js-v3#6109]
### Describe the feature

SDK returns `ValidationError` but its message reports the error fields starting from lower case (in the example below, it's `accessKeyId`, not `AccessKeyId`):

```js
import { STSClient, GetAccessKeyInfoCommand } from "@aws-sdk/client-sts";

const client = new STSClient();
// const command = new GetAccessKeyInfoCommand({ AccessKeyId: "..." });  <= Proper input
const command = new GetAccessKeyInfoCommand();  // <= Wrong input
await client.send(command);
```

```
STSServiceException [ValidationError]: 1 validation error detected: Value null at 'accessKeyId' failed to satisfy constraint: Member must not be null
```

### Use Case

This is a bit confusing. While TypeScript doesn't allow lower case fields, JavaScript users might face bugs due to such typo if they just copy & paste from the error message.

### Proposed Solution

Returning the error fields starting from upper case that matches the command's input type.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

3.577.0

### Environment details (OS name and version, etc.)

Linux d7be8a114a11 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux

**Comment by RanVaknin** [comment]
Hi @riywo ,

The error you are seeing is a _server side_ error thrown by the STS service itself. The types that the SDK generates are in upper case because they reflect STS's `credentials` object described [here](https://docs.aws.amazon.com/STS/latest/APIReference/API_Credentials.html) which models each fields as uppercase.

Since all of the AWS SDKs are code generated from the API model of each AWS service, the SDK team cannot edit those types. Additionally, editing the types to be lower case would be a backwards incompatible change and not something that we can support. 

If you are looking for an ease of use solution, you can use any modern IDE's intellisense to help you fill in the correct parameter name:

![image](https://github.com/aws/aws-sdk-js-v3/assets/50976344/b467e824-b776-49e3-a12c-5ea518c9d62f)

Since this feature is not actionable by the SDK team, I'm going to go ahead and close this.

Thanks,
Ran~
