### ISSUE TITLE
Add Policy Action Name used by a command

### ISSUE THREAD

**Issue by juanf9224** [aws/aws-sdk-js-v3#6111]
### Describe the issue

Currently in the docs there is no reference to the Policy Action that is used by the command, ie: `cognito-idp:AdminGetUser`. Would be helpful when  trying to add a policy statement and not sure about the action this command uses, I just tried to find it in the doc but haven't seen it.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/command/AdminUpdateUserAttributesCommand/

**Comment by RanVaknin** [comment]
Hi @juanf9224 ,

Thanks for reaching out. 
The AWS SDK client specific docs are code generated from the source docs defined by each AWS service. 
Since they are code generated we edit them. The changes need to be made upstream with the service team itself.

You can submit documentation feedback request by going to the main AWS website and click on the `Feedback` button on the top right corner of [each doc page](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html), or by clicking [here](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Cognito&topic_url=https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html). This will ensure that your documentation request makes it directly to the appropriate service team.

Since this is not actionable by the SDK team, I'm going to close this issue.
Thanks again,
Ran~
