### ISSUE TITLE
Provide SendCommandCommand Status Update Guide

### ISSUE THREAD

**Issue by LumaC0** [aws/aws-sdk-js-v3#6128]
### Describe the issue

The SendCommandCommand output features a `Command` object which includes `Status` and `CompletedCount`. The returned values for those keys will very likely be `InProgress` and a value less than the target count. 

Provide a suggestion in the description of the command for how to follow up on those attributes. For instance, before moving on to another operation like reading the sendCommandCommand results in S3, I'd like to be sure all targets executed to completion.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/command/SendCommandCommand/

**Comment by RanVaknin** [comment]
Hi @LumaC0 

Thanks for reaching out.
The AWS SDK client specific docs are code generated from the source docs defined by each AWS service.
Since they are code generated we cannot edit / change them. The changes need to be made upstream with the service team itself.

You can submit documentation feedback request by going to the main AWS website (source of truth) and click on the Feedback button on the top right corner of [each doc page](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_SendCommand.html), or by clicking [here](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Systems%20Manager&topic_url=https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_SendCommand.html). This will ensure that your documentation request makes it directly to the appropriate service team.

Since this is not actionable by the SDK team, I'm going to close this issue.
Thanks again,
Ran~
