### ISSUE TITLE
Link to Lambda Runtimes Page does not show AWS SDK V3 version provided by Lambda

### ISSUE THREAD

**Issue by swhalen-rsc** [aws/aws-sdk-js-v3#6159]
### Describe the issue

This link included in the documentation, [Lambda runtimes doc page](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), does not seem to indicate what node runtimes provide what SDK versions.

While this information can be found by testing a lambda and logging the AWS SDK V3 version, it would be nice to have an official source showing what versions are available.

Use case: I would like to use the same SDK version testing locally as my code will use in the Lambda, installing modules as a peer dependency with npm

### Links

https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#working-with-the-sdk-in-lambda

**Comment by RanVaknin** [comment]
Hi @swhalen-rsc ,

Thanks for reaching out. While I agree that this information is important and useful, the documentation around which SDK version provided in Lambda is owned by the Lambda service, and not the SDK team therefore the SDK docs would not contain which version is provided by lambda. The SDK is vendored as a standalone client and any number of providers can supply their own SDK version without the knowledge of the SDK team.

That being said, this information existed up until not too long ago. The Lambda service team has recently removed this mapping because it wasn't entirely accurate. When the Lambda team updates the Lambda provided SDK, it rolls out the new version update on a per-region basis to avoid pushing a broken version across the board. Because it's hard to project and update this list in real-time, the Lambda team has removed this documentation and instead provided a [new doc page](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html#nodejs-sdk-included) to programmatically check which SDK version is provided for a given lambda:

> Example Node.js 18 and above
> ```js
> const { version } = require("@aws-sdk/client-s3/package.json");
> 
> exports.handler = async () => ({ version });
> ```
> 
> This returns a response in the following format:
> ```
> {
>   "version": "3.462.0"
> }
> ```

Since this is not actionable by the SDK team. I'm going to close this. 
Thanks again,

Ran~
