### ISSUE TITLE
AppSync paginators not present

### ISSUE THREAD

**Issue by ConnorKirk** [aws/aws-sdk-js-v3#6185]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `client-appsync` package does not contain paginator functions.
I expected `paginateListDataSources` to exist, but it is not exported from the package. I can't find any documentation/issues/questions that should indicate it does/doesn't exist.

### SDK version number

    "@aws-sdk/client-appsync": "3.592.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v20.14.0

### Reproduction Steps

```js
const { AppSyncClient, paginateListDataSources } = require("@aws-sdk/client-appsync");
```

### Observed Behavior

`paginateListDataSources` is undefined

### Expected Behavior

I expected `paginateListDataSources` to be defined.

**Comment by kuhe** [comment]
comment for maintainers: service needs to add pagination traits to their model

**Comment by ConnorKirk** [comment]
Thanks! I feared this might be the case. 
Is there a way to note in the client docs when paginators aren't available for a client?

**Comment by aBurmeseDev** [comment]
Hello @ConnorKirk - appreciate you for reporting this. 

I created this internal request (_P135522540_) to service team to update their model with pagination trait. Feel free to check in on the request.

On the docs feedback, I've noted it and will share it with the team to consider for our future releases. 

Since this is not directly actionable by the SDK team and this repo is dedicated for SDK related, I'm going to close this issue. I can check in with you internally when there's an update from service team end.

Best,
John
