### ISSUE TITLE
Enum instead of string

### ISSUE THREAD

**Issue by autarchprinceps** [aws/aws-sdk-js-v3#6215]
### Describe the issue

The documentation claims that you can provide InstanceTypes as an array of strings, when in fact that will result in a hard error, since at some point it has been changed to some kind of enum type, the use of which I cannot find any documentation for.
```
> let type: string = 't4g.micro';
> new DescribeInstanceTypesCommand({InstanceTypes: [type]})
<repl>.ts:6:5 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(input: DescribeInstanceTypesCommandInput): DescribeInstanceTypesCommand', gave the following error.
    Type 'string' is not assignable to type '_InstanceType'.
  Argument of type '[{ InstanceTypes: string[]; }]' is not assignable to parameter of type '[] | [DescribeInstanceTypesCommandInput]'.
    Type '[{ InstanceTypes: string[]; }]' is not assignable to type '[DescribeInstanceTypesCommandInput]'.
      Type '{ InstanceTypes: string[]; }' is not assignable to type 'DescribeInstanceTypesCommandInput'.
        Types of property 'InstanceTypes' are incompatible.
          Type 'string[]' is not assignable to type '_InstanceType[]'.
            Type 'string' is not assignable to type '_InstanceType'.

6 new DescribeInstanceTypesCommand({InstanceTypes: [type]})
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

By the way, next time you do such changes, how about you make them compatible to the old behaviour instead, given this was a breaking change right in the middle of ordinary releases.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ec2/command/DescribeInstanceTypesCommand/

**Comment by aBurmeseDev** [comment]
Hi @autarchprinceps - thanks for reaching out and sorry to hear about the issue.

Can you please share your SDK code to help us understand the issue better? Also what version were you using before updating so that I can check if there was any major changes?

Here's code example I used to reproduce but was unable to.
```ts
import { EC2Client, DescribeInstanceTypesCommand } from "@aws-sdk/client-ec2";
const client = new EC2Client({ region: "us-west-1" });
const input = {
  DryRun: true,
  InstanceTypes: ["a1.medium" || "c3.xlarge"],
};
const command = new DescribeInstanceTypesCommand(input);
const response = await client.send(command);

```

**Comment by autarchprinceps** [comment]
```typescript
import { DescribeInstanceTypesCommand } from "@aws-sdk/client-ec2";
let type: string = 't4g.micro';
new DescribeInstanceTypesCommand({InstanceTypes: [type]})
```
is the smallest code to reproduce the issue. Of course for us it is embedded in a longer programm, but the issue remains the same. If you give over a string type variable, it responds with: Type 'string' is not assignable to type '_InstanceType'.

**Comment by aBurmeseDev** [comment]
@autarchprinceps - thanks for sharing additional info. Can you please try importing `_InstanceType` from client and assign it to input param as shown in the code example below?

```ts
import { EC2Client, DescribeInstanceTypesCommand, _InstanceType } from "@aws-sdk/client-ec2";

const client = new EC2Client({
    region: "us-west-1"
})

const input = {
    InstanceTypes: _InstanceType["a1.medium" || "c3.xlarge"]
}

const command =  new DescribeInstanceTypesCommand(input);
const response = await client.send(command)
```

**Comment by kuhe** [comment]
We removed loose enum types as part of completing https://github.com/aws/aws-sdk-js-v3/issues/4278.

I apologize for the problem that this change caused for you. We made the change because it was considered a bug fix, and had a significant degree of demand. Previously, using unrecognized or incorrect enum values was not flagged at all due to the `| string` widening.

The root cause in this reported issue is the use of intermediate inferred types, which have unintended type widening.

Inferred intermediate variable:
```ts
const externalValue: string = "...";

// inferred as { InstanceTypes: string[] }
const input = {
    InstanceTypes: [externalValue]
};

// inferred type doesn't match input type
const command =  new DescribeInstanceTypesCommand(input);
```

### Solutions

Narrow the string to enum:
```ts
import type { _InstanceType } from "@aws-sdk/client-ec2";

const instanceType = <externally provided string variable> as _InstanceType;

const command =  new DescribeInstanceTypesCommand({
  InstanceTypes: [instanceType]
});
```

----

In AWS SDK for JavaScript (v3), service modeled enums are both types and enum-like runtime objects.
You can use a runtime type check before casting the type.

```ts
import { _InstanceType } from "@aws-sdk/client-ec2";

const externalValue: string = "...";

if (!Object.values(_InstanceType).includes(externalValue)) {
  throw new Error(`unrecognized enum value ${externalValue} for InstanceType`);
}

const instanceType = externalValue as _InstanceType;
```

**Comment by autarchprinceps** [comment]
When you make massive, and ultimately incompatible changes, you should design a version scheme that differentiates those  from the everyday, compatible additions & security fixes, not to mention actually explaining any of this in the documentation.
