### ISSUE TITLE
waitUntilLoadBalancersDeleted never resolves

### ISSUE THREAD

**Issue by anhnh131** [aws/aws-sdk-js-v3#6318]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The waiter, waitUntilLoadBalancersDeleted, returns a promise that never resolves.
The same issue: https://github.com/aws/aws-sdk/issues/639#issuecomment-1800396845

### SDK version number

"@aws-sdk/client-elastic-load-balancing-v2": "^3.620.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v20.11.0

### Reproduction Steps
```js
import {
  ElasticLoadBalancingV2Client,
  waitUntilLoadBalancersDeleted,
} from "@aws-sdk/client-elastic-load-balancing-v2";

await waitUntilLoadBalancersDeleted(
  {
    client: new ElasticLoadBalancingV2Client({}),
  },
  { Names: ["some-fake-name"] }
);
```

### Observed Behavior

The promise from the waiter never resolves.

### Expected Behavior

The promise should resolve immediately for non-existent load balancers.

**Comment by aBurmeseDev** [comment]
Hi @anhnh131 - thanks for reaching out. 

The waiters are managed by the service team. As mentioned, there's an existing issue requesting updates, which I've highlighted to them again. Unfortunately, I don't have any new updates to share at the moment. Since the SDK team can't directly address this, I'll close this issue for now. 

However, please keep an eye on the [original issue](https://github.com/aws/aws-sdk/issues/639#issuecomment-1800396845) for any progress from the service team.
