### ISSUE TITLE
DescribeRoutingProfileCommand not showing AssociatedQueueIds in response

### ISSUE THREAD

**Issue by jose-batres** [aws/aws-sdk-js-v3#6356]
### Describe the issue

When I run the DescribeRoutingProfileCommand, using the documentation provided [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/connect/command/DescribeRoutingProfileCommand/) I am not getting field in **AssociatedQueueIds** in my response.

Ways to reproduce issue:
```js
const {ConnectClient, DescribeRoutingProfileCommand} = require("@aws-sdk/client-connect"); // ES Modules import
const connect = new ConnectClient({ region: 'us-west-2' });
const handler = async () => {
    const input = { // DescribeRoutingProfileRequest
        InstanceId: "######", // required
        RoutingProfileId: "######", // required
    };
    const command = new DescribeRoutingProfileCommand(input);
    const response = await connect.send(command);
    console.log(response.RoutingProfile);
```
Below is the response I get back from the command: 
```
{
  AgentAvailabilityTimer: 'TIME_SINCE_LAST_ACTIVITY',
  DefaultOutboundQueueId: '111111',
  Description: 'Description of RP',
  InstanceId: '######',
  IsDefault: false,
  LastModifiedRegion: 'us-west-2',
  LastModifiedTime: 2024-07-25T14:35:56.219Z,
  MediaConcurrencies: [
    {
      Channel: 'VOICE',
      Concurrency: 1,
      CrossChannelBehavior: [Object]
    }
  ],
  Name: 'RP_Name',
  NumberOfAssociatedQueues: 2,
  NumberOfAssociatedUsers: 9,
  RoutingProfileArn: 'arn:aws:connect:us-west-2:######:instance/######/routing-profile/######',
  RoutingProfileId: '######',
  Tags: {}
}
```

According to the docs I should get an array of associated queue id's on that RoutingProfile in the response. I confirmed in via the Connect console that the Routing Profile has queues associated to it. I'm using version 3.623.0 of the @aws-sdk/client-connect package.

Expected response:
```
RoutingProfile: { // RoutingProfile
InstanceId: "STRING_VALUE",
Name: "STRING_VALUE",
RoutingProfileArn: "STRING_VALUE",
RoutingProfileId: "STRING_VALUE",
Description: "STRING_VALUE",
MediaConcurrencies: [ MediaConcurrencies
{ MediaConcurrency
Channel: "VOICE" || "CHAT" || "TASK", // required
Concurrency: Number("int"), // required
CrossChannelBehavior: { // CrossChannelBehavior
 BehaviorType: "ROUTE_CURRENT_CHANNEL_ONLY" || "ROUTE_ANY_CHANNEL", // required
 },
},
],
DefaultOutboundQueueId: "STRING_VALUE",
Tags: { // TagMap
 "<keys>": "STRING_VALUE",
 },
NumberOfAssociatedQueues: Number("long"),
NumberOfAssociatedUsers: Number("long"),
AgentAvailabilityTimer: "TIME_SINCE_LAST_ACTIVITY" || "TIME_SINCE_LAST_INBOUND",
LastModifiedTime: new Date("TIMESTAMP"),
LastModifiedRegion: "STRING_VALUE",
IsDefault: true || false,
 **AssociatedQueueIds: [ // AssociatedQueueIdList
"STRING_VALUE",
 ],**
},
```

**AssociatedQueueIds: ["STRING_VALUE"],**

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/connect/command/DescribeRoutingProfileCommand/

**Comment by aBurmeseDev** [comment]
Hi @jose-batres - thank you for bringing this issue to our attention.

After investigating, I could successfully replicate the behavior where the `DescribeRoutingProfile` API response does not include the `AssociatedQueueIds` field. Since this appears to be a service model-related issue, I have escalated the matter to the relevant service team for their insights and guidance.

I will keep you informed once I receive further updates or a resolution from the service team. (ref: _P146775803_)

**Comment by aBurmeseDev** [comment]
@jose-batres - service team responded that `DescribeRoutingProfile` API will not return `AssociatedQueueIds` in response and they're going to update the documentation accordingly. 

If you're looking for lists of queues associated with a routing profile, please consider using `ListRoutingProfileQueues` API instead. Here's docs for reference: https://docs.aws.amazon.com/connect/latest/APIReference/API_ListRoutingProfileQueues.html

Code example:
```js
import { ConnectClient, ListRoutingProfileQueuesCommand } from "@aws-sdk/client-connect"; 

const client = new ConnectClient();
const input = { 
  InstanceId: "STRING_VALUE", // required
  RoutingProfileId: "STRING_VALUE", // required
};
const command = new ListRoutingProfileQueuesCommand(input);
const response = await client.send(command);
```
Hope it helps and since there's no action item for SDK team here, I'm going to close this. Feel free to reach out again.
