### ISSUE TITLE
`credentials` property in the `S3` constructor breaks ts check when bumping from 3.623 to 3.624

### ISSUE THREAD

**Issue by pkrucz00** [aws/aws-sdk-js-v3#6359]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi! There is a code in the new version of the `@aws-sdk/s3-client` (3.624) which makes the previous implementation non-compliant with the constructor parameter type.

We have the constructor implemented as:
```
  import {
  S3 as S3Client,
} from '@aws-sdk/client-s3';
[...]
class S3 {
[...]

    this.client = new S3Client({
      endpoint,
      forcePathStyle: getEnvVariable('S3_FORCE_PATH_STYLE', 'false').toLowerCase() === 'true',
      region: this.region,
      credentials: getAWSCredentials({ prefix, requestHandler: S3.createRequestHandler() }),
      ...S3.createRequestHandler(),
    });
```

The `getAWSCredentials` function returns function of type `(retires?: number) => Promise<Credentials>`.

The expected behaviour is that a ts check would pass without errors. In reallity it yields an error (pasted in the `observed behaviour` field.

The error is not present for version 3.623, but is there for 3.624. This means that the contract has changed in between minor release. Could this be fixed, so that the previous implementation is also correct?

### SDK version number

@aws-sdk/client-s3@3.624.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.11.0

### Reproduction Steps

1. Paste the code I've added into the `Describe the bug` section with mocked values.
2. Try `npx tsc -p tsconfig.json --noEmit`

### Observed Behavior

Error when running `npx tsc -p tsconfig.json --noEmit`

```
src/utils/S3.ts(55,32): error TS2345: Argument of type '[{ requestHandler?: NodeHttpHandler | undefined; endpoint: string | undefined; forcePathStyle: boolean; region: string; credentials: (retries?: number) => Promise<Credentials>; }]' is not assignable to parameter of type '[] | [S3ClientConfig]'.

[2024-08-06T08:05:29.867Z]   Type '[{ requestHandler?: NodeHttpHandler | undefined; endpoint: string | undefined; forcePathStyle: boolean; region: string; credentials: (retries?: number) => Promise<Credentials>; }]' is not assignable to type '[S3ClientConfig]'.

[2024-08-06T08:05:29.867Z]     Type '{ requestHandler?: NodeHttpHandler | undefined; endpoint: string | undefined; forcePathStyle: boolean; region: string; credentials: (retries?: number) => Promise<Credentials>; }' is not assignable to type 'S3ClientConfig'.

[2024-08-06T08:05:29.867Z]       Type '{ requestHandler?: NodeHttpHandler | undefined; endpoint: string | undefined; forcePathStyle: boolean; region: string; credentials: (retries?: number) => Promise<Credentials>; }' is not assignable to type 'HttpAuthSchemeInputConfig'.

[2024-08-06T08:05:29.867Z]         Types of property 'credentials' are incompatible.

[2024-08-06T08:05:29.867Z]           Type '(retries?: number) => Promise<Credentials>' is not assignable to type 'AwsCredentialIdentity | AwsCredentialIdentityProvider | undefined'.

[2024-08-06T08:05:29.867Z]             Type '(retries?: number) => Promise<Credentials>' is not assignable to type 'AwsCredentialIdentityProvider'.

[2024-08-06T08:05:29.867Z]               Types of parameters 'retries' and 'identityProperties' are incompatible.

[2024-08-06T08:05:29.867Z]                 Type 'Record<string, any> | undefined' is not assignable to type 'number | undefined'.

[2024-08-06T08:05:29.867Z]                   Type 'Record<string, any>' is not assignable to type 'number'.
```

### Expected Behavior

No error on typescript check

**Comment by kuhe** [comment]
The type of `credentials` used to accept `() => Promise<Credentials>`, which expects no arguments. TS matches `(someArg?) => Promise<Credentials>` but really no arguments should be present.

We've redefined this type as `(props?: Record) => Promise<Credentials>`, which is only compatible with previous no-arg functions.

You should change your credential provider to no-args, since we never called it with `retries: number`. However, I will see if we can fix the compatibility issue by overloading the method with a no-args signature in addition to its existing optional-args signature.

**Comment by kuhe** [comment]
After further analysis, we cannot change the interface of the `IdentityProvider` type which corresponds to the `credentials` field of SDK client constructors.

Constructor example:
```ts
import { S3 } from "@aws-sdk/client-s3";

const s3 = new S3({
  credentials: async () => ({
    accessKeyId, secretAccessKey
  })
});
```

The type of the interface is this:
```ts
export interface AwsCredentialIdentityProvider {
  (identityProperties?: Record<string, any>): Promise<AwsCredentialIdentity>;
}
```

This previously accepted no arguments. While the type `(retries?: number) => Promise<Credentials>` was accepted by TypeScript, it is not an entirely compatible function implementation because of the extra optional parameter. 

We may expand function arguments with additional optional arguments in the future, so we cannot guarantee that this type of issue will not reoccur, but being aware of this issue we will try to minimize the need for this type of change.

Because the new interface has already been released, we do not want to enable the type with a union of 

```ts
() => X | (optional?) => X
```

since this will cause your function to be called at runtime with our optional type `Record` instead of your optional type, a `number`. We would rather have the compile time error than the runtime error.

**Comment by kuhe** [comment]
As a workaround, please modify your input function, for example like this:

```ts

const originalCredentialProvider = (retries?: number) => Promise.resolve(credentials);

const noArgCredentials = async () => originalCredentialProvider();

new SDKClient({
  credentials: noArgCredentials
});
```
