### ISSUE TITLE
QuickSight > SearchAnalysesCommand > Filters limit missing

### ISSUE THREAD

**Issue by naminders** [aws/aws-sdk-js-v3#6468]
### Describe the issue

In the quicksight client documentation for QuickSight > SearchAnalysesCommand
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/quicksight/command/SearchAnalysesCommand/

Filters can have only 1 filter at a time, otherwise an error would be thrown:
`'filters' failed to satisfy constraint: Member must have length less than or equal to 1`

Eg:
`ValidationException: 1 validation error detected: Value '[AnalysisSearchFilter(operator=StringLike, name=ANALYSIS_NAME, value=csv), AnalysisSearchFilter(operator=StringLike, name=ANALYSIS_NAME, value=transaction)]' at 'filters' failed to satisfy constraint: Member must have length less than or equal to 1`

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/quicksight/command/SearchAnalysesCommand/

**Comment by aBurmeseDev** [comment]
Hi @naminders - thanks for reaching out.

The behavior you mentioned is anticipated because the `Filters` array is designed to have a fixed number of one item. This is documented in the AWS QuickSight API Reference for the SearchAnalyses operation: https://docs.aws.amazon.com/quicksight/latest/APIReference/API_SearchAnalyses.html#API_SearchAnalyses_RequestBody

Since this is a service team requirement, SDK does not have control over it. However, I will update the SDK documentation to align with the service documentation for clarity.

Best,
John

**Comment by naminders** [comment]
Thanks @aBurmeseDev for the link, yeah aligning the documentation would be great. 

I'll close the query.
