### ISSUE TITLE
waitUntilObjectNotExists hangs when Bucket is missing.

### ISSUE THREAD

**Issue by cpyle0819** [aws/aws-sdk-js-v3#6469]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When `waitUntilObjectNotExists` is called without providing a `Bucket`, it hangs indefinitely.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-s3@3.651.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.17.0

### Reproduction Steps

```javascript
import { waitUntilObjectNotExists, S3Client } from "@aws-sdk/client-s3";

const main = async () => {
  await waitUntilObjectNotExists(
    { client: new S3Client({}) },
    { Key: "some-key" }
  );
};

// Call function if run directly
import { fileURLToPath } from "url";
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
```

### Observed Behavior

Waiter should fail immediately due to missing param.

### Expected Behavior

Waiter hangs forever.

**Comment by aBurmeseDev** [comment]
Hi Corey - thanks for reaching out. 

In JSv3, waiters requires `maxWaitTime` field in waiter configuration because  the bare-bones modular client does not include the waitFor operation by default. This is similar to `delay` and `maxAttempts` fields in JSv2 waiters. 

```js
...
await waitUntilObjectNotExists({ client, maxWaitTime: 30 });
...
```
If you have the `maxWaitTime` field in your waiter configuration and the client is missing the `Bucket` property, you will encounter a waiter timeout error. This is how waiters are designed to operate.

However, there's room for improvements in our waiter docs, particularly in providing examples. I created [this new issue](https://github.com/aws/aws-sdk-js-v3/issues/6508) to address the need for better documentation on waiters.

Closing this issue now.
