### ISSUE TITLE
Reopening: API to get a list of metric namespaces

### ISSUE THREAD

**Issue by jedwards1211** [aws/aws-sdk-js-v3#6486]
### Describe the feature

I too would like an API to get a list of metric namespaces (#3175)

### Use Case

I find the AWS console painfully slow and I've been building my own for services I use, but I'm unable to list metrics like the console can.

### Other Information

It would be nice if there were an issue tracker for the API itself.  The feedback form in the AWS Console just feels like it gets ignored.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.651.1

### Environment details (OS name and version, etc.)

N/A

**Comment by aBurmeseDev** [comment]
Hi @jedwards1211 - thanks for submitting this feature request.

It appears that you are proposing a new API functionality within Amazon CloudWatch, specifically aimed at listing the available metric namespaces. This would entail modifying the service's underlying model which is managed and developed by the respective service team, AWS CloudWatch in this case. While we do not have the authority to directly implement such changes, I can submit a formal feature request to the team within AWS on your behalf, highlighting your suggestion for their consideration and potential implementation in future updates.

Since this is not directly actionable by the SDK team and this repo is dedicated for SDK related, I'm going to close this issue. Let me know if you have any other questions.

Best,
John

**Comment by jedwards1211** [comment]
Okay sounds good, thank you!
