### ISSUE TITLE
Add cfn-lint to CloudFormation SDK

### ISSUE THREAD

**Issue by bildungsroman** [aws/aws-sdk-js-v3#6491]
### Describe the feature

Currently, the CloudFormation SDK has a [ValidateTemplateCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudformation/command/ValidateTemplateCommand/) that is ...pretty useless as a validator. It would be amazing to have that command run cfn-lint and return the results instead.

### Use Case

I'd like to be able to validate CloudFormation templates in a web app, rather than just the CLI.

### Proposed Solution

Have the `ValidateTemplateCommand` return the results of running `cfn-lint` on a template.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

3

### Environment details (OS name and version, etc.)

MacOS

**Comment by aBurmeseDev** [comment]
Hi @bildungsroman - thanks for reaching out. 

The feature you're requesting requires a modification to the service model. Service models are controlled and generated by the respective service teams within AWS. However, I can submit a feature request to the CloudFormation team internally on your behalf.

Since this is not directly actionable by the SDK team and this repo is dedicated for SDK related, I'm going to close this issue. Let me know if you have any other questions.
Best,
John
