### ISSUE TITLE
StartConversationCommand support in Javascript SDK

### ISSUE THREAD

**Issue by JoshuaBiswas** [aws/aws-sdk-js-v3#6566]
### Describe the issue

I found contradictory information on whether the startconversation command is supported in javascript sdk or not. 
The following two links illustrate this.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lex-runtime-v2/command/StartConversationCommand/

https://docs.aws.amazon.com/lexv2/latest/dg/start-stream-conversation.html

**Comment by zshzbh** [comment]
Hey @JoshuaBiswas ,

Thanks for the feedback! Since the [JavaScript SDK documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lex-runtime-v2/command/StartConversationCommand/) has a dedicated page to illustrate the usage of the `StartConversationCommand`, which means the `StartConversationCommand` is definitely supported in JS SDK.  It makes sense to only keep the information about other supported SDKs in this JS SDK documentation. 

Thanks! 
Maggie
