### ISSUE TITLE
Amazon Transcribe Medical -- ?Correct Sample rate for en-GB

### ISSUE THREAD

**Issue by App-Index** [aws/aws-sdk-js-v3#6643]
### Describe the issue

I am using amazon transcribe medical, when starting a new StartMedicalStreamTranscriptionCommand my paramaters are:

```js
{
    LanguageCode: "en-GB",
    MediaEncoding: "pcm",
    MediaSampleRateHertz: 8000,
    AudioStream: getAudioStream(),
    Specialty: "PRIMARYCARE",
    Type: "CONVERSATION",
  }
```

However this results in an error: 
BadRequestException: The requested language doesn't support the specified sample rate. Use the correct sample rate then try again.

I've tried with 8000-48000 hertz and the same issue persists

### Links

Documentation contains no useful information
https://docs.aws.amazon.com/transcribe/latest/dg/how-input.html#:~:text=Sample%20rates%20for%20low%20fidelity,16%2C000%20Hz%20and%2048%2C000%20Hz.

**Comment by zshzbh** [comment]
Hey @App-Index ,

Thanks for the feedback! The root cause of the issue is that the "en-GB" is not supported by Amazon Transcribe Medical . Right now Amazon Transcribe Medical only supports US English (en-US) - [reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/transcribe-streaming/command/StartMedicalStreamTranscriptionCommand/) 

<img width="913" alt="Screenshot 2024-11-08 at 10 23 30 AM" src="https://github.com/user-attachments/assets/5c0f2104-43ea-404c-9a1d-a169f7dac108">

Please change the languageCode to 
```js LanguageCode: "en-US" ```

Please let me know if there's any other questions!

Thanks!
Maggie
