### ISSUE TITLE
rds-data: Retry does not work with DatabaseResumingException in Serverless V2

### ISSUE THREAD

**Issue by yukihato** [aws/aws-sdk-js-v3#6701]
### Describe the feature

In Serverless v2, DatabaseResumingException occurs when ACU is 0 in auto-pause state, but retry does not work.
It is clear that the system will start up in a few seconds, so I want the retry to be performed.

Below is a sample code and log.

```
import {
    RDSDataClient,
    BeginTransactionCommand,
} from '@aws-sdk/client-rds-data'
const RDS = new RDSDataClient({
    maxAttempts: 10,
})
result = await RDS.send(
    new BeginTransactionCommand({
        resourceArn: ****,
        secretArn: ****,
        database: ****,
    })
)
```

```
"error": {
    "name": "DatabaseResumingException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "***",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "message": "The Aurora DB instance arn:**** is resuming after being auto-paused. Please wait a few seconds and try again."
}
```

### Use Case

In Serverless v2, if auto-pause is enabled

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

@aws-sdk/client-rds-data: 3.699.0

### Environment details (OS name and version, etc.)

Node 22

**Comment by RanVaknin** [comment]
Hi @yukihato ,

The SDK will only retry errors that are considered Retryable. Since 400 errors are not considered retryable the SDK wont retry this operation regardless of how many `maxAttempts` you have configured.

In your case you will need to implement your own retryer logic to retry on this specific DatabaseResumingException error. 
Please refer to our [supplemental docs](https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#retry-strategy-retrystrategy-retrymode-maxattempts) for a code example.

Thanks,
Ran~
