### ISSUE TITLE
Support for Email MFA

### ISSUE THREAD

**Issue by dpetzev** [aws/aws-sdk-js-v3#6720]
### Describe the feature

With the latest announcement of email MFA https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-sms-email-message.html it would be amazing to add support for it to the cognito identity provider client.

Any information on when can we expect support for that would be appreciated as well.

### Use Case

So we can integrate the email MFA workflow with our custom auth flow.

### Proposed Solution

Add `EMAIL_MFA` to `RespondToAuthChallengeCommandInput`

### Other Information

Unless I've missed something currently the Cognito Identity provider client does not support issuing a response to the auth challenge for an Email MFA through the API.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.699.0

### Environment details (OS name and version, etc.)

AWS SDK JS V3

**Comment by aBurmeseDev** [comment]
Hi @dpetzev - thanks for reaching out. 

According to the service docs, in order to use email MFA, you'll have to invoke one of these API: [InitiateAuth](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html) or [AdminInitiateAuth](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminInitiateAuth.html) with `EMAIL_OTP` as `ChallengeName` parameter. Here's more on Email settings: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html#user-pool-email-developer

I've also checked the service model SDK usesand it's up to date with new service team release. Let me know if I'm missing something and I will verify it with service team.

**Comment by dpetzev** [comment]
@aBurmeseDev Sorry for the delayed response. I tried it with `RespondToAuthChallengeCommandInput` and `EMAIL_OTP` and it seems like it works as expected. It was a bit confusing that a `SMS_MFA` challenge response exists, but not `EMAIL_MFA`. Closing this as resolved.
