### ISSUE TITLE
Multiple alpha clients are not returning data

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#695]
**Describe the bug**
Multiple alpha clients are not returning data

**To Reproduce (observed behavior)**
Creating repo for testing
```
$ mkdir alphatest && cd alphatest
$ npm init -y
$ npm install @aws-sdk/client-acm@alpha
```

tested with following file (say `index.js`):
```javascript
const { ACM } = require("@aws-sdk/client-acm");

(async() => {
  const client = new ACM({});
  try {
    const response = await client.listCertificates({});
    console.log(`response: ${response}`);
  } catch(e) {
    console.log(`error: ${e}`);
  }
})();
```

```console
$ node index.js
TypeError: Cannot read property 'CertificateSummaryList' of undefined
    at deserializeAws_json1_1ListCertificatesResponse (/Users/trivikr/workspace/alphatest/node_modules/@aws-sdk/client-acm/dist/cjs/protocols/Aws_json1_1.js:1356:16)
    at Object.deserializeAws_json1_1ListCertificatesCommand (/Users/trivikr/workspace/alphatest/node_modules/@aws-sdk/client-acm/dist/cjs/protocols/Aws_json1_1.js:436:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  '$metadata': { retries: 0, totalRetryDelay: 0 }
}
```

**Expected behavior**
* The response should be successful with list in `CertificateSummaryList`
* Works with aws cli:
  ```console
  $ aws acm list-certificates
  {
    "CertificateSummaryList": []
  }
  ```

**Comment by trivikr** [comment]
Tested with DynamoDB:
```javascript
const { DynamoDB } = require("@aws-sdk/client-dynamodb");

(async() => {
  const client = new DynamoDB({});
  try {
    const response = await client.listTables({});
    console.log(response);
  } catch(e) {
    console.log(e);
  }
})();
```

```console
$ npm install @aws-sdk/client-dynamodb@alpha
$ node index.js
TypeError: Cannot read property 'LastEvaluatedTableName' of undefined
    at deserializeAws_json1_0ListTablesOutput (/Users/trivikr/workspace/alphatest/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:5184:16)
    at Object.deserializeAws_json1_0ListTablesCommand (/Users/trivikr/workspace/alphatest/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:1481:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  '$metadata': { retries: 0, totalRetryDelay: 0 }
}
```

**Comment by AllanFly120** [comment]
This issue is caused by deserializers trying to destruct the response wrapper that not exists. For example in DynamoDB:
https://github.com/aws/aws-sdk-js-v3/blob/7fd2e7b8bb5fcf19fe11b562e4a06930f03e9fc0/clients/client-dynamodb/protocols/Aws_json1_0.ts#L2949-L2954
The deserializer is trying to find `ListTablesOutput` member but it doesn't exit. The raw response body looks like:
```json
{ "TableNames":
   [
     "foo_table",
     "bar_table"
] }
``` 

The root cause IMO is here:
https://github.com/aws/aws-sdk-js-v3/blob/7fd2e7b8bb5fcf19fe11b562e4a06930f03e9fc0/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/JsonRpcProtocolGenerator.java#L105-L114
We should supply `data` as is to the body deser instead of `data.${outputStructure.getId()}`

**Comment by trivikr** [comment]
Fix was released in new clients https://github.com/aws/aws-sdk-js-v3/releases/tag/v0.9.0

Verified with:
* @aws-sdk/client-acm@1.0.0-alpha.2
* @aws-sdk/client-dynamodb@1.0.0-alpha.2
