### ISSUE TITLE
LEX api is failing at runtime with InvalidSignatureException

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#810]
**Describe the bug**
LEX's PostText and PostContent APIs are failing with 403 error 

// POST API response
```
{"message":"The request signature we calculated does not match the signature you provided. 
Check your AWS Secret Access Key and signing method. Consult the service documentation 
for details."}
```
// POST API response header
```
x-amzn-ErrorType: InvalidSignatureException:http://internal.amazon.com/coral/com.amazon.coral.service/
```

**SDK version number**
@aws-sdk/client-lex-runtime-service@1.0.0-alpha.10

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4

**To Reproduce (observed behavior)**
Make a service call to Lex's PostText and PostContent APIs

**Expected behavior**
There should be no error.

**Screenshots**

**Additional context**

**Comment by trivikr** [comment]
I tried to repro this in https://github.com/trivikr/aws-sdk-js-tests/commits/lex-signature-error

**Error**
```console
TypeError: Cannot read property 'contentType' of null
```

**Screenshot**
![Screen Shot 2020-01-29 at 2 51 14 PM](https://user-images.githubusercontent.com/16024985/73405524-faed0e00-42a8-11ea-8777-1b637b83ab3d.png)

**SDK version number**
@aws-sdk/client-lex-runtime-service@1.0.0-alpha.10

How to repro InvalidSignatureException?

**Comment by trivikr** [comment]
☝️ Tried to repro with `@aws-sdk/client-lex-runtime-service@1.0.0-alpha.10`

Error received is `TypeError: Cannot read property 'contentType' of null`

**Comment by Amplifiyer** [comment]
@trivikr  Repo for Repro https://github.com/Amplifiyer/aws-sdk-js-tests/tree/lexruntimeClient

**Comment by trivikr** [comment]
I'm able to repro issue with BookTrip bot, tested with `@aws-sdk/client-lex-runtime-service@1.0.0-alpha.13`
The earlier repro explained in https://github.com/aws/aws-sdk-js-v3/issues/810#issuecomment-580005188 was tried using ScheduleAppointment bot.

Commits: https://github.com/trivikr/aws-sdk-js-tests/commits/lex-signature-error

Response from v2:
![Screen Shot 2020-02-05 at 1 18 51 PM](https://user-images.githubusercontent.com/16024985/73884243-4c9e1700-481a-11ea-9037-2ed7aa3de905.png)

Error from v3:
![Screen Shot 2020-02-05 at 1 18 24 PM](https://user-images.githubusercontent.com/16024985/73884249-532c8e80-481a-11ea-8437-a0c1622db28e.png)

**Comment by trivikr** [comment]
Verified that InvalidSignatureException is fixed in `@aws-sdk/client-lex-runtime-service@1.0.0-alpha.15`
* Code: https://github.com/trivikr/aws-sdk-js-tests/blob/d0aa4eed077efaab3ce0e6e7e9bb4baf526f474b/src/index.js
* Branch: https://github.com/trivikr/aws-sdk-js-tests/tree/lex-signature-error
* yarn upgrade commit: https://github.com/trivikr/aws-sdk-js-tests/commit/d0aa4eed077efaab3ce0e6e7e9bb4baf526f474b

The error `TypeError: Cannot read property 'contentType' of null` mentioned in https://github.com/aws/aws-sdk-js-v3/issues/810#issuecomment-580005188 does gets thrown, to be followed up in https://github.com/aws/aws-sdk-js-v3/issues/892
