### ISSUE TITLE
S3:UploadParts API doesn't return ETag in the output object.

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#825]
**Describe the bug**
S3:UploadParts API should return ETag value for every part uploaded. This value is present in the response headers and should be copied and made it available through UploadPartOutput.ETag

Because of this, CompleteMultiPartUpload API call fails since ETag is undefined in the request.

**SDK version number**
@aws-sdk/client-s3 client@1.0.0-alpha.8

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4

**To Reproduce (observed behavior)**
call S3:UploadParts API and check the output object. ETag value is undefined.

**Expected behavior**
ETag shouldn't be undefined. It should be copied from the response header and present in the output object so that CompleteMultiPartUploadAPI can succeed.

**Screenshots**
![Screen Shot 2020-01-31 at 11 31 50 AM](https://user-images.githubusercontent.com/51211245/73568467-4de7d200-441d-11ea-93b0-e3daa66bc45f.png)

**Additional context**

**Comment by AllanFly120** [comment]
This issue happens because SDK is trying to parse case sensitive header name `"ETag"`, but node actually returns case insensitive(lower cased) `"etag"` header. So the member is not found. 

Reference:
https://github.com/aws/aws-sdk-js-v3/blob/6c3e0988694953220cef300af6c39f6afd116b6a/clients/client-s3/protocols/Aws_restXml.ts#L9120-L9122

**Comment by AllanFly120** [comment]
This issue happens because SDK is trying to parse case sensitive header name `"ETag"`, but node actually returns case insensitive(lower cased) `"etag"` header. So the member is not found. 

Reference:
https://github.com/aws/aws-sdk-js-v3/blob/6c3e0988694953220cef300af6c39f6afd116b6a/clients/client-s3/protocols/Aws_restXml.ts#L9120-L9122

**Comment by AllanFly120** [comment]
Fix as https://github.com/awslabs/smithy-typescript/pull/114 merged
