### ISSUE TITLE
EKS DescribeCluster - missing fields

### ISSUE THREAD

**Issue by omerlh** [aws/aws-sdk-js-v3#988]
**Is your feature request related to a problem? Please describe.**
Looking at the [docs](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeCluster.html), look like some fields are missing - like `identity`.

**Describe the solution you'd like**
Being able to view all the fields.

**Describe alternatives you've considered**
Running the request manually.
**Additional context**

**Comment by AllanFly120** [comment]
@omerlh 
The field exists in our newest packages https://github.com/aws/aws-sdk-js-v3/blob/1463a06be1ea978f6b7742ec953540140fc644e7/clients/client-eks/models/index.ts#L134

Thank you for bringing this up! I'm closing this issue because we recently moved to alpha clients. See [here](https://github.com/aws/aws-sdk-js-v3/issues/944) for more information. Please post a new issue if the bug persists.
